# 논란·미기재 문항에 대한 AI 추정 답(수업 자료 기반). 채점 정답은 학습지 그대로 두고, 해설 맨 위에 참고로만 표시한다.
AI={
'topic-001-area-yama-q-005':'② 감각실어증 — 학습지 정답과 같음. 다만 현재 강의록 기준으로 엄밀히 BA39·40(각회·모서리위이랑) 손상의 대표 증상은 Gerstmann 증후군(실서·실산·손가락 인식불능·좌우 구분 불능)과 읽기장애이고, 선지 중에서는 감각(Wernicke형) 실어증이 가장 가깝다.',
'topic-001-area-yama-q-009':'② Sensory aphasia — 2023 객1과 같은 문제. 선지 중 가장 가까운 답은 감각실어증.',
'topic-001-area-yama-q-007':'② GPi — 강의록 회로 그림에서 시상으로 가는 억제성 출력은 GPi(와 SNr). 선지 ④ "Substantia nigra"는 SNc(도파민 입력)와 SNr(출력)을 구분하지 않아서, 단일 정답으로는 GPi가 맞다.',
'topic-001-area-yama-q-010':'② GPi — 위와 같은 이유.',
'topic-001-area-yama-q-018':'② GPi — 위와 같은 이유.',
'topic-001-area-yama-q-008':'④ 유두체 — 뇌궁섬유의 주 종착점(Papez 회로: 해마 → 뇌궁 → 유두체 → 유두시상로 → 앞시상핵 → 띠이랑). 중격핵으로 가는 섬유(precommissural fornix)도 있지만 수업의 대표 경로 기준으로는 유두체.',
'topic-001-area-yama-q-011':'④ 유두체 — 위와 같은 이유.',
'topic-001-area-yama-q-021':'② median eminence — 시상하부의 신경내분비 구조로 반구를 잇지 않는다. massa intermedia(시상간유착)는 백질 맞교차는 아니지만 양쪽 시상(양측)을 잇는 구조라 "연결하는 구조"로 볼 수 있다.',
'topic-001-area-yama-q-029':'intralaminar nuclei(수질판속핵) — 중심정중핵·다발곁핵과 함께 비특이 시상핵으로 ARAS의 시상 중계를 이룬다. internal medullary lamina는 그 핵들을 품은 백질판 이름이므로 답안에는 "intralaminar nuclei"가 더 정확하다.',
'topic-001-area-yama-q-033':'직접 연결하는 구조로는 stria terminalis(분계섬유줄, 편도체 출력)가 있으나 학습지·수업은 Fornix를 답으로 다룬다. 시험에서는 학습지 답(Fornix)을 쓰는 것이 안전하다.',
'topic-002-area-yama-q-012':'③ L-spine MRI — 반복 세균성 수막염 + 요추부 피부 구멍 → congenital dermal sinus tract. 요추천자는 감염 경로가 될 수 있어 금기이고, MRI로 누관의 깊이·척수 연결·동반 병변(유피종 등)을 확인한다.',
'topic-002-area-yama-q-028':'Tethered cord syndrome(척수견인증후군) — 두꺼운 종사·지방종·지방척수수막류가 원추의 상승을 막아 발 변형, 배뇨장애, 요로감염을 일으킨다. 분류상으로는 disorder of secondary neurulation(occult spinal dysraphism).',
'topic-003-area-yama-q-007':'③ — Brown-Séquard: 병변측은 운동마비·후색(위치·진동·입체감각) 소실, 반대측은 통각·온도감각 소실. 따라서 병변측 온도감각은 정상. ①은 척수쇼크 경과(이완성 → 강직성)가 반대로 적혀 있어 틀림.',
'topic-003-area-yama-q-038':'Modality별 경로: 통증·온도 — spinothalamic(외측척수시상로), Aδ(얇은 유수)·C(무수) 섬유 / 거친 촉각·압력 — 전척수시상로 / 미세촉각·진동·위치감각 — 후색-내측섬유띠(dorsal column–medial lemniscus), Aβ(굵은 유수) 섬유 / 무의식적 고유감각 — 척수소뇌로, Aα(Ia·Ib) 섬유.',
'topic-004-area-yama-q-002':'③ — 시신경염 뒤 MS 진행의 가장 강력한 예측인자는 뇌 MRI T2 병변(무증상 탈수초 병변의 수). OCB 양성(④)도 독립 위험인자이지만 수업·기출에서는 MRI 병변을 가장 중요하다고 다룬다. ⑤ 유두부종은 오히려 NMO/MOG 쪽.',
'topic-004-area-yama-q-024':'① Steroid — 시간적·공간적 파종(시신경염 → 반대측 마비 → 감각장애)과 MRI로 MS 재발. 급성 재발은 고용량 스테로이드(methylprednisolone 펄스), 장기적으로 질병조절치료(interferon-β 등). 보기 중에서는 스테로이드.',
'topic-005-area-yama-q-023':'원래 선지에 경구 prednisone이 있었다면 그것이 정답 — polymyositis 일차 치료는 경구 고용량 스테로이드이고, IVIG는 스테로이드 불응 시 추가 치료. 복원된 선지만 보면 IVIG(②)가 남는다.',
'topic-008-area-yama-q-025':'⑤ — 말초 감작(삼차신경절 1차 뉴런): 기침·몸 숙이기 등 두개내압 변화에 박동성 두통 악화. 두피 이질통(allodynia)은 2차 뉴런(TNC)의 중추 감작, 광·소리공포증은 시상 감작. 해답지의 ②는 중추 감작 소견이라 수업 기준으로는 ⑤가 맞다.',
'topic-009-area-yama-q-002':'지주막하출혈을 먼저 배제하는 선지(④, 비조영 뇌 CT 후 필요하면 요추천자) — 고혈압 병력 + 경부강직·Kernig 양성 + troponin 상승(SAH의 신경성 심근 손상)은 SAH를 시사한다. 수막염 확인용 요추천자(⑤)는 CT로 출혈·종괴를 배제한 뒤에 한다.',
'topic-009-area-yama-q-004':'① SAH + coil embolization — 치료 후 영상에 개두술 흔적이 없고 동맥류 안에 코일 음영이 있으면 coiling. 개두 흔적(골편·클립 음영)이 있으면 ④ clipping.',
'topic-009-area-yama-q-006':'사진에 개두술 흔적과 클립이 보이면 ④ clipping, 동맥류 내 코일만 보이면 ① coil. 학습지 정답 칸은 ④이지만 복원자 해설은 coil이라 적어 원 사진 없이는 확정 불가 — 두 치료의 영상 차이를 알아 두는 것이 핵심.',
'topic-009-area-yama-q-036':'정답은 Hypertension·Hypervolemia·Hemodilution(triple H). 복원 선지의 "Hyperventilation"은 hypervolemia의 오기로 보이며, 과호흡은 triple H가 아니다(ICP 조절 방법).',
'topic-010-area-yama-q-018':'④ 충좌상(coup) — EDH는 외력이 가해진 쪽의 두개골 골절·중경막동맥 손상으로 생긴다. ⑤ 두개골 골절도 흔히(85–95%) 동반되지만 소아에서는 골절 없이도 생길 수 있어, 단일 정답으로는 ④.',
'topic-010-area-yama-q-021':'Acute epidural hematoma — 렌즈(양볼록) 모양 고음영, 중경막동맥 손상, 의식 명료기.',
'topic-010-area-yama-q-034':'⑤ 또는 ③ — 3개월 전 외상 + 서서히 생긴 편마비 → 만성 SDH. 만성 SDH의 표준 수술은 천두술(burr hole) 배액이라 수업 기준으로는 ⑤가 더 자연스럽다. 다만 두께 10 mm 이상·정중선 5 mm 이상 이동이면 신속한 수술이 필요하다는 점에서 학습지는 ③을 답으로 적었다.',
'topic-010-area-yama-q-046':'Uncal(천막경유) 탈출: 동측 동공 산대(동안신경 압박) → 안검하수·안구운동 장애, 의식 저하, 반대측 편마비(Kernohan notch면 동측 편마비), 진행하면 제뇌강직·Cushing 반응(고혈압·서맥·불규칙 호흡).',
'topic-012-area-yama-q-009':'① ABCD2 4점 — 나이(1) + 혈압(1) + 편측 위약(2) + 5분(0) = 4, 당뇨 정보가 없으므로 0점으로 계산. 나머지 선지는 명백히 틀려 ①이 답.',
'topic-012-area-yama-q-020':'복원 문구 그대로라면 틀린 선지 — 가장 먼저 생기는 것은 세포성(cytotoxic) 부종이고 이때 DWI 고신호. 원 선지가 "세포성 부종"이었다면 ④가 정답(2013 객34와 같은 구성).',
'topic-012-area-yama-q-022':'⑤ GP Ib — 혈소판이 vWF에 부착하는 수용체(1차 지혈, 응고 촉진). 나머지(thrombomodulin, heparin-like molecule, protein C)는 내피의 항응고 인자로 묶인다. thrombin receptor도 응고 촉진이지만 강의록 분류는 GP Ib를 답으로 쓴다.',
'topic-012-area-yama-q-031':'엄밀히는 정답이 없는 문항 — anoxic(terminal) depolarization은 infarct core에서, penumbra에서는 반복적인 peri-infarct depolarization이 일어난다. 선지 ②를 "peri-infarct depolarization이 일어나는 곳이 penumbra"로 읽으면 맞다. 다른 해에는 같은 문장이 틀린 선지였으므로 주의.',
'topic-014-area-yama-q-013':'⑤ labetalol 먼저 → 이후 IV tPA — 혈압 205/115는 tPA 금기 기준(185/110 이상)이라 먼저 혈압을 낮춰야 한다(2026 강의록 형성평가와 같은 논리). 학습지 정답 ①은 "tPA 적응증"만 묻는 의도로 보인다.',
'topic-014-area-yama-q-025':'원 문제는 TOAST 분류가 아닌 것을 고르는 문제 — 정답은 TOAST에 없는 분류(예: cancer-related stroke, lacunar stroke 등). 복원된 선지 5개는 모두 TOAST 분류라 답이 없다.',
'topic-014-area-yama-q-033':'① 좌측 MCA — 우측 마비는 좌측 반구 병변. MCA 경색에서 안구는 병변 쪽(좌측)으로 편위하므로 "우측 안구편위"는 복원 오기일 가능성이 크다.',
'topic-014-area-yama-q-034':'① 손가락인식불능증 — 오른손잡이 우측 마비 + 좌측(우세) 두정엽 하부(모서리위이랑·각회) 병변이면 Gerstmann 증후군(손가락 인식불능·실서증·계산불능·좌우 구분 불능). ①②③이 모두 Gerstmann 증상이라 원 사진 없이는 단일 답 확정이 어렵다.',
'topic-014-area-yama-q-035':'⑤ — 만성 고혈압은 뚫고 들어가는 세동맥(penetrating arteriole)에 lipohyalinosis·미세동맥류를 만든다(소혈관 질환). ④는 Virchow-Robin 공간이 지주막하공간과 "연속"이라는 표현이 논쟁적이라(연막하 공간) 수업 기준으로는 ⑤가 더 확실하다.',
'topic-014-area-yama-q-053':'① Neuron — 저산소 허혈성 뇌병증에서 가장 취약하고 손상의 중심이 되는 세포는 뉴런(해마 CA1, 대뇌피질 3·5층, 소뇌 Purkinje 세포 선택적 취약성). microglia는 이차 염증 반응에 관여한다.',
'topic-016-area-yama-q-008':'① Sleep latency — 나이 들수록 수면 잠복기·WASO·N1이 늘고 N3·REM·수면효율이 준다. N1·N2(④⑤)도 늘지만 "수면 패턴"보다 수업에서 강조한 대표 변화는 잠복기·각성 증가라 ①을 고르는 것이 무난하다.',
'topic-017-area-yama-q-018':'① 각성기로 눈을 감은 상태 — 후두부 알파파, 전두부 베타파, 전후 기울기(A-P gradient). 출제 오류로 전원 정답 처리된 문항.',
'topic-018-area-yama-q-041':'① — 초기 β-amyloid 축적(무증상) → 중기 신경퇴행·측두엽(내측) 위축 → 말기 인지·행동 장애(MCI → 치매). 선지 중 순서가 맞는 것은 ①뿐이다.',
'topic-019-area-yama-q-014':'① — 뇌사는 원인이 알려진 혼수 + 뇌간반사 소실 + 무호흡이 모두 있어야 한다. ②는 각성(arousal)만 있고 인식(awareness)이 없는 식물상태도 "alert"로 볼 수 있어 맞는 설명으로 본다.',
'topic-021-area-yama-q-005':'③ 편측무시 — 교과서 정의("감각 기능은 정상이나 감각 자극을 대뇌에서 인지하는 데 장애 = 지각장애, 대표적인 것이 편측무시") 그대로다.',
'topic-021-area-yama-q-033':'⑤ 이해력 훈련 위주의 실어증 치료 — 오른손잡이이고 확산강조영상에서 좌측 측두–두정부(MCA 하분지) 병변이면 Wernicke 실어증(운동·감각은 대체로 정상)이 예상되기 때문. 병변 위치가 사진에 좌우되므로 추정이다.',
'topic-022-area-yama-q-020':'"옳지 않은 것"을 고르는 문제였다면 ① — 언어중추는 반대편으로 "이동"하는 것이 아니라 반대편 상동 영역 또는 양측이 기능을 맡도록 재조직화된다. 나머지(곁발아, 성인 가소성, 조기 재활, 치료 가능하다는 관점)는 모두 수업 내용과 맞다.',
'topic-022-area-yama-q-022':'③ 동측 대뇌피질 뒷발 영역 — 쥐 실험에서 손상된 앞발 영역 주변(같은 반구의 인접 뒷발 영역)으로 재조직화된다는 수업 내용에 맞는다(peri-infarct reorganization).',
'topic-022-area-yama-q-024':'① Thalamus가 정답 칸 기준. 강의록에는 없는 내용이라 확정하기 어렵고, 해설 본문은 cingulate gyrus를 적어 두었다 — 원 문제를 모르는 한 정답 칸(①)을 따른다.',
'topic-023-area-yama-q-008':'④ — 갑작스러운 심한 두통 + 기저조 고음영 → 비외상성 SAH. 다음 단계는 원인 동맥류 확인을 위한 CT 혈관조영(조영증강 CT)이다.',
'topic-024-area-yama-q-014':'③ 가·다 — "라"는 탈수초 신경병증 진단에 운동뿐 아니라 감각신경 전도검사도 포함되므로 맞는 설명이다. 그렇게 보면 가·다·라가 정답이지만 보기 조합에 없어 학습지는 ③을 골랐다.',
'topic-026-area-yama-q-011':'원 문제는 각 T1 고신호 물질과 영상을 짝짓는 문제. 모두 T1 고신호: 지방(지방종), MetHb(아급성 출혈), 고단백, 멜라닌(흑색종), Gd 조영제. 영상 없이 단일 답은 정할 수 없다.',
'topic-026-area-yama-q-019':'충격 반대쪽의 초승달 모양 경막하혈종(SDH) 사진이 countercoup 병변. EDH·두피혈종·골절은 coup 쪽.',
'topic-026-area-yama-q-017':'① — 복원자 기준. 한 사진 안에서 coup(맞은 쪽: EDH·두피혈종)과 contrecoup(반대쪽: SDH)이 함께 보이는 사진을 고르면 된다.',
}
