# 주관식 → 객관식 전환 스펙: cid -> (정답, 정답해설, [(오답, 해설)*4], 추가표시)
def M(c,ce,ds,note=None): return dict(c=c,ce=ce,ds=ds,note=note)
BG=M('선조체(꼬리핵·조가비핵), 창백핵, 흑질, 시상하핵, 중격의지핵','강의록 41쪽 기저핵 구성.',
 [('선조체, 창백핵, 흑질, 시상하핵, 치아핵','치아핵은 소뇌핵.'),('선조체, 창백핵, 적핵, 시상베개, 중격의지핵','적핵·시상베개는 기저핵 아님.'),('꼬리핵, 조가비핵, 해마, 편도, 유두체','해마·편도·유두체는 변연계.'),('시상, 시상하부, 흑질, 창백핵, 소뇌충부','시상·시상하부·소뇌는 아님.')])
CBL=M('Gait, rebound, finger-to-nose, heel-to-shin, rapid alternating movement, speech, nystagmus, hypotonia, pendular reflex, tremor','강의록 소뇌기능검사 목록.',
 [('Romberg, Babinski, Hoffmann, clonus, Tinel sign','Babinski·Hoffmann·clonus는 상부운동신경원 징후.'),('MMSE, clock drawing, Digit span, K-BNT','인지검사.'),('Gag reflex, palatal palsy, vocal cord palsy, swallowing','CN IX·X 검사.'),('Two-point discrimination, stereognosis, graphesthesia','대뇌(피질) 감각검사.')])
NE=M('정신·고위기능, 뇌신경, 운동계, 감각계, 반사, 소뇌기능, 자율신경기능 검사, 혼수환자 검진(+언어, 자세·보행)','강의록 신경학적 검사 항목.',
 [('뇌파, 근전도, 신경전도, 유발전위, 뇌척수액','전기진단·검사실 검사.'),('CT, MRI, MRA, PET, SPECT','영상검사.'),('활력징후, 흉부청진, 복부촉진, 림프절 촉진','일반 이학적 검사.'),('MMSE, MoCA, WAIS, K-BNT','신경심리검사(일부 항목일 뿐).')])
DTR2=M('2+','Reflex grading: 0 없음, 1+ 감소, 2+ 정상, 3+ 증가, 4+ clonus.',[('1+','감소.'),('3+','증가.'),('4+','clonus 동반.'),('5','MRC 근력 정상 등급.')])
ICP=M('두개내압(ICP) 하강','과호흡·만니톨·삼투제·두부거상은 모두 ICP를 낮추는 처치.',[('뇌관류압을 낮추기 위해','틀리다.'),('혈압을 올리기 위해','틀리다.'),('경련 예방','항경련제.'),('혈관연축 예방','nimodipine 등.')])
EDH=M('Epidural hematoma(경막외혈종)','중경막동맥 손상, lucid interval, 볼록렌즈 모양.',[('Acute subdural hematoma','교정맥, 초승달.'),('Subarachnoid hemorrhage','뇌고랑·조.'),('Diffuse axonal injury','shearing.'),('Chronic subdural hematoma','노인, 서서히.')])
C4=M('C4 — right central','monopolar에서 가장 음성(위로 솟은) spike 전극 = focus. 짝수 우측, C central.',[('C3 — left central','홀수는 좌측.'),('T4 — right temporal','틀리다.'),('F4 — right frontal','틀리다.'),('O2 — right occipital','틀리다.')])
ABS=M('Valproic acid, ethosuximide','3 Hz spike-wave → absence seizure.',[('ACTH, 스테로이드','infantile spasm.'),('Carbamazepine, phenytoin','absence 악화 가능.'),('Levodopa, carbidopa','파킨슨병.'),('Pyridostigmine, 스테로이드','중증근무력증.')])
BZD=M('Benzodiazepine, barbiturate','GABA-A 수용체 Cl⁻ 채널 개방 강화.',[('Carbamazepine, phenytoin','Na 채널 차단.'),('Ethosuximide, valproate','T-type Ca(ethosuximide).'),('Topiramate, lamotrigine','glutamate 억제 계열.'),('Levetiracetam, gabapentin','SV2A·α2δ.')])
AD_TX=M('Cholinesterase inhibitor(donepezil·rivastigmine·galantamine), memantine','경도–중등도 ChEI, 중등도–중증 memantine(donepezil은 전 병기).',[('Levodopa, pramipexole','파킨슨병.'),('Valproate, lamotrigine','항경련제.'),('Haloperidol 단독','증상 조절용, 치료제 아님.'),('Interferon-β, natalizumab','다발경화증.')])
AD_PATH=M('Senile plaque(amyloid β)와 neurofibrillary tangle(tau)','세포 밖 Aβ plaque, 세포 안 tau NFT.',[('Lewy body(α-synuclein)와 Pick body','DLB·FTD.'),('Hirano body와 Negri body','틀리다.'),('Spongiform change와 prion','CJD.'),('다발성 열공경색과 백질변성','혈관성.')])
TREAT=M('정상압 수두증, 갑상선기능저하증, 비타민 B12·thiamine 결핍, 신경매독, 만성 경막하혈종, 뇌종양, 알코올, 우울증','강의록 Treatable causes of dementia.',[('알츠하이머병, 전두측두치매, 루이소체치매','퇴행성·진행성.'),('파킨슨병 치매, 헌팅턴병','퇴행성.'),('CJD, 진행성 핵상마비','치료 불가.'),('혈관성 치매, 다발성 경색','예방은 가능하나 되돌리기 어려움.')])
PROG=M('Alzheimer, frontotemporal, Lewy body, Parkinson’s disease dementia','진행성(퇴행성) 치매 4가지.',[('정상압 수두증, 갑상선저하, B12 결핍, 신경매독','치료 가능한 치매.'),('만성 경막하혈종, 뇌종양, 우울증','치료 가능한 원인.'),('섬망, 약물중독, 저혈당','가역적.'),('편두통, 긴장형두통, 군발두통','두통.')])
REORG=M('재조직화(reorganization)','가소성을 통해 손상된 뇌가 재조직화.',[('재생(regeneration)','괴사 조직 재생 아님.'),('고착화','틀리다.'),('퇴행','틀리다.'),('조직화(organization)','원래 상태.')])
DST=M('Congenital dermal sinus tract','정중선 피부 누공 + 반복 수막염.',[('Tethered cord syndrome','하지·배뇨 증상.'),('Myelomeningocele','개방성 척수이분증.'),('Chiari II malformation','뇌간 하방 탈출.'),('Encephalocele','뇌탈출.')])
METOP=M('Metopic suture','Trigonocephaly(삼각두) = 이마봉합 조기유합.',[('Sagittal suture','scaphocephaly.'),('Coronal suture(양측)','brachycephaly.'),('Lambdoid suture','posterior plagiocephaly.'),('Squamosal suture','틀리다.')])
S={
'topic-001-area-yama-q-001':M('Geschwind’s territory','BA39·40 = Geschwind 영역(강의록 39쪽).',[('Broca’s area','BA44·45.'),('Wernicke’s area(BA22)','상측두회.'),('Primary auditory cortex','BA41·42.'),('Exner’s area','쓰기 중추.')]),
'topic-001-area-yama-q-002':M('Central tegmental tract','뇌간 망상체 → 시상 수질판속핵.',[('Medial lemniscus','고유감각.'),('Spinothalamic tract','통각·온도.'),('Corticospinal tract','운동.'),('Medial longitudinal fasciculus','안구운동 연결.')]),
'topic-001-area-yama-q-023':M('Centromedian, parafascicular, intralaminar nucleus','시상 수질판속핵 계열.',[('VPL, VPM nucleus','감각 중계.'),('Lateral·medial geniculate body','시각·청각.'),('Anterior nucleus, mammillary body','Papez.'),('Pulvinar, lateral posterior nucleus','연합.')]),
'topic-001-area-yama-q-024':M('Gerstmann syndrome','좌우지남력장애·손가락실인·실서증·실산증.',[('Anton syndrome','피질맹 부인.'),('Balint syndrome','양측 두정후두.'),('Kluver-Bucy syndrome','양측 측두엽.'),('Alien hand syndrome','뇌량·SMA.')]),
'topic-001-area-yama-q-025':M('Ipsilateral','소뇌 사지 협응 장애는 동측.',[('Contralateral','틀리다.'),('Bilateral 대칭','틀리다.'),('상지만 반대측','틀리다.'),('증상 없음','틀리다.')]),
'topic-001-area-yama-q-026':M('Central sulcus','중심전회·중심후회 경계.',[('Lateral(Sylvian) fissure','전두·측두 경계.'),('Parieto-occipital sulcus','두정·후두.'),('Calcarine sulcus','시각피질.'),('Cingulate sulcus','띠이랑.')]),
'topic-001-area-yama-q-027':M('39 — angular gyrus / 40 — supramarginal gyrus','BA39 각회, BA40 모서리위회.',[('39 — supramarginal / 40 — angular','반대.'),('39 — superior temporal / 40 — middle temporal','틀리다.'),('39 — precentral / 40 — postcentral','틀리다.'),('39 — cuneus / 40 — lingual','후두엽.')]),
'topic-001-area-yama-q-028':M('Hippocampus','변연계 input의 핵심.',[('Amygdala','정서.'),('Mammillary body','Papez 경유.'),('Cingulate gyrus','Papez 경유.'),('Fornix','출력 경로.')]),
'topic-001-area-yama-q-029':M('Intralaminar nucleus(internal medullary lamina 내 핵군)','CM·Pf와 함께 수질판속핵. (원본도 답 불확실)',[('Pulvinar','연합핵.'),('VPL nucleus','감각 중계.'),('Reticular nucleus of thalamus','억제성 외피.'),('Lateral geniculate body','시각.')]),
'topic-001-area-yama-q-030':BG,'topic-001-area-yama-q-035':BG,'topic-001-area-yama-q-040':BG,
'topic-001-area-yama-q-031':M('구음장애(dysarthria)','조음 협응 장애.',[('Broca 실어증','피질 언어.'),('Wernicke 실어증','피질 언어.'),('실독증','PCA.'),('전도실어증','궁상다발.')]),
'topic-001-area-yama-q-032':M('CN III, IV','중뇌 핵.',[('CN V, VI, VII','뇌교.'),('CN IX, X, XII','연수.'),('CN I, II','전뇌.'),('CN VIII, XI','틀리다.')]),
'topic-001-area-yama-q-033':M('Fornix','해마 출력 경로(→ 유두체).',[('Corpus callosum','반구 연결.'),('Internal capsule','투사섬유.'),('Arcuate fasciculus','언어.'),('Uncinate fasciculus 단독','전두-측두.')]),
'topic-001-area-yama-q-034':M('감각 입력 → 뇌간 망상체 → central tegmental tract → 시상 수질판속핵(CM·Pf) → 대뇌피질','강의록 49쪽.',[('척수시상로 → VPL → 체성감각피질','감각 경로.'),('피질척수로 → 전각세포','운동.'),('해마 → 뇌궁 → 유두체 → 시상전핵','Papez.'),('망막 → LGB → 후두엽','시각.')]),
'topic-001-area-yama-q-036':M('기억·학습, 자율신경 조절, 본능·감정','변연계 기능.',[('수의운동 개시','운동피질.'),('시각 처리','후두엽.'),('평형·협응','소뇌.'),('언어 표현','Broca.')]),
'topic-001-area-yama-q-037':M('CN V, VI, VII','원본 답(8번 일부 걸침 주의).',[('CN III, IV','중뇌.'),('CN IX, X, XII','연수.'),('CN I, II','전뇌.'),('CN XI만','척수부.')]),
'topic-001-area-yama-q-041':M('하루 약 500 cc / 뇌실 내 약 35–50 cc','학습지 제공 답.',[('하루 약 150 cc / 뇌실 내 약 500 cc','뒤바뀜.'),('하루 약 50 cc / 뇌실 내 약 5 cc','틀리다.'),('하루 약 1500 cc / 뇌실 내 약 150 cc','틀리다.'),('하루 약 250 cc / 뇌실 내 약 250 cc','틀리다.')]),
'topic-002-area-yama-q-013':M('MRI로 누관 확인 후 병변 근치적 절제','Dermal sinus tract.',[('항생제만 장기 투여','재발.'),('요추천자 반복','틀리다.'),('션트 삽입','수두증 치료.'),('경과관찰','틀리다.')]),
'topic-002-area-yama-q-014':METOP,'topic-002-area-yama-q-016':METOP,
'topic-002-area-yama-q-015':M('검사: 초음파·MRI / 처치: 근치적 제거술','깊이 파악 후 완전 제거.',[('검사: 뇌파 / 처치: 항경련제','틀리다.'),('검사: 요추천자 / 처치: 항생제만','재발.'),('검사: 단순 X-ray / 처치: 경과관찰','틀리다.'),('검사: CT / 처치: 피부 봉합만','불완전.')]),
'topic-002-area-yama-q-018':DST,'topic-002-area-yama-q-020':DST,'topic-002-area-yama-q-022':DST,
'topic-002-area-yama-q-027':M('Suturectomy(봉합선 절개 후 remodeling)','Craniosynostosis 치료.',[('Shunt operation','수두증.'),('Duraplasty','경막.'),('Detethering','tethered cord.'),('Endoscopic third ventriculostomy','수두증.')]),
'topic-002-area-yama-q-028':M('Disorders of secondary neurulation(tethered cord)','종사 두꺼움·lipoma가 conus 상승 방해.',[('Chiari malformation','후뇌.'),('Dandy-Walker malformation','후두와.'),('Holoprosencephaly','전뇌 분리.'),('Encephalocele','일차 신경관.')]),
'topic-002-area-variants-q-026':M('Heterotopia, schizencephaly, pachygyria','이주이상질환(neuronal migration). 원 변형 문항의 정답 표시가 깨져 있어 강의록 분류로 재구성.',[('Encephalocele, dermal sinus tract','신경관 형성 이상.'),('Porencephaly, encephalocele','파괴성·신경관.'),('Holoprosencephaly, dermal sinus tract','전뇌분리·이차.'),('Encephalocele, holoprosencephaly, porencephaly','이주이상 아님.')],note='원 변형 문항 정답 텍스트 깨짐 → 재구성'),
'topic-003-area-yama-q-022':M('Visual and body perception(시지각·신체지각)','얼굴 알아보기, 좌우 신체지각.',[('기억력','틀리다.'),('계산력','틀리다.'),('언어 유창성','틀리다.'),('집행기능','틀리다.')]),
'topic-003-area-yama-q-023':CBL,'topic-003-area-yama-q-024':CBL,'topic-003-area-yama-q-032':CBL,'topic-006-area-yama-q-009':CBL,
'topic-003-area-yama-q-025':DTR2,'topic-003-area-yama-q-031':DTR2,
'topic-003-area-yama-q-026':M('Power(근력)와 tone(긴장도)','운동계 검사.',[('Reflex와 sensation','반사·감각.'),('Gait와 balance','소뇌·보행.'),('Vision과 hearing','뇌신경.'),('Memory와 orientation','고위기능.')]),
'topic-003-area-yama-q-036':M('Tone(긴장도)','운동검사: power + tone.',[('반사','별도 항목.'),('감각','별도.'),('보행','별도.'),('인지','별도.')]),
'topic-003-area-yama-q-027':M('힘줄 급신전 → muscle spindle 자극 → 척수 α 운동신경원 → 근육 반사수축','단일연접 신장반사.',[('피부 자극 → 척수시상로 → 시상 → 피질 → 수의수축','수의운동.'),('Golgi 건기관 → 근육 이완만','역신장반사.'),('뇌간 망상체 → 근긴장 증가','틀리다.'),('소뇌 → 협응 수축','틀리다.')]),
'topic-003-area-yama-q-028':M('소뇌','Finger-to-nose = 소뇌기능검사.',[('기저핵','틀리다.'),('전두엽','틀리다.'),('척수 후주','Romberg.'),('뇌간','틀리다.')]),
'topic-003-area-yama-q-029':M('추체외로계(기저핵·소뇌)','이상운동질환.',[('추체로(피질척수로)','마비.'),('말초신경','틀리다.'),('신경근접합부','근무력.'),('척수 후주','감각실조.')]),
'topic-003-area-yama-q-030':M('5','MRC 정상 5.',[('4','약간 감소.'),('3','중력 대항.'),('2+','DTR 정상.'),('10','틀리다.')]),
'topic-003-area-yama-q-033':M('신경계(뇌·척수·말초신경) 질환을 진단·치료하는 의학 전문분야','정의.',[('정신질환을 약물로 치료하는 분야','정신건강의학.'),('신경계를 수술로 치료하는 분야','신경외과.'),('신경계 영상을 판독하는 분야','영상의학.'),('근골격계 기능을 회복시키는 분야','재활의학.')]),
'topic-003-area-yama-q-034':M('뇌졸중, 어지럼, 두통, 이상운동질환, 치매, 수면장애, 경련, 다발경화증, 척수·말초신경·NMJ·근육질환','강의록 신경학적 증후군.',[('고혈압, 당뇨, 고지혈증, 비만, 흡연','위험인자.'),('폐렴, 요로감염, 패혈증','감염.'),('우울증, 조현병, 불안장애','정신과.'),('골절, 탈구, 인대손상','정형외과.')]),
'topic-003-area-yama-q-035':M('CN IX(설인신경)와 CN X(미주신경)','구개·성대·삼킴·구역반사.',[('CN V, VII','삼차·안면.'),('CN XI, XII','부신경·설하.'),('CN III, IV, VI','안구운동.'),('CN VIII','청각·평형.')]),
'topic-003-area-yama-q-037':M('국소, 방사성, 대칭성 원위부, 감각해리, 감각실조, 피질성 감각이상','강의록 ppt 77.',[('편마비, 사지마비, 하반신마비','운동.'),('실어증, 실행증, 실인증','고위기능.'),('진전, 무도증, 근긴장이상','이상운동.'),('안진, 복시, 안검하수','안구.')]),
'topic-003-area-yama-q-038':M('통각·온도 — 척수시상로, 가는(Aδ·C) 섬유 / 고유감각·진동·정밀촉각 — 후주-내측섬유띠, 굵은(Aβ) 섬유','원본 정답 미기재 → 강의 내용 기반 AI 추정 정답.',[('통각·온도 — 후주, 굵은 섬유 / 진동 — 척수시상로, 가는 섬유','뒤바뀜.'),('모든 감각 — 피질척수로','운동로.'),('통각 — 척수소뇌로 / 진동 — 망상척수로','틀리다.'),('고유감각 — 척수시상로, C 섬유','틀리다.')],note='원본 정답 미기재 · AI 추정'),
'topic-003-area-yama-q-039':M('E(1–4)+V(1–5)+M(1–6), 총 3–15점; 13↑ 경도, 9–12 중등도, 8↓ 중증','GCS 최저 3점.',[('E(1–5)+V(1–5)+M(1–5), 0–15점','틀리다.'),('E(1–4)+V(1–6)+M(1–5), 3–15점','V·M 뒤바뀜.'),('0–10점, 높을수록 중증','틀리다.'),('E+M만 합산, 2–10점','틀리다.')]),
'topic-004-area-variants-q-019':M('시신경척수염(NMOSD) — AQP4(astrocyte 수분통로) 항체 질환','시신경염+횡단성 척수염+area postrema 증상(구역·구토)+AQP4 양성. 원 변형 문항 정답 텍스트 깨짐 → 재구성.',[('다발경화증 — MOG 항체','MOG는 MOGAD.'),('길랭-바레 증후군','말초.'),('급성파종뇌척수염 — 감염·예방접종 후','기왕력 없음.'),('중증근무력증 — AChR 항체','NMJ.')],note='원 변형 문항 정답 텍스트 깨짐 → 재구성'),
'topic-006-area-yama-q-003':NE,'topic-006-area-yama-q-005':NE,'topic-006-area-yama-q-006':NE,'topic-006-area-yama-q-007':NE,'topic-006-area-yama-q-010':NE,
'topic-006-area-yama-q-004':M('신경계 구조·기능을 이해하고 이상 징후를 해석해 병변의 종류와 부위를 찾는 검진','국소화가 핵심.',[('뇌영상으로 병변을 확인하는 것','영상.'),('혈액검사로 원인을 찾는 것','틀리다.'),('근력만 측정하는 것','일부.'),('환자 주관적 증상만 기록하는 것','틀리다.')]),
'topic-006-area-yama-q-008':M('방사통(radicular pain)','국소·연관·방사·CRPS·시상통.',[('환상통','틀리다.'),('중추성 통증','시상통 포함.'),('신경병증성 통증','포괄.'),('근막통','틀리다.')]),
'topic-008-area-yama-q-003':M('양상, 정도, 위치, 기간, 경과, 발생·악화·완화 인자','통합강의록.',[('혈압, 맥박, 체온','활력징후.'),('뇌파, 근전도','검사.'),('MMSE, GDS','인지·우울.'),('시력, 청력만','일부.')]),
'topic-008-area-yama-q-008':M('Central sensitization(시상 감작)','박동성 두통 지속 → 시상까지 감작.',[('Peripheral nerve compression','틀리다.'),('Cortical spreading depression','조짐.'),('Vasodilation of retinal artery','틀리다.'),('Increased intracranial pressure','틀리다.')]),
'topic-008-area-yama-q-009':M('B–D 만족 발작 5회↑; 2(1)–72시간; 편측(소아 양측 가능)·박동·중등도↑·활동 악화 중 2↑; 구역/구토 또는 빛·소리 공포 1↑','소아 IHS 기준.',[('발작 2회↑; 4–72시간; 편측만 인정; 조짐 필수','틀리다.'),('발작 5회↑; 15분–3시간; 자율신경 증상 동반','군발두통.'),('발작 10회↑; 30분–7일; 압박성·양측','긴장형.'),('발작 1회; 지속시간 무관','틀리다.')]),
'topic-009-area-yama-q-017':M('동맥류 파열 지주막하출혈 / 개두술 동맥류 경부 결찰(clipping)','사진: SAH + clipping.',[('고혈압성 뇌출혈 / 혈종 흡인','틀리다.'),('경막외혈종 / 개두 혈종제거','외상.'),('모야모야 / EDAS','틀리다.'),('AVM / 감마나이프','틀리다.')]),
'topic-009-area-yama-q-018':M('좌측 lenticulostriate artery','우측 편마비 + 기저핵 출혈.',[('우측 lenticulostriate artery','반대.'),('좌측 PICA','틀리다.'),('우측 ACA','틀리다.'),('기저동맥','틀리다.')]),
'topic-009-area-yama-q-019':M('Moyamoya disease','양측 ICA 협착 + 측부혈관.',[('AVM','틀리다.'),('Amyloid angiopathy','틀리다.'),('Carotid dissection','틀리다.'),('Vasculitis(GCA)','틀리다.')]),
'topic-009-area-yama-q-020':M('Cerebral amyloid angiopathy','고령·엽상출혈·Aβ.',[('고혈압성 뇌출혈','심부.'),('AVM 파열','젊은 층.'),('모야모야','소아·성인.'),('해면상 혈관종','틀리다.')]),
'topic-009-area-yama-q-043':M('Cerebral amyloid angiopathy','고령·고혈압 없음·Aβ 침착.',[('고혈압성 세동맥경화','틀리다.'),('CADASIL','유전.'),('모야모야','틀리다.'),('거대세포동맥염','틀리다.')]),
'topic-009-area-yama-q-021':M('감마나이프 방사선수술','비관혈적 AVM 치료.',[('개두술 절제','관혈적.'),('색전술','혈관내 시술(마취).'),('Clipping','동맥류.'),('EDAS','모야모야.')]),
'topic-009-area-yama-q-022':M('뇌혈관연축(vasospasm)','3일째 시작·6–8일 최고.',[('재출혈','심각하나 강조 답 아님.'),('수두증','합병증.'),('저나트륨혈증','합병증.'),('경련','합병증.')]),
'topic-009-area-yama-q-035':M('미세혈관 감압술(MVD)','반측안면경련.',[('Gamma knife','틀리다.'),('안면신경 절단','틀리다.'),('Botulinum toxin 영구 주사','수술 아님.'),('Rhizotomy','삼차신경통 일부.')]),
'topic-009-area-yama-q-039':M('4점','size 3–6 cm 2 + eloquent 1 + deep 1.',[('3점','틀리다.'),('5점','틀리다.'),('2점','틀리다.'),('6점','틀리다.')]),
'topic-009-area-yama-q-040':M('Hypertension, hypervolemia, hemodilution','triple H.',[('Hypotension, hypovolemia, hemoconcentration','반대.'),('Hyperventilation, hyperosmolarity, hypothermia','ICP 처치.'),('Heparin, hydration, hypothermia','틀리다.'),('Hypertension, hypovolemia, hemodilution','틀리다.')]),
'topic-009-area-yama-q-041':M('EDAS: encephalo-duro-arterio-synangiosis / EMS: encephalo-myo-synangiosis / EC-IC: extracranial-intracranial bypass','모야모야 문합술.',[('EDAS: extra-dural artery stenting / EMS: endovascular microstent','틀리다.'),('EDAS: encephalo-duro-arterio-synangiosis / EMS: extracranial-muscle shunt','틀리다.'),('EC-IC: external carotid–internal cerebral vein','틀리다.'),('EMS: encephalo-meningeal suture','틀리다.')]),
'topic-009-area-yama-q-042':M('Size, eloquence, venous drainage','Spetzler-Martin.',[('Size, age, rupture 여부','틀리다.'),('Location, feeder 수, aneurysm 동반','틀리다.'),('GCS, Hunt-Hess, Fisher','틀리다.'),('Flow, shape, calcification','틀리다.')]),
'topic-009-area-yama-q-045':M('①③⑤⑦⑧','Hypervolemia, hemodilution, hypertension, IA nimodipine, balloon angioplasty.',[('②④⑥⑦⑧','반대 조건.'),('①③⑤','IA nimodipine·풍선 누락.'),('①④⑤⑧','hemoconcentration 틀림.'),('②③⑥⑦','틀리다.')]),
'topic-009-area-yama-q-046':M('Warfarin 역전(비타민 K·FFP/PCC) 후 정위적 혈종 흡인술, 뇌실 내 출혈·수두증 동반 시 뇌실외배액술','원본 정답 미기재 → 강의 내용 기반 AI 추정.',[('즉시 혈전용해제 투여','금기.'),('경동맥 스텐트','무관.'),('동맥류 clipping','무관.'),('항응고 유지하며 관찰만','틀리다.')],note='원본 정답 미기재 · AI 추정'),
'topic-009-area-yama-q-047':M('개두술 절제, 혈관내 색전술, 감마나이프','AVM 치료 3가지.',[('EDAS, EMS, EC-IC bypass','모야모야.'),('Clipping, coiling, wrapping','동맥류.'),('MVD, rhizotomy','안면경련.'),('Shunt, ETV','수두증.')]),
'topic-010-area-yama-q-025':M('9 (E2 V2 M5)','통증에 눈뜸 2, 신음 2, 국재 5.',[('8 (E2 V2 M4)','도피 아님.'),('10 (E3 V2 M5)','E3는 음성.'),('7 (E1 V2 M4)','틀리다.'),('9 (E2 V3 M4)','틀리다.')]),
'topic-010-area-yama-q-026':M('Acute epidural hematoma','렌즈 + 중경막동맥 + lucid interval (phase까지).',[('Acute subdural hematoma','초승달.'),('Chronic subdural hematoma','노인.'),('Traumatic SAH','틀리다.'),('Contusion','실질.')]),
'topic-010-area-yama-q-027':ICP,'topic-010-area-yama-q-038':ICP,'topic-010-area-yama-q-041':ICP,
'topic-010-area-yama-q-031':EDH,'topic-010-area-yama-q-037':EDH,'topic-010-area-yama-q-039':EDH,
'topic-010-area-yama-q-035':M('Coup contusion(충좌상, 접촉 부위 손상)','접촉 부위: 두피·골절·EDH.',[('Contrecoup contusion','반대측.'),('Diffuse axonal injury','회전.'),('Intermediate coup','틀리다.'),('Shaken baby','틀리다.')]),
'topic-010-area-yama-q-040':M('Subdural hematoma','초승달 모양.',[('Epidural hematoma','렌즈.'),('SAH','틀리다.'),('Contusion','틀리다.'),('Subdural hygroma','CSF 음영.')]),
'topic-010-area-yama-q-044':M('두부거상, 진정, 과호흡, CSF 배액, 삼투요법(mannitol), 신경근차단, barbiturate coma','강의록 slide 31.',[('수액 과다 투여, 두부 하강, 저나트륨 유도','ICP 악화.'),('혈전용해제, 항응고','틀리다.'),('고탄산혈증 유도','혈관 확장.'),('요추천자 반복','탈출 위험.')]),
'topic-010-area-yama-q-045':M('①③⑤ (Raccoon eye, CSF 비루, 후각소실)','전두와 골절.',[('④⑥⑦','중두개와.'),('②④⑥','측두골.'),('①④⑦','혼합.'),('③⑥⑦','혼합.')]),
'topic-010-area-yama-q-046':M('의식 저하, 반대측 편마비, 동측 동공산대·안검하수','Uncal herniation.',[('양측 동공 축동, 사지 이완','틀리다.'),('동측 편마비, 반대측 동공산대만','일반 양상 반대.'),('하지 마비, 요실금','틀리다.'),('발열, 경부강직','수막염.')]),
'topic-010-area-yama-q-047':M('두께 ≥10 mm 또는 정중선 이동 ≥5 mm면 GCS 무관 수술, GCS<9 악화·동공이상·ICP>20이면 수술','ASDH 수술 적응.',[('두께 ≥3 mm면 무조건 수술','틀리다.'),('GCS 15면 모두 수술','틀리다.'),('정중선 이동 ≥20 mm일 때만','틀리다.'),('수술 적응 없음','틀리다.')]),
'topic-010-area-yama-q-048':M('PaCO2 30–35 mmHg','25 이하 허혈 위험.',[('PaCO2 15–20 mmHg','허혈.'),('PaCO2 45–50 mmHg','과탄산.'),('PaCO2 40–45 mmHg','정상.'),('PaCO2 55 mmHg 이상','틀리다.')]),
'topic-013-area-yama-q-022':M('군발성 두통(cluster headache)','자율신경 증상 동반.',[('편두통','틀리다.'),('긴장형 두통','틀리다.'),('측두동맥염','틀리다.'),('부비동염 두통','틀리다.')]),
'topic-013-area-yama-q-023':M('측두동맥염(giant cell arteritis)','고령·ESR↑·steroid 반응.',[('군발두통','틀리다.'),('편두통','틀리다.'),('삼차신경통','틀리다.'),('특발성 두개내압상승','틀리다.')]),
'topic-014-area-yama-q-041':M('좌측 중대뇌동맥(Lt. MCA)','우측 편마비+안면마비+실어증.',[('우측 중대뇌동맥','반대.'),('좌측 전대뇌동맥','하지.'),('기저동맥','의식.'),('좌측 후대뇌동맥','시야.')]),
'topic-017-area-yama-q-011':M('좌측 뇌종양, 좌측 경색, 좌측 혈관기형(좌측 대뇌 병변)','좌측 alpha 소실.',[('우측 대뇌 병변','반대.'),('Absence epilepsy','3 Hz.'),('정상 수면','틀리다.'),('간성뇌증','전반.')]),
'topic-017-area-yama-q-012':M('Right centrotemporoparietal(C4)','C4 최대.',[('Left central(C3)','홀수 좌.'),('Right occipital(O2)','틀리다.'),('Left temporal(T3)','틀리다.'),('Midline(Cz)','틀리다.')]),
'topic-017-area-yama-q-013':C4,'topic-017-area-yama-q-028':C4,'topic-017-area-yama-q-030':C4,'topic-017-area-yama-q-031':C4,'topic-017-area-yama-q-039':C4,
'topic-017-area-yama-q-014':ABS,'topic-017-area-yama-q-015':ABS,
'topic-017-area-yama-q-016':BZD,'topic-017-area-yama-q-023':BZD,
'topic-017-area-yama-q-020':M('NREM stage 2(sleep spindle)','12 Hz 2–4초 방추.',[('NREM stage 1(vertex sharp)','틀리다.'),('NREM stage 3(slow wave)','틀리다.'),('REM(saw tooth)','틀리다.'),('각성(posterior alpha)','틀리다.')]),
'topic-017-area-yama-q-021':M('T4 — right temporal','뒤쪽 monopolar에서 T4 최대 음성.',[('T3 — left temporal','홀수 좌.'),('C4 — right central','틀리다.'),('F8 — right frontal','틀리다.'),('O2','틀리다.')]),
'topic-017-area-yama-q-022':M('Chloride channel','GABA-A.',[('Sodium channel','틀리다.'),('Potassium channel','GABA-B.'),('Calcium channel','틀리다.'),('Magnesium channel','틀리다.')]),
'topic-017-area-yama-q-024':M('Mg2+','Mg가 NMDA 차단.',[('Na+','틀리다.'),('K+','틀리다.'),('Cl−','틀리다.'),('HCO3−','틀리다.')]),
'topic-017-area-yama-q-025':M('각성 상태 / 좌측 alpha 소실 → 좌측 대뇌피질 기능 이상','A-P gradient 비대칭.',[('수면 2단계 / 정상','틀리다.'),('각성 / 우측 대뇌 이상','반대.'),('REM / 전반적 서파','틀리다.'),('혼수 / burst suppression','틀리다.')]),
'topic-017-area-yama-q-026':M('L3–L4 또는 L4–L5(Tuffier line)','장골능선.',[('T12–L1','척수원추.'),('L1–L2','척수 손상 위험.'),('S1–S2','틀리다.'),('C1–C2','틀리다.')]),
'topic-017-area-yama-q-027':M('(1) ACTH·스테로이드 / (2) valproic acid·ethosuximide','hypsarrhythmia / 3 Hz.',[('(1) ethosuximide / (2) ACTH','뒤바뀜.'),('(1) carbamazepine / (2) phenytoin','틀리다.'),('(1) valproate / (2) carbamazepine','틀리다.'),('(1) levodopa / (2) pyridostigmine','틀리다.')]),
'topic-017-area-yama-q-029':M('GABA — Cl⁻ / NMDA — Ca²⁺·Na⁺ / AMPA — Na⁺','강의록.',[('GABA — Na⁺ / NMDA — Cl⁻ / AMPA — K⁺','틀리다.'),('GABA — K⁺ / NMDA — Mg²⁺ / AMPA — Cl⁻','틀리다.'),('GABA — Ca²⁺ / NMDA — Na⁺ / AMPA — Cl⁻','틀리다.'),('모두 Na⁺','틀리다.')]),
'topic-017-area-yama-q-032':M('A-P gradient — 정상 각성 뇌파','앞 빠른저전위, 뒤 alpha.',[('3 Hz spike-wave','absence.'),('Hypsarrhythmia','infantile spasm.'),('Sleep spindle','N2.'),('Burst suppression','혼수.')]),
'topic-017-area-yama-q-035':M('두개내압 상승(탈출 위험)과 천자부위 피부감염','금기(+혈소판 감소, 위중).',[('발열과 두통','적응.'),('의식저하 없는 수막자극','적응.'),('다발경화증 의심','적응.'),('길랭-바레 의심','적응.')]),
'topic-017-area-yama-q-036':M('T3 — left temporal','홀수 좌, T 측두.',[('T4 — right temporal','반대.'),('C3','틀리다.'),('F7','틀리다.'),('O1','틀리다.')]),
'topic-017-area-yama-q-038':M('1) 세균성 수막염 / 2) 바이러스성(무균성) 수막염','PMN vs 림프구.',[('1) 바이러스성 / 2) 세균성','반대.'),('1) 결핵성 / 2) 세균성','틀리다.'),('1) 다발경화증 / 2) 세균성','틀리다.'),('1) 진균성 / 2) 세균성','틀리다.')]),
'topic-018-area-yama-q-026':AD_TX,'topic-018-area-yama-q-031':AD_TX,
'topic-018-area-yama-q-027':M('Behavioral variant FTD(bvFTD)','사회적 부적절 행동.',[('Semantic dementia','의미.'),('Progressive nonfluent aphasia','언어.'),('Alzheimer disease','기억.'),('Lewy body dementia','환시.')]),
'topic-018-area-yama-q-028':TREAT,'topic-018-area-yama-q-034':TREAT,'topic-018-area-yama-q-058':TREAT,
'topic-018-area-yama-q-029':PROG,'topic-018-area-yama-q-032':PROG,
'topic-018-area-yama-q-030':AD_PATH,'topic-018-area-yama-q-033':AD_PATH,
'topic-018-area-yama-q-035':M('ABCD — ADL, Behavior, Cognition, Differential diagnosis','CSBD는 ABCD 오기로 추정.',[('ABCD — Airway, Breathing, Circulation, Disability','응급.'),('CSBD — Cognition, Sleep, Behavior, Depression','틀리다.'),('ADL, IADL, MMSE, CDR','일부.'),('Amyloid, Blood, CSF, DWI','틀리다.')]),
'topic-018-area-yama-q-043':M('1-year rule: 치매가 파킨슨 증상 전 또는 1년 이내면 DLB, 파킨슨병 확립 후면 PDD','감별 도구.',[('3-month rule','틀리다.'),('환시 유무만','틀리다.'),('나이 65세 기준','틀리다.'),('DLB가 PDD로 진행','틀리다.')]),
'topic-018-area-yama-q-047':M('초기 β-amyloid 축적 → 중기 측두엽 중심 위축(NFT) → 말기 인지·행동장애','Aβ → 신경퇴행 → 증상.',[('인지장애 → 위축 → amyloid','역순.'),('위축 → amyloid → 인지장애','틀리다.'),('tau → Lewy body → 인지','틀리다.'),('혈관병변 → 위축 → amyloid','틀리다.')]),
'topic-018-area-variants-q-053':M('Semantic memory — temporal lobe','기억 구성–뇌영역. 원 변형 문항 정답 텍스트 깨짐 → 재구성.',[('Classical conditioning — parietal lobe','틀리다.'),('Conditioned reflex — frontal lobe','틀리다.'),('Episodic memory — cerebellum','내측측두.'),('Procedural memory — temporal lobe','기저핵·소뇌.')],note='원 변형 문항 정답 텍스트 깨짐 → 재구성'),
'topic-019-area-yama-q-017':M('Decerebrate rigidity — 중뇌 이하(뇌교 상부) 병변','팔·다리 신전.',[('Decorticate rigidity — 대뇌반구·간뇌','팔 굴곡.'),('Opisthotonus — 척수','틀리다.'),('Flaccid — 연수','틀리다.'),('Catatonia — 전두엽','틀리다.')]),
'topic-021-area-yama-q-026':M('운동실어증(나), 우측 상지 마비(다)','좌측 MCA 상분지.',[('감각실어증(가), 우측 하지 마비(마)','하분지·ACA.'),('편측무시(사), 좌측 상지 마비(라)','우반구.'),('무동무언증(아), 우측 하지 마비(마)','ACA.'),('운동실어증(나), 좌측 하지 마비(바)','틀리다.')]),
'topic-021-area-yama-q-037':M('대뇌(피질)감각 — 입체감각, 서화감각','통합감각.',[('표재감각','촉·통·온.'),('심부감각(고유위치·진동)','틀리다.'),('운동기능','틀리다.'),('소뇌기능','틀리다.')]),
'topic-021-area-yama-q-040':M('6) 좌측 전뇌동맥','하지 위주+초피질 운동실어증.',[('3) 좌측 중뇌동맥 상지','상지·Broca.'),('4) 좌측 중뇌동맥 하지','Wernicke.'),('5) 우측 전뇌동맥','좌측 하지.'),('7) 후뇌동맥','시야.')]),
'topic-021-area-yama-q-041':M('12) 편측무시, 16) 운동과 감각 기능은 대체로 정상','우측 MCA 하분지.',[('8) 상지>하지 편마비, 10) 운동실어증','상분지 좌측.'),('9) 하지>상지, 13) 무동무언증','ACA.'),('14) 중추성통증, 15) 난독증','PCA.'),('11) 감각실어증, 8) 상지>하지 편마비','좌반구·상분지.')]),
'topic-022-area-yama-q-015':REORG,'topic-022-area-yama-q-017':REORG,'topic-022-area-yama-q-021':REORG,
'topic-022-area-yama-q-019':M('위치','크기와 위치.',[('나이','틀리다.'),('의지','틀리다.'),('가족 간병','틀리다.'),('동반질환','틀리다.')]),
'topic-022-area-yama-q-027':M('fMRI','비침습 뇌기능 영상.',[('PET','방사성동위원소 주사(침습).'),('뇌혈관조영술','침습.'),('CT','구조.'),('뇌생검','침습.')]),
'topic-022-area-variants-q-026':M('뇌졸중의 중증도','Goal setting 핵심(영상으로 판단). 원 변형 문항 정답 텍스트 깨짐 → 재구성.',[('경제적 상황','틀리다.'),('환자의 나이','틀리다.'),('환자의 치료 의지','틀리다.'),('발병 전 직업','틀리다.')],note='원 변형 문항 정답 텍스트 깨짐 → 재구성'),
'topic-023-area-yama-q-018':M('가 CCA, 나 MCA, 다 vertebral, 라 basilar, 마 ACA','학습지 정답 ④(다-vertebral, 나-MCA).',[('가 ECA, 나 ACA, 다 vertebral, 라 PCA, 마 MCA','틀리다.'),('가 CCA, 나 ACA, 다 basilar, 라 vertebral, 마 MCA','틀리다.'),('가 ICA, 나 PCA, 다 vertebral, 라 basilar, 마 ACA','틀리다.'),('가 CCA, 나 MCA, 다 ICA, 라 PCA, 마 ACA','틀리다.')]),
'topic-024-area-yama-q-013':M('c — right radial nerve(Saturday night palsy)','wrist drop + 제1–2지 손등 저림.',[('a — right median nerve','수근관.'),('e — right ulnar nerve','claw.'),('d — left radial nerve','반대.'),('b — left median nerve','틀리다.')]),
'topic-024-area-yama-q-015':M('F-wave, H-reflex','late responses.',[('Blink reflex, RNS','틀리다.'),('CMAP, SNAP','틀리다.'),('MEP, SEP','유발전위.'),('Fibrillation, PSW','EMG.')]),
'topic-024-area-yama-q-016':M('Axonal, demyelinating','축삭형 vs 탈수초형.',[('Motor, sensory','분포.'),('Acute, chronic','경과.'),('Proximal, distal','분포.'),('Myopathic, neuropathic','틀리다.')]),
'topic-024-area-yama-q-019':M('(a) latency (b) amplitude (c) duration','CMAP 파형.',[('(a) amplitude (b) latency (c) area','틀리다.'),('(a) duration (b) amplitude (c) latency','틀리다.'),('(a) latency (b) duration (c) amplitude','틀리다.'),('(a) velocity (b) area (c) latency','틀리다.')]),
'topic-025-area-yama-q-008':M('Dermatomyositis','근위부 위약+피부병변+CK↑.',[('Polymyositis','발진 없음.'),('Inclusion body myositis','원위·비대칭.'),('Myasthenia gravis','일중변동·복시.'),('DM1','근긴장.')]),
'topic-025-area-yama-q-009':M('X-linked recessive(Duchenne)','가성비대+CK 25,000.',[('Autosomal dominant','DM1·FSHD.'),('Autosomal recessive','LGMD R.'),('Mitochondrial','모계.'),('X-linked dominant','틀리다.')]),
'topic-025-area-variants-q-021':M('근긴장디스트로피 1형(DM1) — DMPK CTG 반복 확장, AD','원위·안면 약화·대머리·백내장·당뇨. 원 변형 문항 정답 텍스트 깨짐 → 재구성.',[('FSHD — D4Z4 감소','백내장·당뇨 없음.'),('DMD — dystrophin 결손','소아.'),('DM2 — CCTG','근위부.'),('OPMD — PABPN1','40대 ptosis·dysphagia.')],note='원 변형 문항 정답 텍스트 깨짐 → 재구성'),
}
