from fixlib import Q,S,vis
CBF='CBF = CPP/CVR (CBF는 CPP에 비례, CVR에 반비례), CPP = MAP − ICP. 자동조절은 뇌혈관저항(CVR)을 바꿔 CBF를 일정하게 유지(정상 CPP 약 60–160 mmHg). 회백질 CBF(약 80)가 백질(약 20)의 4배. CPP↓ 시 Stage I: 혈관확장(CVR↓)→CBV↑, CBF 유지 → Stage II: CBF↓, OEF↑ → Stage III: CMR↓(energy failure). PaCO2↑→혈관확장→CBF↑ / PaCO2↓→혈관수축→CBF↓. PaO2는 약 50 mmHg 이하로 떨어져야 의미 있게 작용. 만성 고혈압은 자동조절 곡선을 오른쪽으로 이동시킨다.'
ISCH='허혈성 뇌손상: 치료 목표는 회복 가능한 penumbra를 살리는 것(infarct core는 비가역). Anoxic(terminal) depolarization·ATP depletion은 infarct core 쪽 threshold에서 일어난다. 혈류 감소 시 가장 먼저 단백질 합성↓ → hsp72 발현 → 포도당 이용↓ → lactic acidosis → ATP depletion. 초기에는 세포성(cytotoxic) 부종(DWI 고신호), 1–2일 뒤 BBB 파괴로 혈관성(vasogenic) 부종(DWI pseudonormalization). Spreading depression은 손상을 넓히는 병적 현상. Penumbra 세포사: excitotoxicity → peri-infarct depolarization → inflammation → apoptosis. 재관류 시 손상된 혈관이 터져 출혈성 경색(red infarct)과 혈관성 부종이 생길 수 있다.'
PEN='Ischemic penumbra: CBF 약 10–15(–18) mL/100g/min. 전기적 기능은 소실되었으나 이온펌프 기능과 세포막 투과성은 보존 → 빠른 재관류 시 회복 가능, 치료 목표. CBF 10 이하는 infarct core. 측부순환이 잘 되는 부위는 penumbra가 아니라 측부순환 영역(oligemia)이다.'
GRAPH='MAP–CBF 자동조절 곡선: 위로 이동(a) = hypercapnia(CO2↑→혈관확장→CVR↓→CBF↑), 오른쪽 이동(b) = 만성 고혈압(자동조절 범위가 오른쪽으로), 아래로 이동(c) = hypocapnia(CO2↓→혈관수축→CBF↓). 고혈압 환자의 혈압을 너무 급하게 낮추면 CBF가 떨어져 허혈이 올 수 있다.'
graph_exps=['틀림. a는 위쪽 이동이므로 hypercapnia이다.','정답. a: hypercapnia, b: hypertension, c: hypocapnia.','틀림. a·b가 뒤바뀌었고 c는 hypotension이 아니라 hypocapnia이다.','틀림. b는 오른쪽 이동이므로 hypertension이다.','틀림. a와 c가 서로 바뀌었고 b도 틀렸다.']
GRAPH_VIS=lambda: vis('자동조절 곡선 그래프 (학습지 33쪽)','s_cbf_graph.jpg')
AF='심방세동 → 심인성 색전(CE) 위험 → 이차 예방은 항응고제: warfarin(인공판막·판막협착일 때), DOAC(dabigatran, rivaroxaban, apixaban, edoxaban). 항혈소판제(aspirin, clopidogrel, cilostazol, triflusal)는 부적합.'
ABCD='ABCD2: Age ≥60 → 1, BP ≥140/90 → 1, 임상양상: 편측 위약 2 / 위약 없는 언어장애 1, 지속시간: ≥60분 2, 10–59분 1, <10분 0, 당뇨 1. 61세(1) + 150/90(1) + 편측 편마비(2) + 5분(0) = 4점(당뇨 정보가 없어 0점 가정). TIA는 뇌졸중 전조이므로 tPA·혈전제거술 대상이 아니고, 항혈소판제를 먼저 쓴다. 바로 퇴원은 위험.'
abcd_exps=['정답. 1+1+2+0 = 4점(당뇨 0점 가정).','틀림. CT가 정상이어도 TIA는 뇌졸중의 전조이다.','틀림. 증상이 사라진 TIA는 정맥 혈전용해제 적응증이 아니다.','틀림. 동맥 혈전제거술 대상이 아니다. 아스피린·클로피도그렐을 먼저 쓴다.','틀림. 조기 뇌졸중 위험이 높아 바로 퇴원시키면 안 된다.']
TOAST='TOAST 분류: Large artery atherosclerosis(LAA), Cardioembolism(CE), Small artery occlusion(SAO/SVO), Stroke of other determined etiology, Stroke of undetermined etiology(두 원인 이상, 음성 평가, 불완전 평가). Cancer related stroke는 TOAST 분류에 없다.'
LMI='Lateral medullary infarction(Wallenberg): vestibular nuclei → 어지럼·구토·안진, spinothalamic tract → 반대측 몸 통각·온도감각↓, spinal trigeminal tract → 같은 쪽 얼굴 통각↓, nucleus ambiguus → 같은 쪽 인두·후두·연구개 마비(연하곤란, 쉰 목소리, gag↓), descending sympathetic → 같은 쪽 Horner, spinocerebellar → limb ataxia, (강의록) hypoglossal nucleus → 딸꾹질, nucleus tractus solitarius → 미각 소실. 원인 혈관은 vertebral a.(또는 PICA).'
lmi_exps=['맞는 짝. Vestibular nucleus → 어지럼·안진.','맞는 짝. Spinothalamic tract → 반대측 몸 통각·온도감각 소실.','맞는 짝. Nucleus ambiguus → 쉰 목소리·연하곤란.','정답(틀린 짝). 강의록에서 딸꾹질은 hypoglossal nucleus, nucleus tractus solitarius는 미각 소실과 짝지어진다.','맞는 짝. Spinocerebellar tract → limb ataxia.']
EPI='뇌졸중 역학(강의록): 한국은 뇌경색 약 44%, 뇌출혈 약 34%, 지주막하출혈 약 12–13%로 뇌경색이 가장 많다. 뇌경색 중 혈전증이 약 60%를 차지한다.'
