def Q(src,stem,choices,ans,basis,exps,**k):
  d=dict(src=src,stem=stem,choices=choices,ans=ans,basis=basis,exps=exps); d.update(k); return d
MECH='강의록 8–9쪽 Recovery mechanisms after brain injury: ① Resolution of local harmful factor — local edema·local toxin 해소, local circulation 개선, 부분 손상 신경세포 회복; ② Neuroplasticity — collateral sprouting, unmasking of previously latent functional pathway, assumption of function by undamaged redundant neural pathway, reversibility from diaschisis, denervation supersensitivity, regenerative proximal sprouting of transected neuronal axons.'
DEF='강의록 4–7쪽: ICH 후 necrosis된 조직 자체는 살아나지 않음; 뇌는 조직화(organization)되어 있고, 가소성(plasticity)이 있어 재조직화(re-organization)된다; 뇌질환 환자의 재활치료란 손상된 뇌를 치료 타깃으로 뇌의 가소성을 이용해 손상된 뇌가 최적으로 재조직화되어 살아날 수 있도록 증명된 최상의 치료를 실시하는, 뇌졸중이라는 병 자체에 대한 본격적인 치료분야.'
PAT='강의록 13–21쪽: Motor reorganization(Nudo 1997 원숭이); Reorganization patterns(Cramer 1997) — 1 perilesional(intra-hemispheric), 2 ipsilateral(inter-hemispheric), 3 other motor related structure; 우측 기저핵 경색 환자의 좌측 손 운동 시 활성화; 정상인 손운동·이두박근 운동 vs 상지절단 환자의 의수 작동 시 활성 영역; 3개월 재활치료 전후 비교; Language reorganization(정상 한국 성인 visual verb generation 과제 fMRI, 환자별 좌·우 재조직화).'
STR='강의록 22–23쪽 뇌질환 후 회복 치료 전략: physiologic recovery, environmental enrichment(새로 생긴 DCX 양성 세포 형태 개선, 이식한 SVZ 줄기세포 이동 증진), neurotrophic factor(TGF-β1 외부 보충 → 경색 부피 감소·신경생성 증가), stem cell transplantation, neurostimulation(rTMS, tDCS). 재활의학과 치료: comprehensive rehabilitation therapy, NDT, medication(neurotransmitter, neuron regeneration·brain blood circulation·brain cell metabolism 증진).'
TIME='강의록 24–27쪽: 예후 결정 인자 — 병변의 크기와 위치(25/M, 75/F, 45/M 영상 비교); 치료하지 않거나 부적절하면 "pathologic reorganization"; 재활치료 시기 — 발병 후 3개월, 6개월 표시.'
LEC='학습지(고명환 강의 설명 정리): 가소성은 손상 조직이 어느 정도 확정된 이후 손상되지 않은 다른 부위로 reorganization되면서 다시 살아나는 개념; 재활은 ASAP(중환자실부터 상태에 맞게), 3개월 지나면 회복능력의 90% 이상 소실, 6개월 이상이면 거의 소실; 상지절단 환자 — 의수를 이두박근으로 작동할 때 정상인 손운동 영역까지 끌어와 재조직화(뇌 손상 없이도 재조직화); 피질하 병변 실어증 재활 후 fMRI에서 양측 대뇌피질 활성, 피질 병변은 반대편(우측) 상동 영역으로 이동; 목표 설정은 뇌졸중 중증도(영상)로 판단.'
FA='강의록 30–31쪽 형성평가: 좌측 MCA 상부분지 경색 — right hemiplegia, right hemisensory loss, Broca aphasia, central facial palsy, dysarthria, right homonymous hemianopia, apraxia. 상지기능 향상 재활 — NDT, task-oriented training, CIMT, bilateral arm training, mirror therapy, FES, robot-assisted therapy, virtual reality, rTMS, tDCS.'
OFF=[
Q('강의록','뇌손상 후 회복기전 중 "resolution of local harmful factor"에 해당하지 않는 것은?',['Denervation supersensitivity','Resolution of local edema','Resolution of local toxin','Improvement of local circulation','Recovery of partially damaged neurons'],1,MECH,['정답. 신경가소성.','해당.','해당.','해당.','해당.']),
Q('강의록','뇌졸중 발병 후 손상 병소에서 떨어진 부위의 기능이 일시적으로 저하되었다가 회복되는 신경가소성 기전은?',['Reversibility from diaschisis','Collateral sprouting','Denervation supersensitivity','Resolution of local toxin','Regenerative proximal sprouting'],1,MECH,['정답.','곁가지 발아.','탈신경 과민.','harmful factor.','절단 축삭.']),
Q('강의록','평소 쓰이지 않던 잠재 경로가 손상 후 기능을 하게 되는 기전은?',['Unmasking of previously latent functional pathway','Collateral sprouting','Resolution of local edema','Improvement of local circulation','Denervation supersensitivity'],1,MECH,['정답.','새 가지.','harmful factor.','harmful factor.','수용체 과민.']),
Q('강의록','손상되지 않은 인접 신경세포의 축삭에서 새 가지가 나와 탈신경된 부위에 연결되는 기전은?',['Collateral sprouting','Regenerative proximal sprouting of transected axons','Unmasking','Diaschisis 회복','Local toxin 해소'],1,MECH,['정답.','절단된 축삭 자체의 근위부.','잠재 경로.','원격 기능저하 회복.','harmful factor.']),
Q('강의록','기능이 중복된(redundant) 손상되지 않은 신경경로가 손상된 기능을 떠맡는 기전은?',['Assumption of function by undamaged redundant neural pathway','Resolution of local edema','Denervation supersensitivity','Improvement of local circulation','Recovery of partially damaged neurons'],1,MECH,['정답.','harmful factor.','틀리다.','harmful factor.','harmful factor.']),
Q('강의록','뇌출혈 후 괴사(necrosis)된 조직에 대한 강의의 관점으로 옳은 것은?',['괴사 조직 자체는 살아나지 않고, 다른 부위가 재조직화되어 기능을 대신한다','괴사 조직이 재생되어 원래대로 회복된다','괴사 조직을 제거해야만 회복된다','괴사 부위의 혈류 개선이 가소성의 핵심이다','괴사가 있으면 재활은 무의미하다'],1,DEF+' '+LEC,['정답.','틀리다.','틀리다.','초기 회복 요소.','틀리다.']),
Q('강의록','"뇌는 가소성이 있어서 ( )된다"에서 괄호에 들어갈 말로 강의록 표현과 일치하는 것은?',['재조직화(re-organization)','조직화(organization)','고착화','퇴행','재생(regeneration)'],1,DEF,['정답.','원래 상태.','틀리다.','틀리다.','강의록 표현 아님.']),
Q('강의록','강의록이 정의한 뇌질환 재활치료의 성격으로 가장 적절한 것은?',['뇌졸중이라는 병 자체에 대한 본격적인 치료분야','남은 장애에 적응시키는 보조 치료','합병증 예방만을 위한 치료','보조기 처방 중심의 치료','급성기 치료 후 선택적 치료'],1,DEF,['정답.','틀리다.','일부.','틀리다.','틀리다.']),
Q('강의록','Cramer 등(1997)이 제시한 재조직화 패턴에 해당하지 않는 것은?',['손상 부위 신경세포의 완전 재생(Restitution of necrotic tissue)','Perilesional(intra-hemispheric)','Ipsilateral(inter-hemispheric)','Other motor related structure','—'],1,PAT,['정답.','패턴 1.','패턴 2.','패턴 3.','—'],fixed=True),
Q('강의록','우측 기저핵 경색 후 회복된 환자가 좌측 손을 움직일 때 좌측(병변 반대) 반구 운동피질이 활성화되었다. 이 재조직화 패턴은?',['Ipsilateral(inter-hemispheric) 패턴','Perilesional 패턴','Other motor related structure 패턴','Diaschisis','Local circulation 개선'],1,PAT,['정답. 움직이는 손과 같은 쪽 반구.','병변 주위.','SMA 등.','틀리다.','틀리다.']),
Q('강의록','손상 병소 바로 주변 피질이 기능을 이어받는 재조직화 패턴은?',['Perilesional(intra-hemispheric)','Ipsilateral(inter-hemispheric)','Other motor related structure','Denervation supersensitivity','Unmasking'],1,PAT,['정답.','반대 반구.','기타 운동 관련 구조.','기전.','기전.']),
Q('학습지(강의 설명)','상지절단 환자가 이두박근으로 의수를 작동할 때의 fMRI 사례가 보여주는 것은?',['뇌 손상 없이도 가소성에 의한 재조직화가 일어난다','뇌 손상 환자에서만 재조직화가 일어난다','절단 후 운동피질이 위축되어 기능이 없다','이두박근 영역만 활성화된다','소뇌만 활성화된다'],1,PAT+' '+LEC,['정답. 손운동 영역까지 끌어와 사용.','틀리다.','틀리다.','손운동 영역까지.','틀리다.']),
Q('학습지(강의 설명)','좌측 피질 언어영역이 광범위하게 손상된 실어증 환자가 언어치료 후 회복되었다. 강의에서 설명한 fMRI 활성 양상은?',['우측 대뇌피질의 상동 영역으로 언어중추 이동','소뇌 피질만 활성','뇌간 중앙부 활성','좌측 피질하 영역만 활성','활성 부위 없음'],1,PAT+' '+LEC,['정답. 피질 병변 → 반대편. (피질하 병변이면 양측)','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록','강의록에서 뇌의 활성 부위를 보여주는 뇌 기능지도(brain mapping)의 예로 제시된 검사는?',['Functional MRI','비조영 CT','T1 강조 MRI','단순 두개골 X선','CT 혈관조영'],1,'강의록 11–12쪽 Methods of Brain Mapping — Functional MRI. 학습지: fMRI는 비침습적으로 신경활성에 연동된 혈류를 측정해 활성 부위를 해부학 영상과 함께 보여줌.',['정답.','구조.','구조.','틀리다.','혈관.']),
Q('강의록','뇌질환 후 회복을 위한 치료 전략 중 "neurostimulation"에 해당하는 것은?',['rTMS와 tDCS','Environmental enrichment','Stem cell transplantation','Neurotrophic factor 투여','Physiologic recovery'],1,STR,['정답.','별도 전략.','별도 전략.','별도 전략.','자연 회복.']),
Q('강의록','강의록에서 환경 풍부화(environmental enrichment)의 효과로 제시된 것은?',['이식한 뇌실하영역(SVZ) 줄기세포의 이동 증진','경색 부피 증가','신경생성 억제','뇌부종 악화','DCX 양성 세포 소실'],1,STR,['정답.','틀리다.','틀리다.','틀리다.','형태 개선.']),
Q('강의록','뇌졸중 후 외부에서 보충했을 때 경색 부피를 줄이고 신경생성을 증가시킨 것으로 강의록에 제시된 인자는?',['TGF-β1','Amyloid-β','TNF-α','Glutamate','Interleukin-1'],1,STR,['정답.','틀리다.','틀리다.','흥분독성.','틀리다.']),
Q('강의록','강의록의 "뇌에 대한 재활의학과 치료" 중 약물치료의 목표로 제시되지 않은 것은?',['손상 부위 괴사 조직의 직접 재생','신경전달물질 조절','신경세포 재생 증진','뇌혈류 순환 증진','뇌세포 대사 증진'],1,STR,['정답.','제시.','제시.','제시.','제시.']),
Q('강의록','나이가 다른 세 뇌졸중 환자(25/M, 75/F, 45/M)의 영상을 비교하며 강조한 예후 결정 인자는?',['병변의 크기와 위치','나이','성별','가족의 간병','경제적 상황'],1,TIME+' '+LEC,['정답.','강조 아님.','틀리다.','틀리다.','틀리다.']),
Q('강의록','부적절하거나 늦은 치료로 인해 기능 회복이 저하되는 재조직화를 강의록에서 무엇이라 했는가?',['Pathologic reorganization','Perilesional reorganization','Physiologic recovery','Diaschisis','Unmasking'],1,TIME,['정답.','정상 패턴.','틀리다.','틀리다.','틀리다.']),
Q('학습지(강의 설명)','강의에서 설명한 재활치료 시작 시점과 가소성의 시간 경과로 옳은 것은?',['가능한 한 빨리(중환자실부터) 시작, 3개월이 지나면 회복능력의 대부분이 소실','6주 후 신경학적으로 안정되면 시작','3개월 뒤 가소성이 최대','6개월 이후에도 가소성은 그대로 유지','의식이 완전히 회복된 뒤 시작'],1,TIME+' '+LEC,['정답.','틀리다.','틀리다.','거의 소실.','틀리다.']),
Q('학습지(강의 설명)','세 명의 뇌졸중 환자가 동시에 재활의학과로 전과되었다. 각 환자의 재활 목표(goal)를 설정할 때 강의에서 가장 중요하다고 한 근거는?',['뇌 영상으로 판단한 뇌졸중 중증도(병변 크기·위치)','환자의 경제적 상황','환자의 직업','가족의 의지','입원 기간'],1,LEC,['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록','형성평가 2에서 좌측 중대뇌동맥 상부분지 경색 환자의 문제로 열거되지 않은 것은?',['Wernicke 실어증','Right hemiplegia','Broca 실어증','Central facial palsy','Right homonymous hemianopia'],1,FA,['정답. 하분지.','열거.','열거.','열거.','열거.']),
Q('강의록','형성평가 3에서 뇌질환 후 저하된 상지기능 향상 방법으로 열거되지 않은 것은?',['장기간 침상안정','Mirror therapy','Bilateral arm training','Robot-assisted therapy','Virtual reality-based rehabilitation'],1,FA,['정답.','열거.','열거.','열거.','열거.']),
Q('강의록','형성평가에서 좌측 MCA 상부분지 경색 문제로 열거된 것 중 구음 관련 항목은?',['Dysarthria','Aprosodia','Alexia','Agraphia','Anosognosia'],1,FA,['정답.','비우성.','PCA.','틀리다.','비우성.']),
Q('강의록','뇌 재활치료에 대해 강의록이 던진 질문("손상된 뇌는 살아날 수 있는가?")에 대한 답으로 가장 적절한 것은?',['가소성을 이용한 재조직화로 기능이 살아날 수 있다','손상된 뇌는 어떤 경우에도 회복되지 않는다','자연 경과로 모두 회복되므로 치료가 필요 없다','약물만으로 괴사 조직이 재생된다','소아에서만 가능하다'],1,DEF+' '+LEC,['정답.','틀리다.','남는 게 남음 → 치료 필요.','틀리다.','성인도 가능.']),
Q('강의록','Nudo 등(1997)의 원숭이 실험이 강의록에서 보여주려 한 내용은?',['손상 후 재활훈련에 따른 운동영역 재조직화(motor reorganization)','언어중추의 반대편 이동','시각피질의 재생','소뇌의 보상','말초신경 재생'],1,PAT+' 교과서(021 강의록 그림 27-12): 원숭이 뇌졸중 모델에서 재활치료를 한 경우에만 병변 주위로 수부 영역의 기능적 재배치.',['정답.','언어.','틀리다.','틀리다.','틀리다.']),
Q('강의록','강의록에서 언어 재조직화 연구를 위해 정상 한국 성인에게 시행한 fMRI 과제는?',['Visual verb generation task','Finger tapping','Visual checkerboard','Word reading aloud','Resting state'],1,PAT,['정답.','운동.','시각.','틀리다.','틀리다.']),
]
OFF=[q for q in OFF if not any(c.strip()=='—' for c in q['choices'])]
OFF=[q for q in OFF if '구음 관련' not in q['stem']]
