def Q(src,stem,choices,ans,basis,exps,**k):
  d=dict(src=src,stem=stem,choices=choices,ans=ans,basis=basis,exps=exps); d.update(k); return d
CMP='강의록 비교표: MS — myelin/axon, 단안·통증·중등도 ON, short peripheral myelitis, Dawson finger/U-fiber/CVS, OCB 흔함, relapse+PIRA. AQP4-NMOSD — AQP4 astrocytopathy, 중증·posterior/chiasm ON, LETM central/swelling, area postrema/periependymal, OCB 드묾, attack-related 장애. MOGAD — MOG myelin/oligodendrocyte, 양측·disc edema·anterior/perineural ON, conus·H-sign, ADEM-like/FLAMES, OCB 드묾, 진행성 경과 없음.'
MC='강의록 2024 McDonald: DIS = 5개 위치(periventricular, juxta/intracortical, infratentorial, spinal cord, optic nerve) 중 ≥2곳. 경로 — A DIS+DIT, B DIS+CSF OCB/kFLC+, C DIS+CVS+, D ≥4/5 위치, E 1곳+(CVS 또는 PRL)+(DIT 또는 CSF+). OCB와 kFLC는 대체 가능(cut-off 6.1 제안).'
OFF=[
Q('강의록','CNS 수초를 형성하는 세포는?',['희소돌기아교세포(oligodendrocyte)','Schwann 세포','별아교세포','미세아교세포','뇌실막세포'],1,'강의록: oligodendrocyte — CNS myelin, Schwann cell — PNS myelin.',['정답.','PNS.','AQP4-NMOSD의 표적.','면역세포.','틀리다.']),
Q('강의록','탈수초의 기능적 결과 중 Lhermitte 징후·tonic spasm 같은 발작성 증상을 설명하는 기전은?',['Ephaptic spread','Conduction block','Axonal injury','Remyelination','Wallerian degeneration'],1,'강의록: conduction block → 급성 결손; ephaptic spread → 발작성 증상(Lhermitte, tonic spasm); axonal injury → 비가역적 장애·뇌위축; remyelination → 초기 회복, 나이·병기간에 따라 감소.',['정답.','급성 결손.','비가역 장애.','회복.','강의록에 없음.']),
Q('강의록','탈수초 질환의 분류로 옳지 않은 것은?',['Guillain–Barré 증후군 – 중추신경계','MS – 면역매개','PML – 감염','Adrenoleukodystrophy – 유전/대사','MOGAD – 면역매개'],1,'강의록: 감염 PML, 감염후 GBS(AIDP, 말초), 면역매개 MS·NMOSD·MOGAD, 유전/대사 ALD. GBS·CIDP는 말초신경계.',['틀리다(정답). GBS는 말초.','맞다.','맞다.','맞다.','맞다.']),
Q('강의록','세 질환의 주 병리 연결로 옳은 것은?',['AQP4-NMOSD – 항체매개 astrocytopathy','MS – 순수 B세포 항체질환','MOGAD – 별아교세포병증','AQP4-NMOSD – 희소돌기아교세포 항체','MS – 보체 매개 괴사가 주 병리'],1,CMP,['정답.','T/B cell, microglia, 축삭 변성 포함.','MOG myelin/oligodendrocyte.','AQP4는 별아교세포.','NMOSD의 특징.']),
Q('강의록','MS의 발병 위험 인자와 병태생리로 강의록에 제시된 것이 아닌 것은?',['높은 비타민 D 수치','EBV 감염','흡연','비만','유전적 감수성'],1,'강의록: genetic susceptibility, EBV + environment(smoking·obesity·vit D 부족) → 말초 면역 활성 → BBB 통과 → CNS 염증 + 신경변성. EBV seroconversion 후 MS 위험이 크게 증가.',['정답. 비타민 D 결핍이 위험.','제시.','제시.','제시.','제시.']),
Q('강의록','2024 McDonald criteria에서 새로 5번째 DIS 위치로 포함된 것은?',['Optic nerve','Periventricular','Juxtacortical','Infratentorial','Spinal cord'],1,MC,['정답.','기존.','기존.','기존.','기존.']),
Q('강의록','2024 McDonald criteria의 DIS 정의로 옳은 것은?',['5개 전형 위치 중 ≥2곳에 ≥1개의 전형 병터','4개 위치 중 ≥3곳','증상성 병터만 인정','9개 이상의 T2 병터','조영증강 병터 ≥2개'],1,MC+' 증상성·무증상 병터 모두 사용 가능.',['정답.','틀리다.','무증상도 인정.','과거 기준.','DIT 관련.']),
Q('강의록','28세 여성, 통증성 단안 시신경염. MRI에서 뇌실주위 병터 1개와 경추의 짧은 병터 1개, 조영증강 없음, CSF-restricted OCB 양성, AQP4·MOG 음성. 2024 기준 판단은?',['DIS + CSF 양성으로 MS 진단 가능','DIT가 없어 CIS로만 진단','6개월 뒤 MRI를 기다려야 한다','OCB는 2024 기준에서 쓰지 않는다','시신경 MRI가 정상이므로 MS 배제'],1,MC+' (강의 Quiz 1)',['정답.','DIS+CSF가 DIT를 대체.','불필요.','OCB/kFLC 사용.','틀리다.']),
Q('강의록','2024 McDonald criteria에서 DIT를 대체할 수 있는 경우가 아닌 것은?',['DIS + 혈청 AQP4-IgG 음성','DIS + CSF OCB/kFLC 양성','DIS + CVS 양성','4/5 위치의 전형 병터','1곳 + PRL/CVS + CSF 또는 DIT'],1,MC,['정답. 항체 음성은 DIT 대체 근거가 아니다.','대체.','대체.','대체.','대체.']),
Q('강의록','Paramagnetic rim lesion(PRL)에 대한 설명으로 옳은 것은?',['비조영 T2 병터 가장자리의 철 함유 미세아교세포 테로 chronic active lesion의 표지이며 특이도가 매우 높다.','병터 중앙을 지나는 작은 정맥이다.','모든 MS 환자에게 필수 검사다.','민감도가 매우 높고 특이도는 낮다.','소혈관질환에서 흔하다.'],1,'강의록: CVS — 병터 중앙의 작은 정맥, select-6 또는 >50% 기준. PRL — iron-laden microglial rim, 낮은 민감도·매우 높은 특이도, chronic active lesion 표지. 둘 다 모든 환자에 필수 아님.',['정답.','CVS.','선택적.','반대.','SVD는 CVS/PRL 없음.']),
Q('강의록','MS의 전형적 MRI 소견이 아닌 것은?',['3개 척추 분절 이상의 척수 중심부 병터','Dawson fingers','Juxtacortical/U-fiber 병터','뇌량 침범','척수 단면 일부를 침범하는 짧은 말초 병터'],1,'강의록: MS — ovoid·perivenular(Dawson fingers), 뇌량, juxtacortical/U-fiber, 척수 병터는 보통 <3 분절·단면 일부. LETM·central은 NMOSD.',['정답. NMOSD 소견.','전형.','전형.','전형.','전형.']),
Q('강의록','MS의 전형적 attack이 아닌 red flag 소견은?',['Area postrema 증후군','20–50세 아급성 발생','단안 통증성 시신경염','INO','짧은 분절의 부분 척수염'],1,'강의록: typical — 20–50세 아급성, 단안 통증성 ON, partial myelitis, INO. Red flags — 양측 동시·극심한 ON/chiasm, LETM·conus·부종, area postrema, 뇌병증/ADEM·경련, 발열·전신염증·악성, 진행하는 단일·대칭 병변.',['정답.','전형.','전형.','전형.','전형.']),
Q('강의록','MS의 true relapse와 pseudo-relapse 구분으로 옳은 것은?',['True relapse는 발열·감염 없이 24시간 이상 지속되고 이전 attack 후 30일 이상 간격이 있다.','Pseudo-relapse는 반드시 고용량 steroid로 치료한다.','모든 relapse에 MRI가 필수다.','운동·더위로 기존 증상이 수시간 재현되면 true relapse다.','요로감염 동반 악화도 true relapse로 본다.'],1,'강의록: true relapse — ≥24 h, 이전 attack 후 ≥30일, 발열·감염·대사 이상 없음, MRI는 필수 아님. Pseudo-relapse — 감염·발열·더위·운동·수면부족으로 기존 증상 재현, 원인 교정 후 호전, 불필요한 steroid 위험.',['정답.','불필요한 steroid 위험.','필수 아님.','Pseudo.','Pseudo.']),
Q('강의록','중등도–중증 MS relapse의 급성 치료로 옳은 것은?',['IV methylprednisolone 0.5–1 g/day × 3–5일, 중증·불응 시 PLEX 5–7회','Interferon-β 즉시 시작','경구 저용량 prednisolone 장기 투여','Natalizumab 단회 투여','항생제만 투여'],1,'강의록: 경증 — 교육·증상 치료·관찰; 중등도–중증 — IVMP 0.5–1 g/day × 3–5 d 또는 고용량 경구; 중증·불응 — PLEX 5–7회 조기. Steroid taper는 routine 아님.',['정답.','DMT는 급성 치료가 아니다.','틀리다.','틀리다.','감염 선별은 하지만 치료 아님.']),
Q('강의록','MS DMT와 핵심 위험의 연결로 옳지 않은 것은?',['Fingolimod – PML/JCV가 가장 대표적 위험','Natalizumab – JCV/PML','Anti-CD20 – HBV 재활성화·저감마글로불린혈증','Fingolimod – 서맥·황반부종·rebound','Cladribine·alemtuzumab – 림프구감소·감염·이차 자가면역'],1,'강의록 DMT: platform(IFN-β, glatiramer, teriflunomide, fumarates) — LFT·CBC; S1P(fingolimod 등) — bradycardia, macular edema, rebound; natalizumab — JCV/PML; anti-CD20 — HBV, Ig, 감염; immune reconstitution — lymphopenia, 감염, 자가면역.',['틀리다(정답). PML은 natalizumab의 대표 위험.','맞다.','맞다.','맞다.','맞다.']),
Q('강의록','진행형 MS에서 적응증에 따라 고려하는 약제의 연결로 옳은 것은?',['PPMS – ocrelizumab, active SPMS – siponimod','PPMS – interferon-β, SPMS – glatiramer','PPMS – eculizumab','SPMS – satralizumab','PPMS – 치료 약제 없음'],1,'강의록: progressive MS — ocrelizumab(PPMS), siponimod(active SPMS). MRI activity가 없어도 progression 발생 가능, 재활·증상 조절 병행.',['정답.','틀리다.','NMOSD.','NMOSD.','틀리다.']),
Q('강의록','NEDA-3의 구성 요소가 아닌 것은?',['혈청 neurofilament 정상','재발 없음','장애 진행 없음','MRI 활성 없음','세 가지 모두 충족'],1,'강의록: NEDA-3 = no relapse + no disability progression + no MRI activity. PIRA를 놓치지 않도록 6–12개월 단위 기능 추적.',['정답.','구성 요소.','구성 요소.','구성 요소.','정의.']),
Q('강의록','AQP4가 풍부하게 존재하는 부위가 아닌 것은?',['미엘린 염기성 단백질','별아교세포 발돌기','뇌실막','Area postrema','—'],1,'강의록: AQP4는 astrocyte foot process, ependyma, area postrema에 풍부. 보체·호중구·호산구가 괴사성 병변에 기여. 장애는 severe attack 후 불완전 회복의 누적.',['정답.','풍부.','풍부.','풍부.','—'],fixed=True),
Q('강의록','AQP4-NMOSD의 6가지 core clinical characteristic이 아닌 것은?',['Dawson finger를 동반한 뇌실주위 병터','시신경염','급성 척수염','Area postrema 증후군','간뇌 증후군(기면증·SIADH)'],1,'강의록 core: optic neuritis, acute myelitis, area postrema(난치성 딸꾹질·구토), brainstem, diencephalic(narcolepsy·SIADH), cerebral(뇌병증·경련).',['정답. MS 소견.','core.','core.','core.','core.']),
Q('강의록','31세 여성이 5일간 난치성 딸꾹질과 구토, area postrema 병터, serum AQP4-IgG CBA 양성이며 steroid와 PLEX로 호전되었다. 장기 계획은?',['AQP4+ NMOSD로 진단하고 첫 attack 후 장기 면역치료를 시작','재발 전까지 관찰','Interferon-β 시작','Fingolimod 시작','MOG-IgG가 양성이 될 때까지 대기'],1,'강의록 Quiz 2: AQP4-IgG+ definite NMOSD는 첫 attack 후 maintenance immunotherapy 시작. IFN-β, glatiramer, fingolimod/S1P, natalizumab, alemtuzumab, fumarates는 피해야 할 MS DMT.',['정답.','틀리다.','재발 증가.','피해야 함.','틀리다.']),
Q('강의록','AQP4-NMOSD에서 피해야 할 약제는?',['Interferon-β','Eculizumab','Inebilizumab','Satralizumab','Rituximab'],1,'강의록: NMOSD에서 피해야 할 MS DMT — IFN-β, glatiramer, fingolimod/S1P, natalizumab, alemtuzumab, fumarates. 예방치료 — C5(eculizumab, ravulizumab), CD19(inebilizumab), IL-6R(satralizumab), CD20(rituximab), MMF·AZA.',['정답.','C5.','CD19.','IL-6R.','CD20.']),
Q('강의록','AQP4-NMOSD 예방 표적치료제와 핵심 안전 사항의 연결로 옳은 것은?',['Eculizumab – 수막알균 백신','Satralizumab – JCV/PML','Inebilizumab – 서맥','Rituximab – 황반부종','Azathioprine – 가장 빠른 효과 발현'],1,'강의록: C5 억제제 — 매우 빠른 효과, 수막알균 백신·감염 주의; CD19 inebilizumab — Ig 감소, 감염, HBV; IL-6R satralizumab — SC, 감염·호중구·LFT; rituximab — HBV, Ig; MMF/AZA — 늦은 onset.',['정답.','틀리다.','틀리다.','틀리다.','늦은 onset.']),
Q('강의록','AQP4-IgG 검사에 대한 설명으로 옳은 것은?',['혈청 cell-based assay가 권장되며 역가를 질병 활성 추적의 단독 지표로 쓰지 않는다.','CSF 검사가 routine이다.','역가로 재발을 단독 예측한다.','음성이면 추가 검사 없이 NMOSD를 배제한다.','치료 후 채혈이 가장 유리하다.'],1,'강의록: serum 선호, CSF routine 아님, 치료 전/attack 시 채혈 유리, CBA 권장, titer를 단독 활동 지표로 쓰지 않음; 강한 의심+음성 → CBA 재검·MOG-IgG.',['정답.','틀리다.','틀리다.','재검·MOG 검사.','치료 전.']),
Q('강의록','MOGAD를 시사하는 소견이 아닌 것은?',['진행성 경과','양측 동시 시신경염과 뚜렷한 시신경유두부종','Perineural enhancement','원추 침범·H-sign','소아 ADEM·FLAMES'],1,'강의록: MOGAD — 양측 ON·disc edema·anterior long·perineural enhancement, conus·H-sign, 소아 ADEM·fluffy lesion·FLAMES. Progressive course는 매우 비전형 → 다른 진단 재검토.',['정답.','시사.','시사.','시사.','시사.']),
Q('강의록','19세 여성, 양측 시신경염과 뚜렷한 유두부종, anterior long-segment·perineural enhancement, AQP4 음성, fixed CBA에서 low-positive MOG-IgG. 가장 적절한 해석은?',['Compatible core event와 supportive MRI가 있어 MOGAD를 지지하며 대체진단 배제와 assay 확인이 필요하다.','MOG-IgG 양성만으로 무조건 MOGAD다.','Low-positive이므로 반드시 위양성이다.','전형적 MS 시신경염이다.','Seronegative NMOSD로 확정한다.'],1,'강의록 Quiz 3 / 2023 MOGAD criteria: clear positive는 supportive feature 불필요, low positive·titer 없음·CSF-only는 supportive feature 필요. MOG 양성 단독 ≠ MOGAD, 대체진단 배제.',['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록','MOGAD 치료에 대한 설명으로 옳은 것은?',['급성기 IVMP 후 천천히 감량하면 조기 재발을 줄일 수 있고, 유지치료는 모든 첫 attack에 routine은 아니다.','첫 attack 후 모든 환자에 interferon-β를 시작한다.','Satralizumab이 MOGAD 적응증으로 승인되었다.','급성기 PLEX는 금기다.','진행성 경과가 흔해 조기 고효능 DMT가 필수다.'],1,'강의록: 급성 IVMP 1 g/day × 3–5 d, 불완전 회복 시 PLEX 또는 IVIG, slow oral taper. 유지치료는 재발·중증 첫 attack에서 고려(IVIG, rituximab, MMF/AZA, IL-6R off-label). METEOROID phase 3 satralizumab 양성이나 아직 적응증 미승인.',['정답.','틀리다.','미승인.','가능.','비진행성.']),
Q('강의록','38세 여자가 48시간에 걸친 하지마비와 급성 요저류, 1년 전 양안 시력소실 병력, 척수 MRI에서 LETM이 있다. 혈청에서 확인할 항체의 표적 항원 위치는?',['별아교세포 발돌기','신경세포 가지돌기','미세아교세포','미엘린 염기성 단백질','희소돌기아교세포 표면'],1,'강의록 Quiz 4: AQP4는 별아교세포 발돌기의 물통로 — 탈수초가 아니라 별아교세포병증.',['정답.','틀리다.','틀리다.','틀리다.','MOG.']),
Q('강의록','세 질환의 시신경염 감별로 옳은 것은?',['MOG-ON은 양측 동시가 흔하고 심하지만 회복이 대개 좋다.','MS-ON은 대개 양측 동시이고 회복이 나쁘다.','AQP4-ON은 짧은 안와내 병터가 전형이다.','MOG-ON은 시신경교차·후방 병변이 전형이다.','AQP4-ON은 유두부종이 가장 뚜렷하다.'],1,'강의록 ON 비교: MS — 대개 단측, 중등도, 회복 좋음, 짧은 안와내; AQP4 — 양측/순차, 중증·회복 나쁨, posterior·chiasm·long; MOG — 양측 동시 흔함, 중증이나 회복 좋음, marked disc edema, anterior long·perineural.',['정답.','틀리다.','MS.','AQP4.','MOG.']),
]
OFF=[q for i,q in enumerate(OFF) if i not in {2,15,16,17}]
