def Q(src,stem,choices,ans,basis,exps,**k):
  d=dict(src=src,stem=stem,choices=choices,ans=ans,basis=basis,exps=exps); d.update(k); return d
IMG='강의록(1교시 9쪽) 주요 뇌혈관 영상검사 비교: CTA — 빠른 촬영·넓은 가용성·높은 공간해상도 / 방사선 피폭·요오드 조영제·석회화 시 협착 과대평가 / 급성 뇌졸중 1차 평가·대혈관 폐색 확인. MRA(TOF) — 방사선 없음·조영제 불필요 / 긴 검사시간·난류로 협착 과대평가 가능 / 선별검사·조영제 금기 환자. DSA — 최고 공간·시간해상도, 진단의 표준 / 침습적, 합병증 위험(~0.5–1%) / 치료 계획(혈전제거술 등)·애매한 협착 확진. 경동맥 초음파 — 비침습·방사선 없음·실시간 혈류평가 / 검사자 의존적·두개내 혈관평가 제한 / 경동맥 협착 선별·추적관찰.'
CASE='강의록(1교시 17–19쪽): 64세 여자, 2시간 전 좌측 편마비·구음장애, 10년 전부터 심방세동 → CT 출혈 없음 → IV tPA 0.9 mg/kg 1시간 동안 → 어떤 혈관? (우측 MCA). 75세 남자 1시간 전 우측 편마비 → (좌측 MCA). 66세 남자 1시간 전 코마 → basilar artery(intubation). Take home: 증상, 나이, 증상+혈관 위치. 혈전 원인: 좌심방이(Lt atrial appendage), MI, aorta.'
TOAST='강의록(1교시 22쪽) TOAST: LAA — 주요 혈관 >50% 협착/폐색, 피질 징후(실어증 등) 또는 뇌간·소뇌 기능장애; Cardioembolism — 심방세동, 기계판막, 최근 MI, 좌심실 혈전, 여러 혈관 영역의 다발성 경색; Small-artery occlusion(lacunar) — 병변 <1.5 cm, pure motor hemiparesis, pure sensory stroke, ataxic hemiparesis, 고혈압 연관; Other determined — 박리, 혈관염, 응고병증, 모야모야, 겸상적혈구병; Undetermined — 원인 2개 이상, 음성 평가(cryptogenic), 불완전 평가.'
DIS='강의록(1교시 2·14–16·26·31–38쪽): 혈관질환 — Occlusion(동맥/정맥, 급성/만성), Rupture(동맥 — 위치·박리·동맥류; 자발성/외상성), Vasculitis(협착·파열). Rupture: 동맥 — 뇌동맥류, AVM, AV fistula. Perfusion MRI/CT — core, penumbra, mismatch ratio. Symptomatic nonstenotic carotid stenosis — <50% 경동맥 plaque + 증상성 색전 경색 + 다른 원인 없음. ICAS. Tandem VBO — 시술시간 길고 임상결과 불량(Piechowiak 2019), 기전 in situ atherosclerotic vs pure embolic. MCA 폐색 혈관조영 유형 — truncal(ICAS 관련) vs branching(색전) (Baek 2016). Moyamoya — 뇌기저부 동맥(말단 ICA와 분지)의 진행성 협착·폐쇄와 취약한 측부혈관망, 일본어 "puff of smoke"; TIA, 허혈성·출혈성 뇌졸중, 경련, 반복 두통, 인지저하; 소아 5–10세·성인 30–50세; MRI/MRA·혈관조영에서 양측 말단 ICA 협착과 puff of smoke 측부혈관.'
SAH='강의록(1교시 40–54쪽): 비외상성 출혈 — SAH(동맥류, 정맥성 출혈), 자발성 ICH(성인/소아). 첫 혈관조영에서 동맥류가 없는 SAH — 자발성 SAH의 15–20%: 비동맥류성 중뇌주위(perimesencephalic) 출혈(50%), AVM, 척수 혈관 병변, 종양 출혈. Perimesencephalic SAH — 뇌교 앞 국소, 정맥성. 60/M 두통 3일. Basilar 동맥류 SAH 증례. AVM. 64/M 외상성 CCF — (상)안정맥 확장, fistula. 학습지(강의 설명): 소아에서 외상 없는 ICH → AVM 의심.'
INT='강의록(2교시 Neurointervention): 뇌혈관 질환 — 뇌동맥류, stroke(대·중혈관 폐색, 경동맥·두개내 동맥경화), AVM·dural AVF. 중재 = 내과와 외과의 중간, 사망률 감소·치료효과 극대화. 대상 — hyperacute stroke, 동맥경화성 협착(TIA), carotid stent, 뇌동맥류 coil 색전술, 뇌동정맥기형 색전술, 뇌종양 색전술. 혈전 — carotid emboli, 심방세동·조동; 행선지 관상동맥·뇌동맥·대동맥/말초. 혈전 크기와 양이 폐쇄 위치와 증상 좌우; small thrombus — 약물치료, large thrombus — 약물 효과 제한 → 중재 필요. FDA: IV tPA 3시간(1996) → 4.5시간; IA mechanical recanalization 9시간 이내(MERCI, 2004년 8월); Penumbra system 2008; stent-assisted thrombectomy 2012. 치료 목적: core, penumbra, oligemia. IV tPA 문제점 — 4.5시간이 너무 짧음, 너무 소량이 혈전과 접촉, 효과 적음, 출혈 많음. 약물 한계 — 녹지 않음(심장 혈전: 장기간), 출혈로 인한 사망 → 녹이지 말고 제거. 혈관내 치료 — aspiration, stent retriever, combined technique. 동맥경화 — plaque rupture(TIA), total occlusion; 경동맥·cavernous ICA·MCA·basilar; 풍선확장술·스텐트. 경동맥 스텐트 순서 — A 원위부 색전보호장치 → B 협착부 풍선확장 → C 스텐트 전개 → D 보호장치 회수. 뇌동맥류 — clipping vs endovascular; flow diverter, WEB; 혈관내 치료 — 비교적 비침습, 일상 복귀 빠름, 재발률 10–20%, 합병증은 clipping과 유사. Brain AVM 색전술 — 시술 후 steroid + IV low-dose heparin, 1개월 DSA 완치. Summary — Time is brain, 어느 혈관이 폐쇄되었는가, 치료 전 환자 상태, 협착은 스텐트 vs 약물, 동맥류는 rupture vs unrupture.'
OFF=[
Q('강의록','조영제 투여가 금기인 환자에서 두개내 혈관 협착을 선별하려 한다. 가장 적절한 검사는?',['TOF MRA','CTA','DSA','조영증강 CT','CT perfusion'],1,IMG,['정답. 조영제 불필요.','요오드 조영제.','조영제·침습.','조영제.','조영제.']),
Q('강의록','CTA의 제한점으로 강의록에 제시된 것은?',['혈관 석회화 시 협착을 과대평가할 수 있다','공간해상도가 낮다','촬영 시간이 매우 길다','방사선 피폭이 없다','두개내 혈관 평가가 불가능하다'],1,IMG,['정답.','높음.','빠름.','피폭 있음.','경동맥 초음파.']),
Q('강의록','TOF MRA에서 협착이 과대평가될 수 있는 원인은?',['난류(turbulent flow)','석회화','요오드 조영제','방사선','골 음영'],1,IMG,['정답.','CTA.','틀리다.','틀리다.','틀리다.']),
Q('강의록','뇌혈관 영상의 진단 표준(gold standard)이며 혈전제거술 등 치료 계획과 애매한 협착 확진에 쓰이는 검사는?',['DSA','CTA','TOF MRA','경동맥 초음파','비조영 CT'],1,IMG,['정답.','1차 평가.','선별.','경동맥 선별.','출혈 배제.']),
Q('강의록','강의록에 제시된 DSA의 합병증 위험도는?',['약 0.5–1%','약 5–10%','약 20%','0%','약 30%'],1,IMG,['정답.','틀리다.','틀리다.','침습적.','틀리다.']),
Q('강의록','경동맥 초음파의 제한점으로 옳은 것은?',['검사자 의존적이며 두개내 혈관 평가가 제한적','방사선 피폭','요오드 조영제 필요','실시간 혈류평가 불가','침습적'],1,IMG,['정답.','없음.','불필요.','가능.','비침습.']),
Q('강의록','급성 뇌졸중 1차 평가와 대혈관 폐색 확인에 강의록이 제시한 검사는?',['CTA','경동맥 초음파','TOF MRA','DSA','뇌파'],1,IMG,['정답.','추적관찰.','선별.','치료 계획.','무관.']),
Q('강의록','64세 여자가 2시간 전 발생한 좌측 편마비와 구음장애로 왔다. 10년간 심방세동 치료 중이며 CT에서 출혈은 없다. 강의록의 투여 방법과 예상 폐색 혈관을 옳게 짝지은 것은?',['IV tPA 0.9 mg/kg을 1시간 동안 — 우측 중대뇌동맥','IV tPA 0.9 mg/kg을 1시간 동안 — 좌측 중대뇌동맥','동맥내 urokinase — 기저동맥','IV heparin — 좌측 전대뇌동맥','IV tPA 0.6 mg/kg 일시 주사 — 우측 후대뇌동맥'],1,CASE,['정답.','좌측 편마비 → 우측.','틀리다.','틀리다.','틀리다.']),
Q('강의록','심방세동 환자에서 뇌색전의 혈전 기원으로 강의록에 표시된 부위는?',['좌심방이(left atrial appendage)','우심실','폐정맥','하대정맥','경정맥'],1,CASE+' '+INT,['정답.','틀리다.','틀리다.','역설적 색전 아님.','틀리다.']),
Q('강의록','TOAST 분류에서 cardioembolism을 시사하는 영상 소견은?',['여러 혈관 영역에 걸친 다발성 경색','1.5 cm 미만 단일 피질하 경색','주요 혈관 50% 초과 협착과 해당 영역 경색','양측 말단 ICA 협착과 측부혈관','중뇌주위 SAH'],1,TOAST,['정답.','SVO.','LAA.','모야모야(other).','무관.']),
Q('강의록','TOAST에서 "Stroke of other determined etiology"에 해당하지 않는 것은?',['심방세동','동맥 박리','혈관염','모야모야','겸상적혈구병'],1,TOAST,['정답. cardioembolism.','해당.','해당.','해당.','해당.']),
Q('강의록','TOAST에서 small-artery occlusion의 전형적 임상 증후군이 아닌 것은?',['실어증','Pure motor hemiparesis','Pure sensory stroke','Ataxic hemiparesis','—'],1,TOAST,['정답. 피질 징후 → LAA.','해당.','해당.','해당.','—'],fixed=True),
Q('강의록','경동맥 협착이 50% 미만이지만 증상성 색전 경색이 있고 다른 원인이 없는 경우 강의록이 제시한 개념은?',['Symptomatic nonstenotic carotid stenosis','Tandem occlusion','Perimesencephalic hemorrhage','Carotid-cavernous fistula','Moyamoya'],1,DIS,['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록','관류 MRI/CT에서 치료로 살릴 수 있는 영역을 추정할 때 쓰이는 개념은?',['Core와 penumbra의 mismatch','Core의 크기만','T1 고신호','석회화 정도','Meniscus sign'],1,DIS+' '+INT,['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록','중대뇌동맥 폐색의 혈관조영 유형 중 두개내 죽상경화(ICAS) 관련 폐색을 시사하는 것은?',['Truncal type','Branching type','Tandem type','Meniscus type','Puff of smoke'],1,DIS,['정답.','색전.','틀리다.','틀리다.','모야모야.']),
Q('강의록','모야모야병의 특징으로 옳지 않은 것은?',['주로 기저동맥 말단의 단측성 협착','이름은 일본어 "puff of smoke"에서 유래','소아(5–10세)와 성인(30–50세)에서 증상이 처음 나타남','허혈성뿐 아니라 출혈성 뇌졸중도 발생','혈관조영에서 양측 말단 내경동맥 협착과 측부혈관망'],1,DIS,['정답. 양측 말단 ICA.','옳다.','옳다.','옳다.','옳다.']),
Q('강의록','첫 혈관조영에서 동맥류가 발견되지 않은 자발성 SAH의 원인 중 약 50%를 차지하는 것은?',['비동맥류성 중뇌주위 출혈','AVM','척수 혈관 병변','종양 출혈','외상'],1,SAH,['정답.','일부.','일부.','일부.','자발성 아님.']),
Q('강의록','첫 혈관조영에서 동맥류가 보이지 않는 경우는 자발성 SAH의 약 몇 %인가?',['15–20%','1–2%','50%','80%','5% 미만'],1,SAH,['정답.','틀리다.','중뇌주위 비율.','틀리다.','틀리다.']),
Q('학습지(강의 설명)','9세 아이가 외상 없이 갑자기 두통을 호소하며 쓰러졌고 CT에서 뇌실질 출혈이 보인다. 강의에서 가장 먼저 의심하라고 한 질환은?',['뇌동정맥기형(AVM)','고혈압성 뇌출혈','아밀로이드 혈관병증','당뇨병성 뇌출혈','심인성 색전'],1,SAH,['정답.','성인.','노인.','틀리다.','허혈.']),
Q('강의록','외상 후 안구 돌출과 결막 충혈이 생긴 64세 남자의 혈관조영에서 안정맥으로 조기 배출되는 소견이 보였다. 진단은?',['외상성 경동맥-해면정맥동루(CCF)','모야모야병','AVM','중뇌주위 SAH','경동맥 박리'],1,SAH,['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록','신경중재 치료의 개념으로 강의록에 제시된 것은?',['내과와 외과의 중간 개념으로 사망률 감소·치료효과 극대화','외과 수술의 한 종류','약물치료만을 뜻함','진단 목적의 영상검사','재활치료의 일종'],1,INT,['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록','강의록의 FDA 승인 연대 순서로 옳은 것은?',['IV tPA(1996) → MERCI(2004) → Penumbra system(2008) → stent-assisted thrombectomy(2012)','MERCI → IV tPA → stent → Penumbra','Penumbra → MERCI → IV tPA → stent','stent → Penumbra → MERCI → IV tPA','IV tPA → stent → MERCI → Penumbra'],1,INT,['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록','강의록이 제시한 IV tPA의 문제점이 아닌 것은?',['혈전과 접촉하는 tPA 양이 너무 많아 과용량','치료 가능 시간이 짧다','치료 효과가 적다','출혈이 많다','오래된 심장 혈전은 잘 녹지 않는다'],1,INT,['정답. 너무 소량이 접촉.','문제점.','문제점.','문제점.','약물 한계.']),
Q('강의록','큰 혈전(large thrombus)에 의한 대혈관 폐색에서 강의록이 제시한 치료 방향은?',['녹이지 말고 제거 — aspiration·stent retriever 등 혈관내 치료','IV tPA 용량을 두 배로','항혈소판제만 투여','관찰','경동맥 내막절제술'],1,INT,['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록','경동맥 스텐트 시술 순서로 옳은 것은?',['원위부 색전보호장치 → 풍선확장 → 스텐트 전개 → 보호장치 회수','풍선확장 → 스텐트 → 보호장치 설치','스텐트 → 풍선 → 보호장치 설치 → 회수','보호장치 회수 → 풍선 → 스텐트','스텐트만 단독 삽입'],1,INT,['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록','뇌동맥류 혈관내 치료(코일 색전술)에 대한 설명으로 옳은 것은?',['재발률은 10–20%이며 합병증은 clipping과 유사하다','재발률이 clipping보다 낮다','일상 복귀가 clipping보다 늦다','clipping보다 더 오래된 치료법이다','합병증이 clipping의 10배이다'],1,INT,['정답.','높다.','빠르다.','틀리다.','유사.']),
Q('강의록','뇌동맥류의 혈관내 치료 기구로 강의록에 소개된 것은?',['Flow diverter와 WEB','Emboli-protection device','Stent retriever','Aspiration catheter','MERCI retriever'],1,INT,['정답.','경동맥 스텐트.','혈전제거.','혈전제거.','혈전제거.']),
Q('강의록','뇌 AVM 색전술 후 강의록 증례에서 사용한 시술 후 약물은?',['Steroid와 IV 저용량 heparin','IV tPA','고용량 항혈소판제 2제','항경련제 단독','Mannitol 단독'],1,INT,['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
]
OFF=[q for q in OFF if not any(c.strip()=='—' for c in q['choices'])]
