def Q(src,stem,choices,ans,basis,exps,**k):
  d=dict(src=src,stem=stem,choices=choices,ans=ans,basis=basis,exps=exps); d.update(k); return d
MMC='Myelomeningocele: 신경관 폐쇄 실패로 신경판(neural placode)이 노출된 상태. 출생 후 72시간 이내 수술, 수술 전에는 생리식염수 적신 거즈 드레싱만 하고 latex-free 장갑을 쓴다(강의록).'
TC='Tethered cord: 섬유띠·유착·경막내 지방종이 척수를 잡아당김. Tethered cord syndrome은 늘어난 척수의 혈류 부족에 따른 저산소 스트레스로 생기며 통증, 방광 기능장애, 종아리 근위축을 동반한 다리 위약, 심부건반사 소실, 피부분절형 감각 소실을 보인다. 두꺼운 종사(thickened/fatty filum terminale)에서는 협조된 방광 기능의 점진적 소실이 첫 증상이고 반복 요로감염·요실금이 온다(강의록).'
CS='두개골조기유합증(craniosynostosis): 시상봉합 → 장두증(scaphocephaly), 편측 관상봉합 → 사두증(plagiocephaly), 양측 관상봉합 → 단두증(brachycephaly), 전두(metopic)봉합 → 삼각두(trigonocephaly), 시옷(lambdoid)봉합 → 후사두증. 수술: suturectomy, suturectomy with morcellation(두개골을 작게 조각내 remodeling 유도, 강의 QUIZ).'
OFF=[
Q('강의록','출생 직후 요천추부에 신경판이 노출된 척수수막류(myelomeningocele)가 발견되었다. 수술 전 처치로 옳은 것은?',
 ['생리식염수 적신 거즈로 덮고 latex-free 장갑을 쓴다.','포비돈 요오드 거즈로 단단히 압박 드레싱한다.','건조 거즈로 덮고 2주 뒤 수술한다.','노출된 신경판을 소독 알코올로 닦는다.','일반 라텍스 장갑으로 즉시 봉합한다.'],1,MMC,
 ['정답.','노출된 신경조직에 소독제·압박은 피한다.','72시간 이내에 수술한다.','신경조직 손상 위험.','라텍스 알레르기 위험이 커 latex-free 장갑을 쓴다.']),
Q('강의록','Myelomeningocele의 수술 시기로 강의록에 제시된 것은?',['출생 후 72시간 이내','출생 후 1개월','생후 6개월','돌 이후','증상이 생길 때까지 관찰'],1,MMC,['정답.','늦다.','늦다.','늦다.','감염 위험 때문에 조기 수술한다.']),
Q('강의록','Myelomeningocele의 병태로 옳은 것은?',['신경관 폐쇄 실패로 신경판이 노출된다.','두개골 봉합이 너무 일찍 닫힌다.','제4뇌실이 낭성으로 확장된다.','소뇌 편도가 대후두공 아래로 내려온다.','거미막이 CSF를 품은 낭을 만든다.'],1,MMC,['정답.','Craniosynostosis.','Dandy-Walker.','Chiari.','Arachnoid cyst.']),
Q('강의록','강의록에 제시된 lipomyelomeningocele(LMM)의 분류가 아닌 것은?',['Caudal(terminal)-type','Transitional-type','Dorsal-type','Chaotic-type','Cervical-type'],4,
 '강의록: LMM 분류 — caudal- 또는 terminal-type, transitional-type, dorsal-type. 척수와 지방종의 경계(원추와의 관계, 신경근 주행)가 수술에 중요.',
 ['제시됨.','제시됨.','제시됨.','정답. 강의록에 제시되지 않은 분류.','제시됨.']),
Q('강의록','선천성 피부동관(congenital dermal sinus tract)을 의심해야 하는 임상 상황으로 강의록에 제시되지 않은 것은?',['반복되는 만성 수막염','흔하지 않은 균에 의한 수막염','원인 모를 반복 발열','항문 2.5 cm 안의 5 mm 미만 정중선 단순 보조개','요추부 피부 구멍'],4,
 '강의록: CDST — chronic bouts of meningitis, meningitis by unusual organisms, recurrent fever of unclear origin. 천미골 보조개(sacrococcygeal dimple)는 대개 무해하며, 5 mm 미만·정중선·항문 2.5 cm 이내·다른 피부 징후가 없으면 잠재 척추이분증과 연관이 없었다(Kriss & Desai).',
 ['제시됨.','제시됨.','제시됨.','정답. 단순 보조개는 대개 무해하다.','피부동관의 입구.']),
Q('강의록','천미골 보조개(sacrococcygeal dimple)에 대한 설명으로 옳지 않은 것은?',['대개 무해하다.','엉덩이 틈(natal cleft) 안쪽에서 보인다.','소아의 2–5%에서 보인다.','진짜 피부동관과 혼동되기도 한다.','5 mm 미만의 정중선 단순 보조개도 대부분 잠재 척추이분증과 연관된다.'],5,
 '강의록: Kriss와 Desai는 단순 보조개(5 mm 미만, 정중선, 항문 2.5 cm 이내, 다른 피부 징후 없음) 중 잠재 척추이분증과 연관된 예가 없었다고 보고.',
 ['맞다.','맞다.','맞다.','맞다.','틀리다(정답). 연관된 예가 없었다.']),
Q('강의록','Kriss와 Desai가 제시한 "단순 보조개(simple dimple)"의 기준이 아닌 것은?',['지름 5 mm 미만','정중선','항문에서 2.5 cm 이내','다른 피부 징후가 없음','털 뭉치(hair tuft)가 동반됨'],5,
 '단순 보조개 기준: <5 mm, 정중선, 항문 2.5 cm 이내, 다른 피부 징후 없음. 털·혈관종·지방종 등 피부 징후가 있으면 잠재 척추이분증을 의심.',['기준.','기준.','기준.','기준.','정답. 피부 징후는 단순 보조개가 아니다.']),
Q('강의록','Tethered cord syndrome의 발생 기전으로 강의록에 제시된 것은?',['늘어난 척수의 혈류 부족에 따른 저산소 스트레스','척수의 탈수초','CSF 흡수 장애','자가면역 염증','척수의 선천성 과성장'],1,TC,['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록','Tethered cord syndrome의 증상으로 옳지 않은 것은?',['통증','방광 기능장애','종아리 근위축을 동반한 다리 위약','심부건반사 항진과 간대(clonus)','피부분절형 감각 소실'],4,TC,['증상.','증상.','증상.','정답. 심부건반사는 소실된다.','증상.']),
Q('강의록','두꺼운 종사(thickened/fatty filum terminale)에 의한 견인척수에서 첫 증상으로 가장 흔한 것은?',['협조된 방광 기능의 점진적 소실','급성 사지마비','두통과 구토','시야 결손','경련'],1,TC,['정답. 반복 요로감염·요실금.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록','8세 아이가 반복 요로감염과 새로 생긴 요실금, 종아리가 가늘어지는 다리 위약으로 왔다. 요추부 MRI에서 원추가 낮게 위치하고 종사가 두껍고 지방이 보인다. 가장 적절한 진단은?',['Tethered cord syndrome','Chiari malformation','Dandy-Walker malformation','Arachnoid cyst','Craniosynostosis'],1,TC,['정답.','소뇌 편도 하방 전위.','제4뇌실 확장.','거미막 낭.','두개골 봉합 조기 유합.']),
Q('강의록','Dandy-Walker malformation의 특징이 아닌 것은?',['제4뇌실의 확장','소뇌 충부의 무형성 또는 저형성','소뇌 천막과 정맥동의 상방 전위','소뇌 편도의 대후두공 하방 전위','치료로 VP shunt 또는 CP shunt'],4,
 '강의록: Dandy-Walker — 제4뇌실 확장, 소뇌 충부 무형성·저형성, 소뇌 천막 주위와 정맥동 상방 전위. 치료 VP shunt and/or CP(cystoperitoneal) shunt.',
 ['특징.','특징.','특징.','정답. Chiari 기형의 특징.','치료.']),
Q('강의록','Dandy-Walker malformation의 치료로 강의록에 제시된 것은?',['VP shunt 그리고/또는 CP shunt','Suturectomy','대후두공 감압술 단독','경막내 지방종 절제','72시간 이내 신경판 봉합'],1,
 'Dandy-Walker 치료: VP shunt and/or CP shunt.',['정답.','Craniosynostosis.','Chiari 치료.','LMM·tethered cord.','Myelomeningocele.']),
Q('강의록','Chiari malformation의 정의로 옳은 것은?',['소뇌 편도가 대후두공을 통해 아래로 전위된 기형','제4뇌실이 낭성 확장된 기형','두개골 봉합이 조기 유합된 기형','뇌조직이 두개골 결손으로 빠져나온 기형','거미막 발생 이상으로 CSF 낭이 생긴 기형'],1,
 'Chiari malformation: 소뇌 tonsil이 대후두공을 통해 하방 전위. 치료 — decompression, VP shunt, repair of anomaly.',['정답.','Dandy-Walker.','Craniosynostosis.','Encephalocele.','Arachnoid cyst.']),
Q('강의록','증상이 있는 Chiari malformation의 치료로 강의록에 제시되지 않은 것은?',['대후두공 감압(suboccipital craniectomy)','경막 패치(duraplasty)','C1 laminectomy(선택)','VP shunt','Suturectomy with morcellation'],5,
 'Chiari 치료: decompression(대후두공 두개골 절제 ± C1 후궁절제, 경막 패치), VP shunt, 동반 기형 교정. Suturectomy는 craniosynostosis 수술.',['제시됨.','제시됨.','제시됨.','제시됨.','정답.']),
Q('강의록','Chiari I malformation의 증상으로 가장 대표적인 것은?',['후두-경부 두통','양측 시신경유두부종 없이 생기는 복시만','하지의 이완성 마비','요추부 피부 구멍','반복 세균성 수막염'],1,
 '강의록 Box 190-1(Chiari I): 후두-경부 두통, 이상감각, 등·어깨·사지 통증, 소뇌 증후군(실조), 뇌간 증후군(하부 뇌신경 장애, 반복 흡인), 척수 증후군(손의 운동·감각 소실).',['정답.','틀리다.','틀리다.','CDST.','CDST.']),
Q('강의록','Chiari II malformation 영아에서 신경학적 응급으로 강의록에 제시된 소견이 아닌 것은?',['진행하는 목 통증','무호흡','삼킴곤란','천명(stridor)','지능 향상'],5,
 'Chiari II 신경학적 응급(대개 2세 미만, 흔히 생후 3개월까지): 진행하는 목 통증, 무호흡, 삼킴곤란, 천명, 후궁반장, 안진, 진행하는 뇌간 기능장애.',['응급 소견.','응급 소견.','응급 소견.','응급 소견.','정답.']),
Q('강의록','두개골 결손 부위로 뇌조직·수막이 빠져나온 선천 기형은?',['Encephalocele','Myelomeningocele','Arachnoid cyst','Dandy-Walker malformation','Tethered cord'],1,'강의록: encephalocele — 두개골 결손을 통한 뇌·수막 탈출, 수술 전후 사진 제시.',['정답.','척추 부위.','거미막 낭.','제4뇌실 확장.','척수 견인.']),
Q('강의록','Arachnoid cyst에 대한 설명으로 옳은 것은?',['거미막의 발생 이상으로 CSF를 포함하는 거미막 낭성 질환이다.','소뇌 충부 무형성이 특징이다.','신경관 폐쇄 실패로 생긴다.','두개골 봉합의 조기 유합이다.','항상 악성 종양으로 진행한다.'],1,'강의록: 거미막의 발생 이상으로 뇌척수액을 포함하는 거미막으로 이루어진 낭성 질환(외상 후 증상이 드러나기도 함).',['정답.','Dandy-Walker.','MMC.','Craniosynostosis.','틀리다.']),
Q('강의록','시상봉합(sagittal suture) 조기유합증에서 나타나는 두개 모양은?',['장두증(scaphocephaly)','단두증(brachycephaly)','삼각두(trigonocephaly)','사두증(plagiocephaly)','후사두증'],1,CS,['정답.','양측 관상봉합.','전두봉합.','편측 관상봉합.','시옷봉합.']),
Q('강의록','두개골 봉합과 조기유합 시 두개 모양의 연결로 옳지 않은 것은?',['시상봉합 – 장두증','편측 관상봉합 – 사두증','양측 관상봉합 – 단두증','전두(metopic)봉합 – 삼각두','시옷(lambdoid)봉합 – 장두증'],5,CS,['맞다.','맞다.','맞다.','맞다.','틀리다(정답). 시옷봉합 조기유합은 후사두증.']),
Q('강의록','앞이마가 뾰족하게 삼각형으로 튀어나온 영아에서 조기유합된 봉합은?',['Metopic suture','Sagittal suture','Coronal suture 양측','Lambdoid suture','Squamous suture'],1,CS,['정답. 삼각두.','장두증.','단두증.','후사두증.','틀리다.']),
Q('강의록 33쪽 QUIZ','두개골조기유합증 수술 중 두개골을 작게 조각내어 remodeling을 유도하는 수술 방법은?',['Suturectomy with morcellation','Suboccipital decompression','VP shunt','Cystoperitoneal shunt','Laminectomy'],1,CS,['정답(강의 QUIZ).','Chiari.','수두증.','Dandy-Walker·낭.','척추.']),
Q('강의록','Craniosynostosis의 수술로 강의록에 제시된 것은?',['Suturectomy','Endoscopic third ventriculostomy','Myelomeningocele repair','Untethering of filum','Microvascular decompression'],1,CS,['정답. Suturectomy(± morcellation).','수두증.','MMC.','견인척수.','삼차신경통.']),
Q('강의록','다음 중 척수이분증(spinal dysraphism) 계열에 속하지 않는 것은?',['Myelomeningocele','Lipomyelomeningocele','Congenital dermal sinus tract','Tethered cord','Craniosynostosis'],5,
 '강의 1–4번(MMC, LMM, CDST, tethered cord)은 척수·척추 기형이고, craniosynostosis는 두개골 봉합 기형.',['척수이분증.','척수이분증.','척수이분증.','척수이분증 관련.','정답.']),
Q('강의록','요추부에 작은 피부 구멍이 있고 반복적인 세균성 수막염을 앓는 소아에서 금기인 검사는?',['피부동관을 통한 조영술 또는 그 부위 요추천자','요추 MRI','혈액배양','뇌 MRI','소변검사'],1,
 '피부동관은 경막 안까지 이어질 수 있어 감염 경로가 된다. 그 부위의 탐침·조영술·요추천자는 피하고 MRI로 동관 깊이와 척수 연결을 확인한다.',['정답.','적절.','적절.','적절.','적절.']),
]
