def Q(src,stem,choices,ans,basis,exps,**k):
  d=dict(src=src,stem=stem,choices=choices,ans=ans,basis=basis,exps=exps); d.update(k); return d
GEN='강의록 4–9쪽: 근위부 근쇠약(의자에서 일어나기·계단·머리감기·높은 물건), 일반 근육병증은 지속적, 주기마비·대사근육병증은 간헐적; 골반근 저하 — Gowers sign, lumbar lordosis, waddling gait; 원위부 — foot drop, steppage gait. 기타 — 근육통, 경련, 구축, 근긴장증, 근위축, 근비대(DMD, BMD). CK — 골격근 CK-MM, 심근 CK-MB; 과도한 운동·외상·근경련·전신발작으로도 증가. 근생검 — 근염 염증·괴사 확인, 유전 근육병 보충, 신경병과 감별. 근육 MRI — 침범 양상, 생검 부위 선택, 부종(활동성 초기), 위축·지방 대치(만성), 피하부종·근막염.'
INF='강의록 13–17쪽: DM — 피부병변+근위약, Gottron sign, heliotrope rash, V-sign, shawl sign, mechanic’s hand; MSA anti-Mi-2, TIF-1γ, NXP-2, MDA-5, SAE; 발병 3–5년 내 암 위험 증가(9–32%). IBM — 국소·원위·비대칭 위약(대퇴사두근, 손가락 굴곡근, 족관절 배굴) ± 삼킴곤란(60%), 수년에 걸쳐 진행, 면역치료 무반응, rimmed vacuole·inclusion body, anti-NT5C1A 40–60%. PM — 배제진단; 발진·가족력·근독성 약물(statin, penicillamine, zidovudine)·안면/외안근 침범·내분비병·IBM 표현형이 없는 성인 아급성 근위부 근육병; 20세 이상 여성에 흔함; 목 굴곡근·대칭 근위부 위약, 근육통·압통, 삼킴곤란(1/3); 근육 외 침범 ILD·심근염. Overlap myositis — SLE, Sjögren, RA, SSc 동반. Antisynthetase syndrome — aminoacyl-tRNA synthetase 자가항체, 위약은 심하지 않고 발진·관절염·ILD. IMNM — 공격적 근위부 위약, CK 현저 상승, 괴사(염증은 없음). 치료 — 스테로이드 1차(0.5–1 mg/kg/d, 최대 60–80 mg), 심하면 IV methylPD 1 g/d 3–5일; CK 감소만으로 호전 판단 불가; 2차 MTX, AZA, MMF, CYC; IVIG 1–2 g/kg/월; rituximab — 중증·불응.'
DYS='강의록 19–27쪽: 근디스트로피 — 유전적 진행성 근손상, 괴사·재생, 근섬유 사이 결합조직 증가; 디스트로핀병 심근병증, 근긴장디스트로피 부정맥·갑상샘이상·당뇨. Dystrophinopathy — XR; DMD 완전소실(가장 심함), BMD 부분소실(늦은 발현·진행). DGC — dystrophin, dystroglycan, sarcoglycan, sarcospan, syntrophin: 세포외기질 결합·세포골격 유지, 내부 F-actin 결합. DMD — 남아 5000명 중 1명, 2–3세, Gowers sign, waddling gait, 장딴지 가성비대, 12세 무렵 보행불가, 척추측만·호흡부전·심근병증, CK 10–50배, EMG 근육병 소견, 생검 괴사·재생·hyaline fiber, 디스트로핀 완전 소실. BMD — 16세까지 독립보행, 천천히 진행, 가성비대·심근병증, CK 증가(덜함), 디스트로핀 전반적 감소·불균일. 진단 — MLPA(결손·중복), 염기서열분석; 전형적이면 생검 없이 유전자검사. 치료 — prednisolone, deflazacort; eteplirsen(ASO, 엑손 51 skipping, FDA 승인); Elevidys(AAV 마이크로디스트로핀 유전자치료, 정맥 단회); 6개월–1년 간격 호흡기능평가, 확장성 심근병증·심부전·돌연사 관리, 구축·측만 예방.'
LGMD='강의록 28–39쪽: LGMD — 독립보행 가능해진 이후 발병, 근위부 쇠약; 구분류 LGMD1(AD)/2(AR) + 발견 순서 A,B,C; 신분류 LGMD D(AD)/R(AR) + 원인 유전자 숫자. R1 — CAPN3/calpain3, 일부 winged scapula, DMD보다 느림, eosinophil 침윤. R2 dysferlinopathy — DYSF, 10–20대, CK 10–150배. R3–R6 sarcoglycanopathy — SGCA/B/G/D, 어린 나이 근위부. DM1 — AD, DMPK CTG 확장(길이∝중증도), 원위부·안면 약화, myopathic face, ptosis, 구음·삼킴장애, percussion·grip-release myotonia, napkin ring sign, 부정맥·백내장·인슐린저항·갑상샘, CK ≤500, myotonic discharge, central nuclei·ring fiber, 확진 유전자검사. DM2 — AD, CNBP/ZNF9 CCTG, 근위부, 부정맥·내분비 드묾, CK 경미. 치료 — 근본 치료 없음, mexiletine(근긴장), phenytoin, carbamazepine, 매년 ECG·갑상샘·인슐린저항·테스토스테론. FSHD — 8000명당 1명(DMD, DM 다음), 얼굴·어깨·위팔 → 후기 하지, ptosis 없음, winged scapula, 오목가슴, 측만; CK 경미; 4번 장완 D4Z4 반복 감소 → DUX4 부적절 발현; FSHD1(95%) 1–10회, FSHD2 18–20회+후성유전; 효과적 치료 없음(losmapimod 연구). OPMD — 40대, ptosis+dysphagia+근위부 위약, PABPN1 GCN 반복(11–18), rimmed vacuole, ragged red fiber, tubulofilamentous inclusion, 삼킴장애에 botulinum toxin. EDMD — humeroperoneal 분포, 관절구축, 부정맥·심근병증.'
CH='강의록 41–44쪽: 이온통로병증 — 일차 주기마비(저칼륨: CACNA1S·SCN4A, 가장 흔함, 0–20세, 심한 운동 후 휴식·수면 후·탄수화물·소듐 과다·음주·추위, 아침 발생, 하루 이상, K ≤3 mmol/L; 고칼륨: SCN4A 점돌연변이, 10세 이전, 수시간, 과도한 운동 후 휴식·포타슘 다량·공복·추위, 고칼륨혈증, EMG myotonic discharge). 치료 — 유발인자 회피, 급성기 K 보충/저하; 저칼륨 — K 보충, acetazolamide, 탄수화물 과식·심한 운동 피함; 고칼륨 — K 풍부 음식·공복 피함, acetazolamide. 이차 — 갑상샘독성 주기마비(20–40대 동양인, KCNJ18, 갑상샘 치료로 호전), 이뇨제, 신부전. 비디스트로피 근긴장증 — myotonia congenita(CLCN1, warm-up phenomenon), paramyotonia congenita(SCN4A, 반복 운동에 의해 유발되는 paradoxical myotonia), sodium channel myotonia.'
OFF=[
Q('강의록','근육병증 환자에서 간헐적 근쇠약을 보이는 질환군으로 강의록에 제시된 것은?',['주기마비와 대사근육병증','근디스트로피','다발근육염','봉입소체근염','선천근육병증'],1,GEN,['정답.','지속적.','지속적.','지속적.','지속적.']),
Q('강의록','근육 MRI의 역할로 강의록에 제시되지 않은 것은?',['신경전도속도 측정','전신 골격근 침범 양상 파악','생검 부위 선택','활동성 질환의 근육 부종 확인','만성 질환의 지방 대치 확인'],1,GEN,['정답. NCS.','제시.','제시.','제시.','제시.']),
Q('강의록','CK 상승의 해석으로 옳은 것은?',['과도한 운동·외상·근경련·전신발작으로도 상승할 수 있다','CK-MB는 골격근 특이적이다','CK 상승은 항상 근염을 의미한다','CK 감소만으로 염증근육병 호전을 판단한다','근긴장디스트로피 1형은 CK가 수천 이상이다'],1,GEN+' '+INF+' '+LGMD,['정답.','심근(MM이 골격근).','틀리다.','판단 불가.','≤500.']),
Q('강의록','60세 남자가 수년에 걸쳐 서서히 진행하는 무릎 펴기 약화와 손가락 굽히기 약화, 삼킴곤란을 보인다. 스테로이드에 반응이 없었다. 근생검에서 예상되는 소견은?',['Rimmed vacuole과 inclusion body','Perifascicular atrophy','디스트로핀 완전 소실','Ring fiber','Eosinophil 침윤'],1,INF,['정답. IBM.','DM(강의록 미기재).','DMD.','DM1.','LGMD R1.']),
Q('강의록','피부근염 환자의 추적 관리로 강의록이 강조한 것은?',['발병 후 3–5년간 증가하는 악성종양 위험에 대한 평가','디스트로핀 염색','D4Z4 반복수 검사','Mexiletine 투여','칼륨 보충'],1,INF,['정답(9–32%).','DMD.','FSHD.','근긴장.','주기마비.']),
Q('강의록','다발근육염(PM) 진단 전 배제해야 할 조건이 아닌 것은?',['목 굴곡근과 대칭 근위부 위약','피부발진','근육병 가족력','Statin 등 근독성 약물 노출','안면·외안근 침범'],1,INF,['정답. PM의 전형 소견.','배제.','배제.','배제.','배제.']),
Q('강의록','다발근육염에서 가장 흔한 근육 외 침범은?',['간질성 폐질환(ILD)과 심근염','백내장','난청','신부전','망막박리'],1,INF,['정답.','DM1.','틀리다.','틀리다.','틀리다.']),
Q('강의록','근력위약은 심하지 않고 발진·관절염·간질성 폐질환이 두드러지며 aminoacyl-tRNA synthetase 자가항체가 원인인 질환은?',['Antisynthetase syndrome','IMNM','IBM','Overlap myositis','DM1'],1,INF,['정답.','공격적 위약·괴사.','원위·비대칭.','자가면역질환 동반.','유전.']),
Q('강의록','CK가 현저히 상승하고 공격적인 근위부 위약을 보이며 근생검에서 괴사는 있으나 염증은 없는 질환은?',['면역매개 괴사근육병(IMNM)','피부근염','다발근육염','봉입소체근염','FSHD'],1,INF,['정답.','염증.','염증.','rimmed vacuole.','비특이적.']),
Q('강의록','염증근육병 치료로 옳지 않은 것은?',['CK가 떨어지면 근력과 무관하게 호전된 것으로 판단한다','스테로이드가 1차 치료이다','심한 위약에는 IV methylprednisolone 1 g/d 3–5일 후 경구 전환','스테로이드 실패 시 IVIG','중증·불응성에 rituximab'],1,INF,['정답. CK 감소만으로 호전 아님.','옳다.','옳다.','옳다.','옳다.']),
Q('강의록','Dystrophin glycoprotein complex(DGC)의 구성 요소가 아닌 것은?',['Calpain3','Dystroglycan','Sarcoglycan','Sarcospan','Syntrophin'],1,DYS+' '+LGMD,['정답. LGMD R1.','구성.','구성.','구성.','구성.']),
Q('강의록','Becker 근디스트로피가 Duchenne보다 경과가 가벼운 이유는?',['디스트로핀 단백이 부분적으로 남아 있기 때문','상염색체 우성이기 때문','디스트로핀이 과발현되기 때문','CK가 정상이기 때문','심근을 침범하지 않기 때문'],1,DYS,['정답.','XR.','틀리다.','증가.','심근병증 있음.']),
Q('강의록','DMD 돌연변이 중 가장 흔한 결손·중복을 찾는 데 유용한 검사는?',['MLPA','Western blot calpain3','D4Z4 반복수 분석','CTG 반복 분석','Anti-NT5C1A'],1,DYS,['정답.','LGMD R1.','FSHD.','DM1.','IBM.']),
Q('강의록','Eteplirsen(Exondys 51)의 기전은?',['Antisense oligonucleotide로 인접 엑손을 skip시켜 디스트로핀 발현 증가','AAV로 마이크로디스트로핀 유전자 전달','Myostatin 억제','DUX4 억제','나트륨 통로 차단'],1,DYS+' '+LGMD,['정답.','Elevidys.','FSHD 연구.','FSHD.','mexiletine.']),
Q('강의록','신분류 LGMD의 명명 원칙으로 옳은 것은?',['D는 상염색체 우성, R은 상염색체 열성, 숫자는 원인 유전자에 따라','1은 열성, 2는 우성','A,B,C는 유전형식','X연관 유전은 LGMD D','D는 dystrophin'],1,LGMD,['정답.','반대.','발견 순서(구분류).','틀리다.','틀리다.']),
Q('강의록','근긴장디스트로피 1형에 대한 설명으로 옳은 것은?',['DMPK의 CTG 반복 확장 길이가 중증도와 비례','상염색체 열성','근위부 근육 위주 약화','CK가 정상의 10–50배','Ptosis는 없음'],1,LGMD,['정답.','AD.','원위·안면(DM2가 근위).','≤500.','있음.']),
Q('강의록','얼굴·어깨·위팔 근육 약화와 날개견갑을 보이나 눈꺼풀처짐은 없는 근디스트로피의 원인은?',['4번 염색체 D4Z4 반복 감소로 DUX4 부적절 발현','PABPN1 GCN 반복 증가','DMPK CTG 반복 확장','디스트로핀 결손','CAPN3 돌연변이'],1,LGMD,['정답. FSHD.','OPMD.','DM1.','DMD/BMD.','LGMD R1.']),
Q('강의록','45세에 눈꺼풀처짐, 삼킴곤란, 근위부 위약이 서서히 생겼다. 근생검에서 rimmed vacuole과 전자현미경상 tubulofilamentous inclusion이 보였다. 원인 유전자는?',['PABPN1','DMPK','CNBP','DYSF','CLCN1'],1,LGMD,['정답. OPMD.','DM1.','DM2.','LGMD R2.','myotonia congenita.']),
Q('강의록','팔꿈치 굴곡 구축과 위팔·종아리(humeroperoneal) 위축, 부정맥이 있는 근디스트로피는?',['Emery-Dreifuss 근디스트로피','FSHD','DM2','LGMD R1','OPMD'],1,LGMD,['정답.','얼굴·어깨.','근위부·근긴장.','근위부.','ptosis·dysphagia.']),
Q('강의록','18세 남자가 전날 저녁 고탄수화물 식사와 음주 후 아침에 사지 마비로 깼다. 혈청 K 2.4 mmol/L. 재발 예방으로 강의록에 제시된 것은?',['Acetazolamide와 경구 칼륨, 탄수화물 과식·심한 운동 회피','공복 유지','칼륨 풍부 음식 섭취 제한','Mexiletine','IVIG'],1,CH,['정답. 저칼륨주기마비.','고칼륨 예방법 반대.','고칼륨.','근긴장.','근염.']),
Q('강의록','반복 운동으로 근긴장이 오히려 심해지는(paradoxical myotonia) 질환과 원인 유전자는?',['Paramyotonia congenita — SCN4A','Myotonia congenita — CLCN1','DM1 — DMPK','저칼륨주기마비 — CACNA1S','FSHD — DUX4'],1,CH,['정답.','warm-up.','틀리다.','틀리다.','틀리다.']),
Q('강의록','갑상샘독성 주기마비에 대한 설명으로 옳은 것은?',['20–40대 동양인에서 흔하며 갑상샘중독 치료로 호전','고칼륨혈증 동반','10세 이전 발병','CLCN1 돌연변이','근본 치료가 없음'],1,CH,['정답.','저칼륨.','고칼륨주기마비.','myotonia congenita.','틀리다.']),
]
OFF=[q for q in OFF if 'CK 상승의 해석' not in q['stem'] and 'Becker 근디스트로피가' not in q['stem'] and '갑상샘독성' not in q['stem']]
