def Q(src,stem,choices,ans,basis,exps,**k):
  d=dict(src=src,stem=stem,choices=choices,ans=ans,basis=basis,exps=exps); d.update(k); return d
FR='뇌파1 강의록: delta 0–<4 Hz, theta 4–<8 Hz, alpha 8–13 Hz, beta >13 Hz.'
PR='뇌파1 강의록 소아 후두부 리듬: 4개월 3–4 Hz, 5개월 5 Hz, 1세 6 Hz(하한 5), 2세 7, 3세 8(하한 6), 6세 9(하한 7), 8세 하한 8("eight by eight"), 13세 10 Hz.'
MON='뇌파1 강의록 몽타주: bipolar — 인접 전극 쌍, 넓게 퍼진 동조 전위를 제거하는 공간 필터, 국소적인 저–중진폭 파형 분석에 최적(Fp1-F3, F3-C3 등); referential — 모든 증폭기 input 2에 같은 전극(두부·비두부), 넓게 퍼진 고진폭 활동이 국소 저진폭 활동을 가릴 수 있음(Fp1-Cz 등); average — 모든 10-20 전극 합을 input 2에, 둘의 중간·넓은 전위 감쇠 적음. 극성: input1−input2가 음이면 위, 양이면 아래.'
STG='뇌파2 강의록 수면 단계: W — 후두부 alpha가 epoch 50% 초과(없으면 0.5–2 Hz 눈깜빡임, 독서 안구운동, 정상·높은 턱근 긴장과 불규칙 REMs); N1 — alpha 감쇠, 저진폭 혼합주파수(4–7 Hz) >50%, vertex sharp wave·느린 안구운동 가능(필수 아님); N2 — 각성과 무관한 K complex 또는 sleep spindle(각성 동반 K complex만 있으면 N1 유지); N3 — 서파(SWA)가 epoch의 20% 이상(30초 중 6초), 연령 무관; R — 저진폭 EEG(K complex·spindle 없음) + REMs + 낮은 EMG, 톱니파는 필수 아님, 모든 R epoch에 REM이 있는 것은 아님.'
OFF=[
Q('뇌파1 강의록','EEG 주파수 대역의 연결로 옳은 것은?',['Theta 4–<8 Hz','Delta 4–8 Hz','Alpha 13–20 Hz','Beta <8 Hz','Alpha 4–8 Hz'],1,FR,['정답.','0–<4.','8–13.','>13.','theta.']),
Q('뇌파1 강의록','8–13 Hz에 해당하는 뇌파 대역은?',['Alpha','Beta','Theta','Delta','Gamma'],1,FR,['정답.','>13.','4–<8.','<4.','강의록 외.']),
Q('뇌파1 강의록','"eight by eight" 규칙의 의미로 옳은 것은?',['8세가 되면 후두부 리듬이 8 Hz 이상이어야 한다','8개월에 8 Hz','성인은 8 Hz 미만이 정상','8초 동안 기록','8개 전극만 사용'],1,PR,['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('뇌파1 강의록','소아 후두부 우세 리듬의 연령별 전형 주파수로 옳지 않은 것은?',['1세 – 10 Hz','4개월 – 3–4 Hz','3세 – 8 Hz','6세 – 9 Hz','13세 – 10 Hz'],1,PR,['틀리다(정답). 1세 6 Hz.','맞다.','맞다.','맞다.','맞다.']),
Q('뇌파1 강의록','국소적인 저–중진폭 파형 분석에 가장 적합하며 넓게 퍼진 동조 전위를 제거하는 몽타주는?',['Bipolar montage','Referential montage','Average montage','Cz reference만','Non-cephalic reference'],1,MON,['정답.','가려질 수 있음.','중간.','referential.','referential.']),
Q('뇌파1 강의록','Referential montage의 단점으로 옳은 것은?',['넓게 퍼진 고진폭 활동이 국소 저진폭 활동을 가릴 수 있다','인접 전극 쌍만 사용한다','넓은 전위를 모두 제거한다','전극을 두부에만 둘 수 있다','진폭 비교가 불가능하다'],1,MON,['정답.','bipolar.','bipolar.','비두부 가능.','틀리다.']),
Q('뇌파1 강의록','EEG 증폭기에서 input 1 − input 2가 음(negative)일 때 파형 방향은?',['위(up)','아래(down)','평탄','위상 역전 없음','무작위'],1,MON,['정답.','양일 때.','틀리다.','틀리다.','틀리다.']),
Q('뇌파1 강의록','정상 각성 뇌파(눈 감은 상태)의 특징으로 옳은 것은?',['앞에서 뒤로 갈수록 진폭은 커지고 주파수는 감소하는 전후 경사(anteroposterior gradient)','전두부 진폭이 가장 크다','후두부 alpha는 눈을 떠도 유지된다','앞쪽이 느리고 뒤쪽이 빠르다','경사가 없다'],1,'뇌파1 강의록: 전두→후두로 갈수록 진폭↑·주파수↓, 앞쪽 저전압·뒤쪽 고전압 → anteroposterior gradient; 눈 감으면 후두부 리듬, 눈 뜨면 소실(alpha block).',['정답.','후두부.','눈 뜨면 소실.','반대.','있다.']),
Q('뇌파1 강의록','졸림(drowsy) 단계의 뇌파 변화가 아닌 것은?',['후두부 alpha의 증가와 전후 경사 강화','후두부 리듬의 경미한 느려짐','느린 수평 안구운동','후두부 리듬 소실과 저전압 theta','두정부(vertex) theta 증가'],1,'뇌파1 강의록 drowsy: 후두부 리듬 경미한 느려짐, slow roving lateral eye movements, 후두부 리듬 소실 후 저전압 theta, vertex 중심 미만성 theta 증가; 소아에서 고전압 과동기 서파.',['정답.','변화.','변화.','변화.','변화.']),
Q('뇌파1 강의록','눈이 위로 움직일 때 Fp1·Fp2에서 보이는 전위의 원리는?',['각막이 양전하(cornea positivity)이므로 Fp 전극에 양전위 편향이 생긴다','각막이 음전하이므로','망막이 양전하이므로','근육 전위 때문','전극 불량'],1,'뇌파1 강의록: cornea positivity — 안구가 위로 가면 각막(+)이 Fp 전극에 가까워져 양전위.',['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('뇌파1 강의록','간질양 방전(epileptiform discharge)에 대한 설명으로 옳은 것은?',['발작간기 또는 발작기 활동으로 피질의 흥분성 증가를 나타내며, 존재가 곧 진행 중 발작을 의미하지는 않는다','항상 진행 중인 발작을 의미한다','발작기에만 보인다','정상인에서만 보인다','진단적 가치가 없다'],1,'뇌파1 강의록: epileptiform discharge는 interictal 또는 ictal, 발작이 드물어도 발작간기 방전 검출로 EEG가 중요, 피질 흥분성·과민성 증가를 나타내나 ongoing seizure를 의미하지 않을 수 있음.',['정답.','아닐 수 있음.','발작간기도.','틀리다.','있다.']),
Q('뇌파1 강의록','Electroclinical seizure와 electrographic seizure의 구분으로 옳은 것은?',['Electrographic seizure는 임상 변화 없이 EEG에서만 발작 방전이 기록되는 경우','Electroclinical seizure는 임상 변화가 없어도 된다','Electrographic seizure는 반드시 의식소실이 동반된다','두 용어는 같다','Electroclinical seizure는 두피 전극에서 반드시 보여야 한다'],1,'뇌파1 강의록: electroclinical — EEG 이상 + 임상 변화 필수, 두피에서 못 잡아도 심부전극에서는 기록되어야; electrographic — 임상 변화 없이 EEG에서만.',['정답.','필수.','없음.','다르다.','심부전극.']),
Q('뇌파1 강의록','Spike와 sharp wave의 지속시간 기준으로 옳은 것은?',['Spike ≤70 ms, sharp wave 70–200 ms','Spike ≤200 ms, sharp wave >500 ms','Spike 200–500 ms','Sharp wave ≤20 ms','기준 없음'],1,'뇌파1 강의록: spike ≤70 ms, sharp wave 70–200 ms; 경계는 임의적이며 임상적으로 대개 중요하지 않음(같은 전기 현상). polyspike, spike-and-slow wave complex.',['정답.','틀리다.','틀리다.','틀리다.','있다(임의적).']),
Q('뇌파1 강의록','양성 변이(benign variant) 중 "psychomotor variant"로 불리며 중측두에서 4–7 Hz 음성 예파가 수초 동안 나타나는 것은?',['Rhythmic mid-temporal discharge(RMTD)','Wicket spikes','14 and 6 Hz positive bursts','SREDA','Small sharp spikes(BETS)'],1,'뇌파1 강의록 benign variants: 6 Hz spike-and-wave(phantom), 14 & 6 Hz positive bursts(후측두·두정, 청소년, 수면), RMTD(psychomotor variant, 중측두 4–7 Hz, 수초, 수면, 중년 여성), small sharp spikes/BETS(<50 ms, 수면, 성인), wicket spikes(전·중측두 아치형, 성인), SREDA(성인, 후측두·두정, 40–80초), mu rhythm 등.',['정답.','아치형.','양성 스파이크.','성인 장시간.','짧은 스파이크.']),
Q('뇌파1 강의록','Mu rhythm에 대한 설명으로 옳은 것은?',['각성 상태의 체감각피질 리듬으로 움직임·움직임 생각·반대측 촉각 자극에 감쇠된다','시각피질의 리듬으로 눈을 뜨면 감쇠된다','수면 중에만 나타난다','간질양 방전이다','소아에서만 보인다'],1,'뇌파1 강의록: 후두부 alpha와 비슷하나 시각 대신 체감각피질, 각성 시, 움직임·움직임 생각·반대측 사지 촉각에 감쇠.',['정답.','alpha.','각성.','양성 변이.','틀리다.']),
Q('뇌파1 강의록','양성 변이 중 성인에서 전·중측두에 아치 모양의 반복 스파이크로 나타나는 것은?',['Wicket spikes','RMTD','14 and 6 Hz positive bursts','Hypnagogic hypersynchrony','Midline theta'],1,'뇌파1 강의록: wicket spikes — 반복 스파이크가 아치 형성, 수초, 전·중측두, 주로 성인, 각성·수면.',['정답.','4–7 Hz 예파.','후측두 청소년.','소아 졸림.','정중선.']),
Q('뇌파1 강의록','삼상파(triphasic waves)의 원인이 아닌 것은?',['측두엽 뇌전증','간부전','요독증','Valproate 유발 고암모니아혈증 뇌병증','무산소 뇌손상'],1,'뇌파1 강의록 TW: 전방에서 먼저 후방으로 phase lag 25–140 ms; 원인 — 간부전, 요독증, valproate 고암모니아혈증 뇌병증, 심한 수분·전해질 불균형, 고칼슘혈증, 무산소증, 저혈당, 갑상선 기능 항진·저하, 저체온, CNS 억제제 중독.',['정답.','원인.','원인.','원인.','원인.']),
Q('뇌파1 강의록','삼상파의 전후 방향 위상차(phase lag)에 대한 설명으로 옳은 것은?',['전방에서 먼저 나타나고 후방으로 25–140 ms 늦게 나타난다','후방에서 먼저 나타난다','위상차가 없다','1초 이상 늦게 나타난다','측두부에서만 보인다'],1,'뇌파1 강의록: TWs appear first over anterior regions and later over posterior; fronto-occipital phase lag 25–140 ms.',['정답.','반대.','있다.','틀리다.','틀리다.']),
Q('뇌파1 강의록','소아 결신뇌전증(CAE)과 청소년 결신뇌전증(JAE)의 비교로 옳은 것은?',['CAE는 4–10세 발병, 결신이 매우 잦고 전신강직간대발작은 드물며 관해율이 높다','JAE는 결신이 CAE보다 더 잦다','CAE에서 전신강직간대발작이 흔하다','JAE의 관해율이 더 높다','CAE는 9–13세가 정점이다'],1,'뇌파1 강의록 비교표: CAE — 4–10세, 결신 매우 잦음(하루 여러 번), GTCS 드묾, 규칙적 3 Hz spike-wave, 관해 약 60%↑; JAE — 9–13세, 결신 덜 잦음, GTCS 흔함.',['정답.','반대.','드묾.','CAE.','JAE.']),
Q('뇌파2 강의록','AASM 기준 stage W 판정으로 옳은 것은?',['후두부 alpha 리듬이 epoch의 50% 초과','alpha가 epoch의 20% 이상','K complex가 있으면 W','서파가 20% 이상','턱근 EMG가 최저'],1,STG,['정답.','틀리다.','N2.','N3.','R.']),
Q('뇌파2 강의록','Alpha가 뚜렷하지 않은 epoch를 stage W로 판정할 수 있는 소견은?',['0.5–2 Hz 빈도의 눈깜빡임','K complex','Sleep spindle','서파가 epoch의 20% 이상','톱니파와 낮은 턱근 EMG'],1,STG,['정답.','N2.','N2.','N3.','R.']),
Q('뇌파2 강의록','Stage N1의 판정 기준으로 옳은 것은?',['Alpha가 감쇠되어 저진폭 혼합주파수(4–7 Hz)가 epoch의 50% 초과','Sleep spindle 출현','서파 20% 이상','REM과 낮은 EMG','Alpha 50% 초과'],1,STG,['정답.','N2.','N3.','R.','W.']),
Q('뇌파2 강의록','Stage N2 판정에 대한 설명으로 옳은 것은?',['각성과 무관한 K complex 또는 sleep spindle이 있으면 N2로 판정하며, 각성을 동반한 K complex만 있으면 N1을 유지한다','각성 동반 K complex만 있어도 N2','Vertex sharp wave가 있으면 N2','느린 안구운동이 필수','서파 20% 이상이 필요'],1,STG,['정답.','N1 유지.','N1.','없음.','N3.']),
Q('뇌파2 강의록','Stage N3의 판정 기준은?',['서파(SWA)가 30초 epoch의 20% 이상(6초 이상), 연령 무관','서파가 50% 이상','서파가 10% 이상','Spindle이 있으면 N3 불가','나이에 따라 기준이 다름'],1,STG,['정답.','과거 N4 개념.','틀리다.','있어도 됨.','무관.']),
Q('뇌파2 강의록','Stage R의 구성 요소로 옳은 것은?',['K complex·spindle 없는 저진폭 EEG, 빠른 안구운동, 낮은 턱근 EMG','높은 턱근 EMG','Sleep spindle 다수','서파 20% 이상','모든 R epoch에 REM이 반드시 있다'],1,STG,['정답.','낮다.','없음.','N3.','아님.']),
Q('뇌파2 강의록','Stage R에서 판정에 도움이 되지만 필수는 아닌 소견은?',['톱니파(saw-tooth waves)','낮은 EMG','저진폭 EEG','K complex의 부재','Spindle의 부재'],1,STG,['정답.','구성.','구성.','구성.','구성.']),
Q('뇌파2 강의록','턱근 EMG가 N3에서 보이는 특징으로 옳은 것은?',['진폭이 가변적이며 흔히 N2보다 낮고 때로 R만큼 낮다','항상 각성보다 높다','R보다 항상 높다','소실된다','일정하다'],1,STG,['정답.','틀리다.','때로 같음.','틀리다.','가변.']),
]
