def Q(src,stem,choices,ans,basis,exps,**k):
  d=dict(src=src,stem=stem,choices=choices,ans=ans,basis=basis,exps=exps); d.update(k); return d
ST='강의록 2–3·33쪽: 응급 두부외상 — non-contrast brain CT + bone window 먼저(급성 출혈·골절 평가, bone window와 brain/soft-tissue window 모두); X-ray는 골절 진단 가능하나 제한적; 추적 CT — 초기 미미한 출혈이 수시간 뒤 커질 수 있어 임상 악화·고위험 손상 시 중요; MRI — CT 정상/미미하나 신경학적 증상이 심할 때, DWI/FLAIR + T2*GRE/SWI. "밖에서 안으로" 읽기: scalp(subgaleal hematoma) → skull(골절) → extra-axial(EDH/SDH) → parenchyma(contusion/DAI); 한 병변만 찾고 끝내지 않기. 6-step: 1 Scalp 2 Skull(X-ray + bone window CT) 3 Extra-axial(EDH/SDH/SAH: 위치·모양·midline·suture line) 4 Parenchymal(contusion/DAI) 5 Effect(mass effect, midline shift, herniation) 6 Remarks(필요 시 F/U CT·MRI).'
SK='강의록 5–12쪽: subgaleal hematoma — 모상건막과 골막 사이 성긴결합조직에 피가 고이기 쉬움, 그 부위에 골절 동반 가능성 높음. 골절 형태 — linear(선상, 가장 흔함), diastatic(이개, suture widening), depressed(함몰, bone inward, 실질 손상 동반 가능성 증가), growing(성장, 소아), ping-pong(영유아 함몰, 매끈한 inward indentation, 골절선 없을 수 있음). Linear fracture — straight, more translucent, sharp margin / vascular groove — branching, less translucent, ill-defined, 해부학적 위치 / suture — serrated edge, corticated margin; 위치+분지+피질화로 판단. Diastatic — 정상 suture가 >2 mm 벌어짐, 소아 발달단계 알아야 과진단 방지. Growing fracture — 유합되지 않고 넓어짐, 주로 3세 미만, 초기+추적 영상. 골절 확정은 CT bone window.'
EX='강의록 14–20쪽: EDH — 주로 meningeal artery 손상, biconvex(lens), suture line 넘지 않음, falx 밖에서는 midline 넘을 수 있음. SDH — 주로 bridging cortical vein, crescent, suture 넘음, falx/tentorium 등 dural reflection 넘지 못함(midline 못 넘음), falx/tentorium 출혈은 SDH. Chronic SDH — 서서히 증가, iso/hypo/mixed density(fluid-fluid level), sulci 소실·GW junction 비대칭, mass effect 단서, 양측성 가능. Subdural hygroma — 외상성 거미막 파열로 CSF가 경막하 공간으로 누출, CSF와 같은 density/signal. Traumatic SAH — sulci·cistern 어디든, 다른 외상 병변 동반 흔함; 외상력 없이 basal cistern 중심 SAH → aneurysmal rupture 우선.'
PA='강의록 22–32쪽: Contusion — 뇌가 뼈에 부딪힌 자리, 두개골 돌출부 인접(anterobasal frontal, anterior temporal), 출혈+부종 혼합음영. DAI — 회전·가감속 shearing, CT 다발성 작은 고음영 출혈, CT 정상이어도 배제 불가, 심한 TBI인데 CT 경미하면 고려; 호발 — GW junction, corpus callosum, brainstem, basal ganglia/fornix; MRI가 훨씬 민감, hemorrhagic DAI는 T2*GRE/SWI 저신호. Coup = 충격 측, contrecoup = 반대측; scalp hematoma·skull fracture는 impact side 단서; coup — scalp hematoma, skull fracture, EDH; contrecoup — SDH. Delayed progression — 직후 안 보이거나 작던 출혈이 수시간 뒤 뚜렷 → 임상 악화/고위험 시 추적 검사.'
OFF=[
Q('강의록','응급 두부외상 환자에서 가장 먼저 시행할 영상검사로 강의록이 제시한 것은?',['비조영 뇌 CT(bone window 포함)','조영증강 MRI','두개골 단순촬영만','뇌혈관조영술','SPECT'],1,ST,['정답.','문제 해결 도구.','제한적.','틀리다.','틀리다.']),
Q('강의록','외상성 뇌손상에서 MRI를 고려해야 하는 상황은?',['CT는 정상이거나 미미하지만 신경학적 증상이 심할 때','모든 경증 두부외상','CT에서 큰 EDH가 확인되어 응급수술이 필요할 때','두피 열상만 있을 때','골절 확인이 필요할 때'],1,ST,['정답.','틀리다.','지연 불가.','틀리다.','CT bone window.']),
Q('강의록','강의록의 두부외상 CT 판독 순서("밖에서 안으로")로 옳은 것은?',['Scalp → Skull → Extra-axial → Parenchyma','Parenchyma → Extra-axial → Skull → Scalp','Skull → Parenchyma → Scalp → Extra-axial','Extra-axial → Scalp → Parenchyma → Skull','Parenchyma만 판독'],1,ST,['정답.','반대.','틀리다.','틀리다.','틀리다.']),
Q('강의록','외상 CT 6-step algorithm의 5단계 "Effect"에서 확인하는 것은?',['Mass effect, midline shift, herniation','두피 혈종','골절 형태','Contusion 위치','추적 검사 필요성'],1,ST,['정답.','1단계.','2단계.','4단계.','6단계.']),
Q('강의록','모상건막하(subgaleal) 혈종이 잘 생기는 해부학적 이유와 임상적 의미로 옳은 것은?',['모상건막과 골막 사이 성긴결합조직이 느슨하며, 그 부위에 골절이 동반될 가능성이 높다','경막과 두개골 사이이며 동맥 손상이 원인','거미막하 공간이며 동맥류 파열 시사','항상 contrecoup 측에 생긴다','골절과 무관하다'],1,SK+' '+PA,['정답.','EDH.','SAH.','coup 측 단서.','틀리다.']),
Q('강의록','두개골 골절 중 가장 흔한 형태는?',['선상골절(linear)','이개골절(diastatic)','함몰골절(depressed)','성장골절(growing)','Ping-pong 골절'],1,SK,['정답.','틀리다.','틀리다.','소아.','영유아.']),
Q('강의록','CT에서 두개골의 선이 곧고, 더 투명하며, 경계가 날카롭다. 가장 가능성 높은 것은?',['선상골절','혈관 홈(vascular groove)','봉합선(suture)','Ping-pong 골절','정상 변이'],1,SK,['정답.','branching, less translucent, ill-defined.','serrated, corticated.','함몰.','틀리다.']),
Q('강의록','톱니 모양(serrated) 가장자리와 피질화된(corticated) 경계를 보이는 선은?',['봉합선(suture)','선상골절','혈관 홈','이개골절','성장골절'],1,SK,['정답.','sharp margin.','branching.','벌어짐.','넓어짐.']),
Q('강의록','이개골절(diastatic fracture)의 기준으로 강의록에 제시된 것은?',['정상 봉합선이 2 mm를 초과하여 벌어짐','골편이 안쪽으로 1 cm 함몰','골절선이 분지함','골절이 시간이 지나며 넓어짐','골절선 없이 함몰'],1,SK,['정답.','depressed.','vascular groove.','growing.','ping-pong.']),
Q('강의록','골편이 안쪽으로 함몰된 골절에서 특히 주의할 점은?',['뇌실질 손상 동반 가능성이 증가한다','항상 골절선이 없다','소아에서만 발생한다','X-ray로 충분하다','봉합선만 벌어진다'],1,SK,['정답.','ping-pong.','틀리다.','CT bone window.','diastatic.']),
Q('강의록','생후 4개월 영아가 침대에서 떨어진 후 두개골이 매끈하게 안쪽으로 눌렸으나 골절선은 뚜렷하지 않다. 이 골절 형태는?',['Ping-pong 골절','선상골절','이개골절','성장골절','혈관 홈'],1,SK,['정답. 탄력 있는 영유아 두개골.','골절선.','봉합선.','시간 경과.','정상.']),
Q('강의록','성장골절(growing fracture)에 대한 설명으로 옳은 것은?',['주로 3세 미만에서 유합되지 않고 점차 넓어지며, 초기와 추적 영상의 연결이 중요','성인에서 흔함','골절선이 곧 사라짐','X-ray 한 번으로 진단 종결','골편이 안쪽으로 함몰'],1,SK,['정답.','소아.','넓어짐.','추적.','depressed.']),
Q('강의록','경막외혈종(EDH)의 영상 특징으로 옳지 않은 것은?',['봉합선(suture line)을 넘어간다','양측 볼록한(lens) 형태','주로 수막동맥 손상','falx 밖에서는 정중선을 넘을 수 있다','경막과 두개골 사이'],1,EX,['정답. 넘지 않음.','옳다.','옳다.','옳다.','옳다.']),
Q('강의록','경막하혈종(SDH)의 영상 특징으로 옳은 것은?',['초승달 모양, 봉합선은 넘지만 falx·tentorium은 넘지 못함','Lens 모양, 봉합선에서 멈춤','주로 수막동맥 손상','정중선을 자유롭게 넘음','CSF와 같은 음영'],1,EX,['정답.','EDH.','EDH.','EDH(falx 밖).','hygroma.']),
Q('강의록','falx 또는 tentorium을 따라 보이는 외상성 출혈은?',['경막하출혈(SDH)','경막외출혈(EDH)','모상건막하 혈종','뇌좌상','DAI'],1,EX,['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록','만성 경막하혈종의 CT 소견으로 강의록에 제시되지 않은 것은?',['항상 균일한 고음영','등음영','저음영','fluid-fluid level을 보이는 혼합음영','뇌고랑 소실과 회백질 경계 비대칭'],1,EX,['정답.','가능.','가능.','가능.','단서.']),
Q('강의록','외상 후 경막하 공간에 CSF와 같은 음영·신호의 액체가 보인다. 기전은?',['외상성 거미막 파열로 CSF가 경막하 공간으로 누출(subdural hygroma)','교정맥 파열에 의한 급성 출혈','수막동맥 파열','동맥류 파열','뇌좌상 부종'],1,EX,['정답.','SDH.','EDH.','SAH.','실질.']),
Q('강의록','외상력 없이 기저조(basal cistern) 중심의 거미막하출혈이 보일 때 우선 고려할 원인은?',['동맥류 파열','외상성 SAH','DAI','뇌좌상','EDH'],1,EX,['정답.','외상력 없음.','틀리다.','틀리다.','틀리다.']),
Q('강의록','뇌좌상(cerebral contusion)의 호발 부위는?',['전두엽 앞바닥과 측두엽 앞부분','후두엽 내측','소뇌 충부','뇌량 팽대','연수'],1,PA,['정답. 두개골 돌출부 인접.','틀리다.','틀리다.','DAI.','틀리다.']),
Q('강의록','미만성 축삭손상(DAI)의 기전으로 옳은 것은?',['회전·가속/감속에 의한 shearing injury','직접 타격 부위 골절','교정맥 파열','수막동맥 파열','거미막 파열'],1,PA,['정답.','coup.','SDH.','EDH.','hygroma.']),
Q('강의록','DAI의 호발 부위가 아닌 것은?',['후두엽 피질 표면','회백질-백질 경계','뇌량','뇌간','기저핵/뇌궁'],1,PA,['정답.','호발.','호발.','호발.','호발.']),
Q('강의록','24세 남자가 교통사고 후 의식이 없는데 CT는 거의 정상이다. 다음 검사로 가장 적절한 것과 예상 소견은?',['MRI SWI/T2*GRE — 다발성 점상 저신호','조영증강 CT — 고리 조영증강','뇌혈관조영 — 동맥류','CT bone window — 이개골절','EEG — 3 Hz 극서파'],1,PA,['정답. hemorrhagic DAI.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록','우측 두피 혈종과 우측 두개골 골절이 있는 환자에서 좌측에 경막하혈종이 보였다. 해석으로 옳은 것은?',['충격 측은 우측(coup), 좌측 SDH는 contrecoup 손상','좌측이 충격 측','SDH는 항상 coup 측','두피 혈종은 contrecoup 측 단서','두 병변은 무관'],1,PA,['정답.','틀리다.','contrecoup에 흔함.','impact side 단서.','틀리다.']),
Q('강의록','외상 직후 CT에서 작던 출혈이 3시간 뒤 CT에서 커졌다. 강의록이 강조한 개념과 대응은?',['Delayed progression — 임상 악화나 고위험 소견이 있으면 추적 CT','영상 오류 — 재검 불필요','항상 수술 적응증','MRI만 신뢰','추적 검사는 소아에서만'],1,ST+' '+PA,['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록','강의록의 증례처럼 한 환자에게서 골절, EDH, SDH, SAH, DAI, 좌상이 함께 보일 수 있다. 판독 원칙으로 옳은 것은?',['한 병변만 찾고 끝내지 않고 순서대로 모든 손상을 찾는다','가장 큰 병변만 보고한다','실질 손상은 MRI로만 본다','두피는 생략한다','EDH가 있으면 SDH는 없다'],1,ST+' '+PA,['정답.','틀리다.','CT에서도.','1단계.','공존 가능.']),
]
