def Q(src,stem,choices,ans,basis,exps,**k):
  d=dict(src=src,stem=stem,choices=choices,ans=ans,basis=basis,exps=exps); d.update(k); return d
TOAST='강의록 TOAST: SAO — 병변 <1.5 cm, 피질 증상 없음, HT·DM, 심장색전원 없음, 협착 <50%; CE — 다발성 병변, 전신 색전, 고위험·저위험 색전원; LAA — 피질·뇌간·소뇌 증상, 협착 >50%, 경계부 경색, 동맥-동맥 색전; other — 비죽상 혈관병증·과응고; undetermined — 두 가지 이상 원인·음성·불완전 평가.'
AR='강의록 자동조절: MAP 70–150 mmHg 범위에서 CVR 변화로 CBF 유지(CPP↓ → 세동맥 확장·CVR↓, CPP↑ → 수축·CVR↑). 허혈·종괴·대발작 후·외상·저산소·고탄산에서 손상. 전신 혈관확장제(nitroprusside, NTG, hydralazine, adenosine, CCB)는 하한을 낮춤(좌측 이동); TBI·만성 고혈압은 우측 이동 → 더 높은 MAP 필요.'
PEN='강의록 허혈반음영: 경색으로 진행할 수 있으나 아직 비가역 손상이 아닌 조직, CBF는 제한되나 에너지 대사는 보존("damaged but not yet dead"), 치료 표적. 1–2°C 고체온·고혈당은 세포사를 가속.'
ED='강의록 뇌부종: 초기 세포독성 부종 — CBF 대조군의 30%에서 무산소 대사로 삼투압↑·세포 팽창, 20% 미만에서 anoxic depolarization; 혈류 없으면 ECF→ICF 이동(순 수분량 불변), ADC 감소·DWI 고신호. 후기 혈관성 부종 — BBB 붕괴·혈청 단백 누출, 1–2일째 최고, 천막 탈출(악성 경색), 등삼투성·주로 ECF, DWI pseudonormalization·T2 고신호.'
OFF=[
Q('강의록','WHO(1976) 뇌졸중 정의로 옳은 것은?',['혈관 원인 외 다른 원인 없이 24시간 이상 지속되거나 사망에 이르는 국소 또는 전반 뇌기능 장애가 빠르게 발생','24시간 미만 지속되는 국소 결손','영상에서 우연히 발견된 무증상 경색 포함','망막경색만을 의미','외상성 뇌출혈 포함'],1,'강의록: WHO 1976 — rapidly developing focal/global disturbance, ≥24 h or death, vascular origin. 최근 tissue-based 정의(DWI). TIA — 24시간 미만, 특정 동맥 영역(뇌·눈), amaurosis fugax 포함. ICD-11 stroke에 무증상 경색·후유증은 포함 안 됨.',['정답.','TIA.','포함 안 됨.','틀리다.','틀리다.']),
Q('강의록','뇌졸중의 병리 기전으로 강의록에 제시되지 않은 것은?',['수초 탈락','색전 또는 혈전에 의한 폐색','혈관 파열','혈관벽 투과성 변화','혈액 점도 증가 또는 혈류 성질 변화'],1,'강의록 What is stroke: 1 occlusion(embolus/thrombus), 2 rupture, 3 altered permeability, 4 increased viscosity·change in blood flow.',['정답.','기전.','기전.','기전.','기전.']),
Q('강의록','뇌경색과 뇌허혈의 구분으로 옳은 것은?',['뇌경색은 비가역적 괴사 영역, 뇌허혈은 병적으로 혈류가 감소한 영역','두 용어는 완전히 같다','뇌허혈은 항상 비가역적이다','뇌경색은 혈류가 정상인 영역이다','뇌허혈은 출혈을 뜻한다'],1,'강의록: 뇌경색 — 비가역 괴사; 뇌허혈 — 혈류 감소 영역(경색 + 가능한 허혈반음영).',['정답.','다르다.','가역 가능.','틀리다.','틀리다.']),
Q('강의록','2019년 기준 뇌졸중 아형 비율로 강의록에 제시된 것은?',['허혈 62.4%, 뇌내출혈 27.9%, SAH 9.7%','허혈 90%, 출혈 10%','허혈 50%, 뇌내출혈 40%, SAH 10%','허혈 27.9%, 뇌내출혈 62.4%','SAH가 가장 흔함'],1,'강의록: ischemic 62.4%, ICH 27.9%, SAH 9.7% (2019).',['정답.','틀리다.','틀리다.','반대.','틀리다.']),
Q('강의록','저혈압으로 CPP·CBF가 떨어질 때 동맥 영역의 끝에 생기는 경색은?',['경계부(watershed, border zone) 경색','열공경색','심장색전성 경색','정맥성 경색','출혈성 경색'],1,'강의록: hemodynamic crisis(hypotensive stroke) — BP↓ → CPP↓ → CBF↓, 동맥 영역 끝에서 watershed 경색. 색전 — 좌심·동맥-동맥, 출혈성 변환 흔함; 혈전 — 죽상경화(가장 흔함), FMD, 동맥염, 박리 등.',['정답.','소혈관.','색전.','CVT.','변환.']),
Q('강의록','색전성 뇌경색의 특징으로 강의록에 제시된 것은?',['출혈성으로 변하기 쉽다','죽상경화가 가장 흔한 원인이다','항상 열공경색이다','경계부 경색만 만든다','정맥 혈전이 주원인이다'],1,'강의록: embolism — 좌심방/심실, 동맥-동맥(ICA plaque 혈전 이탈), become hemorrhagic.',['정답.','혈전.','틀리다.','혈역학.','틀리다.']),
Q('강의록','TOAST 분류에서 소동맥폐색(SAO)의 기준이 아닌 것은?',['피질 증상이 있다','병변 <1.5 cm','고혈압·당뇨','심장색전원이 없다','협착 <50%'],1,TOAST,['정답. 피질 증상 없음.','기준.','기준.','기준.','기준.']),
Q('강의록','TOAST 분류에서 원인미결정(undetermined)에 해당하지 않는 것은?',['협착 >50%와 피질 증상','두 가지 이상 원인 확인','검사 음성','불완전한 평가','—'],1,TOAST,['정답. LAA.','해당.','해당.','해당.','—'],fixed=True),
Q('강의록','내경동맥(ICA)에서 직접 나오는 분지는?',['전맥락동맥','전교통동맥','하후소뇌동맥','시상무릎동맥','후맥락동맥'],1,'강의록 퀴즈: ICA 분지 — ophthalmic a., P-com, anterior choroidal a.(중뇌·시상·외측무릎체·내측측두엽·시각로·속섬유막 뒷다리·창백핵·맥락얼기) → MCA·ACA.',['정답.','ACA 사이.','척추동맥.','PCA.','PCA.']),
Q('강의록','MCA M1에서 나와 기저핵·속섬유막을 공급하는 동맥은?',['Lenticulostriate a.','Recurrent a. of Heubner','Thalamogeniculate a.','Labyrinthine a.','Anterior spinal a.'],1,'강의록: MCA M1(수평분절) — lenticulostriate a.(기저핵·속섬유막); M2 상분지 — 운동피질·Broca, 하분지 — 몸감각·각이랑·Wernicke; M4 대뇌 외측 대부분.',['정답.','ACA A1.','PCA P2.','AICA.','척추동맥.']),
Q('강의록','MCA 하분지(inferior division) 공급 영역에 해당하는 것은?',['Wernicke 영역과 각이랑','Broca 영역','운동피질','꼬리핵 머리','시각피질'],1,'강의록: 상분지 — 운동피질 포함 전두부, Broca; 하분지 — 몸감각피질, angular gyrus, 두정부, 외측 상측두, Wernicke.',['정답.','상분지.','상분지.','Heubner.','PCA.']),
Q('강의록','ACA의 recurrent artery of Heubner가 공급하는 구조가 아닌 것은?',['시각피질','꼬리핵 머리','속섬유막 앞다리','창백핵 앞쪽','시상하부 앞쪽'],1,'강의록 ACA: A1 — 관통동맥, recurrent a. of Heubner(꼬리핵 머리, 속섬유막 앞다리, 창백핵 앞쪽, 시상하부 앞쪽); A2; A3–A5 뇌량·띠다발고랑.',['정답. PCA calcarine.','공급.','공급.','공급.','공급.']),
Q('강의록','AICA에서 나와 전정달팽이신경·얼굴신경·속귀를 공급하는 동맥은?',['Labyrinthine a.','PICA','SCA','Anterior spinal a.','Calcarine a.'],1,'강의록 기저동맥: AICA — 소뇌 앞·아랫부분, 타래, 중간소뇌다리, 숨뇌 위·다리뇌 일부; labyrinthine a.; perforating(median·paramedian, circumferential); SCA — 소뇌 윗면·뇌줄기 일부. 척추동맥: PICA — 소뇌 후하부, 숨뇌 배가측; anterior spinal a.',['정답.','숨뇌.','소뇌 위.','척수.','시각피질.']),
Q('강의록','PCA 분지와 공급 영역의 연결로 옳은 것은?',['Calcarine a. – 시각피질','Thalamogeniculate a. – 꼬리핵','Lateral occipital a. – 운동피질','Parietooccipital a. – 소뇌','Posterior choroidal a. – 척수'],1,'강의록 PCA: P1 thalamoperforating; P2 thalamogeniculate, posterior choroidal; P4 medial occipital(두정·후두엽), parietooccipital(두정후두고랑), calcarine(시각피질), lateral occipital(측두엽 아랫면).',['정답.','시상.','측두엽 아랫면.','두정후두고랑.','틀리다.']),
Q('강의록','뇌관류압 감소 시 대뇌 표면에서 전·중·후대뇌동맥을 연결하는 곁순환은?',['연수막 곁순환(leptomeningeal)','윌리스고리','경막경유 곁순환','Persistent trigeminal artery','정맥동'],1,'강의록 곁순환: a 윌리스고리(ACom·ACA·ICA·PCom·PCA·BA), b 경막경유(눈동맥·외경동맥 분지의 두개외-두개내), c 연수막(대뇌 표면 ACA-MCA-PCA). 발생학적 잔류 — persistent trigeminal, otic, hypoglossal, proatlantal.',['정답.','뇌바닥.','두개외.','발생 잔류.','틀리다.']),
Q('강의록','발생학적 잔류 경동맥-척추기저동맥 연결이 아닌 것은?',['Persistent ophthalmic artery','Persistent trigeminal artery','Persistent otic artery','Persistent hypoglossal artery','Persistent proatlantal intersegmental artery'],1,'강의록: 발생학적 잔류 곁순환 — trigeminal, otic, hypoglossal, proatlantal intersegmental.',['정답.','잔류.','잔류.','잔류.','잔류.']),
Q('강의록','Fisher의 5가지 고전적 열공 증후군이 아닌 것은?',['실어증을 동반한 편마비','순수 운동 편마비','순수 감각 뇌졸중','실조성 편마비','구음장애-서툰손 증후군'],1,'강의록: classic lacunar syndromes — pure motor hemiparesis, pure sensory stroke, sensorimotor stroke, ataxic hemiparesis, dysarthria-clumsy hand. 실어증은 피질 증상.',['정답.','열공.','열공.','열공.','열공.']),
Q('강의록','소혈관질환의 병리 소견과 혈관 크기 연결로 옳지 않은 것은?',['Lipohyalinosis – 1000–2000 μm','Small vessel atherosclerosis – 200–800 μm','Microaneurysm – 100–300 μm','Arteriolosclerosis – 40–150 μm','Lipohyalinosis – fibrinoid necrosis'],1,'강의록: small vessel atherosclerosis 200–800 μm, lipohyalinosis(fibrinoid necrosis) 40–300 μm, microaneurysm 100–300 μm, arteriolosclerosis 40–150 μm.',['틀리다(정답). 40–300 μm.','맞다.','맞다.','맞다.','맞다.']),
Q('강의록','피질하 허혈 혈관치매(SIVD)의 임상 특징이 아닌 것은?',['초기부터 뚜렷한 실어증과 실행증','건망','정신운동 느려짐','기분 장애','종종걸음과 배뇨 증상'],1,'강의록: SIVD — forgetfulness, psychomotor slowing, mood disturbances, dysarthria, short stepped gait, urinary symptoms. 위험인자 — 나이·HT·DM·흡연·호모시스테인↑·피브리노겐↑, OSA·CHF·부정맥·기립성 저혈압.',['정답.','특징.','특징.','특징.','특징.']),
Q('강의록','정상 뇌혈류(CBF)와 대사에 대한 설명으로 옳은 것은?',['평균 CBF 약 55 mL/100 g/min이며 회백질이 백질보다 약 4배 높다.','백질 CBF가 회백질보다 높다.','뇌는 전신 기초 산소 소비의 약 2%를 차지한다.','뇌는 에너지 기질을 충분히 저장한다.','CMRO2는 약 35 mL/100 g/min이다.'],1,'강의록: CBF 55 mL/100 g/min, CMRO2 3.5 mL/100 g/min, CMRglc 25 μmol/100 g/min; 회백질 80·백질 20; 전신 기초 산소 소비의 20–25%; 기질 저장이 거의 없어 지속 공급에 의존.',['정답.','반대.','20–25%.','거의 없음.','3.5.']),
Q('강의록','CBF를 결정하는 관계식으로 옳은 것은?',['CBF = CPP / CVR','CBF = CVR / CPP','CBF = MAP × ICP','CBF = CPP × CVR','CBF = ICP / MAP'],1,'강의록: CPP = MAP − ICP(정맥 역압은 ICP 상승·정맥 폐쇄가 없으면 무시), CBF = CPP/CVR; CVR은 점도·혈관 길이·반지름으로 결정.',['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록','뇌혈관 자동조절에 대한 설명으로 옳은 것은?',['MAP 약 70–150 mmHg 범위에서 CBF를 일정하게 유지한다.','CPP가 떨어지면 세동맥이 수축한다.','만성 고혈압은 자동조절 곡선을 왼쪽으로 이동시킨다.','외상성 뇌손상에서는 더 낮은 MAP로도 충분하다.','혈관확장제는 자동조절 하한을 높인다.'],1,AR,['정답.','확장.','오른쪽.','더 높은 MAP.','낮춘다.']),
Q('강의록','만성 고혈압 환자의 뇌혈류 자동조절에 대한 설명으로 옳은 것은?',['자동조절 상·하한이 모두 높아져 MAP 70 mmHg에서도 허혈 위험이 있다.','자동조절 범위가 넓어진다.','하한만 낮아진다.','변화가 없다.','상한만 낮아진다.'],1,AR+' (강의록: A hypertensive patient may be at risk for brain ischemia at a MAP of 70 mmHg.)',['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록','PaCO2와 CBF의 관계로 옳은 것은?',['PaCO2와 CBF는 선형 관계로, 과호흡으로 PaCO2 약 25 mmHg가 되면 CBF가 30–35% 감소한다.','PaCO2가 올라가면 혈관이 수축해 CBF가 감소한다.','PaCO2는 CBF에 영향이 없다.','PaO2가 100 mmHg 이하로만 떨어져도 CBF가 크게 증가한다.','PaCO2 50 mmHg 이상에서 CBF가 절반으로 준다.'],1,'강의록: PaCO2–CBF 선형; PaCO2 25 mmHg → CBF 30–35%↓, >50 mmHg → 약 75%↑; PaO2는 30–50 mmHg 미만일 때만 CBF 증가. PCO2↑ → 혈관확장·CVR↓·CBF↑.',['정답.','확장·증가.','영향 큼.','30–50 미만.','증가.']),
Q('강의록','동맥혈 산소함량(CaO2) 변화와 CBF의 관계로 옳은 것은?',['빈혈·저산소혈증은 CaO2를 낮춰 혈관확장으로 CBF를 증가시킨다.','적혈구증가증은 CBF를 증가시킨다.','빈혈은 뇌 대사를 크게 증가시킨다.','혈당 변화가 CBF의 주 결정인자다.','점도는 CBF의 독립 결정인자다.'],1,'강의록: hypoxemia·anemia → CaO2↓ → vasodilation → CBF↑; polycythemia → CaO2↑ → vasoconstriction → CBF↓; 대사는 불변. 혈당 수급은 CBF에 영향 적음; 점도는 독립 결정인자일 가능성 낮음. 기능 활성 시 국소 CBF·CMRglc 증가.',['정답.','감소.','불변.','영향 적음.','낮음.']),
Q('강의록','뇌관류압 감소에 따른 허혈 단계로 옳은 것은?',['1단계 혈관확장으로 CBV↑·CBF 유지 → 2단계 CBF↓·OEF↑·CMR 유지 → 3단계 CMR↓(에너지 부전)','1단계부터 CMR이 감소한다','2단계에서 OEF가 감소한다','3단계에서 CBV가 정상화된다','혈관확장은 일어나지 않는다'],1,'강의록 Stage I: CPP↓ → vasodilation(CVR↓) → CBV↑, CBF 유지; Stage II: CPP↓↓ → CBF↓ → OEF↑, CMR 유지; Stage III: CPP↓↓↓ → CMR↓(energy failure).',['정답.','3단계.','증가.','틀리다.','일어난다.']),
Q('강의록','허혈반음영(ischemic penumbra)에 대한 설명으로 옳은 것은?',['CBF는 제한되나 에너지 대사가 보존되어 혈류 회복 시 기능을 회복할 수 있는 영역','이미 비가역적 괴사가 끝난 중심부','혈액뇌장벽 자체','세포자멸사가 완료된 영역','혈류가 정상인 영역'],1,PEN,['정답.','infarct core.','틀리다.','틀리다.','틀리다.']),
Q('강의록','허혈반음영의 세포사를 가속하는 요인으로 강의록에 제시된 것은?',['1–2°C 고체온과 고혈당','저체온','정상혈당','산소 투여','혈압 유지'],1,PEN,['정답.','보호적.','틀리다.','틀리다.','틀리다.']),
Q('강의록','허혈 후 세포사 기전에 대한 설명으로 옳은 것은?',['세포자멸사는 약 2시간에 걸쳐, 응고괴사는 6–12시간에 걸쳐 진행한다.','응고괴사가 세포자멸사보다 빠르다.','세포자멸사는 DNA 절단과 무관하다.','염증은 반음영에서 억제된다.','MMP-9 억제는 경색을 키운다.'],1,'강의록: 미세혈전·PMN·혈소판 상호작용; apoptosis — 약 2시간, DNA cleavage suicide protein; coagulation necrosis — 6–12시간, 막 손상; 염증 — IL-1β·IL-6·IL-10 증가, NF-κB·COX-2 반음영 상향, MMP-9 억제로 경색 감소.',['정답.','반대.','관련.','상향.','감소.']),
Q('강의록','허혈 손상 진행의 분자 기전이 아닌 것은?',['GABA 매개 과분극의 증가','Glutamate 흥분독성','칼슘 독성','자유라디칼(ROS)','미토콘드리아 장애'],1,'강의록: excitotoxicity, calcium toxicity, free radicals(peroxynitrite), NO toxicity(내피는 확장·보호, 신경세포는 독성), zinc toxicity, ER 기능장애·단백합성 억제, mitochondrial disturbance.',['정답.','기전.','기전.','기전.','기전.']),
Q('강의록','허혈성 뇌부종의 시기별 특징으로 옳은 것은?',['초기 세포독성 부종은 DWI 고신호·ADC 감소, 후기 혈관성 부종은 BBB 붕괴로 1–2일째 최고','혈관성 부종이 먼저 수분 내 생긴다','세포독성 부종은 ADC를 증가시킨다','혈관성 부종은 세포 내에만 축적된다','혈관성 부종은 T2에서 저신호다'],1,ED,['정답.','후기.','감소.','ECF.','고신호.']),
Q('강의록','허혈 조직에 혈류가 갑자기 회복될 때 생길 수 있는 합병증은?',['출혈(red infarct)과 혈관성 부종','즉각적인 완전 회복만','세포독성 부종의 소실만','수초 재생','저혈당'],1,'강의록: 동맥 폐색은 모세혈관·세동맥·혈관벽도 허혈 손상 → 갑작스러운 재관류 시 취약 혈관 파열로 출혈(red infarct), 대량 경색·재관류 후 혈관성 부종.',['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록','만성 고혈압·동맥경화에서 뇌혈관 내피 기능 변화로 옳은 것은?',['NO 생성·활성 감소와 내피의존 이완 장애, EDCF 분비','NO 증가로 과도한 확장','내피 기능은 정상','혈소판 활성화가 혈관을 확장','호모시스테인은 NO 반응을 증가'],1,'강의록: 동맥경화·고콜레스테롤 — 내피 기능장애, NO 방출·활성 저하, NADPH oxidase; 만성 고혈압 — 내피의존 이완 장애, EDCF, KATP 활성 감소; 활성 혈소판 — ADP·세로토닌·TXA2로 수축; 고호모시스테인 — NO 반응 억제; 당뇨 — 내피 기능장애. NO → cGMP↑ → 확장.',['정답.','감소.','장애.','수축.','억제.']),
]
OFF=[q for i,q in enumerate(OFF) if i not in {7,15}]
