def Q(src,stem,choices,ans,basis,exps,**k):
  d=dict(src=src,stem=stem,choices=choices,ans=ans,basis=basis,exps=exps); d.update(k); return d
OFF=[
Q('강의록 2쪽','Eloquent area와 그 기능의 연결로 옳지 않은 것은?',
 ['Precentral gyrus – movement control','Dominant inferior frontal gyrus – speech production','Dominant superior temporal gyrus – language comprehension','Postcentral gyrus – hearing','Brainstem – respiration, consciousness, cranial nerves'],4,
 '강의록 2쪽 eloquent area: motor cortex(precentral) → 운동, sensory cortex(postcentral) → 감각, Broca(우세 inferior frontal) → 말 산출, Wernicke(우세 superior temporal) → 언어 이해, 1차 시각피질(occipital) → 시각, auditory cortex(superior temporal) → 청각, brainstem → 호흡·의식·뇌신경, cerebellum → 협조·균형.',
 ['맞다. 1차 운동피질.','맞다. Broca 영역.','맞다. Wernicke 영역.','틀리다(정답). Postcentral gyrus는 체성감각이고 청각은 superior temporal gyrus(Heschl 이랑).','맞다.']),
Q('강의록 5–7쪽','Brodmann area와 해당 영역의 연결로 옳은 것은?',
 ['Area 4 – primary somatosensory cortex','Area 6 – premotor cortex and supplementary motor area','Areas 3, 1, 2 – primary motor cortex','Area 43 – primary auditory cortex','Areas 41, 42 – primary gustatory cortex'],2,
 'Area 4 1차 운동피질, area 6 전운동·보조운동영역, areas 3·1·2 1차 체성감각, area 5 체성감각 연합, areas 41·42 청각피질(Heschl), area 43 1차 미각피질.',
 ['틀리다. Area 4는 1차 운동피질.','맞다(정답).','틀리다. 3·1·2는 1차 체성감각피질.','틀리다. Area 43은 1차 미각피질.','틀리다. 41·42는 청각피질.']),
Q('강의록 6·26쪽','Broca 영역을 이루는 Brodmann area 조합으로 옳은 것은?',['4, 6','22, 39','44, 45','41, 42','17, 18'],3,
 'Area 44 pars opercularis, area 45 pars triangularis — inferior frontal gyrus의 일부로 Broca 영역. Area 47은 pars orbitalis.',
 ['운동·전운동피질.','Wernicke 영역(22)과 각회(39).','정답. Pars opercularis(44), pars triangularis(45).','청각피질.','1·2차 시각피질.']),
Q('강의록 7·32쪽','Wernicke 영역에 대한 설명으로 옳은 것은?',
 ['전통적으로 Brodmann area 44에 있다고 본다.','Inferior frontal gyrus에 위치한다.','전통적으로 Brodmann area 22의 뒤쪽(caudal) 부분에 있다고 본다.','오른손잡이의 약 50%에서 좌반구가 우세반구이다.','손상되면 운동실어증이 생긴다.'],3,
 '강의록 32쪽: Wernicke 영역은 전통적으로 BA 22(우세반구 superior temporal gyrus, 주로 caudal part)에 있다. 좌반구가 우세반구인 비율은 오른손잡이 약 95%, 왼손잡이 약 70%.',
 ['BA 44는 Broca 영역.','Inferior frontal gyrus는 Broca 영역.','정답.','오른손잡이의 약 95%에서 좌반구가 우세.','운동실어증은 Broca 영역 손상. Wernicke 손상은 감각(수용성) 실어증.']),
Q('강의록 32쪽','왼손잡이에서 좌반구가 언어 우세반구인 비율로 강의록에 제시된 값에 가장 가까운 것은?',['약 10%','약 30%','약 50%','약 70%','약 95%'],4,
 '좌반구 우세: 오른손잡이 약 95%, 왼손잡이 약 70%.',['너무 낮다.','너무 낮다.','틀리다.','정답.','오른손잡이의 비율이다.']),
Q('강의록 7·16쪽','1차 청각피질에 대한 설명으로 옳은 것은?',
 ['Brodmann area 43이다.','Heschl의 가로이랑(transverse gyrus)에 있다.','Inferior temporal gyrus에 있다.','손상되면 반대측 동측반맹이 생긴다.','자극하면 복잡한 음악 소리를 듣게 된다.'],2,
 '1차 청각피질 BA 41·42 = Heschl’s transverse convolutions(superior temporal gyrus, Sylvian fissure 안쪽). 손상 → 소리 방향 지각 저하, 자극 → 낮거나 높은 단순한 소리.',
 ['BA 43은 미각피질.','정답.','Superior temporal gyrus이다.','동측반맹은 1차 시각피질 손상.','자극하면 단순한 저·고주파 소리.']),
Q('강의록 12–13쪽','1차 운동피질(precentral gyrus, area 4)에 대한 설명으로 옳지 않은 것은?',
 ['모든 수의운동을 시작한다.','Pyramidal tract의 약 40%가 이곳에서 기원한다.','시상의 PVL 핵, 전운동영역 6·8, 체성감각영역에서 입력을 받는다.','자극하면 반대측 근육이 수축하며 얼굴·몸통 일부는 동측도 수축한다.','손상되면 강직성(spastic) 마비가 생긴다.'],5,
 '강의록 13쪽: 1차 운동피질 손상 → 이완성(flaccid) 마비. 전운동영역(area 6) 손상은 추체외로 섬유가 끊겨 강직성 마비. 추체로 기원: 1차 운동 40%, postcentral 20%, 전운동 40%.',
 ['맞다.','맞다.','맞다.','맞다.','틀리다(정답). 1차 운동피질 손상은 이완성 마비이고, 강직성 마비는 area 6 손상.']),
Q('강의록 13쪽','Pyramidal tract의 기원 비율로 강의록에 제시된 것은?',
 ['1차 운동영역 80%, 전운동영역 20%','1차 운동영역 40%, postcentral gyrus 20%, 전운동영역 40%','1차 운동영역 100%','Postcentral gyrus 60%, 1차 운동영역 40%','1차 운동영역 20%, 보조운동영역 80%'],2,
 'Origin of pyramidal tract: primary motor area 40%, postcentral gyrus 20%, premotor area 40%.',['틀리다.','정답.','틀리다.','틀리다.','틀리다.']),
Q('강의록 14쪽','1차 체성감각피질(3, 1, 2) 손상 시 나타나는 소견으로 옳은 것은?',
 ['통각·온도·압력·촉각 지각의 뚜렷한 감소와 판별·위치감각 소실','반대측 이완성 마비','번쩍이는 빛이 보인다.','소리 방향 지각 저하','얼굴 인식 불능'],1,
 '1차 체성감각피질 손상: 통각·온도·압력·촉각 지각이 크게 떨어지고 판별감각과 위치감각이 소실. 자극하면 따끔거림, 개미가 기는 느낌(formication), 저림.',
 ['정답.','1차 운동피질 손상.','1차 시각피질 자극.','1차 청각피질 손상.','시각 연합영역(18·19) 손상의 prosopagnosia.']),
Q('강의록 15쪽','1차 시각피질(area 17)에 대한 설명으로 옳은 것은?',
 ['후두엽 외측면의 Sylvian fissure를 따라 위치한다.','Calcarine fissure를 따라 후두엽 내측면에 있고 후두극 볼록면까지 퍼진다.','손상되면 같은 쪽 동측반맹이 생긴다.','자극하면 복잡한 얼굴 환시가 보인다.','시각 연합영역이다.'],2,
 'Area 17: calcarine fissure를 따라 후두엽 내측면, 후두극 볼록면까지. 손상 → 반대쪽 동측반맹, 자극 → 번개 같은 섬광, 밝은 선, 색. 18(V2)·19(V3–V5)가 시각 연합영역.',
 ['Sylvian fissure가 아니다.','정답.','반대쪽을 향한 동측반맹.','자극하면 섬광·밝은 선·색.','1차 시각피질이다.']),
Q('강의록 17–18쪽','1차 미각피질과 1차 전정피질의 위치로 옳게 짝지어진 것은?',
 ['Area 43 frontoparietal operculum / postcentral gyrus 아래쪽(머리 체성감각 영역 뒤)','Area 41 / area 42','Area 22 / area 40','Area 17 / area 18','Insula 전체 / 소뇌 flocculus'],1,
 '1차 미각피질(43): 체성감각피질 배쪽, Sylvian fissure와 insula 바로 위의 frontoparietal operculum. 1차 전정피질: postcentral gyrus 아래쪽, 머리 체성감각 영역의 뒤.',
 ['정답.','청각피질.','Wernicke·모서리위이랑.','시각피질.','틀리다.']),
Q('강의록 20–21쪽','전운동피질(area 6)에 대한 설명으로 옳지 않은 것은?',
 ['추체외로계의 피질 중추이다.','소뇌·기저핵과 협력해 이전에 학습한 운동 engram을 저장한다.','Frontopontocerebellar tract–dentate nucleus–thalamus–motor cortex 되먹임 회로 때문에 손상 시 평형장애와 넘어지는 경향이 생긴다.','손상되면 반대측 강직(spasticity)이 생긴다.','자극하면 반대측의 정교한 손가락 단일 운동이 생긴다.'],5,
 'Area 6 자극 → 의도하지 않은 정형화된 운동(사지의 mass movement, 몸통·머리·눈의 비틀림 운동, frontal adversive field). 손상 → 반대측 강직, 평형장애.',
 ['맞다.','맞다.','맞다.','맞다.','틀리다(정답). 자극하면 정교한 단일 운동이 아니라 사지·몸통·머리·눈의 정형화된 mass movement가 나온다.']),
Q('강의록 22쪽','보조운동영역(SMA, area 6)의 자극과 손상 소견으로 옳게 짝지어진 것은?',
 ['자극: 양측 비대칭 긴장성 자세 / 손상: 강제 파악반사(grasp reflex)','자극: 섬광 / 손상: 반맹','자극: 무긴장 / 손상: 운동실어증','자극: 단순한 소리 / 손상: 소리 방향 지각 저하','자극: 따끔거림 / 손상: 위치감각 소실'],1,
 'SMA: stimulation → bilateral asymmetric tonic posture, lesion → grasp reflex of forced grasping.',
 ['정답.','1차 시각피질.','Broca 영역.','1차 청각피질.','1차 체성감각피질.']),
Q('강의록 24–25쪽','전두엽 기저부(orbital lobe) 양측 손상 환자에서 가장 두드러질 것으로 예상되는 변화는?',
 ['운동과 사고의 자발성 소실','사회적 행동의 탈억제와 성격 변화','반대측 이완성 마비','운동실어증','동측반맹'],2,
 '강의록 24–25쪽: 볼록면(convexity) 손상 → 운동·사고의 initiative 소실(자발성 저하), 기저부(orbital) 손상 → 사회적 행동의 억제 결여, 성격 변화, 책임 무시.',
 ['전두엽 볼록면(앞 2/3) 손상.','정답.','1차 운동피질.','Broca 영역.','시각 경로.']),
Q('강의록 26쪽','Broca 영역(44, 45)에 대한 설명으로 옳은 것은?',
 ['자극하면 무긴장(atonia)이 생기는 negative motor area이다.','손상되면 감각실어증이 생긴다.','Superior temporal gyrus에 있다.','Area 44와 발성 운동영역을 잇는 섬유가 끊겨도 실어증은 생기지 않는다.','비우세반구 손상이 전형적이다.'],1,
 'Broca: 자극 → atonia(negative motor area), 손상 → 운동실어증. Cortical motor aphasia(area 4 병변), subcortical motor aphasia(aphemia): area 44와 발성 운동영역을 잇는 섬유(arcuate fasciculus) 단절.',
 ['정답.','운동실어증.','Inferior frontal gyrus.','Subcortical motor aphasia(aphemia)가 생긴다.','우세반구.']),
Q('강의록 27쪽','이차 수용 연합영역(secondary receptive cortical fields)과 Brodmann area의 연결로 옳지 않은 것은?',
 ['Area 5, 7 – 체성감각 연합영역','Area 18, 19 – 시각 연합영역','Area 22 – 청각 연합영역','Area 28 – 후각 연합영역','Area 17 – 시각 연합영역'],5,
 'Secondary receptive fields: 5·7 체성감각 연합, 18·19 시각 연합, 22 청각 연합, 28 후각 연합. Area 17은 1차 시각피질.',
 ['맞다.','맞다.','맞다.','맞다.','틀리다(정답). Area 17은 1차 시각피질.']),
Q('강의록 29쪽','눈을 감은 상태에서 손에 쥐어 준 열쇠를 촉각만으로 무엇인지 알아맞히지 못한다. 병변이 있을 가능성이 가장 높은 부위는?',
 ['Area 5, 7 (체성감각 연합영역)','Area 17','Area 41, 42','Area 44, 45','Area 4'],1,
 'Tactile agnosia: 이전에 저장된 촉각 경험이 사라져 눈을 감고 촉각만으로 물체를 알아보지 못함 — 체성감각 연합영역(5·7, superior parietal lobule).',
 ['정답.','1차 시각피질.','1차 청각피질.','Broca 영역.','1차 운동피질.']),
Q('강의록 30쪽','시각 연합영역(18, 19) 손상과 관련된 인식불능증이 아닌 것은?',['Visual object agnosia','Alexia','Color agnosia','Prosopagnosia','Tactile agnosia'],5,
 'Visual agnosia: 특히 양측 손상. Object agnosia(물체), alexia(글자), color agnosia(색), prosopagnosia(얼굴). Tactile agnosia는 체성감각 연합영역.',
 ['시각 연합영역.','시각 연합영역(글자 인식불능).','시각 연합영역.','시각 연합영역(얼굴).','정답. 체성감각 연합영역(5·7) 손상.']),
Q('강의록 31쪽','흔한 소리와 음을 알아듣지 못하고 특히 음악을 이해하지 못하게 되는 청각 인식불능증은 어느 쪽 병변에서 특히 잘 생기는가?',
 ['우측 측두엽','좌측 전두엽','좌측 후두엽','우측 두정엽 위쪽','소뇌 벌레'],1,
 'Acoustic(auditory) agnosia: area 22(청각 연합영역) — 음악 이해 소실은 특히 우측 측두엽 병변.',['정답.','틀리다.','틀리다.','틀리다.','틀리다.']),
Q('강의록 29·33–36쪽','Inferior parietal lobule에 대한 설명으로 옳은 것은?',
 ['Superior parietal lobule과 같은 BA 5·7로 이루어진다.','Supramarginal gyrus(40)와 angular gyrus(39)로 이루어진 삼차 두정 연합영역(Geschwind territory)이다.','뇌에서 가장 먼저 성숙하는 영역이다.','손상되면 이완성 마비가 생긴다.','주로 위치감각·촉각의 1차 입력을 받는다.'],2,
 'Inferior parietal lobule = supramarginal(40) + angular(39) = tertiary parietal association area / Geschwind territory. 가장 늦게 성숙(읽기·쓰기 발달과 일치). 위치감각·촉각 처리는 superior parietal lobule(5·7).',
 ['BA 39·40이다.','정답.','가장 늦게 성숙한다.','운동피질 손상 소견.','Superior parietal lobule 기능.']),
Q('강의록 34쪽','Geschwind territory의 성숙 시기에 대한 강의 내용으로 옳은 것은?',
 ['출생 직후 가장 먼저 성숙한다.','뇌에서 가장 늦게 성숙하며 읽기·쓰기 능력 발달과 시기가 맞는다.','1차 운동피질보다 먼저 성숙한다.','사춘기 이후에는 더 이상 발달하지 않는다고 설명한다.','시각피질과 동시에 성숙한다.'],2,
 '강의록 34쪽: “the last area in the brain to mature, coinciding with the development of reading and writing skills.”',['틀리다.','정답.','틀리다.','강의 내용 아님.','틀리다.']),
Q('강의록 35–36쪽','우세반구 angular gyrus의 단일 병변으로 생기는 Gerstmann syndrome의 구성 요소가 아닌 것은?',
 ['Right/left disorientation','Finger agnosia','Agraphia','Acalculia','Prosopagnosia'],5,
 'Gerstmann syndrome: 좌우 구분 불능, 손가락 인식불능, 실서증, 계산불능 — 우세반구 angular gyrus 단일 병변.',
 ['구성 요소.','구성 요소.','구성 요소.','구성 요소.','정답. 얼굴 인식불능은 시각 연합영역 손상.']),
Q('강의록 33·35쪽','우세반구 area 39·40 손상 때 자기 몸에 대한 느낌을 잃는 증상의 이름은?',
 ['Autotopagnosia(body-image agnosia, asomatognosia)','Prosopagnosia','Aphemia','Anosmia','Alexia'],1,
 'Lesion in area 40, 39: body-image agnosia = autotopagnosia = asomatognosia, finger agnosia, right/left agnosia, agraphia, acalculia. Area 39 병변: 공간에서 자기 몸의 위치와 신체 부위 사이 관계에 대한 느낌 소실.',
 ['정답.','얼굴 인식불능.','Subcortical motor aphasia.','후각 소실.','글자 인식불능.']),
Q('강의록 37쪽','목적이 있는 행동(purposeful movement)의 기전 순서로 옳은 것은?',
 ['감각 자극 → 좌측 두정-후두 연합영역 통합 → 삼차 연합영역에서 계획 → 전운동영역 6의 운동 패턴 활성화 → 1차 운동영역 4','1차 운동영역 4 → 전운동영역 6 → 삼차 연합영역 → 감각 입력','소뇌 → 기저핵 → 1차 운동영역 → 두정엽','전운동영역 6 → 감각 입력 → 1차 운동영역 → 삼차 연합영역','시상 → 전운동영역 → 두정엽 → 1차 운동영역'],1,
 '강의록 37쪽: kinesthetic·acoustic·visual·vestibular 자극 → 좌측 두정-후두(1·2차 연합) 통합 → 삼차 연합영역에서 행동 계획 → 긴 연합섬유로 area 6의 운동 패턴 활성화(반대측은 뇌량 무릎의 교련섬유) → area 4로 순서대로 전달. 이 경로가 끊기면 apraxia.',
 ['정답.','순서가 거꾸로이다.','틀리다.','틀리다.','틀리다.']),
Q('강의록 39쪽 QUIZ 1','강의 QUIZ에서, 이전에 Wernicke’s area로 알려졌던 area 40, 39의 현재 이름으로 제시된 것은?',
 ['Geschwind’s territory','Broca’s area','Heschl’s gyrus','Meyer’s loop','Papez circuit'],1,
 '강의록 39쪽 QUIZ 1 정답: Geschwind’s territory.',['정답.','44·45.','41·42 청각피질.','시방사.','변연계 기억 회로.']),
Q('강의록 3쪽','측두엽 병변에서 상부 사분맹(“pie in the sky”)과 관련된 구조로 강의록에 제시된 것은?',
 ['Meyer’s loop(optic radiation)','Corpus callosum','Internal capsule 후각','Calcarine fissure 위 둑','Lateral geniculate body'],1,
 '강의록 3쪽: temporal lobe의 optic radiation(Meyer’s loop) 손상 → visual field defect(반대쪽 위쪽 사분맹).',
 ['정답.','반구 연결.','운동·감각 섬유.','아래쪽 사분맹과 관련.','시상 중계핵.']),
Q('강의록 41–42쪽','기저핵(basal ganglia)의 주요 구성 요소로 강의록에 나열되지 않은 것은?',
 ['Striatum','Globus pallidus','Substantia nigra','Subthalamic nucleus','Red nucleus'],5,
 'Basal ganglia main component: striatum, GP, SN, STN, nucleus accumbens. 기능: 수의운동 조절, 학습, 습관, 안구운동, 인지, 정서. 억제 기능 손상 시 rigidity, resting tremor.',
 ['구성 요소.','구성 요소.','구성 요소.','구성 요소.','정답. 적핵은 중뇌 구조로 기저핵 구성 요소로 나열되지 않는다.']),
Q('강의록 46쪽','시상 특이 중계핵과 연결의 짝으로 옳지 않은 것은?',
 ['Anterior nucleus – 시상하부 입력, 띠이랑 출력','VA·VL nucleus – 기저핵·소뇌 정보를 운동·전운동피질로 중계','VP nucleus – 내측섬유띠·척수시상로·삼차신경 입력, 1차 체성감각피질 출력','Medial geniculate nucleus – 망막 신경절세포 입력, 1차 시각피질 출력','Lateral geniculate nucleus – 시각 처리'],4,
 '강의록 46쪽(Fig 9.6): MGN – 하구(inferior colliculus) 입력, 1차 청각피질 출력(청각). LGN – 망막 신경절세포 입력, 1차 시각피질 출력(시각).',
 ['맞다.','맞다.','맞다.','틀리다(정답). 설명은 LGN이다. MGN은 청각 중계.','맞다.']),
Q('강의록 47쪽','전전두피질로 출력하며 감정 상태와 기억에 관여하는 시상의 연합핵은?',['Dorsomedial nucleus','Pulvinar','Lateral posterior nucleus','Ventral posterior nucleus','Reticular nucleus'],1,
 'Association nuclei(Fig 9.8): dorsomedial nucleus – 후각피질·편도체·시상하부 입력, 전전두피질 출력, 정서·기억. Pulvinar – 상구·감각연합영역, 감각 처리. LP – 체성감각 연합피질.',
 ['정답.','감각 연합영역 연결.','체성감각 연합피질 출력.','특이 중계핵(체성감각).','비특이 핵으로 시상의 피질 영향 조절.']),
Q('강의록 48쪽','시상 비특이핵 중 대뇌피질·담창구에서 입력받아 꼬리핵·조가비핵으로 출력하며 추체외로 운동계에 관여하는 핵은?',
 ['Centromedian nucleus','Reticular nucleus','Midline nucleus','Anterior nucleus','Lateral dorsal nucleus'],1,
 'Nonspecific nuclei(Fig 9.7): centromedian – 피질·GP 입력, 꼬리핵·조가비핵 출력, 추체외로. Reticular – 시상피질·피질시상 섬유 곁가지 입력, 다른 시상핵으로 출력(시상의 피질 영향 조절). Midline – 뇌간 망상체 입력, 변연계 출력.',
 ['정답.','시상의 피질 영향 조절.','뇌간 망상체 → 변연계.','특이 중계핵.','연합핵.']),
Q('강의록 49·56쪽','의식을 명료하게 유지하는 ARAS에서 연수 망상체의 상행 가지가 동측 수질판속핵(intralaminar nuclei)으로 올라가는 경로는?',
 ['Central tegmental tract','Medial lemniscus','Medullary reticulospinal tract','Corticospinal tract','Spinocerebellar tract'],1,
 '강의록 49쪽: 연수 망상체 출력 1) 상행 가지 → central tegmental tract(비교차) → 동측 intralaminar thalamic nuclei(수면에서 깨는 각성 기전), 2) 하행 가지 → medullary reticulospinal tract. QUIZ 2 정답도 central tegmental tract.',
 ['정답.','후색 감각 경로.','하행 가지.','운동 경로.','소뇌 경로.']),
Q('강의록 53–55쪽','소뇌 부위와 손상 소견의 연결로 옳은 것은?',
 ['Flocculonodular lobe(vestibulocerebellum) – 평형 소실, 넓은 보폭의 불규칙 보행','Vermis(spinocerebellum) 위쪽 – 팔·손의 협조 장애','Lateral hemisphere(cerebrocerebellum) – 전신 운동 장애만 생긴다','Vermis 아래쪽 – 보행장애','Lateral hemisphere – 근긴장도 증가(hypertonia)'],1,
 'Flocculonodular(전정소뇌) 손상 → 평형 소실, 넓은 보폭의 불규칙 보행. Vermis 윗부분 → 보행·다리 협조 장애, 아랫부분 → 팔·손 협조 장애. Lateral hemisphere(대뇌소뇌) → 힘·방향·속도·범위 오류, hypotonia, dysarthria, dysmetria, dysdiadochokinesia, rebound, intention tremor.',
 ['정답.','위쪽은 보행·다리.','숙련된 계획 운동 장애.','아래쪽은 팔·손.','저긴장(hypotonia).']),
Q('강의록 57쪽','양쪽 대뇌반구 사이를 연결하는 구조로 강의록 마지막 쪽에 나열되지 않은 것은?',
 ['Corpus callosum','Anterior commissure','Hippocampal commissure','Habenular commissure','Internal capsule'],5,
 '강의록 57쪽: cerebral hemisphere 연결 — corpus callosum, anterior commissure, posterior commissure, habenular commissure, hippocampal commissure, massa intermedia(시상). Internal capsule은 피질과 뇌간·척수를 잇는 투사섬유.',
 ['나열됨.','나열됨.','나열됨.','나열됨.','정답. 내포는 투사섬유이다.']),
]
