def Q(src,stem,choices,ans,basis,exps,**k):
  d=dict(src=src,stem=stem,choices=choices,ans=ans,basis=basis,exps=exps); d.update(k); return d
OFF=[
Q('강의록','22세 여성이 혼잡한 버스에서 20분 이상 서 있다가 식은땀·메스꺼움·시야협착 후 쓰러졌다. 창백했고 의식소실 약 20초, 팔다리가 5–6회 움찔거렸으며 1분 안에 지남력을 회복했다. 가장 적절한 판단은?',['혈관미주신경성 실신(짧은 경련양 움직임도 가능)','전신 강직간대 발작','심장성 실신','기능성 발작','저혈당'],1,'강의록 Case 1·VVS "3P": posture(오래 서 있음), provocation(통증·공포·열·탈수), prodrome(식은땀·온감·오심·시야흐림·창백). 수평 자세 후 빠른 회복. 짧은 seizure-like activity도 uncomplicated faint에서 가능.',['정답.','회복이 빠르고 전구증상이 전형적.','red flag 없음.','틀리다.','틀리다.']),
Q('강의록','긴급 심혈관 평가가 필요한 실신 red flag가 아닌 것은?',['오래 서 있다가 식은땀과 오심 후 발생','운동 중 발생','전구증상 없는 갑작스러운 의식소실','젊은 돌연사 가족력','심전도의 Brugada pattern'],1,'강의록 red flags: 운동 중·누운 자세 발생, 무전구 LOC, 흉통·호흡곤란·심계항진 선행, 심부전·구조적 심질환, 젊은 돌연사 가족력, 고령의 새 무전구 TLoC; ECG — 고도 AV block·bifascicular block, long/short QT, Brugada, WPW, 허혈, 지속 서맥, VT.',['정답. 전형적 VVS.','red flag.','red flag.','red flag.','red flag.']),
Q('강의록','기립성 저혈압(classic OH)의 정의로 옳은 것은?',['기립 3분 이내 수축기 혈압 ≥20 mmHg 또는 이완기 ≥10 mmHg 하강','기립 10분 내 심박수 ≥30 bpm 상승','기립 1분 내 수축기 혈압 10 mmHg 하강','기립 10분 후에만 혈압 하강','누운 자세 고혈압'],1,'강의록: 5분 이상 누운 뒤 기립 1·3분 측정, classic OH = 3분 이내 SBP↓≥20 또는 DBP↓≥10; initial OH는 매우 이른 일시적 하강, delayed OH는 3분 이후. POTS는 기립 10분 내 HR ≥30 bpm(12–19세 ≥40), SBP 하강 <20.',['정답.','POTS.','틀리다.','Delayed OH.','neurogenic OH 동반 가능.']),
Q('강의록','신경인성 기립성 저혈압(neurogenic OH)을 시사하는 소견은?',['기립 시 심박수 증가가 불충분하고 누운 자세 고혈압이 동반된다.','탈수 후 심박수가 적절히 증가한다.','이뇨제 복용 후 발생한다.','식후·음주 후에만 발생한다.','기립 시 심박수가 40 bpm 이상 증가한다.'],1,'강의록: neurogenic OH — HR 증가 불충분, 파킨슨병·MSA·PAF, 당뇨·소섬유/자율신경병, supine hypertension; non-neurogenic — 탈수·출혈·발열·약물·식후·음주·장기 침상, HR 적절히 증가. ΔHR/ΔSBP가 낮을수록 neurogenic.',['정답.','non-neurogenic.','non-neurogenic.','non-neurogenic.','POTS.']),
Q('강의록','반복되는 혈관미주신경성 실신 환자의 1차 관리로 옳은 것은?',['진단 설명, 수분·염분 보강, 전구증상 시 즉시 앉거나 눕기와 physical counter-pressure maneuver','β-blocker를 1차로 시작','모든 환자에게 즉시 심박동기 삽입','Tilt 검사 음성이면 VVS를 배제','항경련제 투여'],1,'강의록 VVS 관리: 진단 설명 → 수분·염분 → 전구증상 시 즉시 앉기/눕기 → counter-pressure(다리 교차 긴장, hand grip, arm tensing) → 불응 시 약물(midodrine 등)·pacing·CNA. β-blocker·SSRI는 routine 1차가 아님. Pacing은 >40세, 중증 반복, documented asystole. 음성 tilt가 reflex syncope를 배제하지 않음.',['정답.','routine 1차 아님.','선택 기준 있음.','배제 못함.','틀리다.']),
]
