from fixlib import Q,S
from common_headache import *
SPECS={
 'q-001':Q(2,'Red flag가 없는 소아의 반복 두통(수면으로 호전, 진찰·안저 정상)은 임상 진단으로 치료를 시작할 수 있다. 나머지는 영상검사가 필요한 적색신호.',
   'IIH(가성뇌종양) 의심: 아침 두통, 기침 악화, 박동성 이명, 시야 흐림, 체중 증가 → 영상·안저·LP.','정답.','산욕기 진행성 두통 + 기침 악화: 정맥동 혈전증·RCVS 등 → 영상 필요.','68세 새 두통 + jaw claudication: GCA → ESR·CRP·생검, 즉시 스테로이드.','약물과용두통 의심: 평가·중단 계획 필요(영상 여부와 별개로 이 선택지는 오답).'),
 'q-002':Q(4,PAIN+' (출제오류로 안와조직 선지가 두 개)',*pain5),
 'q-003':S('두통의 양상, 정도, 위치, 기간, 변해가는 모습, 발생인자, 악화인자, 완화인자','통합강의록 신경학 각론 p.491.',tail='야마 2015 주15 · 학습지 15쪽'),
 'q-004':Q(4,SAHDX,*sahdx,stem='(2013 객30의 환자: 45세 건강한 여자가 갑자기 의식을 잃음 → 지주막하출혈) 상기 환자는 다음 중 어떤 검사를 하는 것이 진단에 가장 도움이 되겠는가?'),
 'q-005':Q(1,SAH,*sah,tail='야마 2011 객41 · 학습지 17–18쪽 원문대조'),
 'q-006':Q(4,PAIN+' ※ 이전 버전의 정답(③)은 학습지 정답(④)과 달라 수정함.',*pain5),
 'q-007':Q(3,'시각 전조 + 편측 박동성 두통 + 구역·빛/소리 공포 + 활동 시 악화 → 편두통. 2~3일마다 재발하면 예방치료 → topiramate. naproxen·ibuprofen·ergotamine·sumatriptan은 급성기 치료.',
   'naproxen: 급성기 진통제.','ibuprofen: 급성기 진통제.','정답. topiramate(예방).','ergotamine: 급성기 치료.','sumatriptan: 급성기 치료(triptan).',tail='야마 객8 (연도 표기 없음) · 학습지 573쪽 원문대조',
   stem='9살 남아가 머리가 아프다며 병원에 왔다. 두통은 눈이 갑자기 안 보이다가 발생하는데 좌측 측두부에 박동성 두통이 시작된다. 두통은 보통 2-3시간 지속되다 잠자고 나면 호전된다. 메슥거림과 구토가 동반되고, 빛과 소음에 매우 민감한 반응을 보인다. 빠르게 걷거나 뛸 때 두통이 더 심해서 움직이지 않으려 한다. 이러한 두통이 2-3일 재발할 때 예방치료는?'),
 'q-008':S('Central sensitization — 두통이 수시간 지속되면 thalamus까지 감작되어 빛·소리에 민감해짐','throbbing headache가 4시간 이상 지속되면 thalamus가 sensitization되면서 소리·냄새·빛에 민감해진다(central sensitization).',tail='야마 2023 주19 · 학습지 573쪽'),
 'q-009':S('(A) B~D를 만족하는 발작 5회 이상 (B) 2(1)~72시간 지속 (C) 편측(소아는 양측·전측두부 가능), 박동성, 중등도 이상, 일상활동으로 악화 중 2개 이상 (D) 구역/구토 또는 빛·소리 공포(행동으로 추정 가능) 중 1개 이상 (E) 다른 질환으로 설명되지 않음','2004(2013) IHS criteria for pediatric migraine without aura. 강의록은 1시간, 수업에서는 2시간 언급(성인 4~72시간).',tail='야마 2022 주6 · 학습지 573–574쪽'),
 'q-010':Q(5,ANALG,'예방약을 써도 두통 시 진통제를 20~30분 내 투여.','2시간 기다리지 않고 조기 투여.','단순제제가 추천된다.','적절한 용량을 써야 한다.','정답.'),
 'q-011':Q(3,PROPH,'acetaminophen: 급성기 진통제.','ibuprofen: 급성기 진통제.','정답. topiramate.','propranolol: β-blocker. 천식 환자에서 금기, 소아에서는 잘 안 씀.','aspirin: 소아에서 Reye syndrome 위험.',tail='야마 2020 객12 · 학습지 574쪽 원문대조'),
 'q-012':Q(3,ANALG,'20~30분 이내에 준다.','체중에 맞는 용량을 쓴다.','정답.','단순제제가 추천된다.','일주일 3회 이내로 제한.',tail='야마 2019 객28 · 학습지 574쪽 원문대조'),
 'q-013':Q(5,ANALG+' ※ 이전 버전은 이 칸에 성인 지주막하출혈 문제(서만욱 2018 객15)가 잘못 들어가 있어 소아 두통 2018 객15로 교체함.',
   '단순제제가 추천된다.','12세 이하는 aspirin 금지(Reye syndrome).','신기능 저하 시 NSAID(ibuprofen)도 피한다.','20~30분 이내에 복용.','정답.',
   stem='소아청소년 두통 환자 치료 중 진통제 사용에 대한 설명이다. 옳은 것은?',
   choices=['단순제제보다는 복합제형을 더 추천한다.','소아에서 독감이 동반된 경우 아스피린 사용이 추천된다.','신기능(kidney)이 좋지 못하면 Acetaminophen보다 ibuprofen을 추천한다.','두통 발생 후 30분 이상 기다려보고 그래도 두통이 지속되면 진통제를 사용한다.','진통제가 장기간 필요 시 반드시 일주일에 3회 이내로 제한해야 한다.'],
   tail='야마 2018 객15 (소아 두통) · 학습지 575쪽 원문대조'),
 'q-014':Q(3,ANALG,'단순제제 사용.','일주일 3회 이내.','정답. 간 손상 시 ibuprofen.','적절한 용량.','20~30분 이내 복용.',tail='야마 2017 객26 · 학습지 575쪽 원문대조'),
 'q-015':Q(3,ANALG,'신기능 저하 시 ibuprofen(NSAID)도 쓰지 않는다.','20~30분 이내.','정답.','단순제제가 추천.','적절한 용량.',
   choices=['Kidney failure시 Ibuprofen이 Acetaminophen보다 진통효과가 더 좋다.','두통이 발생하면 1시간 관찰한 후 진통제를 주는 것이 좋다.','장기간 사용 시에는 일주일에 3회 이내로 제한한다.','단일제제보다 복합제제가 더 좋다','추천용량보다 적은 양을 사용하는 것이 좋다.'],tail='야마 2016 객7 · 학습지 575쪽 원문대조'),
 'q-016':Q(3,ANALG,'진통효과 우열이 아니라 원칙을 묻는다(둘 다 급성기 약).','20~30분 이내.','정답.','체중에 따라 적정량.','적절한 용량.',tail='야마 2015 객9 · 학습지 576쪽 원문대조'),
 'q-017':Q(3,PROPH,'Naproxen: 급성기 진통제(월경 편두통 예방에는 사용).','Propranolol: 주로 성인 예방약.','정답. Topiramate.','Steroid: 예방약 아님.','CCB: 주로 성인.',choices=['Naproxen','Propranolol','Topiramate','Steroid','Calcium channel blocker'],tail='야마 2015 객10 · 학습지 576쪽 원문대조'),
 'q-018':Q(3,ANALG,'우열 비교가 아니다.','20~30분 이내.','정답.','체중에 따라 적정량.','적절한 용량.',
   choices=['Ibuprofen이 Acetaminophen보다 진통효과가 더 좋다','두통이 발생하면 1시간 관찰한 후 진통제를 주는 것이 좋다.','장기간 사용시에는 일주일에 3회 이내로 제한한다.','소아에서는 체중에 관련없이 소아용 진통제를 사용하는 것이 좋다.','추천용량보다 적은 량을 사용하는 것이 좋다.'],tail='야마 2014 객23 · 학습지 577쪽 원문대조'),
 'q-019':Q(3,PROPH,'Naproxen: 급성기.','Propranolol: 주로 성인.','정답. Topiramate.','Steroid: 예방약 아님.','CCB: 주로 성인.',tail='야마 2014 객24 · 학습지 577쪽 원문대조'),
 'q-020':Q(4,ANALG,'맞는 설명. 단일 성분제.','맞는 설명. 항시 휴대.','맞는 설명. 충분(적절)한 용량.','정답(틀린 설명). 하루가 아니라 일주일 3회 이내.','맞는 설명. 30분 이내.',
   choices=['진통제는 단일 성분제가 추천 된다.','진통제는 항시 휴대하는 것이 좋다.','진통제는 충분한 용량을 사용해야 한다.','진통제는 하루 3회 이내 사용해야 한다.','전조 증상이 보일 때 가능한 30분 이내에 복용한다.'],tail='야마 2013 객34 · 학습지 577–578쪽 원문대조'),
 'q-021':Q(4,'소아 무조짐 편두통: 1(2)~72시간, 편측 또는 양측 전측두부, 박동성, 일상활동으로 악화. 조짐은 5~60분. Cutaneous allodynia는 2nd order trigeminal nucleus의 central sensitization.',
   '맞는 설명.','맞는 설명.','맞는 설명.','정답(틀린 설명). aura는 5~60분.','맞는 설명.'),
 'q-022':Q(2,ANALG,'단순제제가 좋다.','정답. 30분 이내.','규칙적 사용이 아니라 필요 시, 일주일 3회 이내.','체중에 맞는 적절한 용량.','소아에서도 진통제를 쓴다(ibuprofen, naproxen은 FDA 승인).',
   choices=['진통제는 복합 성분제가 좋다.','두통 발생 후 30분 이내에 복용','진통제는 하루 3회로 규칙적으로 사용','소아는 추천 용량보다 낮게 사용해야한다.','두통이 심해도 소아에서 진통제 사용은 안된다.'],tail='야마 2011 객55 · 학습지 578–579쪽 원문대조'),
 'q-023':Q(1,'Cutaneous allodynia: 정상 피부·두피의 무해 자극(빗질, 면도, 안경)에 통증. 편두통(79%)에서 흔하며 central sensitization 소견.',
   '정답. Migraine.','Cluster headache: 자율신경 증상.','Primary stabbing headache: 짧은 찌르는 통증.','Childhood periodic syndrome: 편두통 전구 증후군.','Chronic tension-type headache.',
   choices=['Migraine','Cluster headache','Primary stabbing headache','Childhood periodic syndrome','Chronic tension type headache'],stem='Cutaneous allodynia가 나타나는 경우?'),
 'q-024':Q(4,'소아 편두통: 사춘기 이후 여아에 흔함, 3~7세는 남아, 7~11세는 비슷. 전조 없이도 진단 가능. 대부분 박동성. 일상활동으로 악화.',
   '사춘기 이후에는 여아에서 흔하다.','3~7세는 남아가 흔하다.','전조가 없어도 진단 가능.','정답.','운동으로 악화된다.'),
 'q-025':Q(5,'Peripheral sensitization of trigeminal ganglion neuron: 몸을 숙이거나 기침 등 ICP를 높이는 활동에 박동성 두통이 악화. 나머지(allodynia, photo·phonophobia)는 central sensitization. 복원자: 해답에는 ②로 되어 있어 확실하지 않음.',
   'Phonophobia: central sensitization(thalamus).','Cutaneous allodynia: central sensitization(2nd order TNC).','Photophobia: central sensitization.','Contralateral allodynia: 해당 없음.','정답(복원자 기준). 일상 움직임에 박동성 두통 악화.',
   stem='편두통시 peripheral sensitization에 의한 증상은?',choices=['Phonophobia','Cutaneous allodynia','Photophobia','Contralateral allodynia','일상적인 움직임에 박동성 두통'],tail='야마 2010 객62 · 학습지 579쪽 원문대조',caveat='복원자 정답 불확실(해답지는 ②) — 해설 참고'),
 'q-026':Q(4,'뇌종양 두통: 이른 아침 심한 두통, 긴장형 양상(77%), 오심·구토는 17%뿐, infratentorial 56% > supratentorial 37%.',
   '이른 아침에 심하다.','긴장형 양상이 흔하다.','오심·구토는 17%.','정답.','진행성이다.'),
 'q-027':Q(3,'소아 두통 약물치료: triptan은 어린 소아에 잘 쓰지 않음, 진통제는 일주일 3회 이내, 두통 발생 후 가능한 빨리(20~30분 내), 적절한 용량(10mg/kg/dose), 소아 예방약은 β-blocker·CCB보다 amitriptyline 저용량 등.',
   'triptan은 부작용으로 어린 소아에 잘 안 쓴다.','일주일 3회 이내로 제한.','정답.','적절한 용량.','β-blocker·CCB는 주로 성인.',
   choices=['어린 소아는 triptan 계열이 안전','진통제는 매일 1~2회 충분히 사용','진통제는 두통 발생 후 가능한 빠른 시간에 사용','진통제는 가장 낮은 농도로 투여','소아 편두통 예방약은 beta blocker가 좋다.'],tail='야마 2010 객64 · 학습지 580쪽 원문대조'),
}
