from fixlib import Q,S
MCD='2017 McDonald criteria: 2회 이상 발병 + 객관적 병터 2곳 이상 → 추가 조건 불필요 / 2회 발병 + 병터 1곳 → DIS 필요 / 1회 발병 + 병터 2곳 → DIT 필요(CSF OCB로 대체 가능) / 1회 발병 + 병터 1곳 → DIS와 DIT 모두 필요. CSF OCB는 진단기준에 포함되지만 필수는 아니다.'
mcd=['맞는 설명. 2회 이상 발병 + 2곳 이상 → 추가 조건 불필요.','맞는 설명. 병터가 1곳이면 DIS 필요.','맞는 설명. 1회 발병이면 DIT 필요.','맞는 설명. 1회 발병 + 1곳이면 DIS와 DIT 모두 필요.','정답(틀린 설명). CSF 소견은 필수가 아니다.']
NMO_CR='NMO 진단(2006): optic neuritis + acute myelitis + 보조기준 3개 중 2개 이상(3분절 이상 척수 병변, MS 기준에 맞지 않는 뇌 MRI, NMO-IgG 양성). 경과: 항상 재발로 시작, 80~90% relapsing, 10~20% monophasic. MRI: 3분절 이상의 longitudinally extensive central lesion.'
CASE_NMO='56세 여자환자가 일주일 전부터 시작된 복시와 시력저하를 주소로 내원하였다. 병력상 8개월 전 지속되는 구역과 구토로 입원하였고 2개월 전에는 우측 상지 저림, 근력 저하로 횡단성 척수염 진단을 받아서 스테로이드 정주한 기왕력을 가지고 있다. 감기, 예방접종 기왕력은 없다. 시각 유발 전위검사에서 양측 p100의 잠복기가 연장되었으며 AQP4 특이 자가항체 NMO-IgG 양성이 확인되었다. 이 질환에 관하여 맞는 것을 모두 고르시오.'
NMO_CH=['시신경염과 급성 척수염이 확인되어야 진단 가능하다.','80%는 재발과 완화가 반복되는 다상성경과를 보인다.','척수 MRI 상 3분절 이상의 긴병변과 주로 뇌실 주위 영역을 침범하는 뇌 MRI를 특징으로 한다.','다음 3가지를 모두 만족해야 한다: 1) 척수 MRI에서 3개 이상의 척수분절을 넘는 병변 2) 뇌 MRI가 다발성 경화증 진단기준을 만족하지 못함 3) AQP4 특이 자가항체 NMO-IgG 양성']
nmo_ex=['정답. optic neuritis와 acute myelitis는 필수.','NMO는 remission 없이 재발(relapse)로 경과한다(80~90% relapsing course).','정답(학습지 기준). 척수 MRI 3분절 이상 긴 병변.','보조기준 3개 중 2개 이상이면 되므로 "모두"는 틀림.']
TDX='TCD는 MS 진단 검사가 아니다. MS work-up: 조영증강 brain MRI, VEP, CSF(OCB), C·T spine MRI 등. fundus photography는 강의록에 없으나 시신경염 평가에 쓰일 수 있다.'
SPECS={
 'q-001':Q(2,'양측 시신경염 + 유두부종 + 시신경 앞쪽의 긴 조영증강 + MS 전형 MRI 없음 + OCB 음성 → MOG antibody-associated disease를 의심하여 MOG-IgG 검사.',
   'AQP4-IgG: NMOSD 검사이나 이 소견(양측, 유두부종, 앞쪽 긴 병변)은 MOGAD에 더 합당하다.','정답. MOG-IgG.','OCB 재검은 진단 방향을 바꾸지 못한다.','VEP만으로는 원인 감별이 안 된다.','ANA만으로는 감별이 불충분하다.'),
 'q-002':Q(3,'시신경염 환자에서 MS로의 진행 예측인자: 뇌 MRI T2 고신호 병변(14년 객38: "MS로 가는 위험인자로 MRI T2 소견이 중요하다"). 전형적 시신경염이 MS와 연관. 복원자 정답 표기가 "③?⑤"로 불확실.',
   'typical optic neuritis는 MS와 연관되지만 시신경 MRI 소견이 가장 좋은 예측인자는 아니다.','VEP P100 지연은 시신경 탈수초를 반영하나 MS 진행 예측인자는 아니다.','정답. 뇌 MRI T2 고신호 병변 2개 이상.','OCB 양성도 위험인자이나 뇌 MRI 병변이 가장 강력한 예측인자이다.','시신경유두부종은 비전형적(NMO/MOG) 시신경염 쪽 소견이다.',
   caveat='복원자 정답 표기 "③?⑤" — 불확실 (해설 참고)'),
 'q-003':Q(5,MCD,*mcd),
 'q-004':Q(3,'NMOSD(2015 IPND): AQP4-IgG 양성이면 6가지 핵심 임상증상(ON, acute myelitis, area postrema, acute brainstem, acute diencephalic, symptomatic cerebral) 중 1개만 있어도 진단. 음성이면 ON·LETM·APS 중 1개 포함 2개 이상 핵심증상(DIS) + MRI 요건.',
   '맞는 설명. AQP4 양성이면 핵심증상 1개로 충분.','맞는 설명. 음성이면 핵심증상 2개 이상 + MRI.','정답(틀린 설명). AQP4 양성이면 1개면 충분.','맞는 설명. acute brainstem syndrome도 핵심증상.','음성일 때 ON·LETM·APS 중 적어도 1개가 필요하다는 기준의 변형.'),
 'q-005':Q(5,NMO_CR,'자가반응 T-cell·immune-mediated는 MS 쪽 설명.','베타인터페론 예방은 MS 치료. NMO는 면역억제제.','NMO는 80~90%가 relapsing, monophasic은 10~20%.','OCB는 MS 관련이며 필수 아님.','정답. 3개 이상 척수 분절 침범(LETM).'),
 'q-006':Q(4,'IFN 유지 중 재발(치료 실패) → first line을 순서대로 사용하거나 다음 단계 질병조절치료제로 전환. 선지 중 MS 질병조절치료제는 fingolimod.',
   'plasmapheresis: 급성기 스테로이드 불응 시 치료.','IFN: 이미 실패한 약.','rituximab: NMO 재발 예방 약제.','정답. fingolimod(MS 질병조절치료제).','스테로이드는 급성기 치료이지 질병조절치료가 아니다.'),
 'q-007':Q(2,'Dawson fingers(뇌실 주위 수직 병변)와 척수 다발 국소 병변 → MS. MS 의심 시 brain MRI, VEP, CSF OCB, spine MRI.',
   'area postrema syndrome·LETM은 NMOSD 소견.','정답. MS 평가로 OCB 확인.','스테로이드 불응 시 혈장교환은 적절한 치료이다.','재발 방지는 스테로이드가 아니라 IFN-β 등 질병조절치료.','AQP4는 NMO 진단에 중요.'),
 'q-008':Q(5,NMO_CR,'자가반응 T-cell은 MS 설명(immune-mediated).','CIS는 MS의 첫 임상삽화.','베타인터페론은 MS 예방 치료.','4가지 경과 분류는 MS의 특징.','정답. 여러 척수분절 침범(LETM).'),
 'q-009':Q(4,'1년 전 시신경염, 3개월 전 좌측 다리 마비 후 회복, 현재 좌측 상하지 마비 → MS(DIS·DIT). 수업 티야: preventive therapy 중 first line인 IFN-β만 기억.',
   'fingolimod: 2차 약제.','natalizumab: 2차 약제.','alemtuzumab: 2차 약제.','정답. IFN-β(first line).','재발하는 MS는 질병조절치료가 필요하다.'),
 'q-010':Q(2,'조절되지 않는 구토·딸꾹질(area postrema syndrome) + 6개월 전 단안 시신경염 + 척수 MRI의 LETM → AQP4 정보가 없어도 NMOSD 진단 가능. 문제 지문은 복원자가 전부 외우지 못함.',
   'AQP4 음성이어도 기준을 만족하면 진단 가능.','정답.','OCB는 MS 관련이며 필수 아님.','고용량 스테로이드 불응 시 혈장교환이 적절.','interferon-β는 MS 치료. NMO를 악화시킬 수 있다.',
   stem='33세 여자가 조절되지 않는 구토, 딸꾹질로 내원하였다. 3개월 전 ~~~ (복원 누락) 6개월 전 단안시신경염을 진단받고 치료하였다. (뇌 MRI, 척수 MRI 제시 — 척수에 LETM) 이 환자에 대한 설명으로 옳은 것은?',tail='야마 2020 객77 · 학습지 96쪽 원문대조 (지문 일부 복원 누락)'),
 'q-011':Q(5,TDX,'조영증강 brain MRI: MS 진단의 핵심 검사.','CSF OCB: MS 진단 보조.','VEP: 시신경 침범 평가.','안저촬영: 시신경염 동반 평가에 쓰일 수 있다.','정답(맞지 않는 검사). TCD.',
   stem='28세 여자환자가 1주일 전부터 좌측 팔과 다리의 감각 및 운동기능의 마비증세를 보여 내원하였다. 1년전에 optic neuritis진단을 받아 치료를 받은 과거력이 있다. 3개월 전에는 좌측 다리 마비증세를 보였으나 곧 회복되었다고 한다. 이 환자의 진단을 위한 검사로 맞지 않는 것은?',
   tail='야마 2019 객48 · 학습지 96–97쪽 원문대조 (복원자: 정확한 문제는 기억 안 나나 보기·정답은 확실)'),
 'q-012':Q(1,'딸꾹질·오심(area postrema) + LETM + 이후 양측 시신경염(P100 지연) → NMOSD → NMO-IgG(AQP4-IgG) 검사 (오선영 교수님 티야).',
   '정답. NMO-IgG.','anti-Hu: 부종양성 뇌염/감각신경병.','OCB: MS.','anti-GQ1b: Miller Fisher syndrome.','MBP: MS의 T cell reactivity 대상.'),
 'q-013':Q(2,'MS 면역병리: CSF의 MBP 반응 T cell 증가, perivascular lymphocyte infiltration, OCB, TNF-α·NO·MMP 방출. B세포가 T세포보다 더 중요하다는 근거는 없다.',
   '맞는 설명.','정답(틀린 설명).','맞는 설명.','맞는 설명.','맞는 설명.'),
 'q-014':Q(5,MCD,*mcd),
 'q-015':Q(5,TDX,'조영증강 brain MRI: 핵심 검사.','CSF OCB: 진단 보조.','Evoked potential(VEP): 시신경 평가.','안저촬영: 시신경염 평가에 쓰일 수 있다.','정답(맞지 않는 검사). TCD.'),
 'q-016':Q(4,'반복 발병(시신경염, 상하지마비, 감각이상) → MS. 복원자 해설: 시신경 침범(visual)은 favorable prognosis 인자로 예후 결정에 영향. 원문 3번 선지는 복원 실패.',
   'MS는 CNS 탈수초 질환. Schwann cell은 말초.','최소 2번의 attack과 2곳 이상의 병변(DIS·DIT)이 필요.','(원문 선지 복원 실패)','정답(복원자 해설 기준).','AQP4 항체는 NMO 관련.',
   choices=['Schwann cell을 침범하는 탈수초 질환이다.','이 질환의 진단은 1번의 증상과 2군데 이상에서 발견된다면 가능하다.','(원문 선지 복원 실패)','시신경염 동반이 예후결정에 영향을 미친다.','AQP4(Aquaporin4)의 항체의 존재가 병의 진행과정과 치료에 영향을 줄 수 있다.'],
   tail='야마 2016 객9 · 학습지 99–100쪽 원문대조',caveat='3번 선지 원문 복원 실패'),
 'q-017':Q(3,'MS 진단: CSF(oligoclonal IgG band, IgG index)와 evoked potential(VEP)을 시행. 원문 4번 선지는 복원 실패.',
   'MS는 CNS 탈수초 질환.','한 번의 증상과 영상으로는 진단이 충분하지 않다(DIS·DIT).','정답.','(원문 선지 복원 실패)','AQP4 항체는 NMO 관련.',
   choices=['말초신경계를 흔히 침범하는 탈수초 질환이다.','이 질환의 진단이 한 번의 증상발현과 영상검사로 가능하다.','진단을 위해 뇌척수액 검사와 시신경 유발전위 검사를 시행한다.','(원문 선지 복원 실패)','AQP4(Aquaporin4)의 항체의 존재가 병의 진행과정과 치료에 영향을 줄 수 있다.'],
   tail='야마 2015 객3 · 학습지 100–101쪽 원문대조',caveat='4번 선지 원문 복원 실패'),
 'q-018':Q(5,'Astrocyte: 세포외 이온환경 유지, 구조·대사 지지. Oligodendrocyte: CNS 수초 형성. Microglia: scavenging·phagocytosis. Schwann cell: 말초 수초. 기능 미상: satellite cell.',
   '말초 수초는 Schwann cell.','구조·대사 지지는 astrocyte.','scavenging·phagocytosis는 microglia.','microglia의 기능은 알려져 있다(탐식). 기능 미상은 satellite cell.','정답.',tail='야마 2015 객4 · 학습지 101–102쪽 원문대조'),
 'q-019':Q([1,3],'학습지 정답 1,3 (복원자 이동규). '+NMO_CR,*nmo_ex,stem=CASE_NMO,choices=NMO_CH,tail='야마 2014 객32 · 학습지 102쪽 원문대조 · 복수정답(2개)'),
 'q-020':Q(3,'MS: 중추 탈수초 질환. MS로의 위험인자로 MRI T2 소견이 중요. 예방은 IFN-β. 전형적 시신경염이 MS로 진행 가능성이 높고, 비전형은 NMO 쪽.',
   'MS는 중추를 침범.','AQP4는 NMO.','정답.','예방요법은 IFN-β.','비전형 시신경염은 NMO로 진행 가능성이 높다.'),
 'q-021':Q(5,'NMO: onset always with relapse, AQP4 항체 sensitivity 76%·specificity 94%, 재발 예방은 스테로이드·면역억제제, MS와는 다른 질환. 전형적 시신경염은 MS로 진행 가능성이 크다.',
   'NMO는 remitting 없이 재발로 경과. 85% RR은 MS.','specificity는 94%.','IFN-β는 MS 예방 치료.','현재는 완전히 다른 질환으로 본다.','정답.',tail='야마 2014 객39 · 학습지 103쪽 원문대조'),
 'q-022':Q([1,3],'학습지 정답 1,3 (복원자 정연택). '+NMO_CR,*nmo_ex,stem=CASE_NMO,choices=NMO_CH,tail='야마 2013 객49 · 학습지 103–104쪽 원문대조 · 복수정답(2개)'),
 'q-023':Q(1,'MS: 백인·여성·북위도(USA) 호발, 85% relapsing-remitting, McDonald 기준(DIS·DIT), 진단은 MRI·VEP·CSF, 치료는 IFN-β·GA. AQP4 검사는 NMO.',
   '정답(틀린 설명). AQP4는 NMO 검사.','맞는 설명.','맞는 설명.','맞는 설명.','맞는 설명.',
   stem='다음 중 틀린 것은? (복원 메모: 지문은 반 페이지 분량으로 MS의 특징을 설명하며, MR·CT 소견은 periventricular lesion이다. MS와 NMO의 차이를 묻는 문제.)',tail='야마 2013 객50 · 학습지 104쪽 원문대조 (지문 요약 복원)'),
 'q-024':Q(1,'반복 발병(시신경염, 상하지 마비) + 뇌 MRI → MS 재발. 기존 야마 답은 interferon-β였으나 이 문제 보기에 없어, 재발이므로 steroid로 복원(복원자 추정).',
   '정답(복원자 추정). 급성 재발 치료로 스테로이드.','항생제: 감염 아님.','항진균제: 무관.','Omega3: 치료 근거 없음.','Cholinergic drug: MG 등 치료.',
   choices=['Steroid agent','Antibiotics','Antifungal agent','Omega3','Cholinergic drug'],tail='야마 2012 객28 · 학습지 104–105쪽 원문대조',caveat='복원자 추정 정답 (해설 참고)'),
 'q-025':Q(2,'시신경염 + 상하지 마비 병력 + 뇌실 주위 판 → MS → 탈수초질환 치료 중 interferon-β.',
   '항생제: 감염 아님.','정답. Interferon-β.','항진균제: 무관.','항바이러스제: 무관.','Cholinergic drug: MG 치료.'),
}
