from common_stroke import *
C_ISCH4=['치료의 목적은 infarct core를 회복하는 것이다.','Anoxic depolarization 일어나는 곳이 penumbra이다.','경색 시 spreading depression을 통해 damage를 최소화한다.','가장 먼저 혈관성 부종이 발생하며 MRI의 DWI 신호가 증가된다.']
e_isch4=['틀림. 치료 목적은 회복 가능한 penumbra를 살리는 것이다. Infarct core는 비가역적이다.','틀림. Anoxic depolarization은 infarct core(쪽 threshold)에서 일어난다.','틀림. Spreading depression은 손상을 넓히는 병적 현상이다.','틀림. 세포성(cytotoxic) 부종이 먼저 생기며, 이때 DWI 신호가 증가한다.']
C_CBF5=['뇌혈류는 백질부가 회백질부에 비해 4배정도 많다.','뇌관류압(CPP)는 뇌혈류(CBF)와 뇌혈관저항(CVR)에 비례한다.']
e_cbf2=['틀림. 회백질(약 80 mL/100g/min)이 백질(약 20)의 4배이다.','틀림. CBF = CPP/CVR이다(CPP와 CBF의 위치가 바뀐 지문).']
C_CPP=['뇌관류압은 평균동맥압과 뇌혈관 저항과 관련 있다.','뇌관류압이 감소하면 뇌혈류가 증가하여 뇌혈액량을 일정수준으로 유지한다.','뇌관류압이 감소하면 바로 산소추출분획이 증가하여 보상한다.','뇌혈관은 동맥혈의 이산화탄소 분압에 민감하게 반응하지만 산소분압에는 영향받지 않는다.','신경세포가 활성화되면 신경전달물질이 분비되어 뇌혈류가 증가한다.']
e_cpp=['틀림. CPP = MAP − ICP(두개내압)이다.','틀림. CPP가 감소하면 CVR↓로 뇌혈액량(CBV)이 늘어 뇌혈류(CBF)가 유지된다(Stage I).','틀림. 먼저 CBV가 증가하고(Stage I), OEF 증가는 CBF가 떨어진 뒤(Stage II)이다.','틀림. 산소분압이 약 50 mmHg 이하로 낮아지면 뇌혈관이 반응한다.','정답. 신경 활성 → 신경전달물질 분비 → 뇌혈류 증가(neurovascular coupling).']
C_PEN=['뇌혈류가 10ml/100 이하이다.','전기적 기능이 살아있다.','이온펌프 기능과 세포막 투과율이 망가져 있다.','재관류 시 회복이 된다.','Collateral circulation이 잘 되는 부위이다.']
e_pen=['틀림. Penumbra는 약 10–15 mL/100g/min이다. 10 이하는 core.','틀림. 전기적 기능은 소실되어 있다.','틀림. 이온펌프 기능과 세포막 투과율은 보존되어 있다.','정답. 빠르게 재관류하면 회복된다(치료 목표).','틀림. 측부순환 영역(oligemia)에 대한 설명이다.']
SPECS={
 'q-002':Q(3,CBF,'틀림. CBF = CPP/CVR이다. CPP가 CBF와 CVR에 비례하는 것이 아니다.','틀림. 자동조절에서 CBF를 일정하게 유지하는 핵심은 뇌혈관저항(CVR)의 변화이다.','정답. PaCO2↑ → 혈관 이완 → CVR↓ → CBF↑.','틀림. 외상성 뇌손상에서는 자동조절 하한이 오른쪽으로 이동한다고 설명됨(복원자도 근거를 찾지 못함).','틀림. CPP가 감소하면 CVR↓·CBV↑가 먼저, 이어서 CBF↓, OEF↑ 순으로 변한다.',
   choices=['뇌관류압(CPP)은 뇌혈류(CBF)와 뇌혈관저항(CVR)에 비례한다.','뇌혈류 자동조절 능력을 통해 뇌혈류량을 일정하게 유지하는데 중요한 것은 뇌관류압이다.','동맥 내 이산화탄소 압력이 증가하면 혈관 이완과 뇌혈류 증가가 일어난다.','외상성 뇌손상 환자는 뇌혈류 자동조절능력 곡선의 기울기를 좌측으로 편향시킨다.','뇌관류압이 감소하면 뇌혈류, 뇌혈액량(CBV), 산소추출분획(OER)의 순서대로 변화된다.']),
 'q-003':Q(5,ISCH+' 복원자: 실제 시험에는 여러 장의 사진이 있었고, 가장 비슷한 사진을 첨부함.','틀림. 치료 목표는 infarct core의 확대를 막고 penumbra를 회복시키는 것이다.','틀림. ATP depletion은 penumbra와 infarct core의 경계(threshold)에서 일어난다.','틀림. 세포성 부종이 먼저 생기고, 1–2일 뒤 BBB가 무너지면서 혈관성 부종이 생긴다.','틀림. Spreading depression은 penumbra의 에너지 요구량을 급격히 늘려 손상을 키운다.','정답. 혈관 폐색이 진행되면 출혈성 경색과 폐쇄성 경색이 함께 나타날 수 있다.',
   choices=['치료의 주된 목적은 infarct core 부분을 회복시키는 것이다.','뇌혈류 저하로 ATP depletion이 일어난 부위로 penumbra라 한다.','초기에 혈관성 부종이 발생하고 시간이 지나면서 세포성 부종이 발생한다.','허혈성 손상 주위의 spreading depression은 주위로 손상을 방지하기 위함이다.','혈관 폐색이 진행되면 출혈성 뇌경색과 폐쇄성 뇌경색이 같이 나타날 수 있다.'],
   visual=vis('확산강조영상 (학습지 22쪽, 복원자가 첨부한 유사 사진)','s25_75.jpg')),
 'q-004':Q(4,'2021 객41과 같은 사진이 출제됨(선지는 다름). 수업 증례: 77세 MCA 경색 환자가 IAT 뒤 악화됨. 문제 사진의 고음영은 재관류 손상으로 BBB가 파괴되어 혈액이 새어 나온(extravasation) 부위이며, 부종이 진행되어 뇌실이 밀려 있다. 이후 ICP가 올라 개두 감압술을 받았다. '+ISCH,
   '틀림. 경색 주변의 염증 반응은 지연 손상(delayed injury)으로 조직 손상을 악화시킨다.','틀림. 고음영 부위는 재관류 손상으로 BBB가 파괴되어 extravasation된 곳이다. 자동조절이 유지되는 부위가 아니다.','틀림. 세포독성 부종은 초기(1–2일 이내)에 나타나고, 그 뒤에는 혈관성 부종이 나타난다.','정답. BBB 손상으로 혈청 단백이 새어 나와 혈관성 부종이 생겼다.','틀림. 이미 BBB가 손상되고 부종이 심한 상태이므로, 재관류보다 ICP를 낮추는 것이 우선이다.',
   choices=['뇌경색주변부에서나타나는 염증성 반응은 조직 손상을 보호하는 반응이다.','고밀도 음영을보이는 부위는 뇌혈류 자동조절능력이 유지되어있다.','허혈성 뇌손상후 1주일 정도 지나면서 나타난 세포독성 부종에 의한다','뇌혈관 장벽(blood-brain barrier) 손상에 의한 혈청 단백의 유리가 원인이다.','허혈성 뇌손상의범위를 최소화 하기 위해 혈관의 재개통이 필요하다.'],
   visual=vis('뇌 CT (학습지 23쪽)','s23_28.jpg'),extra=vis('수업 증례 경과 CT (학습지 24쪽 해설)','s21_41_series.jpg')),
 'q-005':Q(4,ISCH,'틀림(학습지 해설). 치료 목표는 infarct core의 확산을 막고 penumbra를 회복시키는 것이다.','틀림. Penumbra의 혈류는 약 10–18 mL/100g/min이다.','(선지 복원 실패)','정답. 급성기 초기에는 세포외액이 세포 안으로 이동해 세포성 부종이 생긴다.','틀림. 경색 직후에는 glutamate 등에 의한 excitotoxicity가 먼저이고, 그 뒤 peri-infarct depolarization → inflammation → apoptosis 순으로 진행한다.',
   choices=['치료의 주된 목적은 penumbra의 확산을 막는 것이다.','penumbra 영역은 8ml/100g/min이다.','(선지 복원 실패)','급성기 뇌경색 초기에 세포외액이 세포내액으로 이동하여 세포성 부종을 일으킨다.','경색이 발생한 직후 작용하는 기전은 염증이다.'],tail='야마 2022 객28 · 학습지 27쪽 원문대조'),
 'q-006':Q(2,GRAPH,*graph_exps,visual=GRAPH_VIS(),tail='야마 2020 객106 · 학습지 32–33쪽 원문대조'),
 'q-007':Q(5,ISCH,'틀림(학습지 해설). 허혈성 손상 치료의 주된 목적은 penumbra를 회복시키는 것이다.','틀림. Anoxic depolarization이 일어나는 곳은 infarct core이다.','틀림. Penumbra의 세포사는 제일 먼저 excitotoxicity로 일어나며, apoptosis는 그 뒤이다.','틀림. 세포외액이 세포 안으로 이동해 생기는 부종은 세포성(cytotoxic) 부종이다.','정답. 손상된 혈관에 혈류가 갑자기 돌아오면 터져서 출혈성 경색이 생긴다.',
   choices=['치료의 주된 목적은 penumbra 영역의 확대를 감소시키는 것이다.','뇌혈류 저하로 anoxic depolarization이 일어난 부위를 penumbra라 한다.','허혈이 발생한 후에 제일 먼저 세포고사(apoptosis)에 의해 세포사망이 일어난다.','급성기 뇌경색 초기에 세포외액이 세포내액으로 이동하여 혈관성 부종이 나타난다.','동맥이 막힌 부위의 뇌혈류가 회복되면 출혈성 병변이 발생할 수 있다.']),
 'q-008':Q(2,GRAPH,*graph_exps,visual=GRAPH_VIS(),tail='야마 2019 객51 · 학습지 36쪽 원문대조'),
 'q-009':Q(1,ABCD,*abcd_exps,caveat='학습지 정답 "①?" — 당뇨 정보가 없어 ABCD2 점수를 확정할 수 없다는 복원자 의견이 있음',
   choices=['ABCD2 score은 4점이다','CT에서 이상이 없었으므로 뇌졸중과는 관련이 없는 다른 질환이다.','1시간이내에 도착했으므로 정맥내 혈전용해제를 투여한다.','증상이 좋아졌으므로 동맥내 혈전제거술을 시행한다.','현제 큰이상은 없으므로 퇴원후 경과관찰한다?'],tail='야마 2019 객53 · 학습지 37–38쪽 원문대조'),
 'q-010':Q(2,GRAPH,*graph_exps,visual=GRAPH_VIS(),tail='야마 2018 객7 · 학습지 39쪽 원문대조'),
 'q-011':Q(5,ISCH,*e_isch4,'정답. 혈관 폐색이 진행되면 출혈성 경색과 폐쇄성 경색이 함께 생길 수 있다(수업 강조).',choices=C_ISCH4+['혈관폐색이 진행되면 출혈성 뇌경색과 폐쇄성 뇌경색이 같이 발생 할 수 있다.']),
 'q-012':Q(2,AF,'Dabigatran: 직접 트롬빈 억제제(DOAC)이므로 사용 가능.','정답. Cilostazol은 항혈소판제이다.','Apixaban: Xa 억제제(DOAC)이므로 사용 가능.','Warfarin: 항응고제이므로 사용 가능.','Rivaroxaban: Xa 억제제(DOAC)이므로 사용 가능.',
   stem='48세 남자가 입원 전날 실어증이 있다고 했으며, 입원 당일 검사하니 심방세동이 있었다. 추가 검사로 MRA에 환자의 증상의 원인이 되는 혈관의 이상소견이 있는 것 말고는 다른 이상 소견이 없었다. 다른 검사들에도 이상 소견은 없었다. 환자의 뇌경색의 2차적 예방으로 사용 가능한 약제가 아닌 것을 고르시오.',tail='야마 2018 객9 · 학습지 40쪽 원문대조'),
 'q-013':Q(4,'허혈의 원인: thrombosis(atherosclerosis, FMD, arteritis, dissection, hypercoagulopathy), embolism(좌심방·심실, artery-to-artery), systemic hypoperfusion(watershed/borderzone), venous thrombosis. TOAST의 SAO: 병변 <1.5 cm, 피질 증상 없음, HT·DM, 심인성 색전원 없음, 협착 <50%. 한국은 LAA와 SVO가 많다. Small vessel disease 병리: small vessel atherosclerosis, lipohyalinosis(fibrinoid necrosis), microaneurysm, arteriolosclerosis.',
   '틀림. Aneurysm은 허혈성 뇌졸중의 원인에 들어가지 않는다.','틀림. 작은동맥 폐색은 심인성 색전원이 없어야 한다.','틀림. 한국은 LAA·SVO가 CE보다 많다.','정답. Lipohyalinosis와 microaneurysm은 small vessel disease의 병리이다.','틀림(복원자: 확실히 틀린 지문).',
   caveat='발문 복원 실패(맞는 지문을 고르는 문제) · 선지 ③⑤ 복원 불완전',tail='야마 2017 객5 · 학습지 41–42쪽 원문대조'),
 'q-014':Q(5,CBF,*e_cbf2,'(선지 복원 실패)','틀림. CVR → CBF → OEF 순서로 변한다(Stage I–III).','정답. PaCO2↓ → 혈관수축 → CVR↑ → CBF↓.',
   choices=C_CBF5+['(선지 복원 실패)','뇌관류압이 떨어지면 뇌혈류 변화, 뇌혈액량(CBV), 산소추출분획(OER)의 순서로 떨어진다.','동맥내 이산화탄소 압력이 감소하면 혈관수축과, 뇌혈류 감소가 나타난다.'],tail='야마 2017 객6 · 학습지 42쪽 원문대조'),
 'q-015':Q(5,ISCH,*e_isch4,'정답. 허혈이 진행되면 단백질 합성↓ → hsp72 upregulation → lactic acidosis → ATP 고갈 단계에서 infarct core로 진행한다.',choices=C_ISCH4+['허혈이 진행되면서 단백질 합성이 감소하고 그에 따른 hsp72 upregulation이 일어난다.']),
 'q-016':Q(5,CBF,'틀림. CBF는 CPP에 비례하고 CVR에 반비례한다.','틀림. 혈관 저항은 혈액 점도와 혈관 길이에 비례하고, 혈관 직경(반지름⁴)에 반비례한다.','틀림. 자동조절은 뇌관류압이 아니라 혈류저항을 바꿔 뇌혈류를 일정하게 유지한다.','틀림. 제일 먼저 혈관이 확장(CVR↓)되어 뇌혈액량이 증가한다. CVR → CBF → OEF 순서.','정답.',
   choices=['뇌혈류(CBF)는 뇌관류압(CPP)와 뇌혈관 저항(CVR)에 정비례한다.','뇌혈관 저항(CVR)은 혈액 점도와 혈관길이, 혈관의 직경에 반비례한다.','뇌혈류 자동조절 능력은 뇌관류압을 변화시켜 뇌혈류량을 일정하게 유지한다.','뇌관류압이 떨어지면 제일먼저 혈관이 수축하여 뇌혈액량을 증가시킨다.','동맥 내 이산화탄소 압력이 감소하면 혈관수축과 뇌혈류 감소가 나타난다.'],tail='야마 2016 객6 · 학습지 44쪽 원문대조'),
 'q-017':Q(5,ISCH+' 시기별: acute injury(ischemic anoxia, energy failure, terminal depolarization) → subacute(spreading depression, ER dysfunction, mitochondrial insufficiency) → delayed(vasogenic edema, inflammation, apoptosis).',
   '틀림(학습지 해설). Penumbra를 최대한 회복시키는 것이 치료 목적이다.','틀림. ATP depletion은 penumbra와 infarct core의 threshold에서 일어난다.','틀림. Terminal depolarization은 acute injury에 속한다.','틀림. 세포성 부종이 먼저 생기며, 이때 DWI는 고신호이다.','정답. 혈관성 부종은 BBB가 무너진 뒤 혈청 단백이 새어 나오면서 생긴다.',
   choices=['치료의 주된 목적은 penumbra 영역의 확대를 감소시키는 것이다.','뇌혈류 저하로 ATP depletion이 일어나는 부위를 penumbra라 한다.','뇌경색 후 delayed injury에 관여하는 것은 termainal depolarization이다.','뇌경색 발생시 혈관성 부종이 먼저 발생하고 확산강조영상(DWI)에서 저신호강도로 보인다.','혈관성 부종은 혈관의 장벽이 손상된 후에 발생한다.'],tail='야마 2016 객7 · 학습지 45쪽 원문대조'),
 'q-018':Q(1,'같은 양상으로 반복되는 짧은 TIA(특히 일과성 단안 시야장애 amaurosis fugax)는 임박한 혈관 폐색, 특히 내경동맥(ICA) 폐색의 경고 신호이다. TIA 뒤 경색의 약 20%는 첫 발작 후 한 달 안에, 약 50%는 1년 안에 생긴다. ※ 이전 버전의 정답(②)은 학습지 정답(①)과 달라 수정함.',
   '정답. 반복되는 일과성 시야장애 → ICA 폐색의 경고 신호.','틀림. 척추동맥(후순환)은 어지럼·복시·운동실조 등이 전형적이다.','틀림. MCA도 편마비를 일으키지만, 반복되는 일과성 시야장애(amaurosis fugax)의 경고 신호는 특히 ICA이다.','틀림. 외경동맥은 뇌 실질을 공급하지 않는다.','틀림. 기저동맥은 후순환이다.',
   caveat='복원 불완전: "좌측마비와 우측시야장애"의 좌우가 원문과 다를 수 있음',tail='야마 2016 객6 · 학습지 45–46쪽 원문대조'),
 'q-019':Q(4,ISCH,'틀림. Infarct core는 이미 괴사된 조직이므로 치료 대상은 penumbra이다.','틀림(매해 틀린 선지). Anoxic depolarization은 경계나 infarct core 쪽이다.','틀림. Spreading depression은 infarct core에서 세포괴사가 일어날 때 나타나는 현상이다.','학습지 정답. 세포성 부종 때 DWI 신호가 증가한다(해설 근거).','틀림. 가장 먼저 생기는 것은 단백질 합성 장애이다.',
   caveat='학습지 정답은 ④이지만 선지 문구가 "혈관성 부종"으로 복원됨. 같은 문장은 2017·2018년에는 틀린 선지였고, 2013 객34 원문은 "Cytotoxic edema시 DWI 이상"임 → 복원 오기일 가능성',
   choices=['치료의 목적은 Infarct core를 회복하는데 있다.','Anoxic depolarization 일어나는 곳이 penumbra다','경색 시 spreading depression을 통해 damage를 최소화한다.','가장 먼저 혈관성 부종이 발생하며 MRI의 DWI 신호가 증가된다.','경색 시 ATP depletion이 가장 먼저 발생하여 Anaerobic glycolysis가 일어난다.']),
 'q-020':Q(3,'큰 혈관 동맥경화는 LDL trapping으로 시작 → 염증(NO↓, adhesion molecule↑). 소혈관 병변: microatheroma, junctional atheroma, mural atheroma. Arteriolosclerosis → 백질 손상(SIVD). Lipohyalinosis는 고혈압 환자에서 호발.',
   '틀림. LDL trapping으로 시작한다.','틀림. 염증 과정에서 NO는 감소하고 adhesion molecule이 증가한다.','정답.','틀림. 평활근이 섬유모세포로 대체되는 것은 맞지만, 허혈성 손상은 회색질이 아니라 백질(SIVD)에 생긴다.','틀림. Lipohyalinosis는 고혈압 환자에서 호발한다.',
   choices=['큰 혈관 동맥경화는 HDL의 산화로 시작된다.','동맥경화의 염증반응 과정에서 NO가 증가한다.','소혈관 동맥경화에는 microatheroma, junctional atheroma와 mural atheroma가 있다.','Arteriosclerosis는 평활근이 섬유모세포로 대체되어 회색질에 허혈성 손상을 일으켜 치매를 유발한다.','Lipohyalinosis(fibrinoid necrosis)는 주로 작은 혈관들에 발생하며 당뇨병 환자에서 호발한다.']),
 'q-021':Q(5,'Primary hemostasis: 혈소판이 GP Ib를 통해 vWF에 결합 → GP Ib는 혈소판 부착을 매개(응고 촉진). 항응고 쪽: heparin-like molecule → antithrombin III 활성화(thrombin, Xa, IXa 불활성화), thrombomodulin → thrombin을 protein C를 활성화하는 항응고물질로 바꿈, protein C → Va·VIIIa 불활성화. ※ 이전 버전의 정답(④)은 학습지 정답(⑤)과 달라 수정함.',
   '항응고: 내피의 thrombomodulin이 thrombin을 protein C 활성화 물질로 바꾼다.','항응고: antithrombin III를 활성화한다.','내피의 thrombin 결합 부위로, 학습지 해설에서는 따로 다루지 않음.','항응고: Va·VIIIa를 불활성화한다.','정답. GP Ib는 혈소판–vWF 부착을 매개한다(응고 촉진).',
   caveat='학습지 정답 ⑤를 따름. 혈소판의 thrombin receptor(PAR)는 응고 촉진이라 ③도 논란 여지 있음',tail='야마 2014 객20 · 학습지 51–52쪽 원문대조'),
 'q-022':Q(3,'우측 근위부 ICA가 완전 폐쇄되면 ① 반대쪽 ICA → 전대뇌동맥 → 전교통동맥(a) → 우측 ACA/MCA, ② 기저동맥 → 후대뇌동맥 → 후교통동맥(c) → 우측 ICA 원위부로 측부순환이 생긴다. (그 밖에 ECA → 안동맥 경로)',
   '틀림. b는 후교통동맥이 아니다.','틀림. b는 전교통동맥이 아니다.','정답. a = anterior communicating a., c = posterior communicating a.','틀림. a는 후교통동맥이 아니다.',
   choices=['a – anterior communicating artery, b – posterior communicating artery','b – anterior communicating artery, c – posterior communicating artery','a – anterior communicating artery, c – posterior communicating artery','b – anterior communicating artery, a – posterior communicating artery'],
   visual=vis('Willis 환 그림 (학습지 52쪽)','s13_30.jpg'),tail='야마 2013 객30 · 학습지 52쪽 원문대조'),
 'q-023':Q(5,CBF,*e_cpp,choices=C_CPP,tail='야마 2013 객32 · 학습지 53쪽 원문대조'),
 'q-024':Q(4,ISCH+' ※ 이전 버전의 ④⑤ 선지는 다른 문항 해설이 섞여 들어가 있어 원문으로 복원함.',
   '틀림. Infarct core는 비가역적 손상이므로 penumbra가 치료 대상이다.','틀림(강의록 기준). Anoxic depolarization은 infarct core에서 일어난다.','틀림. Spreading depression은 infarct core에서 세포괴사가 일어날 때 나타나는 현상이다.','정답. 세포성 부종일 때 DWI에서 이상소견(고신호)을 보인다.','틀림. 가장 먼저 생기는 것은 단백질 합성 장애이다.',
   choices=['치료의 목적은 Infarct core를 회복하는데 있다.','Anoxic depolarization 일어나는 곳이 penumbra다.','경색 시 spreading depression을 통해 damage를 최소화한다.','Cytotoxic edema시에 DWI에서 비정상소견을 보임.','경색 시 ATP depletion이 가장 먼저 발생하여 Anaerobic glycolysis가 일어난다.'],tail='야마 2013 객34 · 학습지 54–55쪽 원문대조'),
 'q-025':Q(4,PEN,*e_pen,choices=C_PEN,tail='야마 2013 객33 · 학습지 56쪽 원문대조'),
 'q-026':Q(4,PEN,*e_pen,choices=C_PEN),
 'q-027':Q(3,'뇌허혈의 경과 분류: TIA(24시간 안에 후유증 없이 회복, 대개 2–30분), RIND(24시간 넘게 지속되지만 3주 안에 회복), complete infarct(3주가 지나도 회복되지 않음), progressive stroke(stroke in evolution: 경동맥은 1–2일, 척추-기저동맥은 약 3일에 걸쳐 점차·계단식으로 악화).',
   '틀림. 24시간 안에 회복된다.','틀림. 24시간 넘게 지속되지만 3주 안에 회복된다.','정답. 치료 중에도 계단식으로 악화 → progressive stroke.','틀림. 3주가 지나도 회복되지 않는 경우이다.','(선지 복원 실패)'),
 'q-028':Q(5,CBF,*e_cpp,subj=False,choices=C_CPP,tail='야마 2012 주23 · 학습지 57쪽 원문대조 (학습지에 5지선다 원문·정답 ⑤ 확인)'),
 'q-029':Q(2,'Heparin: antithrombin III 활성화 → thrombin 불활성화. Warfarin(Coumadin): 비타민 K 의존성 carboxylase 억제, 심방세동에서 INR 2–3 유지. Thienopyridine: ADP 수용체 억제 → ADP 의존성 혈소판 응집 억제. Aspirin: 비가역적 COX 억제, 저용량(75–162 mg/일)으로 항혈소판 작용. ※ 이전 버전의 ④⑤ 선지는 다른 문항 해설이 섞여 들어가 있어 원문으로 복원함.',
   '틀림(학습지 해설). COX 억제는 맞지만 뒷문장 복원이 불완전해 오답으로 처리됨.','정답. 저용량 아스피린이 항혈소판 작용을 한다.','틀림. 와파린은 비타민 K 의존 응고인자에 작용한다.','틀림. INR 2–3으로 유지한다.','틀림. 헤파린은 antithrombin III를 활성화하며, ADP 억제는 thienopyridine의 작용이다.',
   choices=['아스피린은 cycloxygenase를 억제','아스피린은 저농도에서 항혈소판 작용을 한다.','와파린은 비타민E 관련 응고인자에 작용','심질환있을때 와파린은 INR4 이상으로','헤파린은 antithrombin Ⅲ로 ADP를 억제한다.'],tail='야마 2012 객25 · 학습지 58–59쪽 원문대조'),
 'q-030':Q(2,'학습지 해설(복원자 박정수): penumbra의 회생이 제한되는 이유는 peri-infarct depolarization 때문이며, 이는 반복적인 조직 저산소증을 일으킨다. Spreading depression은 core에서 시작해 penumbra 세포를 죽이는 쪽으로 작용한다. Vasogenic edema에서는 DWI가 pseudonormalization(정상처럼 보임)되고 T2 고신호이다. 순서: 단백 합성 감소 → hsp72 발현 → 당 이용 감소 → lactic acidosis → ATP depletion. ※ 이전 버전 정답(③)은 학습지 정답(②)과 달라 수정함.',
   '틀림. Core는 비가역적이므로 penumbra를 회복시켜 손상을 최소화하는 것이 목표이다.','학습지 정답. 복원자는 peri-infarct depolarization을 근거로 들었다.','틀림. Spreading depression은 penumbra 세포를 죽이는 쪽으로 작용한다.','틀림. Vasogenic edema에서는 DWI가 pseudonormalization되어 이상소견이 보이지 않는다.','틀림으로 처리됨(복원자도 순서 해석이 불확실하다고 적음).',
   caveat='학습지 정답 ②는 복원자도 불확실하다고 적었고, 다른 해에는 "anoxic depolarization = penumbra"가 틀린 선지였음 → 동기들과 확인 권장',
   choices=['치료의 목표는 infarction core를 회복하여 brain 조직의 정상화에 있다.','Anoxic depolarization이 일어나는 곳을 penumbra라고 한다.','경색 후에 나타나는 spreading depression은 뇌조직의 회복을 위한 과정이다.','Vasogenic edema가 나타날 경우, DWI에서 이상소견이 나타난다.','가장 먼저 protein synthesis 장애가 일어나고, anaerobic glycolysis가 일어난다.'],tail='야마 2012 객26 · 학습지 59쪽 원문대조'),
 'q-031':Q(4,'Willis 고리와 주위 구조(학습지 해설): 전대뇌동맥, 전교통동맥, 내경동맥, 중대뇌동맥, 후교통동맥, 후대뇌동맥. 기저동맥은 고리에 직접 참여하지 않는다.',
   '포함(학습지 해설 기준). 엄밀히는 MCA가 ICA의 종말분지라 고리 밖으로 보기도 한다.','포함.','포함.','정답. 기저동맥은 Willis 고리에 직접 참여하지 않는다.',tail='야마 2012 객27 · 학습지 59–60쪽 원문대조'),
 'q-032':Q(3,'자동조절(autoregulation): 화학적 자동조절(동맥 내 CO2 분압, 세포외 산도, 대사산물)과 자율성 자동조절(뇌관류압 60–160 mmHg)로 나뉜다. 뇌는 체중의 약 2%이고, 뇌혈류는 심박출량의 약 15%이다.',
   '틀림. 정상 뇌산소소모량이 약 3.3–3.5 mL/100g/min이므로 4.5는 혼수 기준이 아니다(복원자도 근거를 찾지 못함).','틀림. CPP가 감소하면 CBV가 늘어 CBF가 유지된다.','정답.','틀림. 뇌혈류는 심박출량의 약 15%이다.','틀림. 반대이다. CO2 분압에 민감하게 반응하고, 산소분압은 크게 떨어져야 영향을 준다.',
   choices=['뇌산소 소모량이 4.5ml/100g/min으로 감소되면 혼수에 이른다.','뇌관류압이 감소하면 뇌혈류가 증가하여 뇌혈액량을 일정수준으로 유지한다.','자율성 자동조절 기능은 뇌관류압이 60mmHg에서 160mmHg 사이에서 작동한다.','성인의 뇌는 체중의 2-2.5%를 차지하며, 뇌혈류는 심장 박출량의 30-35%를 차지한다.','동맥혈의 산소분압은 미세한 변화라도 직접적으로 뇌혈관에 영향을 미치나, 이산화탄소분압은 크게 영향을 주지 않는다.']),
 'q-033':Q(1,ISCH,'정답. 단백 합성 감소 → hsp72 → 당 이용 감소 → lactic acidosis → ATP depletion.','틀림. Penumbra를 살리는 것이 목적이다.','틀림. ATP depletion이 일어난 부위는 infarct core이다.','틀림. 직후에는 excitotoxicity가 먼저 작용하고, inflammation은 지연 손상(delayed injury)이다.','틀림. 초기에는 세포성 부종이다. 후기 혈관성 부종에서는 DWI가 pseudonormalization된다.',
   choices=['뇌혈류가 감소하면 단백질 합성이 가장 먼저 손상된다.','치료의 주된 목적은 infarction core를 회복하는데 있다','혈류가 저하하여 ATP depletion이 일어난 부위를 penumbra라 한다.','경색의 진행과정 중 경색이 발생한 직후 작용하는 기전은 inflammation이다.','초기에는 혈관성 부종이 발생하여 MRI상 확산강조영상(DWI)에서 이상을 보인다.']),
 'q-034':Q(5,PEN,'틀림. 전기적 기능은 소실되어 있다.','틀림. 재관류 시 회복된다(치료 목표).','틀림. 약 10–15 mL/100g/min이다.','틀림. 측부순환 영역에 대한 설명이다.','정답. 이온펌프 기능과 세포막 투과율은 보존되어 있다.',
   choices=['전기적 기능이 살아 있다.','재관류시 회복이 되지 않는다.','뇌혈류가 10ml/100 이하이다.','Collateral circulation이 잘 되는 부위이다.','이온 펌프 기능과 세포막의 투과율은 보전되어 있다.'],tail='야마 2011 객45 · 학습지 62–63쪽 원문대조'),
}
INSERTS=[('q-017',dict(meta='야마 · 0/0 · 야마 2016 객8 · 학습지 45쪽 원문대조 (앱에서 누락되어 추가)',
  stem='다음 중 다른 것과 성격이 다른 작용을 하는 것은?',
  choices=['tPA (tissue plasminogen activator)','Antithrombin Ⅲ','Thromboxan A2','Protein C','PGI2, NO'],ans=[3],
  basis='Thromboxane A2만 응고(혈소판 동원, fibrinogen 결합 강화)를 촉진하고, 나머지는 모두 항응고·섬유소용해 쪽이다.',
  exps=['항응고: plasmin을 활성화한다.','항응고: thrombin을 불활성화한다.','정답. 응고 촉진: 혈소판을 동원하고 fibrinogen 결합을 강화한다.','항응고: Va·VIIIa를 불활성화한다.','항응고: 혈소판 응집을 억제한다.']))]
