from fixlib import Q,S
MD='Myotonic dystrophy: 성인 MD 중 가장 흔함, 19번 염색체 CTG repeat expansion, AD with anticipation, cranial·distal 근육 위약, percussion myotonia, 백내장·앞머리 탈모·고환위축·심장전도장애·당뇨, 근본 치료 없음(대증), EMG myotonic discharge, DNA test로 확진.'
PM='Polymyositis: 30~60세 여성, 사지 근위부·몸통 대칭 위약, 피부병소 없음, shoulder·pelvic girdle 가장 심함, 외안근·얼굴 침범 거의 없음. DM: PM + 피부병소(Gottron, heliotrope, shawl). IBM: 50세 이상 남성, focal·distal·비대칭. 진단: 근위 위약, CK↑, EMG 근병증, 생검 lymphocytic inflammation. 치료: 스테로이드.'
CASE_MD='21세 남자가 어릴 적부터 서서히 더 진행하는 근위약감을 주소로 내원하였다. 환자는 달리기, 등산, 수영 등을 하지 못하였고 최근에는 계단 오르기도 힘들어졌다. 얼굴과 목 근육이 위축되고 대머리였으며, 시력저하를 보여 방문한 안과에서 백내장 진단을 받았다고 하였다. 내원당시 당이 많이 상승되어 있었다(공복 Glucose 210). 신경학적 검사 상 족부하수(foot drop)가 관찰되었으며 다음과 같은 신경학적 소견이 관찰되었다.'
SPECS={
 'q-001':Q(3,'진행성 대칭 근위부 위약 + 근육통 + CK 20배 + EMG 근병증·자발전위 → 염증성 근병증(PM/면역매개 괴사성 근병증 등) 의심 → muscle MRI 후 생검 부위 선정·근생검 등으로 평가.',
   'AChR Ab: MG 검사. 근병증 양상과 맞지 않다.','Brain MRI: 중추 병변 소견이 없다.','정답.','LP: 근병증 평가 검사가 아니다.','CK 20배 상승 진행성 위약은 관찰할 상황이 아니다.'),
 'q-002':Q(3,'Associated malignancy may be more common in DM. IBM은 50세 이상 가장 흔한 염증성 근병증. 치료반응은 근력 호전과 CK 감소로 평가.',
   '맞는 설명.','맞는 설명. 감별에 근생검이 유효.','정답(틀린 설명). 암 위험은 DM에서 더 높다.','맞는 설명.','맞는 설명.'),
 'q-003':Q(1,PM,'정답. PM.','DM은 피부병소가 있어야 한다.','IBM은 고령 남성, 비대칭·원위부.','JDM은 소아이며 피부병소가 있다.','Myotonic dystrophy는 원위부·안면 위약, percussion myotonia.',stem='38세 여성이 서서히 대칭적으로 진행된 몸통과 사지근위부의 근쇠약을 보임. 특히 shoulder, pelvic girdle 위약이 심함. 피부병소는 없었고 가족력도 없었다. 가장 가능성이 높은 진단은?'),
 'q-004':Q(3,MD,'CTG 반복서열이 증가(expansion)한다.','근본 치료가 없고 대증치료.','정답. Percussion myotonia.','myokymia가 아니라 myotonic discharge.','심장 전도장애가 생긴다.'),
 'q-005':Q(3,'반복성 이완성 마비, 외안근·연수근·호흡근 정상, 흥분·운동·과식(탄수화물) 후 악화, 가족력(AD) → 저칼륨 주기마비(수업 티야).',
   '안데르센병(Andersen-Tawil): 주기마비 + 부정맥 + 이형성.','선천성 근긴장증: chloride channel, 근긴장.','정답. 저칼륨 주기마비.','neuromyotonia: 말초신경 과흥분.','선천성 근무력증: 신경근접합부 유전 질환.'),
 'q-006':Q([2,4],'학습지 정답 나, 라 (복원자 이승환). '+MD+' 가(Type I 괴사·공포화)는 근생검 특이소견이 아니고, 다(IVIG·스테로이드)는 틀림(대증치료).',
   '근생검의 type I 괴사·공포화는 특징적 소견이 아니다.','정답. AD, CTG repeat expansion.','IVIG·스테로이드로 치료되지 않는다.','정답. 성인 MD 중 가장 흔하다.',
   stem=CASE_MD+' 이 질환에 대한 설명으로 맞는 것을 모두 고르시오.',choices=['근육 생검에서 Type I 세포의 Necrosis와 Vacuolation이 관찰된다','이 병은 상염색체 우성이며 CTG Repeat과 Expansion이 관찰된다','IVIG 혹은 스테로이드 주사를 통해서 치료가 가능하다','성인에게서 나타나는 Muscular Dystrophy 질환 중 가장 흔한 질환이다'],
   tail='야마 2017 객26 · 학습지 118–119쪽 원문대조 · 복수정답(나,라)'),
 'q-007':Q(3,'DM 진단기준: 근위 위약, CK↑, EMG 근병증, 생검 lymphocytic inflammation, 피부발진. 동반 악성종양 검사 필요. 치료는 스테로이드. RNS는 MG·LEMS 진단 검사.',
   '맞는 설명.','맞는 설명.','정답(틀린 설명). RNS는 필수가 아니다.','맞는 설명.','맞는 설명.',
   stem='Dermatomyositis 문제 (원 지문은 너무 길어 복원 실패 — 선지 기준으로 풀이) 다음 중 옳지 않은 것은?',caveat='지문 복원 실패 · 선지는 원문'),
 'q-008':S('Dermatomyositis','근위부 위약 + 목근육 위약 + 눈 증상·일중변동 없음 + 피부병변(Gottron sign, heliotrope rash, shawl sign) + CK 상승 → DM.',tail='야마 2016 주19 · 학습지 122쪽'),
 'q-009':S('X-linked recessive (Duchenne muscular dystrophy)','운동 발달 지연 + 종아리 가성비대 + 근위부 위약 + CK 25,522(MM 100%) → Duchenne MD. dystrophin 결핍, X-linked recessive.',tail='야마 2016 주30 · 학습지 122–123쪽'),
 'q-010':Q(3,'피곤·운동 시 악화, 오후 악화, 휴식·아침 호전되는 안검하수·복시 → MG. 약물(aminoglycoside, β-blocker 등)로 악화될 수 있다.',
   'Tensilon(edrophonium)은 증상을 호전시킨다.','뇌간 청각 유발 전위는 MG 진단과 무관.','정답.','Chest CT는 흉선종 확인용이지 진단 검사가 아니다.','동공은 정상, 통증 없음.',tail='야마 2015 객1 · 학습지 123쪽 원문대조'),
 'q-011':dict(keep_excluded=True,choices=['(원문 보기 복원 실패 — 해설의 주기마비 요약 참고)'],ans=[1],
   basis='복원자가 문항·보기를 복원하지 못했다("주기마비에 대해 틀린 보기를 고르는 문제", 양태호 교수님 강의록의 굵은 글씨가 보기였던 것으로 기억). 주기마비 요약: 일차 — 고칼륨(sodium channel 점돌연변이), 저칼륨(calcium channel가 가장 흔함, sodium channel). 이차 — 갑상선중독성 주기마비(20~40대 동양 남성, 저칼륨, 이완성 하지 마비, 근위부, 정신·감각·안구·호흡 보존, DTR 감소).',
   exps=['보기 복원 실패'],tail='야마 2015 객20 · 학습지 125쪽 (보기 복원 실패)'),
 'q-012':Q(5,MD+' multisystemic disease이므로 "근육만 침범"은 틀림.',
   '맞는 설명.','맞는 설명(anticipation).','맞는 설명.','맞는 설명.','정답(틀린 설명).',
   stem='(원 지문 복원 실패) 37세 남자. 주먹쥐기근긴장증이 언급되면서, myotonic dystrophy에 대한 설명이었다. 다음 중 틀린 것은?',caveat='지문 복원 실패 · 선지는 원문'),
 'q-013':Q(1,PM+' 서서히 진행, 근위부, 피부병소 없음, 외안근·얼굴 보존, CK↑, EMG 근병증, lymphocytic inflammation → PM.',
   '정답. PM.','DM은 피부병소가 있다.','IBM은 focal·distal·비대칭.','Myotonic dystrophy는 cranial·distal.','MG는 안구 증상·일중변동.'),
 'q-014':Q(2,PM+' 피부 정상 + 근위부(의자에서 일어나기, 손 올리기) 위약 → PM.','DM은 피부병변이 있다.','정답. PM.','IBM(오기 IMB): 고령, 원위·비대칭.','PMD(진행성 근이영양증): 유전·소아 발병.','MS: 중추 탈수초 질환.',tail='야마 2014 객58 · 학습지 126쪽 원문대조'),
 'q-015':Q(2,'근위부 위약 + 피부병변 → DM. 악성종양(특히 DM, 40세 이상)에 대한 평가 필요.',
   'CK는 상승한다.','정답.','피부병변이 있으므로 DM.','근위부부터 위약.','근생검은 진단기준(lymphocytic inflammation).',tail='야마 2013 객16 · 학습지 128쪽 원문대조'),
 'q-016':Q([2,4],'학습지 정답 ②④ (복원자 이동연). 상염색체 우성(성염색체 아님), 원위부부터 시작. 시험에서는 "하나만 고르라"고 했으나 답이 두 개로 해설됨(12년 객36과 동일).',
   '맞는 설명.','정답(틀린 설명). 상염색체 우성.','맞는 설명(anticipation).','정답(틀린 설명). 원위부부터 시작.','맞는 설명.',tail='야마 2013 객17 · 학습지 129쪽 원문대조 · 복수정답(②④)'),
 'q-017':Q(4,'pyridostigmine은 면역조절 효과 없음, CCB·aminoglycoside는 MG 악화, steroid는 적절한 치료, chest CT로 흉선종 확인 필수.',
   'pyridostigmine은 전신형 진행을 억제하지 못한다.','CCB는 MG를 악화시킨다.','steroid는 적절한 치료이다.','정답.','aminoglycoside는 MG를 악화시킨다.',tail='야마 2012 객33 · 학습지 129쪽 원문대조'),
 'q-018':Q(3,'Duchenne MD: X-linked recessive, dystrophin 결핍, 5세 이전 발병, 하지 근위부부터 시작, Gower sign, 종아리 가성비대. Becker가 더 늦게 발병·느리게 진행.',
   'X-linked recessive이다.','Becker가 더 늦게 발병·느리게 진행.','정답. dystrophin 결핍.','myotonic dystrophy 설명.','upper legs·pelvis·upper arms에서 시작.',
   choices=['Duchenne muscular dystrophy는 Autosomal dominant genetic disorder이다.','Becker muscular dystrophy와 비슷한 임상 양상을 가지지만 Duchenne 근이영양증이 더 늦게 발병하고 더 느리게 진행하는 특징이 있다.','세포막을 유지하는 Dystrophin 단백 생성이 되지 않아 발병한다.','성인에서 발생하는 가장 흔한 근이영양증으로 DNA 염기중 CTG 반복염기서열의 증가로 발생한다.','진행성 근위약이 가장 먼저 안근육, 얼굴, 어깨, 상지에서 시작하는 특징이 있다.'],
   tail='야마 2012 객34 · 학습지 130쪽 원문대조'),
 'q-019':Q([2,4],'학습지 정답 ②④ (복원자 윤진희). 상염색체 우성(성염색체 아님), 원위부부터 시작.',
   '맞는 설명.','정답(틀린 설명). 상염색체 우성.','맞는 설명.','정답(틀린 설명). 원위부부터 시작.','맞는 설명.',tail='야마 2012 객36 · 학습지 131쪽 원문대조 · 복수정답(②④)'),
 'q-020':Q(5,'피곤·운동 시 악화, 오후 악화, 휴식·아침 호전 → MG. 흉선종 확인에 chest CT 필수, 동공 정상·무통성, Tensilon은 증상 호전.',
   'Chest CT는 흉선종 확인에 필수.','뇌간 청각 유발 전위는 무관.','동공 정상, 통증 없음.','Tensilon은 증상을 호전시킨다.','정답.',
   stem='32세 여자가 안검하수와 복시 증상이 간헐적으로 발생하여 내원하였다. 증상은 피곤하거나 심한 운동시에 나타났고, 오후가 되면 악화되었고, 휴식을 취하거나 아침 기상 시에는 호전되었다. 이 질환에 대한 다음 설명 중 옳은 것은?',tail='야마 2011 객5 · 학습지 131–132쪽 원문대조'),
 'q-021':Q(1,MD+' 근본 치료가 없으므로 면역글로불린으로 회복되지 않는다.',
   '정답(틀린 설명).','맞는 설명. myotonic discharge.','맞는 설명.','맞는 설명. multisystemic.','맞는 설명.',
   stem='21세 남자가 어릴적부터 서서히 더 진행하는 근위약감을 주소로 내원하였다. 환자는 달리기, 등산, 수영 등을 하지 못하였고 최근에는 계단 오르기도 힘들어졌다. 얼굴과 목 근육이 위축되고 대머리(baldness)였으며 (사진) 시력저하를 보여 방문한 안과에서 백내장 진단을 받았다고 하였다. 내원당시 당이 많이 상승되어 있었다(공복 glucose 210). 신경학적 검사상 족부하수(foot drop)가 관찰되었으며 다음과 같은 신경학적 소견이 관찰되었다(비디오). 이 질환에 대한 설명으로 맞지 않는 것은?',
   choices=['면역글로불린 주사 치료로서 회복이 가능하다.','근전도 검사상 특징적인 Myotonia가 관찰된다.','성인에서 관찰되는 가장 흔한 형태의 Muscular dystrophy이다.','근육 이외의 심장, 소화기관, 눈, 갑상선 등 다양한 기관의 이환을 특징으로 한다.','유전자 검사로 확진할 수 있으며(DNA test), 상염색체 우성유전을 따르고, CTG repeat expansion에 의한다.'],
   tail='야마 2011 객8 · 학습지 134쪽 원문대조'),
}
