from common_stroke import *
TPA='급성 허혈성 뇌졸중 치료의 기본은 IV tPA(4.5시간 이내)이다. IV tPA를 쓸 수 없는 경우: 4.5시간 초과, NIHSS 25점 이상, 자발성 뇌출혈 과거력 등. 이때 대혈관 폐색이면 동맥 내 혈전제거술(IA thrombectomy)을 시행한다.'
C_ABCD=['ABCD2 score는 4점이다.','CT에서 이상이 없었으므로 뇌졸중과는 관련이 없는 다른 질환이다.','1시간 내에 도착했으므로 정맥 혈전용해제를 사용한다.','증상이 좋아졌으므로 동맥 혈전제거술을 실시한다.','큰 이상이 없으므로 퇴원 후 경과관찰한다.']
C_LMI=['Vestibular neuropathy - vestibular nucleus','Pain, temperature deficit - spinothalamic tract','Hoarseness - nucleus ambigus','Hiccup - nucleus tractus solitarius','Limb ataxia - Spinocerebellar tract']
LMI_STEM_E=['틀림. MCA 병변은 피질 증상을 보이며 교차성 감각장애·Horner를 설명하지 못한다.','틀림. 시상 병변은 반대쪽 얼굴과 몸에 같은 쪽 감각장애를 일으킨다.','틀림. Paramedian(medial) 교뇌 병변 → 반대측 편마비가 주 증상이다.','틀림. AICA(lateral pontine)는 안면마비·청력소실이 특징이고, nucleus ambiguus 증상은 없다.','정답. 같은 쪽(좌) 얼굴 + 반대쪽(우) 몸 통각 저하, Horner, 연하곤란·쉰 목소리, 딸꾹질 → 좌측 lateral medulla(vertebral a.).']
def af(names,wrong,extra=''):
  cls={'apixaban':'Xa 억제제(DOAC)','rivaroxaban':'Xa 억제제(DOAC)','ribaroxaban':'Xa 억제제(DOAC)','edoxaban':'Xa 억제제(DOAC)','dabigatran':'직접 트롬빈 억제제(DOAC)','warfarin':'항응고제','wafarin':'항응고제','aspirin':'항혈소판제','cilostazol':'항혈소판제','cliostazol':'항혈소판제','triflusal':'항혈소판제','statin':'LDL을 낮추는 약'}
  return [('정답. ' if k==wrong else '')+f'{n}: {cls[n.lower()]}'+('.' if k==wrong else (' — 부적합.' if cls[n.lower()] in ('항혈소판제','LDL을 낮추는 약') else ' — 사용 가능.')) for k,n in enumerate(names,1)]
C_CBF_R=['뇌관류압이 감소하여 뇌혈관저항이 증가하였다','뇌혈관저항이 증가하여 뇌혈류량이 증가하였다','혈액 내 이산화탄소 분압의 증가로 뇌 혈관이 확장되었다.','혈액 내 산소분압의 감소로 혈압이 감소하였다.','통제 가능 범위를 벗어나 뇌혈관이 혈류 조절능을 상실하였다.']
HTN='만성 고혈압에서는 자동조절 범위(정상 MAP 약 70–150)가 오른쪽으로 이동한다. 그래서 고혈압 환자의 혈압을 갑자기 크게 낮추면(200/120 → 110/50) 자동조절 하한을 벗어나 CBF가 줄어 허혈 증상(구음장애, 좌측 위약)이 생긴다. 자동조절이 되는 상황이라면 CPP가 감소할 때 CVR도 감소해야 한다. (TBI에서는 하한이 오른쪽, CCB 복용 시 왼쪽으로 이동)'
e_htn=['틀림. 자동조절이 되면 CPP 감소 시 CVR은 감소해야 한다. 지금은 보상이 안 되는 상황이다.','틀림. CVR이 증가하면 CBF는 감소한다.','틀림. 이 상황은 이산화탄소와 관계없다.','틀림. 이 상황은 산소와 관계없다.','정답. 만성 고혈압으로 오른쪽으로 이동한 자동조절 범위를 벗어났다.']
ATH='동맥경화: LDL trapping(병변 시작) → 이후 염증. HDL은 apoA를 가진다. Turbulent flow가 있는 분지부(예: ACA/MCA 분지)에서 LDL trapping이 잘 일어나고, 층류(linear flow)의 shear stress는 내피를 보호한다. Angiotensin II와 homocysteine은 평활근 증식을 촉진 → ACE inhibitor는 동맥경화를 예방한다. Lipohyalinosis는 고혈압 환자의 작은 혈관에 호발한다.'
GER='MCA inferior division(좌측) 폐색: 구음장애, 반대측 반맹, 감각성 실어증, Gerstmann syndrome(좌측 inferior parietal lobule: agraphia, acalculia, finger agnosia, 좌우 구분 불가 ± alexia). 우측 병변에서는 confusion.'
VESSEL='혈관별 증상: MCA → 반대측 얼굴·팔 > 다리 위약·감각저하, 구음장애, 반대측 반맹, 병변 쪽으로 안구 편위, 우성반구면 실어증. ACA → 반대측 다리 > 팔 마비, 무의지(abulia)·느림·속삭임, 요실금, 파악반사. 갑작스러운 발생은 색전을 시사하며, 색전성 경색은 ICA가 곧장 이어지는 MCA 영역에 가장 흔하다.'
SPECS={
 'q-002':Q(1,TPA+' 이 환자: 1시간, NIHSS 19, 출혈 과거력 없음 → 금기가 없으므로 IV tPA.','정답. 발병 1시간, 금기 없음 → IV tPA.','틀림. 재관류 치료가 우선이다.','틀림. 스테로이드는 뇌경색 급성기 치료가 아니다.','틀림. 항응고제는 급성기 재관류 치료가 아니다.','틀림. 수액은 보조 치료이다.',
   visual=vis('혈관 CT (학습지 21쪽)','s25_23.jpg')),
 'q-003':Q(3,AF,*af(['Statin','Aspirin','Apixaban','Cliostazol','Triflusal'],3),visual=vis('뇌 MRI 확산강조영상 (학습지 21쪽)','s25_24.jpg'),caveat='복원자가 원 문제를 정확히 기억하지 못해 2023 객32를 참고해 복원함'),
 'q-004':Q(5,HTN,*e_htn,choices=['뇌관류압(CPP)이 감소되어 뇌혈관저항이 증가된 상황이다','뇌혈관의 저항이 증가되어 뇌 혈류는 증가된 상태이다.','동맥 내 이산화탄소분압이 감소되어 뇌 혈류가 감소된 상황이다','동맥 내 산소농도가 감소되어 뇌혈관저항(CVR)이 감소된 상황이다','평균 동맥혈압(MAP)이 뇌 혈류(CBF)의 자동 조절 능력 범위를 벗어 났다']),
 'q-005':Q(3,TOAST,'TOAST 분류(LAA).','TOAST 분류(CE).','정답. TOAST에 없다.','TOAST 분류(undetermined).','TOAST 분류(SAO).'),
 'q-006':Q(2,ABCD+' 이 문항은 ①이 3점으로 바뀌었고 ②가 새로 추가됨. 우측 편마비 + 언어장애 → 좌측 MCA 영역.',
   '틀림. 최소 4점이다.','정답. 우측 편마비와 실어 → 좌측 중대뇌동맥 영역.','틀림. TIA는 정맥 혈전용해제 대상이 아니다.','틀림. 동맥 혈전제거술 대상이 아니다.','틀림. 뇌졸중 전조이므로 바로 퇴원은 위험하다.',visual=None,
   choices=['ABCD2 score는 3점이다.','증상과 관련된 영역은 좌측 중대뇌동맥 영역일 가능성이 높다.','1시간 내에 도착했으므로 정맥 혈전용해제를 사용한다.','증상이 좋아졌으므로 동맥 혈전제거술을 실시한다.','큰 이상이 없으므로 퇴원 후 경과관찰한다.']),
 'q-007':Q(5,'Warfarin의 치료 범위는 PT-INR 2–3으로 좁다. INR 3.5–5: warfarin을 중단·감량 / 5–9: 중단하고, 출혈이 없으면 vitamin K는 불필요 / 9 초과: 중단하고 vitamin K 투여. 주요 출혈 시 vitamin K IV + FFP/PCC(강의록 별표 슬라이드).',
   '틀림. INR 4.3이고 출혈이 없으므로 vitamin K는 필요 없다.','틀림. IV vitamin K는 INR이 매우 높거나 주요 출혈이 있을 때 쓴다.','틀림. FFP는 주요 출혈 때 쓴다.','틀림. Protamine은 heparin의 해독제이다.','정답. 투약을 멈췄다가 감량해 다시 시작한다.',
   choices=['Vitamin K를 경구로 투여한다.','Vitamin K를 iv로 투여한다.','FFP를 투여한다.','Protamine sulfate를 투여한다.','이틀간 와파린투약을 멈추고 감량하여 다시 투여한다.']),
 'q-008':Q(4,AF,*af(['Rivaroxaban','Apixaban','Edoxaban','Cilostazol','Dabigatran'],4),visual=vis('뇌 MRI 확산강조영상 (학습지 25쪽)','s23_32.jpg')),
 'q-009':Q(2,TPA+' 이 환자는 자발성 뇌출혈 과거력이 있어 IV tPA 금기 → IA thrombectomy.','틀림. 자발성 뇌출혈 과거력은 IV tPA 금기이다.','정답. 혈관 CT에서 대혈관 폐색이 보이므로 동맥 내 혈전제거술을 시행한다.','틀림. 고용량 스타틴은 이차 예방이다.','틀림. 항응고는 급성기 재관류 치료가 아니다(심방세동 이차 예방은 나중).','틀림. 보조 치료이다.',
   stem='52세 남자 환자가 2시간 전 동생 제사에 가서 밥을 먹다 갑자기 우측 편마비 발생하면서 말을 하지 못하여 응급실에 내원하였다. 응급실 내원 당시 시행한 심전도 검사에서 심방세동이 관찰되었고, NIH stroke scale 19점에 체크되었다. 수년전 자발성 뇌출혈이 있어서 머리를 수술받았던 적이 있으며 평소 고혈압이 있어 약 복용 중이었다. 내원 당시 시행한 뇌 전산화 단층 촬영에서 hypodense lesion은 관찰되지 않았고 출혈은 없었으며 혈관 전산화 단층 촬영 소견은 다음과 같았다. 이 환자에서 시행해야 할 치료 방법은?',
   visual=vis('혈관 CT (학습지 26쪽)','s23_33.jpg'),tail='야마 2023 객33 · 학습지 25–26쪽 원문대조'),
 'q-010':Q(5,LMI+' 이 환자: 쉰 목소리·딸꾹질·삼킴장애, 좌측 Horner, 목젖이 우측으로(좌측 연구개 마비), 좌측 얼굴 + 우측 몸 통각 저하 → 좌측 lateral medulla.',*LMI_STEM_E),
 'q-011':Q(2,CBF,'틀림. 뇌혈류는 뇌관류압에 비례하고 뇌혈관 저항에 반비례한다.','정답.','틀림. 60–160 mmHg는 정상혈압인의 범위이다. 고혈압이면 자동조절 범위가 모두 올라간다.','틀림. 산도 변화와 대사산물은 뇌혈관 구경에 영향을 준다.','틀림. 뇌혈관은 CO2 분압에 민감하고, 산소분압에는 크게 반응하지 않는다(낮을 때만 반응).',
   choices=['뇌혈류는 뇌관류압과 뇌혈관 저항에 정비례한다.','뇌혈류 자동조절 능력은 뇌혈관 저항을 변화시켜 뇌혈류랑을 일정하게 유지한다.','고혈압인 사람의 뇌혈류 자동조절 기능은 뇌관류압이 60mmHg~160mmHg일 때 일어난다.','세포의 산도의 변화나 대사산물의 축적은 직접뇌혈관의 구경에 영향을 미치지 않는다.','동맥혈의 산소 분압은 미세한 변화라도 직접적으로 뇌혈관에 영향을 미친다.']),
 'q-012':Q(1,ABCD,*abcd_exps,choices=C_ABCD),
 'q-013':Q(1,'발병 2시간, CT에서 출혈·경색 없음 → IV tPA 적응(학습지 해설). 참고: tPA 전에는 혈압을 185/110 미만으로 낮춰야 한다(이 앱 2026 형성평가 문항 참고).',
   '학습지 정답. 시간 창 안이고 CT가 정상이므로 IV tPA.','틀림. IV tPA를 쓸 수 없거나 대혈관 폐색일 때 고려한다.','틀림. 헤파린은 급성기 재관류 치료가 아니다.','틀림. 아스피린은 tPA를 쓰지 않을 때 또는 tPA 24시간 뒤에 쓴다.','tPA 전 혈압 조절(185/110 미만)에 쓰이지만 학습지 정답은 아니다.',
   caveat='BP 205/115 — tPA 전에 185/110 미만으로 낮춰야 하므로 ⑤도 논란 여지 있음. 학습지 제공 정답 ① 유지',
   choices=['intravenous tPA','intra-arterial thrombectomy','intravenous heparin','oral aspirin','beta-blocker(labetalol)']),
 'q-014':Q(2,AF+' 아스피린 대신 clopidogrel이나 cilostazol이 나와도 답이 된다.',*af(['apixaban','aspirin','dabigatran','wafarin','ribaroxaban'],2)),
 'q-015':Q(2,TPA+' 자발성 뇌출혈 과거력 → IV tPA 금기, 큰 뇌졸중(NIHSS 높음)은 IV tPA 효과가 떨어지고 sICH 위험이 높다 → IA thrombosection.','틀림. 자발성 ICH 과거력은 금기이다.','정답.','틀림. 이차 예방이다.','틀림. 급성기 재관류 치료가 아니다.','틀림. 보조 치료이다.',
   visual=vis('혈관 CT (학습지 28쪽)','s22_33.jpg'),choices=['intravenous tPA','intra arterial thrombosection','high dose statin','anticoagulation','fluid treatment']),
 'q-016':Q(5,LMI,*LMI_STEM_E,
   stem='42세 남자 환자가 내원 당일 발생한 삼킴 장애와 쉰 목소리, 딸꾹질을 하여 내원하였다. 과거력상 고혈압과 당뇨병으로 10년간 약을 먹고 있었다. 신경학적 검사상으로 동공 수축, 이마에 땀이 잘 나지 않았다. 아~ 소리를 낼 때 목젖이 우측으로 올라가고 있었으며, 감각신경은 좌측 안면부위의 통증감각이 10:7로 감소, (몸은) 좌측에 비해 우측에서 10:7 정도로 통증감각이 떨어져 있었다. 이 환자의 병변 위치는?',
   tail='야마 2022 객34 · 학습지 28–29쪽 원문대조'),
 'q-017':Q(3,TOAST,'TOAST 분류.','TOAST 분류.','정답. TOAST에 없다.','TOAST 분류.','TOAST 분류.'),
 'q-018':Q(2,AF,*af(['apixaban','aspirin','dabigatran','wafarin','ribaroxaban'],2)),
 'q-019':Q(5,HTN,*e_htn,choices=C_CBF_R),
 'q-020':Q(1,ABCD,*abcd_exps,choices=C_ABCD),
 'q-021':Q(3,'수업 증례(강의록에는 없는 사진): 77세 MCA 경색 환자가 IAT 뒤 악화됨. 첫 사진은 BBB가 파괴되어 고음영(extravasation)과 부종, 두 번째(시험 사진)는 부종이 심해지고 재관류 손상 부위가 일부 흡수되는 상태, 세 번째는 ICP 상승으로 개두 감압술, 네 번째는 정중선·뇌실이 회복되는 모습. '+ISCH+' ※ 이전 버전은 선지가 한 칸씩 밀려 있었고 정답도 잘못 표시되어 원문으로 복원함.',
   '틀림. Spreading depression은 손상을 막는 것이 아니라 손상을 일으킨다.','틀림. 세포독성 부종은 초기 1–2일에 나타나고, 그 뒤에는 혈관성 부종이다.','정답. BBB 손상 → 혈청 단백 유리 → 혈관성 부종.','(선지 복원 실패) 고음영 부위에 대한 지문이었음. 고음영 = 재관류 손상으로 BBB가 파괴되어 extravasation된 부위.','틀림. 이미 부종이 심해 ICP를 낮추는 것이 우선이다. 재관류 목적은 penumbra를 살리는 것이며, 재관류 손상이 생길 수 있다.',
   choices=['허혈성 손상 주위의 spreading depression은 주위로의 손상을 방지하기 위함이다.','허혈성 손상 48시간 후에는 세포독성에 의한 부종이 나타난다.','뇌혈관 장벽(Blood-brain barrier)의 손상으로 혈청 단백이 유리되어 부종이 발생하였다.','고음영은~~~ (선지 복원 실패)','허혈성 손상을 최소화하기 위해서 혈관을 재관류 해야 한다.'],
   visual=vis('뇌 CT (학습지 31쪽)','s21_41.jpg'),extra=vis('수업 증례 경과 CT (학습지 31쪽 해설)','s21_41_series.jpg'),tail='야마 2021 객41 · 학습지 30–32쪽 원문대조 (선지 ④ 복원 실패)'),
 'q-022':Q(3,GER,'Gerstmann을 일으키는 원인(좌측 inferior branch 폐색).','Gerstmann 관련(읽기 장애 alexia).','정답. Confusion은 우측 병변 증상이다.','Gerstmann 증상(좌우 구분 불가).','Gerstmann 병변 위치.'),
 'q-023':Q(1,ABCD,*abcd_exps,choices=['ABCD2 score은 4점이다','CT에서 이상이 없었으므로 뇌졸중과는 관련이 없는 다른 질환이다.','1시간이내에 도착했으므로 정맥내 혈전용해제를 투여한다.','증상이 좋아졌으므로 동맥내 혈전제거술을 시행한다.','현제 큰이상은 없으므로 퇴원후 경과관찰한다.']),
 'q-024':Q(3,AF+' 2018 객9의 cilostazol이 aspirin으로 바뀌어 출제됨.',*af(['Apixaban','Rivaroxaban','Aspirin','Warfarin','Dabigatran'],3)),
 'q-025':dict(keep_excluded=True,ans=[1],answer_note='학습지 정답 "X" — 복원자가 보기와 답을 기억하지 못함',
   basis='복원자가 보기와 답을 정확히 기억하지 못해 모두 옳은 보기(TOAST 5분류)를 적어 둠. 그대로는 답이 없으므로 채점하지 않음. '+TOAST,tail='야마 2020 객44 · 학습지 35쪽 (정답 미복원)'),
 'q-026':Q(4,LMI,*lmi_exps,choices=C_LMI),
 'q-027':Q(5,ISCH,'틀림(학습지 해설). 치료 목적은 ischemic penumbra를 빨리 회복시키는 것이다.','틀림. Anoxic depolarization은 infarct core에서 일어난다.','틀림. Penumbra의 세포는 necrosis가 아니라 apoptosis로 죽는다. Inflammation은 지연 손상이다.','틀림. BBB가 파괴되면 혈관성 부종이 생긴다. 세포성 부종은 세포 내 전해질 불균형 때문이다.','정답. 재관류 시 손상된 혈관이 터지면 출혈성 경색이 생긴다.',
   choices=['치료의 주된 목적은 penumbra영역의 확대를 감소시키는 것이다.','Penumbra영역에서 anoxic depolarization 이 일어난다.','경색 초기에 inflammation에 의한 necrosis가 나타난다.','BBB의 파괴로 인한 세포성 부종이 나타난다.','혈관 폐색이 진행되면 출혈성 뇌경색과 폐쇄성 뇌경색이 같이 나타날 수 있다.']),
 'q-028':Q(4,LMI,*lmi_exps,choices=C_LMI),
 'q-029':Q(3,GER,'Gerstmann 증상.','Gerstmann 증상.','정답. 실어증은 Gerstmann 4징에 들어가지 않는다(Wernicke 병변 시 별도로 감각성 실어증).','Gerstmann 증상.','Gerstmann 증상.'),
 'q-030':Q(2,ATH+' 소혈관 병리 그림에서 mural atheroma가 혈관을 가장 크게 막는다.','틀림. LDL이 모이는 것(LDL trapping)으로 시작한다.','정답.','틀림. 회색질이 백질의 4배이다.','틀림. SIVD(피질하 허혈성 혈관 치매)에 대한 설명이다. Lacunar syndrome은 운동·감각 기능 장애 위주이다.','틀림. Watershed/borderzone 경색은 전신 저관류(LAA 관련)에 의한 것이지 정맥 혈전증이 아니다.',
   choices=['동맥경화의 시작은 HDL과 ApoA2가 만나 산화하면서 시작된다.','소혈관경화의 경우 arteriosclerosis에 의한 mural atheroma가 가장 큰 병변이다.','CBF의 경우 백질이 회색질의 4배정도 이다.','Lacunar syndrome은 인지장애, 정서변화, 배뇨장애, 보행장애를 특징으로 한다.','정맥 혈전증은 watershed, borderzone infarction이라고 한다.']),
 'q-031':Q(4,LMI,*lmi_exps,choices=['Vestibular neuropathy - Vestibular nucleus','Pain, temperature deficit - spinothalamic tract','Hoarseness - Nucleus ambigus','Hiccup - Nucleus tractus solitarius','Limb ataxia - Spinocerebellar tract']),
 'q-032':Q(1,ABCD+' 복원자: TIA와 ABCD2 score에 관한 문항이며 4점이었던 것으로 기억함.',*abcd_exps,
   stem='61세 남자 환자가 내원 3시간 전 갑자기 발생한 일시적인 우측 편마비를 주소로 응급실에 왔다. 증상은 5분 정도 지속되다가 호전되었으며, 편마비와 함께 말을 하고 싶었으나 나오지 않았다. 내원 당시 혈압은 150/90 이었으며, 이후 증상은 없었으나 불안해서 왔다고 한다. 과거 고혈압이 있었으나 약물 복용하지 않고 지냈으며 하루 한 갑씩 40여년 피웠던 흡연자였다. 응급실에서 시행한 뇌 CT에서는 이상이 없었다. 이 환자에 대한 설명으로 맞는 것은?',
   choices=['ABCD score은 4점이다','CT에서 이상이 없었으므로 뇌졸중과는 관련이 없는 다른 질환이다.','1시간이내에 도착했으므로 정맥내 혈전용해제를 투여한다.','증상이 좋아졌으므로 동맥내 혈전제거술을 시행한다.','현재 큰 이상은 없으므로 퇴원 후 경과관찰한다.']),
 'q-033':Q(1,VESSEL,'정답. MCA 폐색 → 반대측(우측) 위약.','틀림. 외경동맥은 뇌 실질을 공급하지 않는다.','틀림. 가능은 하지만 학습지 정답은 MCA이다.','틀림. 후순환 증상이 아니다.','틀림. 후순환 증상이 아니다.',
   caveat='MCA 병변은 병변 쪽(좌측)으로 안구가 편위됨 — "우측 안구편위"는 복원 오기일 수 있음'),
 'q-034':dict(keep_excluded=True,ans=[1],answer_note='학습지 정답 미기재 — 복원자도 답을 찾지 못함',
   basis='45세 오른손잡이, 우측마비, MRI(그림)에서 좌측 대뇌 병변. 복원자가 답을 찾지 못해 채점하지 않음. 참고: 좌측(우성) inferior parietal lobule 병변이면 Gerstmann(손가락 인식불능, 실서증, 계산불능, 좌우 구분 불가)이 나타난다.',
   visual=vis('MRI 모식도 (학습지 43쪽)','s17_9.jpg'),tail='야마 2017 객9 · 학습지 43쪽 (정답 미기재)'),
 'q-035':Q(5,'뇌혈관은 바깥 → 안쪽 방향(outside-in)으로 penetrating artery가 들어가며, 이 혈관들은 ① 혈압·혈류 감소 시 허혈 변화가 생기기 쉽고 ② 막히면 보상이 안 되며 ③ 만성 고혈압 같은 지속적인 기계적 스트레스로 변성된다 → small vessel pathology(필기).',
   '틀림. 전교통동맥과 후교통동맥은 ICA와 ECA를 잇는 측부순환이 아니다(ECA → ICA 측부순환은 안동맥 경유).','틀림. 뇌혈관은 "outside-in"으로 혈류를 공급한다.','틀림. BBB는 astrocyte와 내피세포로 이루어진다.','틀림. Virchow-Robin space는 연막하(subpial) 공간이다(교수님은 ④가 답이라 하셨다는 기록 있음).','학습지 정답. 만성 고혈압은 penetrating arteriole에 직접 영향을 준다.',
   caveat='학습지 정답 ⑤ — 단, 해설에 "교수님께서 답을 ④라 하셨다"는 기록이 있어 의견이 갈림',
   choices=['외경동맥과 내경동맥을 연결하는 측부 순환은 주로 전교통동맥과 후교통동맥에 의한다.','대뇌 혈관은 신장이나 간과 다르게 "inside out" 형태를 보인다.','뇌혈관장벽의 형성은 oligodendrocyte와 혈관의 내피세포가 구성한다.','Virchow-Robin space (perivascular space)는 지주막하공간이 연속된 곳이다.','만성적인 고혈압에 의해 뇌혈관의 penetrating arteriole에 직접적인 영향을 준다.'],tail='야마 2016 객5 · 학습지 43–44쪽 원문대조'),
 'q-036':Q(1,'좌측으로 안구 편위(병변 쪽을 바라봄) + 우측 얼굴·팔다리 마비 → 좌측 대뇌(MCA) 병변. 자극 시 통증 위치를 찾아가고(pain localization) 눈을 뜬 상태. 뇌간 병변이면 병변 반대쪽(마비된 쪽)으로 안구가 편위된다. ※ 이전 버전의 정답(⑤)은 학습지 정답(①)과 달라 수정함.',
   '정답. 병변 쪽으로 안구 편위 + 반대측 마비 → 좌측 대뇌.','틀림. 우측 대뇌 병변이면 우측으로 편위되고 좌측이 마비된다.','틀림. 좌측 뇌간 병변이면 마비된 쪽(우측)으로 안구가 편위된다.','틀림. 우측 뇌간 병변이면 좌측 마비가 생긴다.','틀림(복원 불확실 선지).',
   visual=vis('환자 그림 (학습지 46쪽, 1학년 진단학 시험 그림과 동일)','s16_7.jpg'),caveat='복원 불완전 — 복원자가 기억에 의존해 복원함',tail='야마 2016 객7 · 학습지 46쪽 원문대조'),
 'q-037':Q(1,VESSEL,'정답. 무의지·느림·작은 목소리 + 다리 > 팔 마비 → ACA.','틀림. MCA는 팔·얼굴 > 다리이다.','틀림. PCA는 시야장애·감각장애가 주 증상이다.','틀림.','틀림. 후순환 증상이 아니다.'),
 'q-038':Q(1,'뇌혈관: main artery(ACA, MCA 등) → perforating artery의 "outside-in" 공급. Willis 고리: ACom, PCom, ACA, MCA, PCA, ICA, basilar. 안동맥은 ICA의 분지. Virchow-Robin space는 연막하 공간. 색전은 갑자기 발생해 처음부터 증상이 최대이고, 시간이 갈수록 심해지는 것은 hemodynamic infarction이다.',
   '정답.','틀림. 전교통동맥·후대뇌동맥·내경동맥 등도 포함된다.','틀림. 안동맥은 내경동맥의 분지이다.','틀림. 연막하(subpial) 공간이다.','틀림. 색전은 갑자기 발생해 처음부터 증상이 최대이다.',
   choices=['뇌동맥 혈류는 간과 신장과 다르게 "outside in"으로 혈류를 공급한다.','Willis\' circle은 중대뇌동맥 전대뇌맥동맥 후교통동맥으로 구성된다.','안동맥은 전두동맥의 분지로서 외경동맥과 우회로를 형성한다.','Virchow-Robin space(perivascular space)는 지주막하 공간이 연결된 공간이다.','Embolism에 의한 혈관폐색은 시간이 지날수록 심해진다.']),
 'q-039':Q(5,CBF,'틀림. 회백질이 백질의 4배이다.','틀림. CBF = CPP/CVR이다.','틀림. 자동조절은 혈관저항을 바꿔 혈류량을 일정하게 유지한다.','틀림. CVR → CBF → OEF 순서로 변한다.','정답.',
   choices=['뇌혈류는 백질부가 회백질부에 비해 4배정도 많다.','뇌관류압(CPP)는 뇌혈류(CBF)와 뇌혈관저항(CVR)에 비례한다.','뇌혈류 자동조절 능력은 뇌관류압을 변화시켜 뇌혈류량을 일정하게 유지한다.','뇌관류압이 떨어지면 뇌혈류 변화, 뇌혈액량(CBV), 산소추출분획(OER)의 순서로 떨어진다.','동맥내 이산화탄소 압력이 감소하면 혈관수축과, 뇌혈류 감소가 나타난다.'],tail='야마 2015 객12 · 학습지 47–48쪽 원문대조'),
 'q-040':Q(3,ATH,'틀림. ApoA II는 HDL의 특징이다.','틀림. LDL trapping이 병변 시작이고, 그 뒤 염증이 생긴다.','정답.','틀림. ACE inhibitor는 동맥경화를 줄인다.','틀림. Lipohyalinosis는 고혈압 환자에서 호발한다.'),
 'q-041':S('좌측 중대뇌동맥(Left MCA) — 원문 선지 ④ 좌중간대뇌동맥','갑작스러운 발생 → 색전. 우측 운동장애 + 우측 안면마비 + 실어증 → 좌측(우성반구) MCA 영역(Broca·중심 언어 영역·운동/감각 영역). 색전성 경색은 ICA가 곧장 이어지는 MCA 영역에 가장 흔하다.',
   subj=True,keep_excluded=False,stem='환자가 갑작스럽게 우측 운동장애, 우측 안면마비, 실어증으로 응급실에 내원하였다. 얼마 전에도 이와 비슷한 문제로 내원하였다고 한다. 어느 구조(혈관)의 문제일 것이라고 예상하는가?',
   tail='야마 2015 객15 · 학습지 49쪽 원문대조 (정답 선지 외 ①②③⑤ 복원 실패 → 주관식으로 전환)'),
 'q-042':Q(3,VESSEL,'틀림. 후순환이다.','틀림. 후순환이다.','정답. 무의지·작은 목소리 + 다리 > 팔 마비 → ACA.','틀림. MCA는 팔 > 다리이다.','틀림. PCA는 시야장애가 주 증상이다.'),
 'q-043':Q(5,'대동맥궁 → brachiocephalic trunk, 좌 common carotid, 좌 subclavian. 안동맥은 ICA의 분지. Subclavian steal은 쇄골하동맥 근위부(추골동맥 분지 전) 협착으로 추골동맥 혈류가 역전되는 것. 전교통동맥은 양측 ACA를 잇는다.',
   '틀림. brachiocephalic trunk, subclavian a., common carotid a.에서 공급된다.','틀림. 전두동맥(anterior frontal a.)이 아니라 전대뇌동맥이다.','틀림. 안동맥은 내경동맥의 분지이다.','틀림. 원위부가 아니라 근위부 협착이다.','정답.',
   choices=['뇌혈관은 두 개의 쇄골하동맥과 두 개의 경동맥에 의해 이루어진다.','Willis 환은 내경동맥과 전두동맥, 후교통 동맥 등이 관여한다.','안동맥은 전두동맥의 분지로서 외경동맥과 우회로를 형성한다.','쇄골하동맥 도류 증후군은 쇄골하동맥 원위부의 협착에 의해 추골동맥에서 혈류의 역전에 의해 일어난다.','전교통동맥은 양측 전뇌대동맥을 연결한다.']),
 'q-044':Q(4,VESSEL+' 좌측 편마비 + 감각장애 + 구음장애 → 우측 MCA.','틀림. 좌측 병변이면 우측 증상이 생긴다.','틀림. 좌측 병변이면 우측 증상이 생긴다.','틀림.','정답. 우측 MCA → 좌측 운동·감각 장애.','틀림. PCA는 시야장애 위주이다.'),
 'q-045':Q(5,ISCH,'틀림. 뇌혈류는 뇌관류압에 비례하고 뇌혈관 저항에 반비례한다.','틀림. Penumbra를 살리는 것이 치료 목적이다.','틀림. Spreading depression은 손상이 퍼지는 현상이다(NMDA 길항제로 진행을 줄일 수 있다고 언급).','틀림. 혈관성 부종에서는 DWI가 pseudonormalization된다.','정답. Penumbra부터 단백 합성 감소 → hsp72 → lactic acidosis → ATP 고갈로 core로 진행한다.',
   choices=['뇌혈류량은 뇌관류압에 반비례하며 뇌혈관 저항에 비례한다.','치료의 목표는 infarction core를 회복하여 brain 조직의 정상화에 있다.','경색 후에 나타나는 spreading depression은 뇌조직의 회복을 위한 과정이며 NMDA receptor에 의해 이루어진다.','세포성 부종이 먼저 발생 한 후, 혈관성 부종이 발생하며 혈관성 부종에서 MRI의 DWI 신호가 감소된다.','가장 먼저 단백질 합성 장애가 일어나고, lactic acidosis가 일어난다.']),
 'q-046':Q(1,'CT가 아직 정상(출혈·경색 없음) + 심방세동 → 색전성 뇌경색. 발병 1시간 → 말초 정맥으로 tPA(IV tPA). IA tPA/urokinase(6시간 이내)는 IV tPA의 한계(짧은 시간, 큰 혈전, 출혈)가 있을 때 고려.',
   '정답. IV tPA.','틀림. 말초 동맥에는 주입하지 않는다.','틀림. IV tPA가 가능하면 먼저 한다.','틀림. 뇌 정맥이 아니다.','틀림. 1시간 안에 왔으므로 IV tPA가 먼저이다.',visual=vis('뇌 CT (학습지 52쪽)','s13_31.jpg'),tail='야마 2013 객31 · 학습지 52–53쪽 원문대조'),
 'q-047':Q(3,ATH+' ※ 이전 버전의 선지에는 다른 자료가 섞여 들어가 있어 원문으로 복원함.','틀림. apoB가 아니라 apoA이다.','틀림. LDL trapping이 병변 시작이고, 그 뒤 염증이 생긴다.','정답.','틀림. ACE inhibitor는 동맥경화를 줄인다.','틀림. 층류에서는 shear stress로 혈관이 유지되고, turbulent flow에서 LDL trapping이 일어난다.',
   stem='혈관의 동맥경화에 대한 설명이다. 맞는 것은?',
   choices=['HDL cholesterol은 apoB에 의해 LDL cholesterol을 제거한다.','LDL trapping은 inflammation에 의해 발생한다.','혈류가 turbulence flow일 때, ACA와 MCA가 나뉘는 부분에서 동맥경화증이 잘 발생한다.','ACE inhibitor를 사용하면 동맥경화증을 증가시킨다.','혈류가 linear flow일 때, 동맥경화증이 잘 발생한다.'],tail='야마 2013 객33 · 학습지 54쪽 원문대조'),
 'q-048':Q(1,'Heparin: antithrombin III 활성화 → thrombin 불활성화. Warfarin: 비타민 K 의존 carboxylase 억제, 심방세동은 INR 2–3. Thienopyridine: ADP 수용체 억제. Aspirin: 비가역적 COX 억제.',
   '정답(학습지). COX를 억제한다.','틀림. 아스피린은 비가역적으로 COX를 억제한다.','틀림(선지 뒷부분 복원 실패). Thienopyridine은 ADP 수용체를 억제한다.','틀림. INR 2–3으로 유지한다.','틀림. ATIII 활성화는 맞지만, ADP 억제는 thienopyridine이다.',
   choices=['Aspirin은 COX를 억제하여 혈관 확장시킨다.','Aspirin은 가역적으로 COX를 억제하기 때문에, 시간이 지나면 계속 복용해 주어야 한다.','Thienopyridine 은 ~ (선지 복원 실패)','심질환 있을 때 Warfarin은 INR 3-4 정도로 유지한다.','Heparin 은 antithrombin 3을 활성화시켜 ADP를 억제시켜 혈액 응고를 막는다.']),
 'q-049':Q(1,EPI,'정답. 뇌경색 중 혈전증이 가장 많다.','색전보다 혈전이 많다.','한국은 뇌출혈 비율이 선진국보다 높지만 뇌경색보다는 적다.','약 12%이다.','드물다.'),
 'q-050':Q(1,EPI,'정답.','색전보다 혈전이 많다.','뇌경색보다 적다.','약 12%이다.','드물다.'),
 'q-051':Q(3,'뇌혈류의 자동조절: ① 화학적 자동조절 — 세포외 산도 변화와 대사산물 축적이 직접 뇌혈관 구경에 영향을 준다. 동맥혈 PCO2는 작은 변화도 직접 영향을 주고, PO2는 약 50 mmHg 이하일 때 의미가 있다. ② 자율성 자동조절 — 뇌관류압 60–160 mmHg를 벗어나면 상실된다.',
   '맞는 설명.','맞는 설명.','정답(틀린 설명). 산도 변화와 대사산물 축적은 직접 뇌혈관 구경에 영향을 준다.','맞는 설명.','틀림. ③이 틀린 설명이다.'),
 'q-052':Q(4,ATH+' ※ 이전 버전에는 선지 대신 다른 자료가 들어가 있어 원문으로 복원함.','틀림. apoB가 아니라 apoA이다.','틀림. LDL trapping이 병변 시작이다.','틀림. Turbulent flow에서 잘 생긴다.','정답. Angiotensin II가 평활근 증식을 일으키므로 ACE inhibitor는 동맥경화를 예방한다.','틀림. Shear stress는 혈관을 유지하는 쪽이다.',
   choices=['HDL cholesterol은 apoB에 의해 LDL cholesterol을 제거한다.','LDL trapping은 inflammation에 의해 발생한다.','혈류가 linear flow일 때, 동맥경화증이 잘 발생한다.','ACE inhibitor를 사용하면 동맥경화증을 예방할 수 있다.','혈관내피세포는 shearing stress가 작용하여 동맥경화를 촉진한다.'],tail='야마 2012 객24 · 학습지 58쪽 원문대조'),
 'q-053':Q(2,'복원자 해설: 저산소 뇌손상에서 뉴런은 apoptosis로 죽고, 이를 탐식하는 microglia가 답일 것 같다고 추정함(확실하지 않음).','뉴런은 손상을 받는 세포이다.','학습지 정답(복원자 추정).','Astrocyte.','Ependymocyte.','Oligodendrocyte.',caveat='복원자도 확신하지 못한 정답(제보 요청) — 참고용'),
 'q-054':Q(4,ATH,'틀림. LDL cholesterol이다.','틀림. 염증은 동맥경화를 촉진한다.','틀림(근거 미확인). 동맥경화는 Willis 고리 근위부·분지부에 잘 생긴다.','정답. Homocysteine과 angiotensin II는 평활근 증식을 촉진한다.','틀림. Shear stress가 높을수록 동맥경화 위험이 줄어든다.',
   choices=['동맥경화는 HDL cholesterol에 의해 일어난다.','혈관의 동맥경화에는 inflammation에 의해 방지될 수 있다.','동맥경화는 일반적으로 Willi\'s circle의 원위부에서 대부분 일어난다.','동맥경화에 homocysteine과 angiotensin II는 평활근 증식을 촉진시킨다.','일반적으로 혈관내피세포는 shearing stress가 작용하여 동맥경화를 촉진한다.'],tail='야마 2011 객12 · 학습지 61쪽 원문대조'),
 'q-055':Q(1,'Thrombin만 지혈(응고) 쪽: fibrinogen → fibrin. 나머지는 지혈 억제 쪽: protein C(Va·VIIIa 억제), t-PA(plasminogen → plasmin, fibrin 용해), thrombomodulin(thrombin을 protein C 활성화 물질로 바꿈), PGI(혈소판 응집 억제).',
   '정답. 응고 촉진.','항응고.','섬유소 용해.','항응고.','혈소판 응집 억제.'),
 'q-056':Q(1,EPI,'정답.','뇌경색보다 적다.','약 13%.','드물다.','드물다.',
   choices=['뇌경색','뇌내출혈','지주막하출혈','뇌실출혈','모야모야병'],tail='야마 2011 객43 · 학습지 62쪽 원문대조'),
 'q-057':Q(3,'화학적 자동조절: 세포외 산도·대사산물이 직접 뇌혈관 구경에 영향. 동맥혈 PCO2는 작은 변화도 직접 영향을 주고, PO2는 50 mmHg 이하로 떨어져야 의미 있는 영향. 자율성 자동조절: 뇌관류압 60 이하 또는 160 이상이면 상실(외상·SAH에서 손상).',
   '맞는 설명.','맞는 설명.','정답(틀린 설명). 이산화탄소 분압과 산소분압이 반대로 적혀 있다.','맞는 설명.','틀림. ③이 틀린 설명이다.',
   choices=['세포의 산도의 변화나 대사산물의 축적은 직접 뇌혈관의 구경에 영향을 미친다.','뇌혈류를 정상으로 유지시켜주는 자동 조절 기능에는 크게 화학적 자동조절 기능과 자율성 자동조절 기능이 있다.','동맥혈의 산소 분압은 미세한 변화라도 직접적으로 뇌혈관에 영향을 미치나, 이산화탄소 분압은 크게 영향을 주지 않는다.','자율성 자동조절 기능은 뇌관류압이 60 mmHg 이하로 떨어지거나 160 mmHg 이상으로 올라가면 상실된다.','모두 맞다.'],tail='야마 2011 객44 · 학습지 62쪽 원문대조'),
 'q-058':Q(2,'TIA: 국소 뇌허혈이 24시간 안에 후유증 없이 회복되는 경우. Amaurosis fugax(일과성 단안 시력소실)는 내경동맥(안동맥) 계통 이상과 관련된다. 정상 뇌혈류 50–55 mL/100g/min, 15–18 이하면 시냅스 전달 불가, 10 이하면 Na-K-ATPase 정지.',
   '맞는 설명.','정답(틀린 설명). Amaurosis fugax는 추골-기저동맥이 아니라 내경동맥 계통 이상이다.','맞는 설명(복원자 추론: 20–30 이하에서 잘 생김).','맞는 설명.','틀림. ②가 틀린 설명이다.',
   choices=['일과성 뇌허혈증은 국소적으로 뇌허혈이 발생되었다가 24시간 이내에 후유증 없이 회복되는 경우이다.','Amaurosis fugax이 있는 경우에는 추골-기저혈관계 이상일 가능성이 높다.','뇌혈류가 20 내지 30 ml/100g/min 이하로 떨어진 경우에 잘 발생한다.','약 25%에서 일 년 내에 뇌졸중이 발생한다.','다 맞다.'],tail='야마 2011 객46 · 학습지 63쪽 원문대조'),
}
