from fixlib import Q,S,vis
STG='인지저하 환자 분류: 객관적 인지기능 검사 정상 → 주관적인지장애(SCD). 나이·학력 대비 검사 저하 + 일상생활능력 유지 → 경도인지장애(MCI). 검사 저하 + 독립적 일상생활 곤란 → 치매(Dementia).'
AD='알츠하이머병: 세포 밖 amyloid β(plaque) + 세포 안 tau(neurofibrillary tangle). 서서히 진행하는 기억력 저하 → 길찾기·일상생활 장애, 망상(도둑 망상) 등 행동 증상. MRI에서 양측 내측 측두엽·두정엽 위축. 치료: cholinesterase inhibitor(donepezil, rivastigmine, galantamine), NMDA 길항제(memantine).'
VAD='혈관성 치매: ① Multi-infarct dementia — 큰 혈관이 반복적으로 막힘 → 계단식 진행, MRI에서 여러 부위 경색. ② Strategic infarct dementia — fornix·시상 등 인지에 중요한 부위(Papez 회로)의 작은 경색으로 갑자기 인지 급감. ③ Subcortical vascular dementia — 작은 혈관 질환, white matter hyperintensity, 서서히 진행(알츠하이머와 MRI로 감별).'
NPH='정상압 수두증(NPH): 보행장애 + 소변실수 + 기억장애(triad), MRI에서 뇌실 확장. 대용량 요추천자 후 호전되면 shunt 수술.'
DLB='루이소체 치매(DLB): 파킨슨 증상, 인지 변동, 반복적이고 구체적인 환시(벌레 등), 실신·낙상, 항정신병약 과민. 1-year rule: 치매가 파킨슨 증상보다 먼저이거나 1년 이내에 함께 나타나면 DLB, 파킨슨병이 확립된 뒤 치매가 오면 PDD.'
MEM='기억의 분류: Declarative(explicit) — episodic(개인 경험), semantic(일반 지식) / Non-declarative(implicit) — procedural(피아노·자전거), emotional conditioning, priming, conditioned reflex.'
TRT='치료 가능한 치매(Dementia with treatable causes): 정상압 수두증, 알코올 관련 치매, 갑상선기능저하증, 비타민 결핍(B12, thiamine), 뇌 감염(신경매독 등), 경막하혈종, 뇌종양, 우울증(가성치매), 약물 중독.'
PROG='진행성(퇴행성) 치매: Alzheimer\'s dementia, Frontotemporal dementia, Dementia with Lewy bodies, Parkinson\'s disease dementia.'
ABCD='치매 환자 평가 ABCD: A — ADL(일상생활능력; 저하되면 치매), B — Behavior(망상·우울·불안 등, 치매에 흔함), C — Cognition(주의력, 언어, 시공간, 기억, 전두엽/집행 기능; 하나라도 떨어지면 인지저하), D — Differential diagnosis(신경학적 진찰, 신경심리검사, 혈액검사, 뇌영상).'
PLACE='요양시설 입소 권고 원인(Causes of nursing home placement): 고관절 골절로 이어지는 낙상, 공격적 초조(언어·신체), 통제되지 않는 배회, 요실금, 수면장애, 주 보호자 상실.'
SPECS={
 'q-005':Q(5,AD+' α-synuclein은 루이소체(파킨슨병·DLB), 14-3-3 단백은 CJD의 CSF 표지자.','틀림. α-synuclein은 루이소체.','틀림.','틀림. 14-3-3은 CJD.','틀림.','정답. Amyloid β(plaque) + tau(NFT).',tail='야마 2025 객42 · 학습지 227쪽 원문대조'),
 'q-006':Q(4,STG+' '+AD+' 강의록 퀴즈가 그대로 출제됨.','틀림. 계단식 진행이 아니다.','틀림. 일상생활장애가 있으므로 치매이다.','틀림. 검사·일상생활 모두 저하되어 있다.','정답.','틀림. 서서히 진행하지만 MRI 소견이 내측 측두엽·두정엽 위축이다.'),
 'q-007':Q(2,STG,'틀림.','정답. 검사 저하 + 일상생활 유지.','틀림. 객관적 검사가 저하되어 있다.','틀림. 일상생활 문제가 없으므로 치매가 아니다.','틀림.'),
 'q-008':Q(5,AD+' 이 환자: 서서히 진행하는 최근 기억 저하 + 길 잃음 + 혼자 외출 곤란 + 측두-두정엽 위축 → 알츠하이머 치매.','틀림. 혈관성 위험 관리 약이다.','틀림. 고지혈증 약이다.','틀림. 심방세동 등에 쓴다.','틀림. 파킨슨병 약이다.','정답. 기억력 저하에는 cholinesterase inhibitor.'),
 'q-009':Q(2,VAD+' 그래프(x축 시간, y축 인지)가 계단식으로 떨어진다 → multi-infarct dementia(국시 빈출).','틀림. 파킨슨 증상과 치매가 함께 나타나는 퇴행성 질환이다.','정답. 계단식 진행.','틀림. 초반부터 운동장애가 있는 퇴행성 치매이다.','틀림. 서서히 진행한다.','틀림. 서서히 진행한다.',visual=vis('진행경과 그래프 (학습지 228쪽)','d23_45.jpg')),
 'q-010':Q(2,ABCD+' '+STG,'틀림. ADL이 저하되면 치매이다.','정답.','틀림. 인지검사에서 확인되면 경도인지장애 수준이다.','틀림. 치매로 진단해도 감별진단(D)이 필요하다.','틀림. 반복되는 환시는 루이소체 치매의 핵심 소견이다.',
   choices=['Activity of daily living이 저하되면 경도인지장애 수준이다.','Behavioral problem으로 우울, 망상. 불안 등의 증상을 평가한다.','Cognitive impairment가 인지검사에서 확인되면 주관적인지장애 수준이다.','Dementia로 진단하면 추가적인 differential diagnosis는 필요하지 않다.','Visual Hallucination이 반복적으로 발생하면 알츠하이머병일 가능성이 높다.']),
 'q-011':Q(5,STG,'틀림.','틀림. 검사가 정상범위이다.','틀림.','틀림.','정답. 스스로는 저하를 느끼지만 검사는 정상 → SCD.'),
 'q-012':Q(4,ABCD,'틀림. ADL은 일상생활능력을 평가한다.','틀림. 우울·망상·불안은 치매에 흔하다.','틀림. 기억력이 정상이어도 다른 인지기능을 평가해야 한다(하나라도 떨어지면 인지저하).','정답. 감별진단(D).','틀림. 집행기능 하나만 문제여도 인지저하로 판단한다.',
   choices=['Activities of daily linving은 주관적 인지능력을 평가한다.','behavioral problem에서 우울, 망상, 불안이 있는 치매 드물다.','cognitive impairment에서 기억력이 정상일 시 다른 인지기능저하는 평가하지 않는다.','감별진단을 위해 신경학적 진단, 뇌영상검사, 혈액검사를 시행한다.','executive function만 문제가 있는 경우 치매로 진단하지 않는다.']),
 'q-013':Q(3,STG+' '+AD,'틀림. 초반부터 운동장애·환시가 특징이다.','틀림.','정답.','틀림. 보행장애·소변실수·뇌실 확장이 없다.','틀림. 파킨슨병이 먼저 있어야 한다.'),
 'q-014':Q(1,VAD+' 이 환자: 3일 전 갑자기 시작한 기억장애 + DWI에서 fornix 경색 → strategic infarct dementia.','정답.','틀림. 여러 번의 경색이 아니다.','틀림. 갑자기 발생했다.','틀림.','틀림.',visual=vis('DWI (학습지 231쪽)','d22_14.jpg')),
 'q-015':Q(3,STG+' (복원자: ④⑤ 선지는 기억나지 않아 임의로 작성)','틀림.','틀림. 검사에서 저하되어 있다.','정답.','틀림. 일상생활에 지장이 없다.','틀림.'),
 'q-016':Q(3,STG+' '+AD,'틀림.','틀림.','정답.','틀림.','틀림.'),
 'q-017':Q(1,'신경매독: 두통, 혼란, 기억력 저하, 공격적·충동적 성향. CSF에서 WBC·protein 증가. (복원자: 세부 수치와 선지는 정확하지 않음)','정답.','틀림. CSF 염증 소견과 맞지 않는다.','틀림.','틀림.','틀림. 보행장애·소변실수가 주 증상이다.',caveat='발문 일부 복원 누락(진단을 고르는 문제)'),
 'q-018':Q(5,'Thiamine(B1) 결핍: 원인 — 알코올, 오래 지속된 구토, 굶주림(위절제 후 섭취 불량). 증상 — confusion, 안구운동장애(안진), 보행 실조. MRI에서 내측 시상·유두체 병변. 치료 — IV thiamine.','틀림.','틀림.','틀림.','틀림. 보행장애·소변실수·기억장애 triad이다.','정답. 위절제 후 섭취 불량 + 혼돈·안진·실조 → thiamine 결핍.'),
 'q-019':Q(4,'치매 원인: 알츠하이머병 약 50%, 혈관성 치매 약 35%, 기타 15%(강의록). (복원자: 보기 순서와 일부 내용은 정확하지 않음)','틀림.','두 번째로 흔하다.','틀림.','정답.','틀림.'),
 'q-020':Q(1,VAD+' 이 환자: 고혈압·당뇨, 증상이 비교적 갑자기 단계적으로 추가됨(이해력 → 무관심 → 편측 무시) + MRI 다발성 경색 → multi-infarct dementia.','정답.','틀림. 단일 부위 경색이 아니다.','틀림.','틀림.','틀림. 서서히 진행하며 백질 고신호가 특징이다.',visual=vis('뇌 MRI (학습지 233쪽)','d20_43.jpg')),
 'q-021':Q(4,STG+' '+AD+' 김고운 교수님 수업 퀴즈가 그대로 출제됨.','틀림.','틀림.','틀림. 일상생활장애가 있다.','정답.','틀림.'),
 'q-022':Q(1,VAD,'정답.','틀림.','틀림.','틀림.','틀림.',visual=vis('뇌 MRI (학습지 234쪽)','d19_26.jpg'),
   choices=['Multi infarct dementia','mild cognitive impairment','Subjective cognitive decline','Alzheimer’s disease dementia','Subcortical vascular dementia']),
 'q-023':Q(5,NPH,'틀림.','틀림.','틀림.','틀림.','정답.',visual=vis('뇌 MRI (학습지 235쪽)','d19_27.jpg')),
 'q-024':Q(1,STG,'정답. 검사 저하 + 일상생활 유지.','틀림.','틀림. 일상생활에 문제가 없으므로 치매가 아니다.','틀림.','틀림.'),
 'q-025':Q(5,NPH,'틀림.','틀림.','틀림.','틀림.','정답.',visual=vis('뇌 MRI (학습지 235쪽 — 2019 객27과 같은 문항)','d19_27.jpg')),
 'q-026':S('Cholinesterase inhibitor: donepezil(모든 병기), rivastigmine, galantamine(경도–중등도) / NMDA 길항제: memantine(중등도–중증)','서만욱 교수님 강의록: early to moderate stages에는 cholinesterase inhibitor 3가지, moderate to severe stages에는 memantine.',
   stem='Alzheimer’s disease의 치료약으로 현재 쓰는 것은?',tail='야마 2018 주4 · 학습지 236쪽 원문대조'),
 'q-027':S('Behavioural variant frontotemporal dementia (bvFTD)','FTD는 전두·측두엽의 진행성 신경세포 소실(frontotemporal lobar degeneration). bvFTD는 사회적 행동 변화, 사회적 인식 상실, 충동 조절 저하가 특징. 그 밖에 semantic dementia, progressive nonfluent aphasia. (문제 사진은 강의록의 bvFTD 설명 그림)',tail='야마 2018 주5 · 학습지 237쪽 원문대조'),
 'q-028':S('정상압 수두증, 알코올 관련 치매, 갑상선기능저하증, 비타민 결핍 치매, 뇌 감염, 경막하혈종, 뇌종양 (하나만 써도 됨)',TRT,tail='야마 2017 주1 · 학습지 237쪽 원문대조'),
 'q-029':S('Alzheimer\'s dementia, Frontotemporal dementia, Dementia with Lewy bodies, Parkinson\'s disease dementia',PROG+' 전년도 기출이자 수업 강조 부분.',tail='야마 2017 주2 · 학습지 238쪽 원문대조'),
 'q-030':S('Senile plaques(amyloid β), neurofibrillary tangles(tau)',AD,tail='야마 2017 주3 · 학습지 238쪽 원문대조'),
 'q-031':S('Cholinesterase inhibitor(donepezil, rivastigmine, galantamine) — 경도–중등도 / Memantine(NMDA 수용체 길항제) — 중등도–중증 (+ 신경정신과 약물)','증상을 완화하고 진행을 늦추는 약. Donepezil은 모든 병기에 쓸 수 있다.',tail='야마 2017 주4 · 학습지 238쪽 원문대조'),
 'q-032':S('Alzheimer\'s dementia, Frontotemporal dementia, Dementia with Lewy body, Parkinson\'s disease dementia',PROG+' 교수님 TY가 그대로 출제.',tail='야마 2016 주10 · 학습지 239쪽 원문대조'),
 'q-033':S('Amyloid β 단백의 축적(senile plaque), neurofibrillary tangle(tau)',AD,tail='야마 2016 주11 · 학습지 239–240쪽 원문대조'),
 'q-034':S('정상압 수두증, 알코올 관련 치매, 갑상선기능저하증, 비타민 결핍 치매, 뇌 감염, 경막하혈종, 뇌종양, 우울증',TRT+' 복원자: 출제 의도는 "치료 가능한 원인을 가진 치매"로 보임.',tail='야마 2016 주12 · 학습지 240쪽 원문대조'),
 'q-035':S('(CSBD는 ABCD의 오기로 추정) A: ADL — 인지장애로 일상·사회생활 지장 / B: Behavior — 이상행동·문제행동 / C: Cognition — 인지기능 저하 / D: Differential diagnosis — 증상군이며 원인 질환이 다양',ABCD+' 복원자: "CSBD"가 아니라 티야였던 "ABCD"로 보임.',tail='야마 2016 주13 · 학습지 240쪽 원문대조'),
 'q-036':Q(5,MEM+' 아들 생일에 있었던 일 → Long term(나) + Explicit(다) + Episodic(마).','틀림.','틀림.','틀림.','틀림.','정답.',
   stem='아들의 생일에 있었던 일에 대한 기억, 자전거를 가르쳐줬던 기억 등 자신만이 가진 특별한 기억에 해당하는 것을 다음 보기에서 고르시오.\n가. Short term memory\n나. Long term memory\n다. Explicit memory\n라. Implicit memory\n마. Episodic memory\n바. Sementic memory'),
 'q-037':Q(3,'알츠하이머병은 병리 변화가 임상 증상보다 먼저 일어난다: Stage 1 — Aβ plaque 병리 → Stage 2 — 신경퇴행(NFT, tau) → Stage 3 — 미세한 인지저하 → MCI → AD.','틀림.','틀림. Aβ 다음이다.','정답. 가장 먼저 Aβ 축적.','틀림. 뒤 단계이다.','틀림. 마지막이다.'),
 'q-038':Q(5,DLB+' 파킨슨병 진단 전에 인지장애가 먼저 → DLB. ※ 이전 버전의 정답(④ CJD)은 학습지 정답(⑤)과 달라 수정함.','틀림.','틀림. 파킨슨병이 확립된 뒤 치매가 온 경우이다.','틀림.','틀림.','정답.'),
 'q-039':Q(1,'CSF 바이오마커: 알츠하이머병에서 뇌실질에 Aβ42가 침착되므로 CSF Aβ42는 감소하고, tau는 증가한다.','정답.','틀림. CSF tau는 증가한다.','틀림. 조직 병변이지 CSF 측정 물질이 아니다.','틀림. 루이소체.','틀림. 간 효소이다.'),
 'q-040':Q(5,MEM+' 몇 년 전 아들 생일 일 → long term, declarative, episodic.','틀림.','틀림.','틀림. Episodic이다.','틀림. Declarative이다.','정답.'),
 'q-041':dict(keep_excluded=True,ans=[1],answer_note='학습지 정답 미기재',
   stem='다음은 Alzheimer disease의 진행단계(초기 – 중기 – 말기)로 구성이 올바르게 된 것은?',
   choices=['β-amyloid 축적 – 측두엽 위축 – 경도 인지장애','측두엽 위축 – 기억력 장애 – β-amyloid 축적','기억력, 운동장애 – β-amyloid 축적 – 측두엽 위축','β-amyloid 축적 – CSF내 Aβ 항체감소 – 기억 & 운동장애','β-amyloid 축적 – 기억력, 운동장애 – 측두엽 위축'],
   basis='학습지에 정답이 없음. 참고: 2013 객39 복원 — 초기 β-amyloid 축적, 중기 측두엽 중심 위축, 말기 인지·행동장애. 이 순서에 가장 가까운 것은 ①.',
   exps=['초기 Aβ → 중기 위축 → 말기 인지저하 순서와 가장 가깝다.','순서가 거꾸로이다.','Aβ가 먼저이다.','CSF "Aβ 항체"는 강의 내용이 아니다.','위축이 인지·운동장애보다 먼저이다.'],tail='야마 2014 객16 · 학습지 242쪽 (정답 미기재)'),
 'q-042':Q(4,STG+' MCI 진단기준: 주관적 인지 호소(정보제공자 확인), 나이 대비 1개 이상 인지영역 저하, 일상 기능은 정상, 치매 아님. K-MMSE 50퍼센타일이지만 기억 호소가 있고 다른 영역 장애 없음 → 학습지 정답 MCI. ※ 이전 버전의 정답(⑤)은 학습지 정답(④)과 달라 수정함.',
   '틀림.','틀림.','틀림.','정답(학습지).','틀림.',caveat='학습지 해설 칸 번호가 "48번"으로 적혀 있으나 내용상 이 문항(객26) 해설임',tail='야마 2014 객26 · 학습지 242–243쪽 원문대조'),
 'q-043':S('1-year rule: 치매가 파킨슨 증상 이전 또는 1년 이내에 나타나면 DLB, 파킨슨병이 확립된 뒤 치매가 오면 PDD',DLB+' (1-year rule은 두 질환을 감별하는 도구이며, DLB가 PDD로 진행하는 것이 아니다.)',
   stem='(원문 발문·선지 복원 실패) 파킨슨병 치매(PDD)와 루이소체 치매(DLB)를 구분하는 기준을 쓰시오.',tail='야마 2014 객27 · 학습지 243쪽 (발문 복원 실패 → 주관식으로 전환)'),
 'q-044':Q([2,3,4,5,6],MEM+' "6살 때부터 시작" → episodic(declarative), "명곡"이라는 뜻을 앎 → semantic(declarative), "베토벤을 칠 수 있다" → procedural(non-declarative).',
   '해당 없음.','해당. 피아노 연주 능력.','해당. 6살 때 시작한 개인 경험.','해당. "명곡"의 의미.','해당. Episodic·semantic.','해당. Procedural.','해당 없음.','해당 없음.',
   choices=['Short term memory','Procedural memory','Episodic memory','Semantic memory','Declarative memory','Non-declarative memory','Emotional memory','Conditioned memory'],
   stem='다음의 대화에서 해당되는 것을 모두 고르시오\nA : 피아노는 언제부터 시작하셨나요?\nB : 유치원 때니까 6살쯤이요.\nA : 지금은 어려운 명곡도 칠 수 있으시나요?\nB : 예. 베토벤을 칠 수 있어요',tail='야마 2013 객36 · 학습지 243–244쪽 원문대조 (복수정답 ②③④⑤⑥)'),
 'q-045':Q(1,'치매 정의: 기억력 장애 + 언어장애·실행증·실인증·전두엽기능 장애 중 1개 이상 + 사회·직장생활 장애 + 섬망 아님. 이 환자: 직장생활 곤란(MCI보다 진전), 기억(회상·재인) 저하, 보속증, 보행장애·환시 없음, MRI 전반적 위축 → 알츠하이머 치매. MMSE 20–23점은 치매 의심.',
   '정답.','틀림. 보행장애 등 혈관성 소견이 없다.','틀림.','틀림. 직장생활이 어려우므로 치매이다.','틀림. 환시·파킨슨 증상이 없다.'),
 'q-046':Q(5,DLB+' 기억력 장애 2년 → 1년 전 파킨슨 증상 + 벌레 환시 → DLB.','틀림.','틀림.','틀림.','틀림.','정답.'),
 'q-047':S('초기: β-amyloid 축적 → 중기: 측두엽 중심 위축(신경퇴행, NFT) → 말기: 인지 및 행동장애','Stage 1 Aβ plaque → Stage 2 neurodegeneration(NFT) → Stage 3 biomarker + 미세한 인지저하 → MCI → AD. 복원자: 시험 보기는 이 세 가지 조합의 순서를 바꿔 가며 나왔으나 정확한 선지는 기억나지 않아 주관식처럼 답을 올림.',
   stem='알츠하이머병의 초기·중기·말기에 일어나는 변화를 순서대로 쓰시오. (원문 객관식, 선지 복원 실패)',tail='야마 2013 객39 · 학습지 245쪽 (선지 복원 실패 → 주관식으로 전환)'),
 'q-048':Q(3,MEM+' 처음 만난 때·처음 손잡은 때 → 개인 경험 = episodic memory.','틀림.','틀림.','정답.','틀림. 일반 지식이 아니다.','틀림. Declarative이다.',
   stem='남녀가 대화를 하고 있다.\n여자 A : 우리가 처음 만난 때가 언제였지?\n남자 B : 100일전, 빼빼로 데이때!\n여자 A : 우리가 언제 처음 손을 잡았지?\n남자 B : 영화보고 나오다가.ㅎㅎ\n다음 중 여자 A가 남자 B에게 어떤 기억을 묻고 있는가? 가장 적절한 것을 고르시오.',
   choices=['Short-term memory','Procedural memory','Episodic memory','Semantic memory','Non-declarative memory'],tail='야마 2012 객19 · 학습지 245–246쪽 원문대조'),
 'q-049':Q(4,STG+' MMSE 24점(25퍼센타일 미만)이지만 다른 인지영역 장애가 없고 직장생활에 지장 없음 → MCI. MMSE는 학력·연령의 영향을 받는다.','틀림.','틀림.','틀림.','정답.','틀림.'),
 'q-050':Q(5,DLB,'틀림.','틀림.','틀림.','틀림.','정답.'),
 'q-051':Q(2,'APOE: E2(약 7%) — 보호, E3(약 79%) — 중립, E4(약 14%) — 알츠하이머병 위험 유전자(Aβ 올리고머화·plaque 형성 촉진, 해마 위축).','틀림.','정답.','틀림. 중립형이다.','틀림. 보호인자이다.','틀림.'),
 'q-052':Q(4,MEM,'틀림. 뜻 설명은 declarative(semantic).','틀림. Emotional conditioning(non-declarative).','틀림. Procedural(non-declarative).','정답.','틀림. Priming effect.',
   choices=["'책상'의 뜻을 설명하는 것은 non-declarative memory에 의존한다.","'독사'를 보면 떠오르는 무서움이나 혐오는 declarative memory 때문이다.","피아노를 배우고 익혀 더 잘 칠 수 있는 것은 declarative memory에 기인한다.","최근 치매수업에 대한 내용이나 시간 등에 대한 기억은 declarative memory에 의존한다.","무의식 중에 자주 접하는 광고에 따라 상품을 선택하는 것은 procedural memory 때문이다."],tail='야마 2011 객17 · 학습지 247–248쪽 원문대조'),
 'q-053':Q(3,MEM+' Declarative memory(episodic, semantic)는 해마·내측 측두엽이 담당한다.','틀림.','틀림.','정답.','틀림. Episodic은 내측 측두엽(해마).','틀림. Procedural은 기저핵·소뇌.',
   choices=['Classical conditioning - parietal lobe','Conditioned reflex - frontal lobe','Semantic memory - temporal lobe','Episodic memory - cerebellum','Procedural memory - temporal lobe'],tail='야마 2011 객18 · 학습지 248쪽 원문대조'),
 'q-054':Q(3,'혈관성 치매 진단: 치매 + 뇌혈관질환 + 두 장애의 관련성(인지된 뇌졸중 후 3개월 이내 치매 발생, 또는 인지기능의 갑작스러운 악화·변동이 있는 계단식 진행). 초기부터 보행장애·요실금이 흔하다.','틀림. 보행장애가 초기에 나타난다.','틀림. 3개월 이내이다.','정답.','틀림. 요실금이 흔하다.','틀림. 알츠하이머병의 설명이다.',
   choices=['대개 보행 장애는 매우 늦게 나타난다.','뇌졸중이 있고 대개 1년 이후에 치매 증상을 보인다.','치매의 증상이 갑자기 악화되거나, 변동이 있는 계단식 진행을 보인다.','치매 증상과는 별개로 대개 요실금 증상이 드물고, 나타나도 후기에 동반된다.','인지장애를 설명할 뇌병변 없이 기억력의 소실을 초기에 보이고, 서서히 진행한다.']),
 'q-055':Q(4,PLACE,'틀림.','틀림.','틀림.','정답. 수면장애.','틀림.',
   choices=['심한 기억력 상실로 아무도 못알아 볼 때','인지 전영역에 걸친 심한 인지 장애를 호소할 때','직장생활장애로 인한 경제상황의 악화를 호소할 때','수면장애로 보호자가 쉬지 못하고 힘들어 할 때','시도 때도 없이 음식을 섭취하나 체중은 오히려 감소할 때']),
 'q-056':Q(4,'DSM-IV 치매: 기억력 장애 + 언어장애·실행증·실인증·전두엽기능 장애 중 1개 이상 + 사회·직장생활 장애 + 섬망이 아님. 인지기능의 진행성 저하.','틀림. 섬망이 아니어야 한다.','틀림. 장애가 있어야 한다.','틀림. 1개 이상이면 된다.','정답.','틀림. 일시적이 아니다.'),
 'q-057':Q(3,'알츠하이머병 위험인자: 노인, 여자, 치매 가족력, ApoE ε4, 저학력, 두부외상. 보호인자: ApoE ε2, 고학력(, 항산화제, estrogen).','틀림. 고연령이 위험인자.','틀림. 저학력이 위험인자.','정답.','틀림. 반대로 짝지어졌다.','틀림. 반대로 짝지어졌다.'),
 'q-058':S('갑상선기능저하증, 신경매독, 비타민 B12 결핍, 약물 중독, 뇌종양, 만성 경막하혈종, 정상압 수두증 (학습지 정답: ③번 선지)','정슬기 교수님 치매 PPT의 Treatable causes of dementia. ※ 원문 선지가 학습지에 남아 있지 않아(이전 버전의 선지는 다른 문항 해설이 섞인 것) 주관식으로 전환함.',
   stem='치매는 신경퇴행성 질환으로 본질적인 치료는 어렵다. 그러므로 신경퇴행성 치매 환자를 볼 때 먼저 치매증상을 보이나 치료가능한 질환과의 초기 감별이 중요하다. 치료 가능한 치매에 해당하는 질환을 쓰시오. (원문 객관식, 선지 복원 실패)',
   subj=True,tail='야마 2010 객44 · 학습지 249–250쪽 (선지 미수록 → 주관식으로 전환)'),
 'q-059':Q(5,PLACE,'틀림.','틀림.','틀림.','틀림.','정답. 낙상 및 골절 위험.'),
}
for k in ['q-026','q-027','q-028','q-029','q-030','q-031','q-032','q-033','q-034','q-035','q-043','q-047']: SPECS[k]['subj']=True
