from fixlib import Q,S
ICH='자발성(고혈압성) 뇌실질내 출혈: 고혈압 병력 + 반대측 편마비(감각 보존) + CT상 putamen 부위 고음영 → ICH. lenticulostriate artery가 가장 흔한 출혈 혈관. CT 모양: SAH 별(불가사리) 모양, SDH 초승달, EDH 렌즈, IVH 뇌실 내 고음영.'
ich=['정답. Intracerebral hemorrhage.','SAH: basal cistern 별 모양.','SDH: 초승달 모양, 외상.','EDH: 렌즈 모양, 외상.','IVH: 뇌실 내 고음영.']
AMY='아밀로이드 혈관병증에 의한 출혈: 70대 이상, 고혈압 병력 없이 뇌엽 내 대량 출혈, 피질 소혈관의 수축요소가 비수축성 amyloid β로 대치되어 정상 혈압에서도 파열.'
amy=['고혈압성 ICH: 고혈압 병력, basal ganglia·thalamus 등 심부.','정답. 아밀로이드 혈관병증.','뇌동맥류 파열: SAH.','뇌동정맥 기형: 젊은 연령.']
MF='Miller Fisher grade(CT상 SAH 양으로 혈관연축 예측): 1 출혈 없음 / 2 얇은 층(<1mm) / 3 두꺼운 층·국소 응고 / 4 뇌실질·뇌실 내 출혈. 사진이 뇌실질까지 침범 → 4(복원자 기억: 3 또는 4).'
HH='Hunt and Hess grade: 0 비파열 / I 무증상·경미한 두통 / II 중등도 이상 두통·경부강직, 뇌신경마비 외 결손 없음 / III 기면·혼돈·경도 국소결손 / IV 혼미(stupor)·반신마비 / V 깊은 혼수·제뇌경직. 의식 혼미 + 반신마비 → IV(매해 출제).'
SM='Spetzler-Martin grade: size <3cm 1 / 3~6cm 2 / >6cm 3 + eloquence(감각운동, 언어, 시각, 시상·시상하부, 뇌간, 소뇌각, 심부 소뇌핵) 1 + deep venous drainage 1. 문제: 2(size) + 1(cerebellar peduncle) + 1(deep) = 4.'
num=lambda ok,n=5:[('정답. '+str(i)) if i==ok else str(i)+': 해당하지 않음.' for i in range(1,n+1)]
SPECS={
 'q-001':Q(1,'CT에서 basal cistern 별 모양 고음영 + CTA에서 동맥류 → 동맥류 파열에 의한 SAH.','정답.','고혈압성 ICH: 뇌실질 내 국소 고음영.','EDH: 렌즈 모양.','SDH: 초승달 모양.','IVH: 뇌실 내.'),
 'q-002':dict(keep_excluded=True,choices=['(선지 복원 실패)','심혈관 추가검사를 실시한다.','혈압을 낮추는 내과적 치료를 실시한다.','지주막하 출혈 관련 선지(원문 복원 실패)','감염성 수막염 가능성을 배제하기 위해 요추천자, CSF 검사를 실시한다.'],ans=[5],
   basis='복원자 정답 "⑤?" — 문제·선지 복원이 불완전(1번 공란, 4번은 "지주막하 출혈 관련 선지"로만 기억). Kernig sign·경부강직으로 뇌수막염을 생각해 CSF 검사를 골랐다는 의견과, 신병수 교수님 두통 강의록의 비외상성 SAH 경부강직 내용으로 4번을 골랐다는 학습부 의견이 갈린다. 박정수 교수님은 SAH 치료(coiling vs clipping)를 강조.',
   exps=['(선지 복원 실패)','troponin 경미 상승만으로 심혈관 검사가 우선은 아니다.','혈압 조절은 필요하나 다음 단계의 핵심 검사는 아니다.','(SAH 관련 선지 — 원문 미상)','복원자 정답 후보.'],tail='야마 2025 객30 · 학습지 381쪽 (정답·선지 복원 불완전)'),
 'q-003':Q(1,ICH,*ich),
 'q-004':Q(1,'반혼수로 내원, CT에서 SAH, 치료 후 영상에서 개두술 흔적 없이 동맥류 모양 그대로 coil이 채워짐 → coil embolization(행인 의견). 복원자 정답 표기는 "① or ④".',
   '정답(학습지 기준).','SDH, trephination: 영상 소견과 맞지 않다.','ICH, craniotomy: 맞지 않다.','clipping은 개두술 흔적이 있어야 한다.','IVH, EVD: 맞지 않다.',caveat='복원자 정답 표기 "① or ④" (해설 참고)'),
 'q-005':Q(1,ICH+' 박정수 교수님 티야.','정답. lenticulostriate artery.','Recurrent artery of Heubner: caudate 머리, 내포 앞다리.','Anterior choroidal artery: 내포 뒷다리 후방, 시삭.','Posterior choroidal artery: 시상 후부.','Thalamogeniculate artery: 시상.'),
 'q-006':Q(4,'SAH와 그 치료(clipping vs coil) 구분 문제. 머리를 연 흔적 유무로 구분. 학습지 정답 표기는 ④(clipping)이나 복원자 해설에는 "수술은 coil embolization"으로 적혀 있어 서로 맞지 않는다. 나머지 선지는 임의 구성.',
   'coil embolization.','EDH가 아니다.','EDH가 아니다.','정답(학습지 표기).','SDH가 아니다.',caveat='정답 표기(④)와 복원자 해설(coil)이 충돌 — 해설 참고'),
 'q-007':Q(1,'가: common carotid artery, 나: anterior cerebral artery, 다: vertebral artery, 라: middle cerebral artery, 마: posterior cerebral artery (박정수 교수님 티야, 작년 야마).',
   '정답.','나는 ACA.','가는 CCA.','다는 vertebral artery.','가는 CCA.'),
 'q-008':Q(1,'흐릿한 SAH 영상 + 수술 후 영상에서 개두 소견 → SAH, clipping. 원문 2번 선지는 일부만 복원.',
   '정답.','IVH가 아니다(원문 선지 일부 복원).','ICH가 아니다.','coil이 아니라 개두술(clipping).','IVH, EVD가 아니다.',tail='야마 2021 객4 · 학습지 383쪽 원문대조'),
 'q-009':Q(1,'CT·뇌혈관조영에서 후교통동맥 분지부 동맥류 파열(교수님 정답 공개 ①). 동맥류 파열 SAH는 재출혈 위험이 높아 응급 수술(clipping·coil)이 필요.',
   '정답.','수술적 치료가 필요하다.','자발성 ICH가 아니다(원문 오타 "동맥한"=동반한).','재출혈 가능성이 높다.','재출혈 위험이 높아 응급치료가 필요하다.'),
 'q-010':Q(4,'가: CCA, 나: ACA, 다: vertebral artery, 라: MCA, 마: PCA. 정답 외 선지는 복원자가 임의 구성.',
   '라는 PCA가 아니라 MCA.','나는 middle cerebellar가 아니다.','마는 posterior cerebellar가 아니다.','정답.','가는 external carotid가 아니다.'),
 'q-011':Q(4,'AVM의 크기·위치(eloquence)·배출정맥으로 grading → Spetzler-Martin.','Hunt-Hess: SAH 임상 등급.','Fisher: SAH CT 출혈량 등급.','Suzuki: 모야모야 혈관조영 단계.','정답.','GCS: 의식 수준.'),
 'q-012':Q(5,'동맥류 파열 SAH: 첫 24시간 재출혈 4%, 한 달 30%, 1년 50%, 재출혈 시 사망률 50% → 수술적 치료 필요. 병변은 MCA(동맥류 호발 부위는 Acom). 원문 2·3번 선지는 복원 실패.',
   '이 환자의 병변은 MCA.','(선지 복원 실패)','(선지 복원 실패)','재출혈이 흔해 보존적 치료로 충분하지 않다.','정답.',
   choices=['앞교통 뇌동맥에 병변이 위치한다.','(선지 복원 실패)','(선지 복원 실패)','보존적 치료만으로도 경과가 좋다.','재출혈 가능성이 높아 수술적 치료가 필요하다.'],tail='야마 2020 객17 · 학습지 385–386쪽 원문대조',caveat='2·3번 선지 원문 복원 실패'),
 'q-013':Q(1,ICH,*ich,tail='야마 2020 객28 · 학습지 386쪽 원문대조'),
 'q-014':Q(4,'ICA stenosis + MRA의 연기 같은 abnormal vascular network → 모야모야병(progressive, bilateral, idiopathic steno-occlusive: distal ICA, proximal ACA·MCA).',
   'AVM: nidus와 조기 배출정맥.','CCF: 안구 돌출, 잡음.','Cavernous AVF.','정답. Moyamoya disease.','Carotid stenosis만으로는 abnormal network를 설명하지 못한다.',
   stem='43세 여자 환자가 반복되는 뇌허혈 발작으로 병원에 입원하여 정확한 evaluation을 하기로 하였다. MRI에서 ICA의 stenosis가 관찰되었고 MRA 사진은 다음과 같다. 진단은?',tail='야마 2020 객40 · 학습지 386–387쪽 원문대조'),
 'q-015':Q(4,'양측 ICA stenosis + 연기 같은 abnormal vascular network → 모야모야병. 원문 2·3·5번 선지는 복원 실패.',
   '뇌실질출혈: 영상 소견과 맞지 않다.','(선지 복원 실패)','(선지 복원 실패)','정답. 모야모야병.','(선지 복원 실패)',
   choices=['뇌실질출혈','(선지 복원 실패)','(선지 복원 실패)','모야모야병','(선지 복원 실패)'],tail='야마 2019 객68 · 학습지 387쪽 원문대조',caveat='2·3·5번 선지 원문 복원 실패'),
 'q-016':Q(1,ICH+' 치료: 정위수술을 통한 혈종제거술.',*ich),
 'q-020':S('아밀로이드 혈관병증에 의한 출혈 (cerebral amyloid angiopathy)',AMY,tail='야마 2017 주7 · 학습지 389쪽'),
 'q-022':S('뇌혈관연축 (vasospasm)','뇌동맥류 파열 환자의 사망·신경학적 장애의 주요 원인. SAH 양이 많을수록 흔하고, 출혈 후 3일째 시작 → 6~8일 최고조 → 3주 후 안정. 가장 심각한 합병증이라고 강조한 티야. 치료: triple H(수업: hypervolemia → euvolemia로 바뀜), 동맥내 nimodipine, balloon angioplasty.',tail='야마 2017 주9 · 학습지 390쪽'),
 'q-023':Q(2,AMY,*amy),'q-027':Q(2,AMY,*amy),'q-031':Q(2,AMY,*amy),
 'q-024':Q(4,MF,*num(4,4)),'q-028':Q(4,MF,*num(4,4),tail='야마 2015 객3 · 학습지 392쪽 원문대조'),'q-032':Q(4,MF,*num(4,4)),
 'q-025':Q(5,HH+' (보기가 0부터 시작 → ⑤번이 grade 4)','grade 0: 비파열.','grade I.','grade II.','grade III.','정답. grade IV.'),
 'q-029':Q(4,HH,*num(4)),'q-033':Q(4,HH,*num(4),tail='야마 2014 객5 · 학습지 394쪽 원문대조'),
 'q-026':Q(4,SM.replace('2(size)','2(size 4cm)'),*num(4)),'q-030':Q(4,SM.replace('2(size)','2(size 3cm로 복원 — 강의록 기준 3~6cm)'),*num(4)),'q-034':Q(4,SM,*num(4)),
 'q-035':S('미세혈관 감압술 (microvascular decompression, MVD)','반측안면경련(hemifacial spasm): 정상 혈관이 안면신경 root entry zone을 압박. mastoid 뒤쪽으로 접근해 혈관과 신경 사이에 패드·mesh를 대어 감압. 가장 효과적이고 재발이 적다.',tail='야마 2014 주69 · 학습지 395쪽'),
 'q-036':Q([1,2,3],'학습지 정답 ①②③(R형, 복원자 권은영 — "답만 기억"). 강의록 triple H: hypertension, hypervolemia, hemodilution. 복원 선지의 "Hyperventilation"은 hypervolemia를 잘못 기억한 것일 가능성이 크다.',
   '학습지 정답(원래는 hypervolemia였을 가능성).','정답. Hypertension.','정답. Hemodilution.','(나머지 선지 복원 실패)',
   choices=['Hyperventilation','Hypertension','Hemodilution','(나머지 선지 복원 실패)'],tail='야마 2013 객17 · 학습지 396쪽 원문대조 · 복수정답',caveat='선지 복원 불완전 · Hyperventilation은 hypervolemia 오기 가능성 (해설 참고)'),
 'q-037':Q([1,2,3,4],'모야모야병 수술방법 4개를 모두 고르는 문제(복원자 김남융): EDAS, EMS, EC-IC bypass, multiple burr hole trephination. 원래 선지 순서·오답 선지는 미상.',
   '정답. EDAS(뇌경질막동맥간접문합술).','정답. EMS(뇌근육혈관간접문합술).','정답. EC-IC bypass(두개강 내외 혈관 문합술).','정답. Multiple burr hole trephination.',
   choices=['EDAS (encephalo-duro-arterio-synangiosis)','EMS (encephalo-myo-synangiosis)','EC-IC bypass','Multiple burr hole trephination'],tail='야마 2013 객18 · 학습지 396쪽 원문대조 · 모두 고르기',caveat='원 선지 중 정답 4개만 복원 (해설 참고)'),
 'q-038':Q(2,AMY,'뇌동맥류: SAH.','정답. Amyloid angiopathy.','모야모야병: 양측 ICA 말단 협착.','Dolichoectasia: 혈관 확장·사행.'),
 'q-039':S('4점 (size 3~6cm 2 + eloquent(시상하부) 1 + deep venous drainage 1)',SM,tail='야마 2013 주52 · 학습지 396쪽'),
 'q-040':S('Hypertension, Hypervolemia, Hemodilution','SAH 후 혈관연축(3일째 시작, 6~8일 최고조, 3주 후 안정) 치료: triple H, 동맥내 nimodipine, balloon angioplasty.',tail='야마 2012 주37 · 학습지 396–397쪽'),
 'q-041':S('(1) EDAS: Encephalo-duro-arterio-synangiosis (2) EMS: Encephalo-myo-synangiosis (3) EC-IC bypass: Extracranial-intracranial bypass','모야모야병의 간접·직접 혈관문합술.',tail='야마 2012 주38 · 학습지 397쪽'),
 'q-042':S('Size(nidus 최대직경), Eloquence(기능 부위 여부), Venous drainage(심부 배출 여부)',SM,tail='야마 2012 주39 · 학습지 397쪽'),
 'q-043':S('아밀로이드 혈관병증 (amyloid angiopathy)',AMY+' ※ 이전 버전의 정답 "⑤"는 학습지 표기 오류를 그대로 옮긴 것이라 수정함.',tail='야마 2012 주40 · 학습지 397쪽'),
 'q-044':Q(3,'한쪽(우측)만 ICA 말단 협착 + 비정상 측부혈관 → probable moyamoya(학습지 정답 ③). Moyamoya disease는 양측, moyamoya syndrome은 방사선치료·뇌염 등 원인이 있는 경우. ※ 이전 버전의 정답(②)은 학습지 정답(③)과 달라 수정함.',
   'Moyamoya disease: 양측성.','Moyamoya syndrome: 방사선치료(백혈병)·뇌염 등 기저 원인.','정답. Probable moyamoya(편측).',tail='야마 2011 객55 · 학습지 397–398쪽 원문대조'),
 'q-045':S('①③⑤⑦⑧ (Hypervolemia, Hemodilution, Hypertension, Intra-arterial nimodipine, Balloon angioplasty)','혈관연축 치료: triple H(hypertension, hypervolemia, hemodilution), 동맥내 nimodipine, balloon angioplasty.',
   stem='뇌지주막하출혈 후 발생하는 혈관연축에 대해 시도할 수 있는 치료방법을 모두 고르시오.\n① Hypervolemia ② Hypovolemia ③ Hemodilution ④ Hemoconcentration ⑤ Hypertension ⑥ Hypotension ⑦ Intra-arterial nimodipine ⑧ Balloon angioplasty',tail='야마 2011 주1 · 학습지 398쪽'),
 'q-046':dict(keep_excluded=True,tail='야마 2011 주8 · 학습지 398쪽 (정답 미기재)'),
 'q-047':S('개두술을 이용한 동정맥기형 절제, 뇌혈관내 수술(색전술), 감마나이프 수술','뇌동정맥 기형의 치료 3가지(고은정 교수님 ppt p35).',tail='야마 2011 주9 · 학습지 398쪽'),
}
