from fixlib import Q,S
DRUG='Drugs that worsen MG: aminoglycosides·macrolides·fluoroquinolones, β-blocker·CCB·quinidine·procainamide, chloroquine·penicillamine, vecuronium·succinylcholine, ACE inhibitor, magnesium, lithium, lidocaine, (steroid 초기 악화).'
MG='MG: variability·fatigability, 저녁·운동 후 악화, 휴식 시 호전(일주기성). 외안근 침범(안검하수·복시)이 90%, 동공 정상, 무통성, 감각 정상, 근위부 위약, 민무늬근·심장근 침범 없음.'
MUSK='MuSK-MG: seronegative gMG의 30~70%(40%), 20~30대 여성, cranial·bulbar·neck·호흡근 침범, 사지·순수 안구형 드묾, diurnal variation 적음, 흉선종 연관 없음, AChE 억제제 반응 불량·혈장교환 효과, 항체 역가가 중증도와 연관(AChR은 아님).'
CR='Myasthenic crisis: 감염·수술 등으로 악화, edrophonium(neostigmine)에 호전. Cholinergic crisis: AChE 억제제 과량, 복통·설사·분비물·축동·근섬유속연축, edrophonium에 악화.'
MD='Myotonic dystrophy: 성인 MD 중 가장 흔함, 19번 염색체 CTG repeat expansion, AD with anticipation, cranial·distal 근육 위약, percussion myotonia, 백내장·앞머리 탈모·고환위축·심장전도장애·당뇨·정신지체, 근본 치료 없음(대증), EMG myotonic discharge.'
SPECS={
 'q-001':Q(3,'MuSK 항체는 주로 IgG4로 보체를 활성화하지 않는다. eculizumab은 보체(C5) 억제제이므로 보체 매개인 AChR-MG에 효과가 있고 MuSK-MG에는 기전상 효과를 기대하기 어렵다.',
   '투여 기간 문제가 아니라 기전 문제이다.','azathioprine이 eculizumab을 차단하지 않는다.','정답. IgG4 → 보체 비의존성.','백신(수막구균)은 부작용 예방용이다.','MuSK 항체는 AChR 군집을 방해한다.'),
 'q-002':Q(2,MG,'아침에 양호, 저녁에 악화.','정답.','안구마비가 아니라 안검하수·복시(외안근 위약).','근통·감각저하는 없다.','동공은 정상.'),
 'q-003':Q(3,DRUG+' (야마 + 티야)','아세타졸아미드: 이뇨제.','메트포르민: 당뇨병 약.','정답. 아미노글리코사이드.','레보티록신: 갑상선 호르몬.','아만타딘: 항바이러스·파킨슨병 약.'),
 'q-004':Q(5,MD,'가, 나, 다만이 아니라 라도 맞다.','나, 라도 맞다.','가, 다도 맞다.','라만이 아니다.','정답. 가~라 모두 맞다.',
   stem='근긴장성 이영양증에서 맞는 소견은?\n가. Autosomal dominant inheritance\n나. Percussion myotonia\n다. CTG repeat expansion\n라. Distal myopathy'),
 'q-005':Q(5,MUSK,'AChR 항체 역가는 중증도와 연관이 없다(MuSK는 연관).','MuSK-MG는 20~30대 여성에 호발.','diurnal variation은 덜 흔하다.','흉선 병리와 명확한 연관은 없다.','정답.'),
 'q-006':Q(5,'악화요인: 감염(respiratory infection), 발열, 갑상선기능이상, 임신, 스트레스, 신경근전달에 영향을 주는 약물(Botox), corticosteroid(초기), β-blocker(propranolol). 가~라 모두 해당(오선영 교수님 깜짝 탈야).',
   '라(corticosteroid)도 악화요인.','나, 라도 악화요인.','가, 다도 악화요인.','라만이 아니다.','정답. 모두.',
   stem='다음 중 중증근무력증(Myasthenia gravis, MG)을 악화시킬 수 있는 것은?\n가. Botox administration\n나. Propranolol\n다. Respiratory infection\n라. Corticosteroid'),
 'q-007':Q(1,'Heliotrope rash·Gottron sign + 근위부 위약 → dermatomyositis. 발병 3~5년 내 암 위험 증가(9~32%, 난소·유방·대장암 등) → 첫 3년간 매년 검사.',
   '정답.','심장 침범(부정맥, 심근염, 심부전)이 있을 수 있다.','CK는 중증도를 반드시 반영하지 않는다.','Heliotrope rash·Gottron sign은 DM 소견.','근병증: short-duration, low-amplitude polyphasic MUAP.'),
 'q-008':Q(2,MG+' (tensilon·pyridostigmine에 호전)','맞는 설명. fluctuation·fatigue가 특징.','정답(틀린 설명). 동공은 정상(자율신경 보존).','맞는 설명. 근위부 침범.','맞는 설명. 골격근만 침범.','맞는 설명. 무통성.',tail='야마 2022 객65 · 학습지 111쪽 원문대조'),
 'q-009':Q(5,CR+' neostigmine 투여로 일시 호전 → myasthenic crisis.','콜린성 위기라면 neostigmine에 악화.','불응성 MG는 이 급성 호흡부전 양상의 진단명이 아니다.','스테로이드 이상반응이 아니다.','면역억제제 이상반응이 아니다.','정답. 중증근무력증위기.'),
 'q-010':Q(4,MD,'CTG 반복서열이 증가(expansion).','근본 치료 없음(대증).','myokymia가 아니라 myotonic discharge.','정답. percussion myotonia.','심장 전도장애 등을 초래한다.'),
 'q-011':Q(4,'fatigability, 비음·복시·안검하수, 아침 양호·저녁 악화, Tensilon·pyridostigmine에 호전, RNS(Jolly test)에서 decremental response → MG. 원문 2번 선지는 복원 실패.',
   'Kennedy disease: X-linked 척수연수근위축증.','(원문 선지 복원 실패)','GBS: 급성 상행성 마비, 반사 소실.','정답. Myasthenia gravis.','LEMS: RNS에서 incremental, 근위 하지·자율신경 증상.',
   choices=['Kennedy disease','(원문 선지 복원 실패)','Guillain-Barre syndrome','Myasthenia gravis','Lambert-Eaton Myasthenic syndrome'],
   stem='49세 여자 환자가 3개월 전부터 심해졌다가 완화되는 전신위약감으로 내원하였다. 증상은 아침에는 괜찮다가 저녁에 심해지는 경향이었다. 비음, 복시, 안검하수를 동반하였다. Tensilon test에서 증상이 완화되었고 pyridostigmine을 투여했을 때 근위약이 호전되었다. Repetitive nerve stimulation 검사(Jolly test) 결과이다. 다음 중 가장 가능성이 높은 진단을 고르시오.',
   tail='야마 2021 객48 · 학습지 113–114쪽 원문대조',caveat='2번 선지 원문 복원 실패 · RNS 그림 미포함'),
 'q-012':Q(1,'MG 진단 검사: RNS, single fiber EMG, edrophonium·neostigmine test, anti-AChR antibody, chest CT(흉선종). 근생검은 MG 진단 검사가 아니다.',
   '정답(검사가 아닌 것). Muscle biopsy.','RNS: MG 진단.','Chest CT: 흉선종 확인.','SFEMG: 가장 민감한 검사.','Anti-AChR antibody: 혈청학적 진단.',stem='(2021 객48의 MG 환자) 상기 질환의 진단&예후 평가를 위해서 할 검사가 아닌 것은?'),
 'q-013':Q(4,MUSK+' bulbar·호흡근 침범, AChR 항체 음성, AChE 억제제 무반응, 혈장교환술에 호전 → anti-MuSK MG. 원문 2번 선지는 복원 실패.',
   'Kennedy disease: X-linked 척수연수근위축증.','(원문 선지 복원 실패)','GBS: 급성 상행성 마비.','정답. Anti-MuSK antibody positive MG.','LEMS: 근위 하지 위약, 자율신경 증상.',
   choices=['Kennedy disease','(원문 선지 복원 실패)','Guillain-Barré syndrome','Anti-MuSK antibody positive myasthenia gravis','Lambert-Eaton myasthenic syndrome'],
   tail='야마 2020 객11 · 학습지 114–115쪽 원문대조',caveat='2번 선지 원문 복원 실패'),
 'q-014':Q(1,'LEMS: 근위 하지 위약, 자율신경 증상(입마름 등), 반사 감소 후 운동 뒤 증강, RNS incremental. 50~60%가 small cell lung cancer와 연관.',
   '정답. LEMS.','MG: 외안근·일중변동, 자율신경 증상 없음.','GBS: 급성 상행성 마비, 반사 소실 지속.','PM: 근병증, 자율신경 증상·반사 증강 현상 없음.','뇌 전이로는 이 양상을 설명할 수 없다.'),
 'q-015':Q(2,'머리 손질 어려움(shoulder girdle), 의자에서 일어나기 어려움(pelvic girdle) + heliotrope rash + Gottron sign → dermatomyositis.',
   'PM: 피부병소 없음.','정답. DM.','MG: 일중변동, 안검하수·복시.','LEMS: 자율신경 증상, SCLC 연관.','GBS: 급성 상행성 마비.'),
 'q-016':Q(3,CR+' AChE 억제제 증량 후 급격한 악화 → cholinergic crisis 의심 → edrophonium test로 감별.',
   'Ice pack test: 안검하수 평가.','AChR Ab titer: 중증도·위기 감별에 쓰지 않는다.','정답. Edrophonium test.','Chest CT: 흉선종 평가.','RNS: 진단 검사, 위기 감별용이 아니다.'),
 'q-017':Q(4,MUSK,'여성에 더 흔하다.','흉선종 연관 없음.','edrophonium 반응이 불량하다.','정답.','pyridostigmine 반응이 불량하다.'),
 'q-018':Q(5,MD+' a~d 모두 맞다(b는 복원자도 불확실).','d도 맞다.','a, c 외 b, d도 맞다.','d만이 아니다.','b, d 외 a, c도 맞다.','정답. 모두.',
   stem='Myotonic muscular dystrophy의 특징으로 옳은 것을 고르시오.\na. Testicular atrophy & Frontal alopecia\nb. Hyperostosis of frontal bone and calcification of basal ganglia\nc. Lenticular opacity\nd. Mild to moderate mental retardation'),
 'q-019':Q(4,'MG 진단: RNS, AChE 억제제 검사, anti-AChR antibody, SFEMG. 뇌간청각유발검사는 MG 진단과 무관.',
   'RNS: 진단 검사.','edrophonium·neostigmine test: 진단 검사.','anti-AChR antibody: 진단 검사.','정답(적절하지 않은 검사).','SFEMG: 가장 민감한 검사.',tail='야마 2017 객28 · 학습지 120쪽 원문대조'),
 'q-020':Q(3,'The amount of anti-AChR Ab in the serum does NOT predict the severity of the disease.',
   '맞는 설명. SFEMG sensitivity 82~99%로 가장 높다.','맞는 설명. generalized 53~100%, ocular 10~17%.','정답(틀린 설명).','맞는 설명. 작용시간 약 5분.','맞는 설명. seronegative MG 표적: MuSK, LRP4, agrin.'),
 'q-021':Q(3,'운동 후 수시간 지속되는 사지마비 + 갑상선 정상 + K 상승 → 고칼륨 주기마비 → sodium channel gene(SCN4A) 점돌연변이. 저칼륨 주기마비는 calcium channel(가장 흔함)·sodium channel. ※ 원문 2·4번 선지가 동일하게 복원됨.',
   'Chloride channel: 선천성 근긴장증.','Calcium channel: 저칼륨 주기마비.','정답. Sodium channel.','Calcium channel(원문 중복 선지).','AChR gene: 선천성 근무력증.'),
 'q-022':Q(2,'오후 악화·휴식 시 호전되는 구음장애·안검하수·복시 → MG. 치료: AChE 억제제, 면역억제제, IVIG, 혈장교환술, 흉선절제. 사춘기~60세 전신형 MG는 흉선절제.',
   '혈당 조절: 무관.','정답. Thymectomy.','항혈소판제: 뇌졸중 치료.','혈압약: 무관(β-blocker는 오히려 악화).','이뇨제: 무관.'),
 'q-023':Q(2,'PM(피부병소 없는 근위부 위약, CK↑, 근병증 EMG, lymphocytic inflammation) 일차 치료는 경구 prednisone. 복원된 보기에 경구 스테로이드가 없어 IVIG로 답했으나, 동기 제보로는 3번이 oral prednisone이었을 수 있다(그러면 3번이 정답).',
   'IV prednisone: 강의록의 스테로이드는 경구(IV는 methylprednisolone 펄스).','정답(복원자 기준). IVIG.','(복원 불확실한 선지 — oral prednisone이었을 가능성)','경구 항응고제: 무관.','physostigmine: MG 치료 아님.',
   stem='다음 환자에서 적절한 치료제는?\n56세 여성, 한 달 전부터 서서히 대칭적으로 진행된 사지근위부와 몸통의 근쇠약을 보이며 피부병소는 없었다. 위약은 어깨근육과 pelvic girdle 근육 등 근위부 근육 위약이 심하다. 외안근과 얼굴근육은 정상이다. 검사상 CK 상승했고 근전도에서는 myopathic changes를 보였다. 근조직 검사상 lymphocytic inflammation이 보였다.',
   caveat='선지 복원 불확실 · 3번이 oral prednisone이었을 가능성 (해설 참고)'),
 'q-024':Q(5,'변동성 안검하수·복시, RNS decrement, AChR 양성 → MG. 1차 치료는 AChE 억제제(pyridostigmine). ①③④는 LEMS 설명.',
   'SCLC 연관은 LEMS. MG는 흉선종.','MG는 외안근을 먼저 침범.','hypothyroidism·pernicious anemia는 LEMS와 연관. MG는 hyperthyroidism.','P/Q VGCC 항체는 LEMS.','정답.'),
 'q-025':Q(4,'pyridostigmine은 면역조절 효과 없음, CCB·aminoglycoside는 MG 악화, steroid는 적절한 치료, chest CT로 흉선종 확인 필수.',
   'pyridostigmine은 면역조절·전신형 진행 억제 효과가 없다.','CCB는 MG를 악화시킨다.','steroid는 적절한 치료이다.','정답.','aminoglycoside는 MG를 악화시킨다.',tail='야마 2013 객14 · 학습지 127쪽 원문대조'),
 'q-026':Q(1,MG,'정답(틀린 설명). MG는 painless.','맞는 설명.','맞는 설명. 안검하수는 진행 중 90%.','맞는 설명.','맞는 설명.'),
 'q-027':Q(2,'근위부 위약 + 목근육 위약 + 눈 증상·일중변동 없음 + 피부병변 + CK 상승 → DM. Tensilon·RNS는 MG 진단 검사.',
   '맞는 설명. 일차 치료는 스테로이드.','정답(틀린 설명).','맞는 설명.','맞는 설명. 악성종양 동반 검사.','맞는 설명.',tail='야마 2012 객35 · 학습지 130–131쪽 원문대조'),
 'q-028':Q(2,'근위부 위약 + 목근육 위약 + 눈 증상·일중변동 없음 + 피부병변 + CK 상승 → DM. Tensilon test와 RNS는 MG 진단 검사이다.',
   '맞는 설명. PM/DM 일차치료제는 스테로이드.','정답(틀린 설명).','맞는 설명.','맞는 설명. 염증성 근병증은 악성종양 동반.','맞는 설명.',
   choices=['치료로서 고용량의 경구 스테로이드 치료를 시작한다.','Tensilon test와 반복신경자극검사가 진단에 필수적이다.','근 생검 상 림프구가 침착된 염증소견이 주요소견이다.','동반되어 있는 종양(occult malignancy)에 대한 검사가 필요하다.','근전도 검사가 진단에 중요하며 근병증소견(myopathic pattern)이 관찰될 가능성이 크다.'],
   tail='야마 2011 객6 · 학습지 132–133쪽 원문대조'),
 'q-029':Q(3,'Ocular MG: 흉부 CT로 흉선종 확인, RNS 민감도는 ocular에서 10~17%, AChE 억제제는 증상 완화만 하고 전신형 진행 예방 효과 없음, AChR 항체는 SLE·ALS 등에서도 검출.',
   '폐암이 아니라 흉선종 확인.','가장 예민한 검사는 SFEMG. ocular에서 RNS 민감도는 낮다.','정답.','전신형 진행 예방 효과가 없다.','다른 질환에서도 관찰된다.'),
}
