from fixlib import Q,S,vis
MONO='monopolar(AVG) 뇌파에서는 가장 negative한(위로 솟은) spike가 있는 전극이 간질파 위치. 전극: Fp frontal pole, F frontal, T temporal, C central, P parietal, O occipital, Z midline / 홀수 좌측, 짝수 우측.'
SLP='수면 뇌파: 각성(눈 감음) — posterior alpha, frontal beta, 좌우 대칭(A-P gradient) / N1 — vertex sharp wave / N2 — sleep spindle(frontal·central, 12~14Hz, 2~4초), K-complex / N3 — slow wave 20% 이상 / REM — saw tooth wave, 안구운동.'
st=['각성 상태.','NREM stage 1: vertex sharp wave.','NREM stage 2: sleep spindle, K-complex.','NREM stage 3: slow wave.','REM: saw tooth wave.']
BV='Benign variants(정상인에서도 보이는 소견): mu rhythm(반대측 사지 움직임에 약화), 6Hz spike and wave, rhythmic mid-temporal discharge, wicket spikes, small sharp spikes(BETS). 강현구 교수님 티야.'
def V(*names,note=''): return vis('원본 뇌파 (학습지)',*names,note=note)
SPECS={
 'q-001':Q(3,'Generalized 3Hz spike-and-wave → childhood absence epilepsy의 전형 소견. 1초 안에 spike-wave가 3개.','1Hz: 너무 느리다.','2Hz 전후: slow spike-wave(Lennox-Gastaut).','정답. 3Hz.','6Hz: benign variant(6Hz spike and wave).','12Hz: spike-wave 빈도가 아니다.'),
 'q-002':Q(3,'이 EEG의 generalized spike-and-wave는 약 4Hz(3Hz보다 빠른 4~6Hz는 JME 등에서 흔함).','1Hz: 너무 느리다.','2Hz: slow spike-wave.','정답. 약 4Hz.','8Hz: 너무 빠르다.','12Hz: spike-wave 빈도가 아니다.'),
 'q-003':Q(3,'Generalized 3Hz spike-and-wave → absence seizure (강의 STT 설명).','1Hz: 너무 느리다.','2Hz: slow spike-wave.','정답. 3Hz.','6Hz: benign variant.','12Hz: 해당 없음.'),
 'q-004':Q(3,'짧은 spike 여러 개 뒤 slow wave → polyspike-and-wave(JME 등 generalized epilepsy).','PLEDs: 한쪽 반구의 주기적 방전(급성 구조적 병변).','Triphasic wave: 대사성 뇌병증.','정답. Polyspike-and-wave.','Sleep spindle: 정상 N2 소견.','Wicket spike: benign variant.'),
 'q-005':Q(3,'Sleep spindle과 K-complex가 보이는 epoch → N2.',*st[:0],'Wake: posterior alpha.','N1: vertex sharp wave.','정답. N2: spindle, K-complex.','N3: slow wave 20% 이상.','REM: saw tooth wave, 급속안구운동.'),
 'q-006':Q(2,'Delta 0~<4Hz, Theta 4~8Hz, Alpha 8~13Hz, Beta >13Hz (류한욱 교수님 강력한 티야).','순서가 틀림.','정답. delta < theta < alpha < beta.','역순에 가깝다.','순서가 틀림.','순서가 틀림.',tail='야마 2025 객62 · 학습지 150쪽 원문대조'),
 'q-007':Q(5,SLP+' 나머지 선지가 명확히 틀리므로 ⑤(복원자: 근거는 찾지 못함).','K-complex는 N2.','Sleep spindle은 N2.','posterior alpha는 각성(눈 감음) 상태.','뇌파로 수면 단계를 알 수 있다.','정답.'),
 'q-008':Q(4,BV,'맞는 설명.','맞는 설명.','맞는 설명.','정답(틀린 설명). wicket spike도 benign variant.','맞는 설명.'),
 'q-009':Q(4,SLP,'K-complex는 N2.','Sleep spindle은 N2.','posterior alpha는 각성 상태.','정답. 뇌파로 수면 주기를 파악.','복원자는 오답으로 판단(N3의 slow wave와 구분).'),
 'q-010':Q(4,BV,'맞는 설명.','맞는 설명.','맞는 설명.','정답(틀린 설명).','맞는 설명.'),
 'q-011':S('Left side brain tumor, left side infarction, left side vascular malformation (등 좌측 대뇌 병변)','우측에서는 posterior alpha rhythm이 잘 나오는데 좌측에서 사라짐 → 좌측 뇌 손상.',tail='야마 2023 주13 · 학습지 519쪽',visual=V('t017_2023_j13.jpg')),
 'q-012':S('Right centrotemporoparietal area (C4)','제시된 뇌파에서 C4가 가장 높음 → Rt. central. '+MONO+' bipolar montage에서는 위상역전(만나는 곳)이 focus.',tail='야마 2023 주14 · 학습지 519쪽',visual=V('t017_2023_j14a.jpg','t017_2023_j14b.jpg')),
 'q-013':S('Right central (C4)',MONO+' C4의 파가 가장 크다.',tail='야마 2022 주11 · 학습지 519–520쪽',visual=V('t017_2022_j11.jpg')),
 'q-014':S('Valproic acid, Ethosuximide','세로선 간격 1초, 3Hz spike-wave → absence seizure → valproic acid, ethosuximide. 참고: infantile spasm은 ACTH·스테로이드, benign rolandic epilepsy는 carbamazepine·valproic acid.',tail='야마 2022 주12 · 학습지 520쪽',visual=V('t017_2022_j12.jpg',note='그림 위의 TY 표시·파란 선은 복원자 표시')),
 'q-015':S('Valproic acid, Ethosuximide','3Hz spike-wave → absence seizure(소아·청소년, 여아, staring, 자세 유지). 약제는 valproic acid, ethosuximide.',stem='다음 뇌파를 보이는 질환이 발생했을 때 약 2가지는?',tail='야마 2022 주13 · 학습지 520–521쪽',visual=V('t017_2022_j13.jpg')),
 'q-016':S('Benzodiazepine, Barbiturate','GABAa receptor에 작용하는 항경련제: benzodiazepine, barbiturate, sabril(vigabatrin).',tail='야마 2022 주14 · 학습지 521쪽'),
 'q-017':Q(3,'Sleep spindle과 K-complex → NREM stage 2 (김선준 교수님 강의록 그림).',*st,visual=V('t017_2020_g37.jpg')),
 'q-018':Q(1,'posterior alpha wave + frontal beta wave, 좌우 대칭(A-P gradient) → 눈을 감은 각성 상태. ※ 이 문제는 2~4번 선지가 다른 문항(20번)과 같게 나온 오류로 전원 정답 처리됨.',
   '정답. 각성기로 눈을 감은 상태.','출제 오류로 들어간 선지.','출제 오류로 들어간 선지.','출제 오류로 들어간 선지.','출제 오류로 들어간 선지.',visual=V('t017_2019_g21.jpg'),caveat='출제 오류로 전원 정답 처리된 문항 (해설 참고)'),
 'q-019':Q(4,MONO+' T3에서 파가 가장 높다 → left temporal (2012년 기출 그대로).','Left frontal: F3·F7.','Right frontal: F4·F8.','Left parietal: P3.','정답. Left temporal(T3).','Generalized: 모든 전극에서 동시에 나타난다.',visual=V('t017_2019_g22.jpg')),
 'q-020':S('NREM stage 2 (sleep spindle)','양측 전두부에 2~4초간 12Hz 대칭 규칙파 = sleep spindle → NREM stage 2(가장 긴 수면기). '+SLP,tail='야마 2018 주32 · 학습지 522쪽'),
 'q-021':S('T4 — right temporal',MONO+' 뒤쪽 monopolar EEG에서 T4가 가장 negative.',stem='다음 뇌파에서 간질파의 위치는? (두 EEG 중 뒤쪽에 있는 monopolar EEG가 출제됨)',tail='야마 2018 주33 · 학습지 523쪽',visual=V('t017_2018_j33.jpg')),
 'q-022':S('Chloride channel','GABA-A receptor 모식도 가운데의 chloride channel이 열린다.',tail='야마 2018 주34 · 학습지 523쪽'),
 'q-023':S('Benzodiazepine, Barbiturate','뇌전증 약제 작용기전: Na channel 차단(carbamazepine, phenytoin, valproate), GABA 강화(benzodiazepine, barbiturate, sabril), glutamate 억제(topiramate, lamotrigine, felbamate), T-type Ca 차단(ethosuximide).',tail='야마 2017 주14 · 학습지 523–524쪽'),
 'q-024':S('Mg2+','hypomagnesemia 시 Mg2+가 NMDA receptor를 막지 못해 Ca2+·Na+ 유입 → 탈분극 → seizure.',tail='야마 2017 주15 · 학습지 524쪽'),
 'q-025':S('1) 각성 상태 2) 좌측 alpha rhythm 소실 → 좌측 cerebral cortex 기능 이상 (moyamoya with infarction)','각성 상태에서는 A-P gradient가 좌우 대칭으로 유지되어야 하는데 좌측 alpha rhythm이 사라짐 → 좌측 대뇌피질 이상. 강의록과 같은 EEG(moyamoya 환아).',
   stem='뇌파를 해석하시오.\n1) 의식 (수면-각성) 상태?\n2) 뇌 기능을 평가하시오.',tail='야마 2017 주16 · 학습지 524–525쪽',visual=V('t017_2017_j16.jpg',note='복원자 메모는 가림')),
 'q-026':S('L3-L4 또는 L4-L5 (Tuffier line)','요추천자 위치: L3-4 or L4-5(장골능 상연 연결선).',tail='야마 2016 주22 · 학습지 525쪽'),
 'q-027':S('(1) Infantile spasm → ACTH, 부신피질호르몬  (2) Absence seizure → Valproic acid, Ethosuximide','(1) hypsarrhythmia → infantile spasm, (2) 3Hz spike-wave → absence seizure.',
   stem='(1) 다음 EEG를 보고 사용해야할 약제를 쓰시오.\n(2) 다음 EEG를 보고 사용해야할 약제를 쓰시오.',tail='야마 2016 주23 · 학습지 525–526쪽',
   visual=vis('참고 뇌파 (1)·(2)','t017_2016_j23a.jpg','t017_2016_j23b.jpg',note='복원자가 구글 이미지로 대체한 그림')),
 'q-028':S('C4 — right central',MONO,tail='야마 2016 주24 · 학습지 526쪽',visual=V('t017_2016_j24.jpg')),
 'q-029':S('① GABA receptor – Cl⁻  ② NMDA receptor – Ca²⁺, Na⁺  ③ AMPA receptor – Na⁺','김선준 교수님 소아 경련성 질환 강의록.',stem='다음과 관련된 이온은?\n① GABA receptor\n② NMDA receptor\n③ AMPA receptor',tail='야마 2015 주3 · 학습지 526–527쪽'),
 'q-030':S('C4 — right central',MONO,tail='야마 2015 주5 · 학습지 527쪽',visual=V('t017_2015_j5.jpg')),
 'q-031':S('C4 — right central',MONO,tail='야마 2014 주61 · 학습지 527쪽',visual=V('t017_2014_j61.jpg')),
 'q-032':S('A-P gradient (frequency-amplitude gradient) — 정상 각성 뇌파','앞쪽은 low voltage fast wave, 뒤쪽(posterior)은 alpha rhythm의 high voltage slow wave가 좌우 대칭으로 나타나는 정상 각성 상태의 A-P gradient.',stem='다음 뇌파는 어떤 성향을 나타내는가?',tail='야마 2014 주62 · 학습지 527–528쪽',visual=V('t017_2014_j62.jpg',note='실제 시험지를 찍은 사진이라 화질이 낮음')),
 'q-033':Q(1,'우측에 alpha rhythm이 보이므로 깨어 있는 상태, 좌측은 비정상(diffuse atrophy → tumor) → waking 상태 + 좌측 뇌 기능 부전(강의록 103쪽 그림).',
   '정답.','NREM stage 1이 아니고, 우뇌 간질 소견도 없다.','수면 뇌파가 아니다.','수면 뇌파가 아니다.','REM이 아니다.',visual=V('t017_2013_g12.jpg')),
 'q-034':Q(3,'F7-C3~C4-T6 앞쪽에서 약 3초간 alpha 대역 파(sleep spindle) → NREM stage 2.',*st,visual=V('t017_2012_g10.jpg')),
 'q-035':S('Raised ICP(tentorial herniation 위험), skin infection, thrombocytopenia(<20K), critically ill moribund patient 중 2가지','통합강의록 p83. 뇌압 상승이 의심되면 안저검사·CT 후 결정.',tail='야마 2012 주44 · 학습지 529쪽'),
 'q-036':S('T3 — left temporal lobe',MONO+' 통합강의록 p.124 slide 59와 동일한 그림.',tail='야마 2012 주45 · 학습지 529쪽',visual=V('t017_2012_j45.jpg',note='T3 부위 원 표시는 복원자 표시')),
 'q-037':Q(1,'posterior alpha, frontal beta, 좌우 대칭(A-P gradient) → 각성 상태.',*st,tail='야마 2011 객20 · 학습지 529–530쪽 원문대조',visual=V('t017_2011_g20.jpg')),
 'q-038':S('1) Segmented neutrophil 증가: bacterial meningitis  2) Lymphocyte 증가: viral(무균성) meningitis','Abnormal CSF: PMNL — 세균성, 무균성 초기 / lymphocyte — 무균성, 결핵성, 진균성, 탈수초성 질환, 교원질 질환, 종양 등.',
   stem='뇌척수액 검사에서 뇌척수액에서\n1) Segmented neutrophil 증가를 보이는 경우 1가지\n2) Lymphocyte 증가를 보이는 경우 1가지',tail='야마 2011 주15 · 학습지 530쪽'),
 'q-039':S('C4 — right central',MONO,tail='야마 2011 주17 · 학습지 530쪽',visual=V('t017_2011_j17.jpg')),
}
